### PR TITLE
fix: clearedColor should be changed when initial value is undefined

### LINKED ISSUE #48577: ColorPicker被Form.Item包裹，value不生效
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-n54htc?file=%2Fpackage.json%3A8%2C5&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltzh4mlp00072a67toltqbh2%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltzh4mlp00032a67er19ojp0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltzh4mlp00042a67mzzosg76%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltzh4mlp00062a67odr7h4sk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltzh4mlp00032a67er19ojp0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltzh4mlp00022a67b6bxdv0i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A32%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A32%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvaqgube00022a69d56yrjst%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cltzh4mlp00032a67er19ojp0%2522%252C%2522activeTabId%2522%253A%2522clvaqgube00022a69d56yrjst%2522%257D%252C%2522cltzh4mlp00062a67odr7h4sk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltzh4mlp00052a67doidnqg1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltzh4mlp00062a67odr7h4sk%2522%252C%2522activeTabId%2522%253A%2522cltzh4mlp00052a67doidnqg1%2522%257D%252C%2522cltzh4mlp00042a67mzzosg76%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltzh4mlp00042a67mzzosg76%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

打开重现链接

### What is expected?

效果跟5.12.5版本一样，Form初始化能设置value
321178459-e2d353e5-1061-4ede-8122-0f47711e5d8c

### What is actually happening?

Form初始化没有设置value
图片

| Environment | Info |
| --- | --- |
| antd | 5.16.4 |
| React | 18.2.0 |
| System | Win11 |
| Browser | Microsoft Edge 122.0.2365.92 |

### PR DESCRIPTION
**Pull request by MadCcc**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
fix https://github.com/ant-design/ant-design/issues/48577

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix ColorPicker that cleared icon should change when initial value is `undefined`.       |
| 🇨🇳 Chinese |     修复 ColorPicker 在初始未受控时清除图标不会改变的问题。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/color-picker/hooks/useColorState.ts [hunk 1]
```diff
@@ -43,13 +43,11 @@ const useColorState = (
       return;
     }
     prevValue.current = value;
-    if (hasValue(value)) {
-      const newColor = generateColor(value || '');
-      if (prevColor.current.cleared === true) {
-        newColor.cleared = 'controlled';
-      }
-      setColorValue(newColor);
+    const newColor = generateColor(hasValue(value) ? value || '' : prevColor.current);
```
Comment (crazyair) [inline components/color-picker/hooks/useColorState.ts:46]: "value" in props

Comment (MadCcc) [reply components/color-picker/hooks/useColorState.ts:46]: `value={undefined}` 也看作非受控

**Review by kiner-tang — APPROVED** [review]

File: components/color-picker/hooks/useColorState.ts (hunk 1 above)
Comment (MadCcc) [reply components/color-picker/hooks/useColorState.ts:46]: 都是这样的，undefined 代表非受控，null 代表空

Comment (yoyo837) [reply components/color-picker/hooks/useColorState.ts:46]: 好吧，可能我还未升级成功5.x，印象滞后了。
