### PR TITLE
enhance: Resolve Splitter ssr render view

### LINKED ISSUE #51268: Splitter panel changes size after page load
### Reproduction link

[https://ant.design/components/splitter](https://ant.design/components/splitter)

https://github.com/user-attachments/assets/03eeb93d-0636-4fb1-a128-37dbe4b63003

### Steps to reproduce

1. Open https://ant.design/components/splitter
2. First panel initially is as wide as "First"
3. After a second or two panels jump and both take 50/50 width

### What is expected?

When both panels have width provided, they should not be jumping/changin width after page loads.

### What is actually happening?

Initially panel width is not set, only after a second or two.

| Environment | Info |
| --- | --- |
| antd | 5.21.3 |
| React | 18.2.0 |
| System | Mac |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by zombieJ**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [ ] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [x] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

resolve #51268

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      Optimize Splitter pre-render in SSR to make Splitter.Panel much closer to the client-side.     |
| 🇨🇳 Chinese |    优化 Splitter 在 SSR 下预渲染的样式，使 Splitter.Panel 更贴近客户端的比例。       |

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

File: components/splitter/Splitter.tsx [hunk 1]
```diff
@@ -68,7 +68,7 @@ const Splitter: React.FC<React.PropsWithChildren<SplitterProps>> = (props) => {
   }
 
   // ====================== Container =======================
-  const [containerSize, setContainerSize] = useState<number>(100);
+  const [containerSize, setContainerSize] = useState<number | undefined>();
```
Comment (crazyair) [inline components/splitter/Splitter.tsx:71]: 100 删了，这里 undefined 也不用加了
