### PR TITLE
fix: adjust the message content display attribute

### LINKED ISSUE #49416: After customising the fonts, the message icons are misaligned.
### Reproduction link

[Edit on StackBlitz](https://stackblitz.com/edit/react-flmde8?file=index.css)

### Steps to reproduce

Click on the button to trigger a message popup to see the layout of the icon.

### What is expected?

Typography is normal.

### What is actually happening?

Typography out of alignment.

image

| Environment | Info |
| --- | --- |
| antd | 5.18.1 |
| React | 18.3.1 |
| System | macOS 14.4.1 - arm64 Apple M2 Pro |
| Browser | Chrome: 126.0.6478.62 |

---
For now, setting the icon's parent to `flex` is a temporary solution.

```css
.ant-message-custom-content {
  display: flex;
} 
```

It's not clear if it's the macos fonts that are causing this, or something else.

### PR DESCRIPTION
**Pull request by nova1751**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

Close #49416

### 💡 Background and solution

The message custom content is normally aligned, which leads to the problem where the icon and the text are not strictly centered, just like the picture below. Using `flex` can solve this problem.
image
After change:
image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix the bug where the icon and the text aren't strictly centered in Message component. |
| 🇨🇳 Chinese | 修复了 `Message` 组件的图标与文本内容没有严格居中对齐的问题。          |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/message/style/index.ts [hunk 1]
```diff
@@ -88,6 +88,11 @@ const genMessageStyle: GenerateStyle<MessageToken> = (token) => {
     padding: paddingXS,
     textAlign: 'center',
 
+    [`${componentCls}-custom-content`]: {
+      display: 'flex',
+      alignItems: 'center',
+    },
+
     [`${componentCls}-custom-content > ${iconCls}`]: {
       verticalAlign: 'text-bottom',
```
Comment (afc163) [inline components/message/style/index.ts:97]: This line could be removed now.

**Review by afc163 — APPROVED** [review]
