### PR TITLE
fix: Upload remove margin using flex display

### LINKED ISSUE #47992: Upload picture-card 可以更改为 flex   gap 布局，不会有多余的右 margin 和 下 margin
### Reproduction link

[https://ant.design/components/upload-cn#components-upload-demo-picture-card](https://ant.design/components/upload-cn#components-upload-demo-picture-card)

### Steps to reproduce

查看最右侧和最下侧的 margin

### What is expected?

最右侧和最下侧的没有 margin

### What is actually happening?

最右侧和最下侧的有 margin

| Environment | Info |
| --- | --- |
| antd | 5.15.3 |
| React | latest |
| System | mac |
| Browser | chrome |

---
但是也要考虑下是不是会和 Tag 的 margin 一样会有 break change

### PR DESCRIPTION
**Pull request by CooperHash**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [X] Other (about what?)

### 🔗 Related issue link

- close #47992

### 💡 Background and solution

改动前

image

改动后

image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    --       |
| 🇨🇳 Chinese |    --       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

### CODE REVIEW

File: components/upload/style/picture.ts [hunk 1]
```diff
@@ -138,19 +136,33 @@ const genPictureCardStyle: GenerateStyle<UploadToken> = (token) => {
 
       // list
       [`${listCls}${listCls}-picture-card, ${listCls}${listCls}-picture-circle`]: {
+        display: 'flex',
+        flexWrap: 'wrap',
+        '& > *': {
+          margin: token.marginXS,
+        },
```
Comment (MadCcc) [inline components/upload/style/picture.ts:143]: 这个用 `@supports not`

File: components/upload/style/picture.ts [hunk 2]
```diff
@@ -138,19 +136,32 @@ const genPictureCardStyle: GenerateStyle<UploadToken> = (token) => {
 
       // list
       [`${listCls}${listCls}-picture-card, ${listCls}${listCls}-picture-circle`]: {
+        display: 'flex',
+        flexWrap: 'wrap',
+        '@supports not (gap: 1px)': {
+          '& > *': {
+            margin: token.marginXS,
```
Comment (MadCcc) [inline components/upload/style/picture.ts:143]:
```suggestion
          marginBlockEnd: token.marginXS,
          marginInlineEnd: token.marginXS,
```

**Review by MadCcc — APPROVED** [review]
