### PR TITLE
fix: Fix date_picker et time_picker locale for 🇫🇷

### LINKED ISSUE #22674: [4.0.4] Locale `lang` types are not up-to-date.
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/PaulJln/antd-4.0.4-date-picker-local-fr-FR](https://github.com/PaulJln/antd-4.0.4-date-picker-local-fr-FR)

### Steps to reproduce
Open antd/lib/date-picker/locale/fr_FR.d.ts and antd/lib/date-picker/locale/en_US.d.ts, type lang looks different. The type `rangePlaceholder: string[]` is missing.

### What is expected?
Related to : https://github.com/ant-design/ant-design/pull/22122

The field `rangePlaceholder: string[];` is missing.

### What is actually happening?
```
Types of property 'timePickerLocale' are incompatible.
    Property 'rangePlaceholder' is missing in type '{ placeholder: string; }' but required in type '{ placeholder: string; rangePlaceholder: string[]; }'.ts(2719)
en_US.d.ts(44, 9): 'rangePlaceholder' is declared here.
```

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.12 |
| System | MacOS 10.15.3 |
| Browser | Firefox Developer Edition v74 |

### PR DESCRIPTION
**Pull request by PaulJln**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #22674

Open `antd/lib/date-picker/locale/fr_FR.d.ts` and `antd/lib/date-picker/locale/en_US.d.ts`, type lang looks different. The type `rangePlaceholder: string[]` is missing.

Additional attribute `placeholderQuarter: []` was missing as well.

### 💡 Background and solution

Adding fields in target files.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | 🇫🇷 Date picker and time picker update |
| 🇨🇳 Chinese |  🇫🇷 日期选择器和时间选择器更新 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by abenhamdine — APPROVED** [review]

File: components/time-picker/locale/fr_FR.tsx [hunk 1]
```diff
@@ -2,6 +2,7 @@ import { TimePickerLocale } from '../index';
 
 const locale: TimePickerLocale = {
   placeholder: "Sélectionner l'heure",
+  rangePlaceholder: ['Heure de début', 'Heure de fin'],
```
Comment (yoyo837) [inline components/time-picker/locale/fr_FR.tsx]: How about move this line to `date-picker/locale` ?

Comment (PaulJln) [reply components/time-picker/locale/fr_FR.tsx]: I preferred to copy the implementation of `components/time-picker/locale/en_US.tsx` and the placeholder is related to the _time-picker_
