### PR TITLE
fix: Upload item removed should keep status className

### LINKED ISSUE #36286: Upload Error状态删除时有蓝色Icon闪过
### Reproduction link

[https://ant.design/components/upload-cn/#components-upload-demo-picture-card](https://ant.design/components/upload-cn/#components-upload-demo-picture-card)

### Steps to reproduce

1、这是官网文档中照片墙的例子
2、删除那张代表Error状态的图片
3、在删除瞬间可以看到有个蓝色的图片ICON闪过

### What is expected?

没有蓝色的图片ICON闪过

### What is actually happening?

有蓝色的图片ICON闪过

| Environment | Info |
| --- | --- |
| antd | 4.21.4 |
| React | 17.0.2 |
| System | macOS Catalina 10.15.7 |
| Browser | Chrome 103.0.5060.53 |

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix #36286

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fixed Upload removing file status color is wrong.       |
| 🇨🇳 Chinese |       修复 Upload 移除文件时状态色会变化的问题。    |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by afc163 — APPROVED** [review]

File: components/upload/UploadList/ListItem.tsx [hunk 1]
```diff
@@ -72,6 +72,15 @@ const ListItem = React.forwardRef(
     }: ListItemProps,
     ref: React.Ref<HTMLDivElement>,
   ) => {
+    // Status: which will ignore `removed` status
+    const { status } = file;
+    const [mergedStatus, setMergedStatus] = React.useState(status);
```
Comment (afc163) [inline components/upload/UploadList/ListItem.tsx:77]:
```suggestion
    const [statusForUI, setStatusForUI] = React.useState(status);
```

这样命名是不是准一点。

Comment (zombieJ) [reply components/upload/UploadList/ListItem.tsx:77]: 下面所有用到 status 的都替换成了 `mergedStatus`，`removed` 状态对于 UploadItem 其实是不关注的。
