### PR TITLE
Fix empty missing when Table is loading

### LINKED ISSUE #15582: Table missing Empty render when loading is true
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/7w3k17q026)

### Steps to reproduce
Click switch to mock table start loading

### What is expected?
Empty should keep in the view

### What is actually happening?
Empty lose

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.0 |
| System | Mac |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

close #15582

### 💡 Solution

现在用了 Empty 之后，#9069 就会有点问题，我把这个改动回滚掉。

### 📝 Changelog description

> Describe changes from userside, and list all potential break changes or other risks.

1. English description

- Fix empty missing when Table is loading. #15582

2. Chinese description (optional)

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Review by ztplz — APPROVED** [review]

**Review by zombieJ — APPROVED** [review]

File: components/table/Table.tsx [hunk 1]
```diff
@@ -1164,7 +1163,7 @@ export default class Table<T> extends React.Component<TableProps<T>, TableState<
         className={classString}
         expandIconColumnIndex={expandIconColumnIndex}
         expandIconAsCell={expandIconAsCell}
-        emptyText={!loading.spinning && mergedLocale.emptyText}
+        emptyText={mergedLocale.emptyText}
```
Comment (Jrgsto) [inline components/table/Table.tsx:1166]: Why has this been approved, how can I actually achieve to not show the empty text in case its loading?
