### PR TITLE
fix(Select): clear icon position

### LINKED ISSUE #51577: Select wrapped in Form.Item with hasFeedback and no status has incorrect clear icon placement
### Reproduction link

https://codepen.io/nking07049925/pen/RwXELxv

### Steps to reproduce

Wrap a `<Select allowClear />` in `<Form.Item hasFeedback>` and no status, set a value and hover over the input

### What is expected?

The close icon is drawn on top of the select arrow icon
image

### What is actually happening?

The close icon is drawn to the left of the select arrow icon
image

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18 |
| System | Win11 |
| Browser | Microsoft Edge 130.0.2849.80 Chromium version 130.0.6723.117 |

---
We noticed this issue when migrating our project from antd4 to antd5

Same codepen in antd4, where this works correctly    
https://codepen.io/nking07049925/pen/jOgXGvM

hasFeedback is set to true with no status as per https://github.com/ant-design/ant-design/issues/34458#issuecomment-1066313811 to avoid issues with focus on inputs with validation when status has to be set

### PR DESCRIPTION
**Pull request by dislido**
Fix `.ant-select-has-feedback .ant-select-clear` position when `validateStatus` is empty

[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [x] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues
fix https://github.com/ant-design/ant-design/issues/51577

### 💡 Background and Solution
antd@4中，清除按钮会在`.ant-select-status-${validateStatus}.ant-select-has-feedback`下左移  
antd@5遗漏了`.ant-select-status-${validateStatus}`条件

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix the problem that the clear icon position of `Select` is incorrect when setting `hasFeedback` but no `validateStatus` in `Form.Item` |
| 🇨🇳 Chinese | 修复在有`hasFeedback`但没有`validateStatus`的`Form.Item`中的`Select`组件清除按钮位置错误 |

### CODE REVIEW

File: components/select/style/index.ts [hunk 1]
```diff
@@ -185,13 +185,17 @@ const genBaseStyle: GenerateStyle<SelectToken> = (token) => {
...
     // ========================= Feedback ==========================
-    [`${componentCls}-has-feedback`]: {
-      [`${componentCls}-clear`]: {
-        insetInlineEnd: token
-          .calc(inputPaddingHorizontalBase)
-          .add(token.fontSize)
-          .add(token.paddingXS)
-          .equal(),
+    [`${componentCls}-status`]: {
+      [`&-error, &-warning, &-success, &-validating`]: {
```
Comment (thinkasany) [inline components/select/style/index.ts:189]:
```suggestion
      '&-error, &-warning, &-success, &-validating': {
```

Comment (thinkasany) [reply components/select/style/index.ts:189]: 有个biome的lint错误，好像可以直接用string，其他地方有看到类似的用法。
image
image

File: components/select/__tests__/index.test.tsx [hunk 2]
```diff
@@ -126,6 +127,43 @@ describe('Select', () => {
     });
   });
 
+  describe('clear icon position', () => {
+    it('normal', () => {
+      const { container } = render(
+        <Select allowClear options={[{ value: '1', label: '1' }]} value="1" />,
```
[the remark this answers is not in the document]
Comment (dislido) [reply components/select/__tests__/index.test.tsx:133]: Not necessary for this test

**Review by afc163 — APPROVED** [review]

**Comment by afc163** [comment]
hover 时把日期图标也隐藏了，感觉不太对。

图片

**Comment by afc163** [comment]
这应该也是某个版本改出来的 bug。

suffix 隐藏的原意是原来 clear icon 和 suffix 位置在同一个地方，避免动画过程中两者有重叠效果。

**Comment by dislido** [comment]
image
这个问题处理起来似乎有些麻烦，传`suffixIcon`的时候是直接替换`ant-picker-suffix`的children的，考虑到兼容性不用`:has(*)`的情况下只靠css似乎没办法区分string(`.ant-picker-suffix { opacity: 0 }`)和非string(`.ant-picker-suffix > :last-child { opacity: 0 }`)的情况，且用`:has(*)`也处理不了`suffixIcon={<><Icon />str</>}`这样的

或者是自定义suffixIcon全隐藏处理，只处理默认suffix的情况，但需要加个has-suffix之类的class标记下
(antd@4的处理是clearIcon直接白色背景盖上，感觉也不太合适）

这个是date-picker组件相关的问题，与原issue没什么关系，建议单开issue处理吧
