### PR TITLE
fix: switcherIcon cannot be hidden

### LINKED ISSUE #41705: Can't hidden Icon via switcherIcon props
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/mu-lu-antd-5-4-0-forked-vqj4jl?file=/demo.tsx)

### Steps to reproduce

/

### What is expected?

I can change this Icon , but I can't hidden it . In fact , I need't  it.

### What is actually happening?

/

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 18.2.0 |
| System | macos 12.6.3 |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by acyza**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #41705 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix switcherIcon cannot be hidden  |
| 🇨🇳 Chinese |  修复switcherIcon无法隐藏  |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 9dd721c</samp>

This pull request fixes issue #32841 by allowing the `switcherIcon` prop of the `Tree` component to accept a function that can return a custom icon or null. It also adds a test case to verify the functionality of the prop.

### <samp>🤖 Generated by Copilot at 9dd721c</samp>

* Fix issue #32841 by allowing switcherIcon prop to hide or customize tree node icons ([link](https://github.com/ant-design/ant-design/pull/41708/files?diff=unified&w=0#diff-da22d6f22f631152c49377ec55ca75e97414b83b5686fcb93e57904e15c19096L67-R67), [link](https://github.com/ant-design/ant-design/pull/41708/files?diff=unified&w=0#diff-532a06c009c07c3f70338f01f6db867a000491f718b25e64085acda42823ca04R188-R199))
  - Modify getSwitcherIcon function in `iconUtil.tsx` to return switcherIcon prop as a React element if it is a function ([link](https://github.com/ant-design/ant-design/pull/41708/files?diff=unified&w=0#diff-da22d6f22f631152c49377ec55ca75e97414b83b5686fcb93e57904e15c19096L67-R67))
  - Add test case in `index.test.tsx` to verify that switcherIcon prop can return null to hide switcher icons ([link](https://github.com/ant-design/ant-design/pull/41708/files?diff=unified&w=0#diff-532a06c009c07c3f70338f01f6db867a000491f718b25e64085acda42823ca04R188-R199))

### CODE REVIEW

**Comment by li-jia-nan** [comment]
- #41709 

我好像慢了一步，那你来修吧，我 close 了

File: components/tree/utils/iconUtil.tsx [hunk 1]
```diff
@@ -64,7 +64,7 @@ const SwitcherIconCom: React.FC<SwitcherIconProps> = (props) => {
     });
   }
 
-  if (switcher) {
+  if (switcher || typeof switcherIcon === 'function') {
```
Comment (li-jia-nan) [inline components/tree/utils/iconUtil.tsx:67]: 这个逻辑有点问题，如果直接传 null 呢？

File: components/tree/utils/iconUtil.tsx [hunk 2]
```diff
@@ -64,7 +64,7 @@ const SwitcherIconCom: React.FC<SwitcherIconProps> = (props) => {
     });
   }
 
-  if (switcher) {
+  if (switcher !== undefined || typeof switcherIcon === 'function') {
```
Comment (li-jia-nan) [inline components/tree/utils/iconUtil.tsx:67]: `typeof switcherIcon === 'function'` 是出于什么考虑呢？感觉不是很有必要

Comment (acyza) [reply components/tree/utils/iconUtil.tsx:67]: 传入`()=>undefined`
要不还是先去掉把，好像确实没太必要。

File: components/tree/__tests__/index.test.tsx [hunk 3]
```diff
@@ -185,4 +185,16 @@ describe('Tree', () => {
       expect(nodeDraggable).toHaveBeenCalledWith(dragTreeData[0]);
     });
   });
+
+  it('hidden switcherIcon', () => {
+    const { container } = render(
+      <Tree defaultExpandAll switcherIcon={() => null}>
```
Comment (li-jia-nan) [inline components/tree/__tests__/index.test.tsx:191]: 可以再加一个测试 null 的 test case

File: components/tree/utils/iconUtil.tsx (hunk 2 above)
Comment (acyza) [reply components/tree/utils/iconUtil.tsx]: ci可能需要修一下
图片

Comment (li-jia-nan) [reply components/tree/utils/iconUtil.tsx]: - #41701

Comment (li-jia-nan) [reply components/tree/utils/iconUtil.tsx]: 等等这个

**Review by li-jia-nan — APPROVED** [review]
