### PR TITLE
fix(transfer): background overflow when last item on current page is selected

### LINKED ISSUE #51883: [bug] 穿梭框组件最后一项选中后背景溢出
### Reproduction link

[https://ant-design.antgroup.com/components/transfer-cn#transfer-demo-basic](https://ant-design.antgroup.com/components/transfer-cn#transfer-demo-basic)

### Steps to reproduce

最后一个被选中后，背景超出去了！

image

### What is expected?

希望溢出隐藏

### What is actually happening?

没有溢出隐藏

| Environment | Info |
| --- | --- |
| antd | 5.22.2 |
| React | ^18 |
| System | MacOS 14 |
| Browser | Chrome 版本 131.0.6778.86（正式版本） (arm64) |

### PR DESCRIPTION
**Pull request by ayangweb**
### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

fix #51883 

### 💡 Background and Solution

fix #51883 

### 📝 Change Log

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix Transfer's background overflow when the last item on the current page is selected      |
| 🇨🇳 Chinese |     修复 Transfer 选中当前页最后一项时背景溢出的问题      |

### CODE REVIEW

File: components/transfer/style/index.ts [hunk 1]
```diff
@@ -147,6 +147,7 @@ const genTransferListStyle: GenerateStyle<TransferToken> = (token: TransferToken
     height: listHeight,
     border: `${unit(lineWidth)} ${lineType} ${colorBorder}`,
     borderRadius: token.borderRadiusLG,
+    overflow: 'hidden',
```
Comment (afc163) [inline components/transfer/style/index.ts:150]: 一般不加 `overflow: hidden`，去给 last item 设置 `border-radius`。

Comment (ayangweb) [reply components/transfer/style/index.ts:150]: 怎么判断是当前页最后一个？

Comment (ayangweb) [reply components/transfer/style/index.ts:150]: https://github.com/user-attachments/assets/3c71e3cd-60a9-4c19-96de-dc6a0c3e66df

Comment (afc163) [reply components/transfer/style/index.ts:150]: 那不对，这里已经有滚动条了，理论上 overflow 已经有了

Comment (afc163) [reply components/transfer/style/index.ts:150]: 给 ant-transfer-list-content 加 `border-radius`。

File: components/transfer/style/index.ts [hunk 2]
```diff
@@ -221,6 +221,7 @@ const genTransferListStyle: GenerateStyle<TransferToken> = (token: TransferToken
       padding: 0,
       overflow: 'auto',
       listStyle: 'none',
+      borderRadius: `0 0 ${unit(borderRadiusLG)} ${unit(borderRadiusLG)}`,
```
Comment (afc163) [inline components/transfer/style/index.ts:224]: 图片

radius 需要减 1px 或者 0.5px，否则会有间隙。

File: components/transfer/style/index.ts [hunk 3]
```diff
@@ -221,6 +221,7 @@ const genTransferListStyle: GenerateStyle<TransferToken> = (token: TransferToken
       padding: 0,
       overflow: 'auto',
       listStyle: 'none',
+      borderRadius: `0 0 ${unit(token.calc(borderRadiusLG).sub(lineWidth).equal())} ${unit(token.calc(borderRadiusLG).sub(lineWidth).equal())}`,
```
Comment (afc163) [inline components/transfer/style/index.ts:224]: 算一次就行了，提一个变量。

**Review by afc163 — APPROVED** [review]
