### PR TITLE
fixes #10289 and #10209: lost of user selection on table data updates

### LINKED ISSUE #10289: Broken table filter when data change occurs
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
any browser

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/wk3oopzlj5)

### Steps to reproduce
Using the provided demo, try to use the filter feature

### What is expected?
That the user selection is not lost also if he hasn't clicked on the OK button yet

### What is actually happening?
If a data change occurs the current selection is lost

---
I found a possible fix, but I'm not sure about that.
https://github.com/ant-design/ant-design/blob/3d079af7cd2fdc72d9455e54738727824596aad4/components/table/filterDropdown.tsx#L39-L55

Replace this
````
if ('selectedKeys' in nextProps) {
    newState.selectedKeys = nextProps.selectedKeys;
}
````
with this
````
if ('selectedKeys' in nextProps && !this.state.visible) {
   newState.selectedKeys = nextProps.selectedKeys;
}
````

### PR DESCRIPTION
**Pull request by chrvadala**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [X] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [X] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [X] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [X] Rebase before creating a PR to keep commit history clear.
* [X] Add some descriptions and refer relative issues for you PR.

Extra checklist:

**if** *isBugFix* **:**

  * [X] Make sure that you add at least one unit test for the bug which you had fixed.

### CODE REVIEW

File: components/table/filterDropdown.tsx [hunk 1]
```diff
@@ -43,7 +43,15 @@ export default class FilterMenu<T> extends React.Component<FilterMenuProps<T>, F
...
-    if ('selectedKeys' in nextProps) {
+
+    /**
+     * if the state is visible the component should ignore updates on selectedKeys prop to avoid
+     * that the user selection is lost
+     * this happens frequently when a table is connected on some sort of realtime data
+     * Fixes https://github.com/ant-design/ant-design/issues/10289 and
+     * https://github.com/ant-design/ant-design/issues/10209
+     */
+    if ('selectedKeys' in nextProps && !this.state.visible) {
```
Comment (yesmeck) [inline components/table/filterDropdown.tsx]: I think we also need to compare `this.props.selectedKeys` and `nextProps.selectKeys` are not shallow equal so that `selectedKeys` can be controlled from outside.

Comment (chrvadala) [reply components/table/filterDropdown.tsx]: In that case I think that is no more required the visibility check, but the shallow compare should fix the issue as well
