### PR TITLE
fix: Fix token of  `Layout.colorBgHeader` not work when single use Layout.Header directly

### LINKED ISSUE #40909: ConfigProvider 组件提供的 token 不生效
### Reproduction link

[https://stackblitz.com/edit/ant-desigin-configprovider?file=demo.tsx](https://stackblitz.com/edit/ant-desigin-configprovider?file=demo.tsx)

### Steps to reproduce

1.使用 `ConfigProvider` 组件包裹 `Layout.Header` 组件
2.在 `ConfigProvider` 组件中，为 `Layout.Header` 设置专属的 `theme`, 如 `colorBgHeader`

### What is expected?

Header的背景色变白

### What is actually happening?

`colorBgHeader` 无效

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2.0 |
| System | Window 10 |
| Browser | Google Chrome(110.0.5481.178) |

---
我查询到一个相关的 [issue](https://github.com/ant-design/ant-design/issues/38975)，应该是造成该问题的原因。
如果官方暂时不支持组件全量token注入，但是又不再使用 Less，那么当前推荐的修改样式的方案，应该是如何？
比如，我当前使用 emotion （CSS-in-JS），我该如果修改样式？因为`::where`选择器的存在，我的 emotion 代码权重被降低了。

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #40909

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix token of  `Layout.colorBgHeader` not work when single use Layout.Header directly      |
| 🇨🇳 Chinese |     修复 Layout.Header 单独使用时，`Layout.colorBgHeader` token 配置不生效的问题。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/layout/layout.tsx [hunk 1]
```diff
@@ -48,10 +45,28 @@ function generator({ suffixCls, tagName, displayName }: GeneratorProps) {
...
+  const prefixCls = getPrefixCls('layout', customizePrefixCls);
+
+  const [wrapSSR, hashId] = useStyle(prefixCls as string);
+
+  const prefixWithSuffixCls = suffixCls ? `${prefixCls}-${suffixCls}` : prefixCls;
 
-  return React.createElement(tagName, { className: classString, ...others, ref }, children);
+  return wrapSSR(
+    <TagName
+      className={classNames(customizePrefixCls || prefixWithSuffixCls, className, hashId)}
```
Comment (kiner-tang) [inline components/layout/layout.tsx:65]: 这里是不是用`??`好一点，是不是会有外界传过来的`prefixCls`为`''`的情况？
```suggestion
      className={classNames(customizePrefixCls ?? prefixWithSuffixCls, className, hashId)}
```

**Review by heiyu4585 — APPROVED** [review]

File: components/layout/layout.tsx (hunk 1 above)
Comment (zombieJ) [reply components/layout/layout.tsx:65]: 不会的，`prefixCls` 本身就是内部属性。传入 `''`那都没办法魔改样式了。

Comment (kiner-tang) [reply components/layout/layout.tsx:65]: ok
