### PR TITLE
fix(Input): fix password prop action

### LINKED ISSUE #15587: Input.Password的PasswordProps中的action的字段为可选的
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/input/Password.tsx#L8](https://github.com/ant-design/ant-design/blob/master/components/input/Password.tsx#L8)

### Steps to reproduce
https://github.com/ant-design/ant-design/blob/master/components/input/Password.tsx#L8

### What is expected?
Input.Password的PasswordProps中的action的字段为可选的

### What is actually happening?
Input.Password的PasswordProps中的action的字段是必选的

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16 |
| System | mac |
| Browser | chrome |

---
尽快修复

### PR DESCRIPTION
**Pull request by Yangzhedi**
## 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?
fix[#15587](https://github.com/ant-design/ant-design/issues/15587)

### 💡 Solution

1. How to fix the problem, and list final API implementation and usage sample if that is an new feature.

2. GIF or snapshot should be provided if includes UI/interactive modification.

### 📝 Changelog description

> Describe changes from userside, and list all potential break changes or other risks.

1. English description

2. Chinese description (optional)

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

File: components/input/Password.tsx [hunk 1]
```diff
@@ -37,7 +37,7 @@ export default class Password extends React.Component<PasswordProps, PasswordSta
   };
 
   getIcon() {
-    const { prefixCls, action } = this.props;
+    const { prefixCls, action = 'click' } = this.props;
```
Comment (ztplz) [inline components/input/Password.tsx]: 这个没必要  defaultProps就是click

**Review by ztplz — APPROVED** [review]

File: components/input/Password.tsx (hunk 1 above)
Comment (Yangzhedi) [reply components/input/Password.tsx]: 不加这个，下面的ActionMap提取时，ts会报错

Comment (ztplz) [reply components/input/Password.tsx]: 加个非空断言 本来defaultProps就已经设置了 又重复赋值了一次  看起来不是很好
