### PR TITLE
fix: update select multiple item max-width to prevent overflow

### LINKED ISSUE #54179: Form 下使用 Spin   Select 样式有问题
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/ji-ben-shi-yong-antd-5-25-4-forked-n4mtqj?file=%2Fdemo.tsx%3A11%2C23)

### Steps to reproduce

查看 demo

### What is expected?

样式没问题

### What is actually happening?

样式有问题

Image

| Environment | Info |
| --- | --- |
| antd | 5.26.1 |
| React | latest |
| System | mac |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by afc163**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

close https://github.com/ant-design/ant-design/issues/54179

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)! Track your changes, like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Select multiple item max-width to prevent unexpected wrapping.          |
| 🇨🇳 Chinese | 修复多选 Select 在单条选中项文本超长时意外换行的问题。         |

### CODE REVIEW

File: components/select/style/multiple.ts [hunk 1]
```diff
@@ -128,7 +128,8 @@ export const genOverflowStyle = (
       '&-item': {
         flex: 'none',
         alignSelf: 'center',
-        maxWidth: '100%',
+        // https://github.com/ant-design/ant-design/issues/54179
+        maxWidth: 'calc(100% - 4px)',
```
Comment (li-jia-nan) [inline components/select/style/multiple.ts:132]: 这个 4px 有必要换成 token 吗？

**Review by li-jia-nan — APPROVED** [review]

File: components/select/style/multiple.ts (hunk 1 above)
Comment (afc163) [reply components/select/style/multiple.ts:132]: 意义不大，现在 4px 是写在 js 里的，暂时没关联起来。

Comment (yoyo837) [reply components/select/style/multiple.ts:132]: 那搞成参数传进来联动是不是也比写死好一点，js那边没备注，改了这里可能未改

Comment (ziaochina) [reply components/select/style/multiple.ts:132]: 这个修改应该是有点问题，我们用formily，里面有select item，升级到antd 最新版本后，select form项在一长一短不停的闪烁，我们将样式调整回maxWidth 100%就不会闪烁了
