### PR TITLE
docs: fix misdocumented component token meta

### LINKED ISSUE #43987: `footerPaddingInline` incorrectly documented as 'Vertical padding of footer'
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/ji-chu-chou-ti-antd-5-8-1-forked-vxd95h?file=/demo.tsx:215-287)

### Steps to reproduce

Check doc comments here:
https://github.com/ant-design/ant-design/blob/master/components/drawer/style/index.ts#L12-L20

### What is expected?

`footerPaddingBlock`、`footerPaddingInline` 得到正确注释

### What is actually happening?

`footerPaddingBlock`、`footerPaddingInline` 未正确注释

| Environment | Info |
| --- | --- |
| antd | 5.8.1 |
| React | 18.2.0 |
| System | MacOS 11.7.7 |
| Browser | Chrome  114.0.5735.198 |

---
P.S.  `<Anchor/>` 也有同样的注释问题   : https://github.com/ant-design/ant-design/blob/master/components/anchor/style/index.ts#L8-L16

### PR DESCRIPTION
**Pull request by wving5**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/43987

### 💡 Background and solution
fix misdocumented component token meta

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |fix misdocumented component token meta in `<Drawer />`、`<Anchor />`          |
| 🇨🇳 Chinese | 修正`<Drawer />`、`<Anchor />` 部分 token 的错误元信息         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 12d43e1</samp>

Swapped the order of comments and properties for some padding variables in `components/anchor/style/index.ts` and `components/drawer/style/index.ts`. This change improved the code readability and consistency across the anchor and drawer components.

### <samp>🤖 Generated by Copilot at 12d43e1</samp>

*  Swap the order of comments and properties for vertical and horizontal padding in the `ComponentToken` interface for the anchor and drawer components ([link](https://github.com/ant-design/ant-design/pull/43994/files?diff=unified&w=0#diff-317d329fe73e0dd37dc2416f47e9ddb7f377ece859e71f5f36a65025e7f8581eL8-R14), [link](https://github.com/ant-design/ant-design/pull/43994/files?diff=unified&w=0#diff-cb2507ee40e1f2f8ba644202d9eb67d9eb5fc3d766b7ba3628703498a44225e3L12-R18)). This improves the readability and consistency of the code in `components/anchor/style/index.ts` and `components/drawer/style/index.ts`.

### CODE REVIEW

File: components/anchor/style/index.ts [hunk 1]
```diff
@@ -5,13 +5,13 @@ import { genComponentStyleHook, mergeToken } from '../../theme/internal';
 
 export interface ComponentToken {
   /**
-   * @desc 链接横向内间距
-   * @descEN Link horizontal padding
+   * @desc 链接纵向内间距
+   * @descEN Link vertical padding
```
Comment (MadCcc) [inline components/anchor/style/index.ts:9]:
```suggestion
   * @descEN Vertical padding of link
```

File: components/anchor/style/index.ts [hunk 2]
```diff
@@ -5,13 +5,13 @@ import { genComponentStyleHook, mergeToken } from '../../theme/internal';
...
    */
   linkPaddingBlock: number;
   /**
-   * @desc 链接纵向内间距
-   * @descEN Link vertical padding
+   * @desc 链接横向内间距
+   * @descEN Link horizontal padding
```
Comment (MadCcc) [inline components/anchor/style/index.ts:14]:
```suggestion
   * @descEN Horizontal padding of link
```

**Review by MadCcc — APPROVED** [review]
