### PR TITLE
fix: statistic timer cannot display tooltip as a children

### LINKED ISSUE #53872: Tooltip包裹Statistic.Timer没效果
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/devbox/hungry-cache-92wzky)

### Steps to reproduce

Timer外层用Tooltip包裹，并设置open

### What is expected?

Timer附近出现弹层

### What is actually happening?

Timer附近没有出现弹层。react18的表现是正常的，react19不行

Image

| Environment | Info |
| --- | --- |
| antd | 5.25.2 |
| React | 19.1.0 |
| System | mac |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by jin19980928**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🐞 Bug fix

### 🔗 Related Issues
fix https://github.com/ant-design/ant-design/issues/53872

### 💡 Background and Solution

> - statistic timer cannot display tooltip as a children.

### 📝 Change Log

> - statistic timer cannot display tooltip as a children.

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    statistic timer cannot display tooltip as a children       |
| 🇨🇳 Chinese |     statistic timer 组件作为tooltip的childern无法正常展示tooltip文字提示      |

### CODE REVIEW

File: components/statistic/Timer.tsx [hunk 1]
```diff
@@ -80,7 +80,15 @@ const StatisticTimer: React.FC<StatisticTimerProps> = (props) => {
...
 
   // ======================== Render ========================
-  return <Statistic {...rest} value={value} valueRender={valueRender} formatter={formatter} />;
+  return (
+    <Statistic
+      {...rest}
+      value={value}
+      valueRender={valueRender}
+      formatter={formatter}
+      style={{ display: 'inline-block' }}
```
Comment (yoyo837) [inline components/statistic/Timer.tsx:89]: Please do not use inline styles.

File: components/statistic/Statistic.tsx [hunk 2]
```diff
@@ -27,7 +27,7 @@ interface StatisticReactProps extends FormatConfig {
 
 export type StatisticProps = HTMLAriaDataAttributes & StatisticReactProps;
 
-const Statistic: React.FC<StatisticProps> = (props) => {
+const Statistic = React.forwardRef<HTMLDivElement, StatisticProps>((props, ref) => {
```
Comment (zombieJ) [inline components/statistic/Statistic.tsx:30]: ref 使用:

```tsx
{
  nativeElement: HTMLDivElement;
}
```

以备未来要拓展

File: components/statistic/Timer.tsx (hunk 1 above)
Comment (jin19980928) [reply components/statistic/Timer.tsx]: ok

File: components/statistic/Statistic.tsx (hunk 2 above)
Comment (jin19980928) [reply components/statistic/Statistic.tsx]: ok

File: components/statistic/Statistic.tsx [hunk 3]
```diff
@@ -9,6 +9,10 @@ import StatisticNumber from './Number';
 import useStyle from './style';
 import type { FormatConfig, valueType } from './utils';
 
+export interface StatisticRef {
+  nativeElement: HTMLDivElement;
```
Comment (zombieJ) [inline components/statistic/Statistic.tsx:13]: 测试用例

Comment (jin19980928) [reply components/statistic/Statistic.tsx:13]: ok

**Review by zombieJ — APPROVED** [review]
