### PR TITLE
Bugfix/modal destroy all with context

### LINKED ISSUE #31190: Modal destroyAll() not working when using contextHolder
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/use-hooks-to-get-context-antd4166-forked-7qizm)

### Steps to reproduce
When opening modal from Modal.useModal(), destroyAll function won't work.

### What is expected?
destroyAll function should close all opened modals

### What is actually happening?
nothing

| Environment | Info |
|---|---|
| antd | 4.16.6 |
| React | 16.14.0 |
| System | Ubuntu 20.04 |
| Browser | 89.0.2 |

### PR DESCRIPTION
**Pull request by ds1371dani**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/31190

### 💡 Background and solution

I had created this issue some time ago and there was a PR for it, but it never merged (because of lack of response from creator).
https://github.com/ant-design/ant-design/pull/31626
https://github.com/ant-design/ant-design/pull/31629

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | :lady_beetle: Fix Modal.useModal `destroyAll` not working |
| 🇨🇳 Chinese | :lady_beetle: 修复 Modal.useModal `destroyAll` 不工作 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/modal/useModal/index.tsx [hunk 1]
```diff
@@ -69,6 +70,8 @@ function useModal(): readonly [
 
         closeFunc = holderRef.current?.patchElement(modal);
 
+        if (closeFunc) destroyFns.push(closeFunc);
```
Comment (yoyo837) [inline components/modal/useModal/index.tsx:73]:
```suggestion
        if (closeFunc) {
          destroyFns.push(closeFunc);
        }
```

**Review by yoyo837 — APPROVED** [review]
