### PR TITLE
fix: Slider handler should be movable after click tracker

### LINKED ISSUE #43728: The slider does not move after clicking on a random spot on the track
### Reproduction link

[https://ant.design/components/slider](https://ant.design/components/slider)

### Steps to reproduce

https://github.com/ant-design/ant-design/assets/803674/9a9b6d3e-463a-48f0-a51b-07b0c827ce92

### What is expected?

After grabbing the slider, it should move regardless of whether we clicked on it or on a random spot on the track. 
Expected behavior is as shown here https://3x.ant.design/components/slider/. As you can see, in the third version, everything was working correctly.

### What is actually happening?

After clicking on a random spot on the track, the slider moves, but it doesn't respond to the mouse. 

| Environment | Info |
| --- | --- |
| antd | 5.7.2 |
| React | 18 |
| System | Mac |
| Browser | All |

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/react-component/slider/pull/948

close https://github.com/ant-design/ant-design/issues/43728

### 💡 Background and solution

图片

点击轨道直接移动鼠标时，滑块不会移动。MUI 则可以：https://mui.com/material-ui/react-slider/

| before | MUI | After |
| --- | --- | --- |
|  Nov-03-2023 00-16-46 | Nov-03-2023 00-16-34 | Nov-03-2023 00-16-38 |

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Slider handler should be movable after click tracker.          |
| 🇨🇳 Chinese | 优化 Slider 交互体验，点击轨道后可直接拖拽滑块。          |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 8b9bfab</samp>

Updated `rc-slider` dependency to fix slider component bugs. This was part of a larger dependency update for the `ant-design` UI library.

### <samp>🤖 Generated by Copilot at 8b9bfab</samp>

* Updated several dependencies to fix issues and improve performance ([link](https://github.com/ant-design/ant-design/pull/45651/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L150-R150),

### CODE REVIEW

File: components/slider/style/index.tsx [hunk 1]
```diff
@@ -145,7 +145,7 @@ const genBaseStyle: GenerateStyle<SliderToken> = (token) => {
         height: token.handleSize,
         outline: 'none',
 
-        [`${componentCls}-dragging`]: {
+        '&-dragging': {
```
Comment (afc163) [inline components/slider/style/index.tsx:148]: 顺手修一个样式丢失的问题。

Comment (afc163) [inline components/slider/style/index.tsx:148]:
```suggestion
        [`${componentCls}-dragging`]: {
```

**Review by li-jia-nan — APPROVED** [review]

**Comment by afc163** [comment]
原来之前有人提过了：https://github.com/ant-design/ant-design/issues/43728
