### PR TITLE
fix(upload): `file` in `fileList` should get `uid` at first

### LINKED ISSUE #30080: Unnecessary image FileList appearing
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/brave-jepsen-4o5ih?file=/src/App.js:1851-1857)

### Steps to reproduce
1. Open the codesandbox URL
2. You will see the unnecessary image file list

### What is expected?
Only coded input image URLs should appear

### What is actually happening?
Extra 2 images are appearing along with input images

image

| Environment | Info |
|---|---|
| antd | 4.15.0 |
| React | 17 |
| System | Ubuntu 20.04 LTS |
| Browser | Chrome 89 |

### PR DESCRIPTION
**Pull request by jameslahm**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
Fix #30080

### 💡 Background and solution
Originally, `file` in `fileList` get `uid` in `useEffect`, which will cause `key` is undefined in `CSSMotionList` and other trouble in update. Using `useMemo` should get rid of this.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Upload unnecessary `fileList`. |
| 🇨🇳 Chinese | 修复 Upload 多余的文件初始列表。 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by yoyo837 — APPROVED** [review]

File: components/upload/Upload.tsx [hunk 1]
```diff
@@ -73,7 +73,7 @@ const InternalUpload: React.ForwardRefRenderFunction<unknown, UploadProps> = (pr
   }, []);
 
   // Control mode will auto fill file uid if not provided
-  React.useEffect(() => {
+  React.useMemo(() => {
```
Comment (zombieJ) [inline components/upload/Upload.tsx:76]: Seems a little hack but not found better way.

**Review by zombieJ — APPROVED** [review]
