### PR TITLE
fix: BreadcrumbItem menu type

### LINKED ISSUE #41361: TypeScript error with selectable property in BreadcrumbItem
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/typescript-error-with-selectable-property-in-breadcrumbitem-e2dcuv)

### Steps to reproduce

1. Install `antd` version 5.3.0 and `typescript` version 4.9.5 in a React Typescript project.
2. Create a `BreadcrumbItem` component with a `menu` property that includes a `selectable` property set to `true`.
3. Attempt to compile the project.

### What is expected?

The project should compile the project without errors.

### What is actually happening?

The compiler generates the following error:

(property) selectable: boolean
Type '{ items: DropdownItemType[]; selectable: true; onClick: ({ key: subtopicIndex }: { key: any; }) => void; }' is not assignable to type 'Omit<MenuProps | undefined, "items"> & { items?: MenuItem[] | undefined; }'.
  Object literal may only specify known properties, and 'selectable' does not exist in type 'Omit<MenuProps | undefined, "items"> & { items?: MenuItem[] | undefined; }'.ts(2322)
BreadcrumbItem.d.ts(17, 5): The expected type comes from property 'menu' which is declared here on type 'IntrinsicAttributes & BreadcrumbItemProps'

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | 18.2.0 |
| System | Mac OS |
| Browser | Chrome v111.0.5563.64 |

---
It seems that the selectable property is not recognized as a known property in the Omit<MenuProps | undefined, "items"> & { items?: MenuItem[] | undefined; } type, which causes a TypeScript error when compiling the project. The issue appears to be related to changes made in antd version 5.3.0, as the project was compiling without errors using earlier versions of antd.

We would appreciate any assistance in resolving this issue. Thank you!

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #41361

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix Breadcrumb.Item `menu` type not working.        |
| 🇨🇳 Chinese |    修复 Breadcrumb.Item `menu` 类型定义不正确的问题。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

File: components/breadcrumb/BreadcrumbItem.tsx [hunk 1]
```diff
@@ -11,7 +11,7 @@ export interface SeparatorType {
   key?: React.Key;
 }
 
-type MenuType = DropdownProps['menu'];
+type MenuType = Required<DropdownProps>['menu'];
```
Comment (acyza) [inline components/breadcrumb/BreadcrumbItem.tsx:14]:
```suggestion
type MenuType = NonNullable<DropdownProps['menu']>;
```
