### PR TITLE
fix: upload event should not trigger the file out of maxCount

### LINKED ISSUE #43031: Upload 组件在上传列表超过 maxCount 数量时，再进行文件上传将不会在文件上传成功/失败回调 onChange 方法
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/xian-zhi-shu-liang-antd-4-24-10-forked-ch8kvj)

### Steps to reproduce

1. 先上传文件直至达到maxCount 要过的数量
2. 然后再进行上传文件将只会触发一次 onChange 且 file 的 status 是 uploading 状态
3. 后续文件上传成功或者失败都不会继续出发onChange, 且上传列表也不会更新

### What is expected?

需要进行确认，期望是覆盖掉最老的文件，还是说需要弹窗提示“超过文件数量不能继续上传”而且第一次触发的onChange file 的 status 是 error 状态

### What is actually happening?

Upload 组件在上传列表超过 maxCount 数量时，再进行文件上传不会在文件上传成功/失败回调 onChange 方法

| Environment | Info |
| --- | --- |
| antd | 4.24.10 |
| React | 18.0.0 |
| System | MaxOS Big Sur 11.3.1 |
| Browser | 114.0.5735.106 |

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #43031

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix Upload trigger extra `onChange` event when upload the file exceeds `maxCount`.   |
| 🇨🇳 Chinese |   修复 Upload 配置 `maxCount` 后，上传超出范围的文件仍然会触发 `onChange` 事件的问题。        |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at d7aa1c7</samp>

This pull request enhances the Upload component by adding a `maxCount` prop to limit the number of files and fixing a related bug. It also improves the test case for this feature in `upload.test.tsx`.

### <samp>🤖 Generated by Copilot at d7aa1c7</samp>

*  Add logic to limit the `onChange` callback for files that exceed the `maxCount` prop in the Upload component ([link](https://github.com/ant-design/ant-design/pull/43034/files?diff=unified&w=0#diff-a2e7152a9f97730a600f9bda0bf15029cce0148818a6ee8d2a037fafc101427dL110-R116), [link](https://github.com/ant-design/ant-design/pull/43034/files?diff=unified&w=0#diff-a2e7152a9f97730a600f9bda0bf15029cce0148818a6ee8d2a037fafc101427dL132-R143))
*  Remove unnecessary `await` keyword from the mock `removePromise` call in the test case for the Upload component ([link](https://github.com/ant-design/ant-design/pull/43034/files?diff=unified&w=0#diff-72ea20f11250bb41ad13135c67af7e612d56bd43c8e24ad4db9c782f58306ac7L483-R483))
*  Add assertion to the test case to verify that the `onChange` callback is only called for the file that matches the `maxCount` prop ([link](https://github.com/ant-design/ant-design/pull/43034/files?diff=unified&w=0#diff-72ea20f11250bb41ad13135c67af7e612d56bd43c8e24ad4db9c782f58306ac7R774-R778))

### CODE REVIEW

**Review by kiner-tang — APPROVED** [review]

**Review by MadCcc — APPROVED** [review]

File: components/upload/Upload.tsx [hunk 1]
```diff
@@ -129,9 +132,15 @@ const InternalUpload: React.ForwardRefRenderFunction<UploadRef, UploadProps> = (
       changeInfo.event = event;
     }
 
-    flushSync(() => {
-      onChange?.(changeInfo);
-    });
+    if (
+      !exceedMaxCount ||
+      // We should ignore event if current file is exceed `maxCount`
+      cloneList.map((f) => f.uid).includes(file.uid)
```
Comment (BoyYangzai) [inline components/upload/Upload.tsx:138]: cloneList.find(f => f.uid === file.uid)

File: components/upload/Upload.tsx [hunk 2]
```diff
@@ -129,9 +132,15 @@ const InternalUpload: React.ForwardRefRenderFunction<UploadRef, UploadProps> = (
       changeInfo.event = event;
     }
 
-    flushSync(() => {
-      onChange?.(changeInfo);
-    });
+    if (
+      !exceedMaxCount ||
+      // We should ignore event if current file is exceed `maxCount`
+      cloneList.find((f) => f.uid === file.uid)
```
Comment (yoyo837) [inline components/upload/Upload.tsx:138]: 不使用返回值,应该some?

Comment (li-jia-nan) [reply components/upload/Upload.tsx:138]: +1
