### PR TITLE
fix: Select alignment issue when label is Typography

### LINKED ISSUE #40421: Text alignment issue with Typography component in Select component
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/basic-usage-antd-5-1-6-forked-izq79l?file=/demo.tsx)

image

### Steps to reproduce

- Set value with antd typography component for Select component
- Select the value
- Text is not aligned center

### What is expected?

Text alignment is centered

### What is actually happening?

Text alignment is not centered

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 18.2.0 |
| System | macOS Ventura |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close #40421

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Select alignment issue when label is Typography         |
| 🇨🇳 Chinese | 修复 Select 的 label 为 Typography 组件时的选中文本对齐问题。          |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 50a9a20</samp>

Fixed some style issues and bugs in the `select` component and its variants. Added a new `antCls` property to the `genSizeStyle` function to support customizing the ant design class prefix.

### <samp>🤖 Generated by Copilot at 50a9a20</samp>

* Add `antCls` property to `token` parameter of `genSizeStyle` function in both `multiple.tsx` and `single.tsx` files to access ant-design prefix class name for typography components ([link](https://github.com/ant-design/ant-design/pull/44756/files?diff=unified&w=0#diff-bdbff67724f9cb38a989e08057fac4b1dbbffcb715ecb8597db624ffd72f3ab5L19-R19), [link](https://github.com/ant-design/ant-design/pull/44756/files?diff=unified&w=0#diff-d074c411bd6636664ae405c3b7a1744f68b0d236d82b2adbef155746711ec8a2L7-R7))
* Add CSS rule to set display property of typography components to inline in `genSizeStyle` function in both `multiple.tsx` and `single.tsx` files to fix overflow bug for select components ([link](https://github.com/ant-design/ant-design/pull/44756/files?diff=unified&w=0#diff-bdbff67724f9cb38a989e08057fac4b1dbbffcb715ecb8597db624ffd72f3ab5R142-R146), [link](https://github.com/ant-design/ant-design/pull/44756/files?diff=unified&w=0#diff-d074c411bd6636664ae405c3b7a1744f68b0d236d82b2adbef155746711ec8a2R55-R59))

### CODE REVIEW

File: components/select/style/index.tsx [hunk 1]
```diff
@@ -239,7 +239,14 @@ const genBaseStyle: GenerateStyle<SelectToken> = (token) => {
       [`${componentCls}-selection-item`]: {
         flex: 1,
         fontWeight: 'normal',
+        position: 'relative',
+        userSelect: 'none',
```
Comment (afc163) [inline components/select/style/index.tsx:243]: 两段重复的代码也合并过来。

**Review by kiner-tang — APPROVED** [review]
