### PR TITLE
fix: table pagination theme color broken with small size

### LINKED ISSUE #52334: The itemBg property of the Pagination component does not apply without using !important
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/gracious-brattain-5zm8km)

### Steps to reproduce

1. Configure a custom theme using `ThemeConfig` in an Ant Design project.
2. Change the `Pagination.itemBg` property to a color like `"red"`.
3. Notice that the background color is not applied to the component.
4. Apply `!important` to the `itemBg` value (e.g., `"red !important"`).
5. Observe that the background color is applied but overrides other styles

### What is expected?

The background color (`itemBg`) should be applied correctly without the need to use `!important`.

### What is actually happening?

- Without `!important`: The background color defined in `itemBg` is not applied.

| Environment | Info |
| --- | --- |
| antd | 5.23.0 |
| React | 18 |
| System | Windows |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by Can-Chen**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - fix #52334

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - 当size为small时，会命中genPaginationMiniStyle把所有背景色设置为透明的css代码，删除对应的设置。
> - 该代码是为了解决在pagination disable状态下hover会改变颜色的问题，但是在设置主题后还是会存在该问题#43829

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |         table pagination theme color broken with small size    |
| 🇨🇳 Chinese |    table组件size属性设置为small 导致table下pagination主题设置不生效的问题       |

## Summary by CodeRabbit

- **样式**
  - 更新了禁用分页项的视觉效果，现在采用透明背景。
  - 移除了小分页项中不活跃状态下的背景和边框样式，简化了整体视觉效果。

### CODE REVIEW

File: components/pagination/style/index.ts [hunk 1]
```diff
@@ -140,6 +140,8 @@ const genPaginationDisabledStyle: GenerateStyle<PaginationToken, CSSObject> = (t
       [`${componentCls}-item`]: {
         cursor: 'not-allowed',
 
+        backgroundColor: 'transparent',
```
Comment (afc163) [inline components/pagination/style/index.ts:143]:
```suggestion
        backgroundColor: 'transparent',
```

**Review by afc163 — APPROVED** [review]

**Review by afc163 — APPROVED** [review]
