### PR TITLE
fix: Table loading compatibility

### LINKED ISSUE #22733: 4.0.4 Table组件中对loading属性使用spin对象时，spin中的spinning默认值未生效
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/yuanchengjiazaishuju-ant-design-demo-8qodq)

### Steps to reproduce
1. 通过HTTP加载远程数据时使用代码设置Table组件的loading属性
```
this.setState({ loading: {tip: "加载数据..."} })
```
2. 点击Table组件中的翻页按钮，Table组件不出现加载中状态，且不显示“加载数据...”提示文字
3. 修改设置Table组件loading属性的代码为
```
this.setState({ loading: {tip: "加载数据...", spinning: true} })
```
4. 点击Table组件中的翻页按钮，Table组件正常出现加载中状态，并显示“加载数据...”提示文字

### What is expected?
使用 `{tip: "加载数据..."}` 设置Table组件的loading属性后，Table组件正常出现加载中状态，并显示“加载数据...”提示文字

### What is actually happening?
Table组件不出现加载中状态，且不显示“加载数据...”提示文字

必须显式设置spin中的spinning属性为true

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.12.0 |
| System | MacOS 10.14.4 |
| Browser | Google Chrome 80.0.3987.149 |

---
原来使用3.x版本时正常

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #22733

### 💡 Background and solution

```jsx
<Table loading={{ tip: 'tip' }} />

should be loading.
```

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/table/Table.tsx [hunk 1]
```diff
@@ -398,20 +398,7 @@ function Table<RecordType extends object = any>(props: TableProps<RecordType>) {
...
-          break;
-
-        case 'both':
-          topPaginationNode = renderPagination();
-          bottomPaginationNode = renderPagination();
-          break;
-
-        default:
-          bottomPaginationNode = renderPagination();
-      }
```
Comment (afc163) [inline components/table/Table.tsx]: 不需要兼容，从来没支持过。
