### PR TITLE
fix: Search crash in AutoComplete

### LINKED ISSUE #25031: Search in AutoComplete throw exceptions
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/2d6e6d](https://riddle.alibaba-inc.com/riddles/2d6e6d)

### Steps to reproduce
click search

### What is expected?
No error

### What is actually happening?
Uncaught TypeError: Cannot read property 'input' of undefined

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.8.4 |
| System | ios |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix #25031

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix Input.Search as AutoComplete customize component crash issue.        |
| 🇨🇳 Chinese |   修复 Input.Search 作为 AutoComplete 自定义组件会崩溃的问题。      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/input/Search.tsx [hunk 1]
```diff
@@ -46,7 +47,7 @@ const Search = React.forwardRef<unknown, SearchProps>((props, ref) => {
       return;
     }
     if (customOnSearch) {
-      customOnSearch(inputRef.current.input.value, e);
+      customOnSearch(inputRef.current?.input.value!, e);
```
Comment (afc163) [inline components/input/Search.tsx:50]: ? 和 ! 感觉是矛盾的。

Comment (zombieJ) [reply components/input/Search.tsx:50]: 第一个一个是判断是否有 instance。第二个是有了 instance 一定会有 value。
