### PR TITLE
fix: Upload onChange immutable

### LINKED ISSUE #22281: Form component Upload UI render error
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-kfqm5)

### Steps to reproduce
依次上传就行

### What is expected?
正确展示上传状态

### What is actually happening?
上传完成，UI显示上传中

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.8.6 |
| System | macOs Mojave |
| Browser | Chrome 版本 80.0.3987.132（正式版本） （64 位） |

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #22281

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Adjust Upload `onChange` return `fileList` is immutable data to avoid render issue.       |
| 🇨🇳 Chinese |     调整 Upload `onChange` 返回参数 `fileList` 为不可变数据以解决渲染问题。     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/tree/DirectoryTree.tsx [hunk 1]
```diff
@@ -171,24 +171,24 @@ class DirectoryTree extends React.Component<DirectoryTreeProps, DirectoryTreeSta
...
       newEvent.selectedNodes = convertDirectoryKeysToNodes(treeData, newSelectedKeys);
     } else {
       // Single click
-      newSelectedKeys = [eventKey];
-      this.lastSelectedKey = eventKey;
+      newSelectedKeys = [key];
+      this.lastSelectedKey = key;
       this.cachedSelectedKeys = newSelectedKeys;
-      newEvent.selectedNodes = [event.node.props.data];
+      newEvent.selectedNodes = convertDirectoryKeysToNodes(treeData, newSelectedKeys);
```
Comment (afc163) [inline components/tree/DirectoryTree.tsx]: 为啥改了 Tree。
