### PR TITLE
fix: React 17 findDOMNode is deprecated

### LINKED ISSUE #22493: Using <Button> results in "findDOMNode is deprecated in StrictMode" warning
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate * (It was reported by somebody else but not through Issue Creator and it got auto-closed).

### Reproduction link
[https://github.com/latobibor/antd-tryout/commit/e373cb5038d88bf73358a05c8b37e0369dbaf478](https://github.com/latobibor/antd-tryout/commit/e373cb5038d88bf73358a05c8b37e0369dbaf478)

### Steps to reproduce
1. install dependencies (npm i)
2. run app (npm start)
3. check console

### What is expected?
No warnings should be displayed.

### What is actually happening?
A warning message will appear in console.log stating "Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Wave which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here:"

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.1 |
| System | Windows 8.1 |
| Browser | Chrome 80 |

---
The source of the problem is coming from `<Button />` component.

See the file in question:
https://github.com/latobibor/antd-tryout/commit/e373cb5038d88bf73358a05c8b37e0369dbaf478#diff-b525f6f7c3584f9af17112d37dae3a42

### PR DESCRIPTION
**Pull request by fardad-dev**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]
findDOMNode is Deprecated we should use ref.
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #22493
ref https://github.com/ant-design/ant-design/issues/26136

### 💡 Background and solution
Use ref instead of findDOMNode

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by trane294** [comment]
Please merge

**Comment by goulkreek** [comment]
Please Merge. "findDOMNode" warning is really annoying.

**Comment by zombieJ** [comment]
Could you help to use `rc-util` func instead?

https://github.com/react-component/util/blob/master/src/ref.ts
https://github.com/react-component/util/blob/master/src/Dom/findDOMNode.ts

**Comment by hosseinmd** [comment]
> Could you help to use `rc-util` func instead?
> 
> https://github.com/react-component/util/blob/master/src/ref.ts
> https://github.com/react-component/util/blob/master/src/Dom/findDOMNode.ts

Done.

File: components/_util/wave.tsx [hunk 1]
```diff
@@ -195,7 +198,19 @@ export default class Wave extends React.Component<{ insertExtraNode?: boolean }>
     const { children } = this.props;
     this.csp = csp;
 
-    return children;
+    if (!React.isValidElement(children)) return children;
+
+    let ref: React.Ref<any> = this.containerRef;
+    if ((children as any).ref) {
```
Comment (zombieJ) [inline components/_util/wave.tsx:204]: Use `supportRef` to check element need ref or not:
https://github.com/ant-design/ant-design/blob/0fec3aa6022c2c0ca5f11a4ff128cfa0082d848a/components/form/FormItem.tsx#L357

**Comment by hosseinmd** [comment]
used supportRef

File: components/_util/wave.tsx [hunk 2]
```diff
@@ -195,7 +199,19 @@ export default class Wave extends React.Component<{ insertExtraNode?: boolean }>
...
+    if (supportRef(children)) {
+      ref = setAndForwardRef({
+        getForwardedRef: () => (children as any).ref,
+        setLocalRef: _ref => {
+          (this.containerRef as any).current = _ref;
+        },
+      });
+    }
+
+    return cloneElement(children, { ref });
```
Comment (zombieJ) [inline components/_util/wave.tsx:214]: Use `composeRef` directly instead of `setAndForwardRef`:

```tsx
if (supportRef(children)) {
  return cloneElement(children, {
    ref: composeRef(this.containerRef, children.ref),
  });
}
```

Comment (zombieJ) [reply components/_util/wave.tsx:214]: PS: `composeRef` is in `rc-util/lib/ref`

**Comment by hosseinmd** [comment]
I removed setAndForwardRef and used composeRef instead

**Comment by goulkreek** [comment]
Fixed for me with release 4.8.4 !
Thx a lot !

**Comment by ogrotten** [comment]
I am receiving this error on 4.9.4 using Upload component. It is the only component in use as I'm just getting started on this project.

My code:

```
import React, { useState } from 'react';

import { Upload, Button, message } from 'antd';
import { UploadOutlined } from '@ant-design/icons';

import "antd/dist/antd.css";
import './App.css';

function App() {
	const [fileList, updateFileList] = useState([]);
	const props = {
		fileList,
		beforeUpload: file => {
			if (file.type !== 'application/json') {
				message.error(`${file.name} is not a json file`);
			}
			return file.type === 'application/json';
		},
		onChange: info => {
			console.log(info.fileList);
			// file.status is empty when beforeUpload return false
			updateFileList(info.fileList.filter(file => !!file.status));
		},
	};
	return (
		<div className="App">
			<Upload {...props}>
				<Button icon={<UploadOutlined />}>Upload json only</Button>
			</Upload>
		</div>
	);
}

export default App;
```

with a very few changes, it is exactly the example from the docs: https://ant.design/components/upload/#components-upload-demo-upload-png-only

**Comment by casulit** [comment]
Still receiving this error @4.10.0

**Comment by arocki7** [comment]
I still have issues with 4.10.2.

**Comment by Ildorado** [comment]
Still have the same issue with 4.11.2

**Comment by SaadEla** [comment]
same issue on :
antd:  4.12 
 react: 17.0

**Comment by yoyo837** [comment]
trace in https://github.com/ant-design/ant-design/issues/26136

**Comment by LevieGu** [comment]
Still have the same issue with 4.12.3 and library version 17.0.1 when i used Menu component

**Comment by sberequek** [comment]
Hi, the problem is still present with antd 4.15.0 and react 17.0.2 when I use the Menu component.

**Comment by leandrosnx** [comment]
Hi, any updates?

**Comment by codetestmg** [comment]
any updates ?
Thanks

**Comment by jmaric** [comment]
I get same error on Menu component, any update?

**Comment by bamtheboozle** [comment]
still happens when using the Menu component with 5.3.0

**Comment by qinshuze** [comment]
2024年了当前是5.16.5版本使用Button组件依旧会出现警告：react-dom.development.js:86 Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

**Comment by thomastvedt** [comment]
I get this on antd version `5.20.5`, looks like it's coming from Tooltip / Popover component.
