### PR TITLE
fix Layout style

### LINKED ISSUE #4459: 侧边布局当内容过长时Sider与子Layout变为垂直排列
#### Environment(required)

- antd version: 2.6.0
- OS and its version: MacOS 10.12.2
- Browser and its version: Google Chrome 55.0.2883.95， Safari 10.0.2

#### What did you do? Please provide steps to re-produce your problem.

使用布局中的侧边布局，在Content部件中放入一段长一点的文字

#### What do you expected?

Sider与子Layout水平排列

#### What happen?

Sider与子Layout垂直排列， 原来子Layout所占据位置空白

#### Re-producible online demo

http://codepen.io/aarryy/pen/WRNzQg

### PR DESCRIPTION
**Pull request by ddcat1115**
Layout `flex-direction` will variable according to whether has Sider

close #4459

### CODE REVIEW

File: components/layout/layout.tsx [hunk 1]
```diff
@@ -16,36 +17,50 @@ function generator(props) {
...
+    let hasSider;
+    if (name === 'Layout') {
+      React.Children.forEach(children, (ele: React.ReactElement<any>) => {
+        if (ele && ele.props && ele.props.name === 'Sider') {
+          hasSider = true;
+        }
+      });
+    }
+    const divCls = classNames(className, prefixCls, {
+      [`${prefixCls}-hasSider`]: hasSider,
```
Comment (afc163) [inline components/layout/layout.tsx]: has-sider
