### PR TITLE
fix: modal mask should block pointer events when opened

### LINKED ISSUE #46129: Frequently clicking on confirm modal button would open multiple modals
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-48k2jl)

### Steps to reproduce

Clicking on the button multiple times

### What is expected?

Exactly one modal is open, which is the default behavior in v4.

### What is actually happening?

Multiple modals are open, the click operations are not blocked

| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | 18 |
| System | mac big sur |
| Browser | chrome |

### LINKED ISSUE #47499: dropdown 打开 Modal 时，若打开时鼠标在其它 dropdown 上，其它 dropdown 会展开一下
### Reproduction link

[https://stackblitz.com/edit/react-lzj8ld?file=demo.tsx](https://stackblitz.com/edit/react-lzj8ld?file=demo.tsx)

### Steps to reproduce

1、hover 到第一个 dropdown，点击 item 打开 Modal（点击 item 时鼠标要在其它 dropdown 上）

### What is expected?

其它 dropdown 不会展开

### What is actually happening?

其它 dropdown 展开了

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | latest |
| System | mac |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
fix https://github.com/ant-design/ant-design/issues/46129
fix https://github.com/ant-design/ant-design/issues/47499

### 💡 Background and solution
这段代码是为了修复 https://github.com/ant-design/ant-design/issues/44197 添加的，实测删掉之后不会复现

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix Modal that pointer events will triggered during openning animation.        |
| 🇨🇳 Chinese |        修复 Modal 在打开期间会触发其他鼠标事件的问题。   |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

File: components/modal/style/index.ts [hunk 1]
```diff
@@ -131,12 +131,6 @@ export const genModalMaskStyle: GenerateStyle<TokenWithCommonCls<AliasToken>> =
           overflow: 'auto',
           outline: 0,
           WebkitOverflowScrolling: 'touch',
-
-          // Note: Firefox not support `:has` yet
-          [`&:has(${componentCls}${antCls}-zoom-enter), &:has(${componentCls}${antCls}-zoom-appear)`]:
-            {
-              pointerEvents: 'none',
-            },
```
Comment (yoyo837) [inline components/modal/style/index.ts:139]: 不会重新引起 https://github.com/ant-design/ant-design/issues/43860 https://github.com/ant-design/ant-design/issues/44197 的问题吗？

Comment (MadCcc) [reply components/modal/style/index.ts:139]: 这个问题后来用其他方式解决过，可以用 https://codesandbox.io/s/antd-reproduction-template-forked-fh43nt 这个来测一下，我是没有复现的
