### PR TITLE
fix(upload): adjust type declaration for the onError of customRequest

### LINKED ISSUE #26570: The type declaration for the onError function of the upload component's customRequest function is incomplete.
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Other parameters of the onError function can be used more smoothly in the Typescript environment

### What does the proposed API look like?
```diff
export interface RcCustomRequestOptions {
    onProgress: (event: {
        percent: number;
    }, file: RcFile) => void;
-   onError: (error: Error) => void;
+   onError: (error: Error, response?: any, file?: UploadFile) => void;
    onSuccess: (response: object, file: RcFile) => void;
    data: object;
    filename: string;
    file: RcFile;
    withCredentials: boolean;
    action: string;
    headers: object;
}
```

Ref: 
- [onError code](https://github.com/ant-design/ant-design/blob/88ae028321e31b0270c9a48aec51abacbbdc5125/components/upload/Upload.tsx#L141)
- [old typing](https://github.com/ant-design/ant-design/blob/88ae028321/components/upload/interface.tsx#L18)

### PR DESCRIPTION
**Pull request by yingpengsha**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #26570

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix the type declaration of onError in `customRequest` options of Upload.  |
| 🇨🇳 Chinese | 修复 Upload 组件中 `customRequest` 的 `onError` 的类型定义。 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/upload/interface.tsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ export interface RcFile extends File {
 
 export interface RcCustomRequestOptions {
   onProgress: (event: { percent: number }, file: RcFile) => void;
-  onError: (error: Error) => void;
+  onError: (error: Error, response?: any, file?: UploadFile) => void;
```
Comment (Kermit-Xuan) [inline components/upload/interface.tsx:18]: the type of `file` should be `RcFile`

Comment (yingpengsha) [reply components/upload/interface.tsx:18]: Even if the [code define](https://github.com/ant-design/ant-design/blob/88ae028321e31b0270c9a48aec51abacbbdc5125/components/upload/Upload.tsx#L141) is `UploadFile`?

Comment (yingpengsha) [reply components/upload/interface.tsx:18]: ok, I agree
