### PR TITLE
fix: fix the issue about throw a warning when Splitter nested in a hidden tab panel

### LINKED ISSUE #51106: Splitter: invalid value for the "flexBasis" css style property
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/fpld9r)

### Steps to reproduce

When using the Splitter component inside a Tabs component and changing the size of the panels by dragging and finally changing the Tab the following error is generated:
"Warning: `NaN` is an invalid value for the `flexBasis` css style property."

### What is expected?

no warning

### What is actually happening?

The value for the css property "flexBasis" is NaN

| Environment | Info |
| --- | --- |
| antd | 5.21.2 |
| React | react@18.3.1 |
| System | macOS 14.6.1 |
| Browser | Chrome Version 129.0.6668.90(x86_64) |

### PR DESCRIPTION
**Pull request by kiner-tang**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [X] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

close #51106

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix the issue about throw a warning when Splitter nested in a hidden tab panel |
| 🇨🇳 Chinese | 修复当 Splitter 嵌套在一个隐藏的 Tabs 面板中时抛出警告的问题。  |

### CODE REVIEW

File: components/splitter/Splitter.tsx [hunk 1]
```diff
@@ -71,6 +71,12 @@ const Splitter: React.FC<React.PropsWithChildren<SplitterProps>> = (props) => {
   const [containerSize, setContainerSize] = useState<number>(100);
 
   const onContainerResize: GetProp<typeof ResizeObserver, 'onResize'> = (size) => {
+    const containerSize = isVertical ? size.offsetHeight : size.offsetWidth;
+    // Skip when container has no size, Such as nested in a hidden tab panel
+    // to fix: https://github.com/ant-design/ant-design/issues/51106
+    if (containerSize === 0) {
+      return;
+    }
     setContainerSize(isVertical ? size.offsetHeight : size.offsetWidth);
```
Comment (afc163) [inline components/splitter/Splitter.tsx:80]:
```suggestion
    setContainerSize(containerSize);
```

**Review by afc163 — APPROVED** [review]
