### PR TITLE
fix: Table should not crash if filterDropdown is boolean

### LINKED ISSUE #44351: Tabe filterIcon does not work
### Reproduction link

[https://codepen.io/rustam-as/pen/qBLELZx?editors=1111](https://codepen.io/rustam-as/pen/qBLELZx?editors=1111)

### Steps to reproduce

created react app with vite and npx
added antd table to my app.jsx
in columns array there is filterIcon for add custom filter and onlick func

### What is expected?

I expect when i click filter icon it consoles some string

### What is actually happening?

it throws error "Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | react@18.2.0 |
| System | Windows 11 pro 64bit (10.0 Build 22000) |
| Browser | Google Chrome Version 110.0.5481.77 (Official Build) (64-bit) |

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/44351

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Table that would crash when `filterDropdown` do not support `ref`.          |
| 🇨🇳 Chinese |    修复 Table 组件 `filterDropdown` 不支持 `ref` 时报错的问题。       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at fab89f5</samp>

Improved the menu component's ref handling and added a regression test for the table component's filter dropdown. These changes fix a bug and enhance the performance and usability of the components.

### <samp>🤖 Generated by Copilot at fab89f5</samp>

* Import `supportRef` function to check children's ref support ([link](https://github.com/ant-design/ant-design/pull/44357/files?diff=unified&w=0#diff-fab289ecf381929ccfd1ab5e53c7170d3e249910d5774f13f2a76eca26bb6630R4))
* Modify `OverrideProvider` component to conditionally clone children with ref ([link](https://github.com/ant-design/ant-design/pull/44357/files?diff=unified&w=0#diff-fab289ecf381929ccfd1ab5e53c7170d3e249910d5774f13f2a76eca26bb6630L37-R48))
* Add test case for table component with boolean `filterDropdown` prop ([link](https://github.com/ant-design/ant-design/pull/44357/files?diff=unified&w=0#diff-d86c8b951332164873bf880555e68c0e38dfd36612b14396f4c001b7f2d1187fR2837-R2856))
* Prevent table component crash when `filterDropdown` is boolean (issue #32879, [link](https://github.com/ant-design/ant-design/pull/44357/files?diff=unified&w=0#diff-d86c8b951332164873bf880555e68c0e38dfd36612b14396f4c001b7f2d1187fR2837-R2856))

### CODE REVIEW

**Review by RedJue — APPROVED** [review]

File: components/menu/OverrideContext.tsx [hunk 1]
```diff
@@ -34,9 +35,17 @@ export const OverrideProvider = React.forwardRef<
     ],
   );
 
+  const shouldRef =
+    typeof children !== 'string' &&
```
Comment (Yuiai01) [inline components/menu/OverrideContext.tsx:39]: 感觉这里可以用 isValidElement

Comment (MadCcc) [reply components/menu/OverrideContext.tsx:39]: 等会去改一下 `supportRef`

File: components/table/__tests__/Table.filter.test.tsx [hunk 2]
```diff
@@ -2834,4 +2834,24 @@ describe('Table.filter', () => {
...
+  it('should not crash when filterDropdown is boolean', () => {
+    const tableProps = {
+      key: 'stabletable',
+      rowKey: 'name',
+      dataSource: [],
+      columns: [
+        {
+          title: 'Name',
+          dataIndex: 'name',
+          filterDropdown: true,
```
Comment (afc163) [inline components/table/__tests__/Table.filter.test.tsx:2847]: filterDropdown 为啥可以为 true？

Comment (MadCcc) [reply components/table/__tests__/Table.filter.test.tsx:2847]: ReactNode 包含 boolean

Comment (afc163) [reply components/table/__tests__/Table.filter.test.tsx:2847]: 好的，居然以前是 ok 的。

**Review by afc163 — APPROVED** [review]
