### PR TITLE
fix: Modal open should not block dropdown hidden

### LINKED ISSUE #43860: Dropdown 和Modal Button组合，打开弹框，快速hover到图标会重新唤起，但去掉modal的destroyOnClose就不会出现这个现象
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/ji-ben-antd-5-7-3-forked-4pxznq?file=/demo.tsx:604-618)

### Steps to reproduce

1.hover点开弹框
2.快速hover到图标，Dropdown会被重新唤起

### What is expected?

点开后不会被重新唤起

### What is actually happening?

有30%的概率会重新唤起

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18.0.0 |
| System | win10 |
| Browser | 谷歌 |

---
modal的destroyOnClose去掉后不会再唤起

### LINKED ISSUE #44197: Dropdown 和Modal Button组合，打开弹框，有其他时间较长处理，dropdown气泡会重新唤起
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/ji-ben-antd-5-8-3-forked-cjm8lc)

### Steps to reproduce

1.hover 10 出现气泡，打开弹框，气泡消失
2.hover 10000 出现气泡，打开弹框

### What is expected?

气泡也消失，也不会重新唤起

### What is actually happening?

气泡消失后又重新唤起

| Environment | Info |
| --- | --- |
| antd | 5.8.3 |
| React | 18.0.0 |
| System | win10 |
| Browser | 谷歌 |

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #43860
fix #44197

### 📝 Changelog

`createPortal` of React will bubble event which makes hovering the Modal as hovering the MenuItem. Since `rc-trigger` will not reopen when hover the hidden item. Let's make Modal show `pointsEvents: none` when motion.

ref: https://github.com/facebook/react/issues/11387

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix Modal in Dropdown `menu.items` makes popup reopen in some case.      |
| 🇨🇳 Chinese |   修复 Modal 在 Dropdown `menu.items` 中，展开 Modal 时快速移动鼠标会使 Dropdown 重新打开的问题。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 1a4478e</samp>

Simplified and fixed modal style code. Added `zIndex` and `pointerEvents` to improve zoom transition.

### <samp>🤖 Generated by Copilot at 1a4478e</samp>

*  Simplify the `box` function to use the `inset` property ([link](https://github.com/ant-design/ant-design/pull/44204/files?diff=unified&w=0#diff-a27b99943336f4a3b470158edbccad703a421adf1b1453c0c006e0794c7db486L65-R65))
*  Fix the bug where the modal could not be closed by clicking outside or pressing the escape key by adding `pointerEvents: 'none'` to the modal mask style ([link](https://github.com/ant-design/ant-design/pull/44204/files?diff=unified&w=0#diff-a27b99943336f4a3b470158edbccad703a421adf1b1453c0c006e0794c7db486R95))
*  Improve the modal appearance and behavior during the zoom transition by adding `zIndex` and `pointerEvents: 'none'` to the modal wrap style ([link](https://github.com/ant-design/ant-design/pull/44204/files?diff=unified&w=0#diff-a27b99943336f4a3b470158edbccad703a421adf1b1453c0c006e0794c7db486L106-R112))
*  Remove the redundant modal wrap style from the `genModalStyle` function ([link](https://github.com/ant-design/ant-design/pull/44204/files?diff=unified&w=0#diff-a27b99943336f4a3b470158edbccad703a421adf1b1453c0c006e0794c7db486L123-L130))

### CODE REVIEW

**Review by kiner-tang — APPROVED** [review]

File: components/modal/style/index.tsx [hunk 1]
```diff
@@ -103,9 +101,16 @@ export const genModalMaskStyle: GenerateStyle<TokenWithCommonCls<AliasToken>> =
 
         [`${componentCls}-wrap`]: {
           ...box('fixed'),
+          zIndex: token.zIndexPopupBase,
           overflow: 'auto',
           outline: 0,
           WebkitOverflowScrolling: 'touch',
+
+          // Note: Firefox not support `:has` yet
+          [`&:has(${componentCls}${antCls}-zoom-enter), &:has(${componentCls}${antCls}-zoom-appear)`]:
```
Comment (MadCcc) [inline components/modal/style/index.tsx:110]:
```suggestion
          [`&${componentCls}${antCls}-zoom-enter, &${componentCls}${antCls}-zoom-appear`]:
```
这里是不是等价这么写了？都是同一个元素上的选择器
