### PR TITLE
fix(Card): adjust Card border-radius in grid mode without head

### LINKED ISSUE #56198: Card.Grid uses incorrect border radius
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/headless-fire-lktfnk)

### Steps to reproduce

Nest `Card.Grid` inside `Card` component. Do not give the parent `Card` a title. Check border radius on each corner.

### What is expected?

`Grid` items inside the parent `Card` should follow the shape of the parent `Card` with the correct corner radius.

### What is actually happening?

Top row items have correct radius on the `Card.Grid` body and border, but have an additional (doubled) grey border with hard corners that stick out from the card body (requires parent `Card` to have no title). Bottom row items have hard corners on the borders. None of the corners use the correct radius that matches the regular `Card` component.

| Environment | Info |
| --- | --- |
| antd | 6.1.0 |
| React | 19.2.0 |
| System | Mac Tahoe 26.1 |
| Browser | Chrome 143 |

### PR DESCRIPTION
**Pull request by DDDDD12138**
### 🤔 This is a ...

- [x] 🐞 Bug fix

### 🔗 Related Issues

fix: #56198

### 💡 Background and Solution

In `Card.grid` mode, the component container applies `borderRadius` to the top corners by default. However, when the user does not provide a `title`, `extra`, or `tabs` (i.e., no header), this results in a visual conflict where the card has rounded corners while the internal grid items have square corners, leading to a "double border" or visual glitch at the top.

#### Solution:

~~1. Detect if the card has a header (`hasHead = title || extra || tabs`).
2. Add a specific class `${prefixCls}-contain-grid-no-head` when `isContainGrid` is true but `hasHead` is false.
3. Force `borderRadius: 0` in the styling when this class is present to ensure the card borders align perfectly with the grid items.~~

Use pure CSS with `:not(:has(> .ant-card-head))` selector to reset `borderRadius` to 0 when the card contains grid but has no header element.

#### Preview:

|Before|After|
|---|---|
|image|image|

### 📝 Change Log

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix style issue where Card displays unexpected border radius when using Card.Grid without a header.      |
| 🇨🇳 Chinese |    修复 Card 组件在使用 Card.Grid 且未设置头部内容时，边框圆角显示异常的问题。       |

### CODE REVIEW

**Review by afc163 — DISMISSED** [review]

**Comment by afc163** [comment]
ci 挂了

**Comment by DDDDD12138** [comment]
> ci 挂了

抱歉，忘更新快照了，现在可以了

**Review by meet-student — DISMISSED** [review]

**Review by thinkasany — DISMISSED** [review]

File: components/card/style/index.ts [hunk 1]
```diff
@@ -381,6 +381,11 @@ const genCardStyle: GenerateStyle<CardToken> = (token): CSSObject => {
 
     [`${componentCls}-contain-grid`]: {
       borderRadius: `${unit(token.borderRadiusLG)} ${unit(token.borderRadiusLG)} 0 0 `,
+
+      [`&${componentCls}-contain-grid-no-head`]: {
+        borderRadius: 0,
+      },
```
Comment (afc163) [inline components/card/style/index.ts:388]: https://codesandbox.io/p/sandbox/antd-card-grid-border-radius-forked-vrqlrv?file=%2Findex.tsx%3A10%2C5

纯 css 方案如何？

```css
.ant-card-contain-grid:not(:has(.ant-card-head)) {
  border-radius: 0;
}
```

Comment (DDDDD12138) [reply components/card/style/index.ts:388]: 我在你的方案基础上添加了子选择器 `>`，只检查直接子元素，避免嵌套 Card 场景下的样式误判 [demo](https://codesandbox.io/p/sandbox/antd-card-grid-border-radius-forked-y6zggc)

**Review by afc163 — APPROVED** [review]
