### PR TITLE
fix: Upload has empty space

### LINKED ISSUE #48365: Upload picture-card 顶部出现多余的空间
### Reproduction link

[https://ant.design/components/upload-cn#components-upload-demo-picture-card](https://ant.design/components/upload-cn#components-upload-demo-picture-card)

### Steps to reproduce

查看顶部

### What is expected?

无多余空间

### What is actually happening?

有多余空间

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | latest |
| System | mac |
| Browser | chrome |

---
ref: https://github.com/ant-design/ant-design/pull/48091

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #48365

### 💡 Background and solution

- 来源于 #17897 为了以块状区域展示支持点击。当时因为看是 `span` 所以选择了 `inline-block`，但是实际上照片墙总是占满区域，因而切换成 `block` 是安全的。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix Upload `listType` with `picture-card` or `picture-circle` has additional space on top.     |
| 🇨🇳 Chinese |     修复 Upload 配置 `listType` 为 `picture-card` 或 `picture-circle` 时，上方有额外空隙的问题。     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by li-jia-nan — DISMISSED** [review]

**Review by crazyair — DISMISSED** [review]

File: components/upload/style/picture.ts [hunk 1]
```diff
@@ -107,7 +107,7 @@ const genPictureCardStyle: GenerateStyle<UploadToken> = (token) => {
       ${componentCls}-wrapper${componentCls}-picture-circle-wrapper
     `]: {
       ...clearFix(),
-      display: 'inline-block',
+      display: 'block',
       width: '100%',
```
Comment (afc163) [inline components/upload/style/picture.ts:111]: width: '100%', 就不需要了吧。

**Review by li-jia-nan — APPROVED** [review]

**Review by MadCcc — APPROVED** [review]
