### PR TITLE
fix: PageHeader style breaks when title is too long

### LINKED ISSUE #15664: PageHeader 文字过多超出换行了
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/4qn7nvozy7)

### Steps to reproduce
输入超长的 title 后可以看到

### What is expected?
正确处理换行逻辑

### What is actually happening?
样式有问题

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.0 |
| System | Mac |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #15664

### 💡 Background and solution

before ❌ | after ✅
---|---
image | image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix PageHeader style breaks when `title` is too long and improve it's responsive design. |
| 🇨🇳 Chinese | 修复 PageHeader `title` 超长时布局被破坏的问题并优化响应式表现。 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/page-header/demo/responsive.md](https://github.com/ant-design/ant-design/blob/fix-page-header-style/components/page-header/demo/responsive.md)

### CODE REVIEW

File: components/page-header/index.tsx [hunk 1]
```diff
@@ -97,45 +113,54 @@ const renderChildren = (prefixCls: string, children: React.ReactNode) => {
...
-        style,
-        footer,
-        children,
-        breadcrumb,
-        className: customizeClassName,
-      } = props;
-      let ghost: undefined | boolean = true;
+const PageHeader: React.FC<PageHeaderProps> = props => {
+  const [compact, updateCompact] = React.useState(false);
+  const onResize = ({ width }: { width: number }) => {
```
Comment (afc163) [inline components/page-header/index.tsx:118]: 这个参数没有类型，不得已声明了一下。
