### PR TITLE
fix: update rc-virtual-list and fix scrollbar color in dark theme

### LINKED ISSUE #46177: table开启虚拟滚动的时候，滚动条的颜色没有变化，在dark模式下看不清，可以添加一个token去修改这个颜色吗？
### Reproduction link

[https://ant-design.antgroup.com/components/table-cn?theme=dark](https://ant-design.antgroup.com/components/table-cn?theme=dark)

### Steps to reproduce

官网调成深色模式就可以看到

### What is expected?

期望滚动条颜色跟着变化

### What is actually happening?

滚动条颜色没有变化

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | 18.2 |
| System | mac最新 |
| Browser | chrome最新 |

### LINKED ISSUE #47565: Virtual List in Dark Mode lacking some contrast at the scrollbar
### Reproduction link

[https://ant.design/components/table?theme=dark#components-table-demo-virtual-list](https://ant.design/components/table?theme=dark#components-table-demo-virtual-list)

### Steps to reproduce

Seen in the dark mode, the scrollbar lacking some contrast. The scrollbar mostly invisible.

### What is expected?

I want to see the scrollbar to be visible

### What is actually happening?

The scrollbar mostly invisible.

| Environment | Info |
| --- | --- |
| antd | 5.14.2 |
| React | React 18.2.0 |
| System | Windows 11 |
| Browser | Version 120.0.6099.225 |

### LINKED ISSUE #50316: 暗色主题下，Tree的滚动条颜色难以辨认
### Reproduction link

[Edit on StackBlitz](https://stackblitz.com/edit/antd-reproduce-5x-kcuhn7?file=demo.tsx)

### Steps to reproduce

- 使用暗色主题
- 设置Tree的height并添加数据使其出现滚动条

### What is expected?

滚动条有更明显的颜色

### What is actually happening?

滚动条颜色几乎和背景颜色一样

| Environment | Info |
| --- | --- |
| antd | 5.20.0 |
| React | * |
| System | windows 11 |
| Browser | Edge 125 |

### PR DESCRIPTION
**Pull request by afc163**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

close https://github.com/ant-design/ant-design/issues/50316
close https://github.com/ant-design/ant-design/issues/47565
close https://github.com/ant-design/ant-design/issues/46177

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

解法在 https://github.com/react-component/virtual-list/pull/323

| Before ❌ | After ✅ |
| --- | --- |
| 图片 | 图片 |
| [线上链接](https://ant.design/components/tree-cn?theme=dark#tree-demo-virtual-scroll) | [修复后的链接](https://fix-scrollbar-color-in-dark.ant-design.pages.dev/components/tree-cn?theme=dark#tree-demo-virtual-scroll) |

Select 因为滚动条在一个浮层背景上，效果还可以，符合预期。本次修复不动。

图片

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)! Track your changes, like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Tree/List/Table virtual scrollbar visibility in dark themes.          |
| 🇨🇳 Chinese | 修复 Tree/List/Table 等组件的虚拟滚动条样式在暗色主题下难以识别的问题。          |

### CODE REVIEW

File: components/list/style/index.ts [hunk 1]
```diff
@@ -199,6 +199,10 @@ const genBaseStyle: GenerateStyle<ListToken> = (token) => {
     [componentCls]: {
       ...resetComponent(token),
       position: 'relative',
+      // https://github.com/ant-design/ant-design/issues/47486
+      // From testing, it seems that the virtual scrollbar in rc-virtual-list will not be styled by scrollbar-color.
+      // So we need to define the style of the scrollbar color separately.
```
Comment (afc163) [inline components/list/style/index.ts]:
```suggestion
      // Fix https://github.com/ant-design/ant-design/issues/46177
```

File: components/table/style/index.ts [hunk 2]
```diff
@@ -265,6 +265,10 @@ const genTableStyle: GenerateStyle<TableToken, CSSObject> = (token) => {
     [`${componentCls}-wrapper`]: {
       clear: 'both',
       maxWidth: '100%',
+      // https://github.com/ant-design/ant-design/issues/47486
+      // From testing, it seems that the virtual scrollbar in rc-virtual-list will not be styled by scrollbar-color.
+      // So we need to define the style of the scrollbar color separately.
+      ['--rc-virtual-list-scrollbar-bg' as any]: token.tableScrollBg,
```
Comment (afc163) [inline components/table/style/index.ts]:
```suggestion
      // fix https://github.com/ant-design/ant-design/issues/46177
      ['--rc-virtual-list-scrollbar-bg' as any]: token.tableScrollBg,
```

File: components/tree/style/index.ts [hunk 3]
```diff
@@ -124,6 +124,10 @@ export const genBaseStyle = (prefixCls: string, token: TreeToken): CSSObject =>
   return {
     [treeCls]: {
       ...resetComponent(token),
+      // https://github.com/ant-design/ant-design/issues/47486
+      // From testing, it seems that the virtual scrollbar in rc-virtual-list will not be styled by scrollbar-color.
+      // So we need to define the style of the scrollbar color separately.
```
Comment (afc163) [inline components/tree/style/index.ts]:
```suggestion
      // fix https://github.com/ant-design/ant-design/issues/50316
```

File: package.json [hunk 4]
```diff
@@ -360,7 +360,8 @@
     }
   },
   "overrides": {
-    "nwsapi": "2.2.20"
+    "nwsapi": "2.2.20",
+    "rc-virtual-list": "3.19.1-0"
```
Comment (afc163) [inline package.json]:
```suggestion
    "nwsapi": "2.2.20"
```

File: package.json [hunk 5]
```diff
@@ -294,7 +294,7 @@
     "puppeteer": "^24.7.1",
     "rc-footer": "^0.6.8",
     "rc-tween-one": "^3.0.6",
-    "rc-virtual-list": "^3.17.0",
+    "rc-virtual-list": "3.19.1-0",
```
Comment (afc163) [inline package.json]:
```suggestion
    "rc-virtual-list": "^3.19.1",
```

**Review by yoyo837 — DISMISSED** [review]

File: components/tree/style/index.ts [hunk 6]
```diff
@@ -124,6 +124,8 @@ export const genBaseStyle = (prefixCls: string, token: TreeToken): CSSObject =>
   return {
     [treeCls]: {
       ...resetComponent(token),
+      // fix https://github.com/ant-design/ant-design/issues/50316
+      ['--rc-virtual-list-scrollbar-bg' as any]: token.colorSplit,
```
Comment (afc163) [inline components/tree/style/index.ts]:
```suggestion
      ['--rc-virtual-list-scrollbar-bg' as const]: token.colorSplit,
```

File: components/table/style/index.ts [hunk 7]
```diff
@@ -265,6 +265,8 @@ const genTableStyle: GenerateStyle<TableToken, CSSObject> = (token) => {
     [`${componentCls}-wrapper`]: {
       clear: 'both',
       maxWidth: '100%',
+      // fix https://github.com/ant-design/ant-design/issues/46177
+      ['--rc-virtual-list-scrollbar-bg' as any]: token.tableScrollBg,
```
Comment (afc163) [inline components/table/style/index.ts]:
```suggestion
      ['--rc-virtual-list-scrollbar-bg' as const]: token.tableScrollBg,
```

File: components/list/style/index.ts [hunk 8]
```diff
@@ -199,6 +199,8 @@ const genBaseStyle: GenerateStyle<ListToken> = (token) => {
     [componentCls]: {
       ...resetComponent(token),
       position: 'relative',
+      // Fix https://github.com/ant-design/ant-design/issues/46177
+      ['--rc-virtual-list-scrollbar-bg' as any]: token.colorSplit,
```
Comment (afc163) [inline components/list/style/index.ts]:
```suggestion
      ['--rc-virtual-list-scrollbar-bg' as const]: token.colorSplit,
```

**Review by yoyo837 — APPROVED** [review]

**Comment by yoyo837** [comment]
> No docstrings were generated.

What's wrong with you?
