### PR TITLE
fix: add onChange prop type definition to Steps

### LINKED ISSUE #16839: Steps lack onChange prop's type definition.
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
typescript user need onChange type definition to get through type check.

### What does the proposed API look like?
add onChange type defiinition, like below:
`onChange: (current: number) => void`

### PR DESCRIPTION
**Pull request by JonathanLee-LX**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Refactoring
- [ ] Test Case
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

close #16839

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | add onChange prop type definition to Steps |
| 🇨🇳 Chinese | 为Steps组件增加了onChange的类型定义|

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/steps/index.tsx [hunk 1]
```diff
@@ -16,6 +16,7 @@ export interface StepsProps {
   size?: 'default' | 'small';
   status?: 'wait' | 'process' | 'finish' | 'error';
   style?: React.CSSProperties;
+  onChange?: (current: number) => void
```
Comment (afc163) [inline components/steps/index.tsx]: missing `;`

Comment (JonathanLee-LX) [reply components/steps/index.tsx]: yep!
