### PR TITLE
docs: fix Rate demo type for strict mode

### LINKED ISSUE #46519: character-function.tsx demo code causing misstype error
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/customize-character-antd-5-12-3-336334?file=%2Fdemo.tsx%3A17%2C11)

### Steps to reproduce

It's a bug in the demo source code on the official page

### What is expected?

No type errors when using the code

### What is actually happening?

````typescript
<Rate defaultValue={2} character={({ index }: { index: number }) => index + 1} />
````

This line is causing the issue: 
````
Type '({ index }: { index: number; }) => ReactNode' is not assignable to type 'ReactNode | ((props: StarProps) => ReactNode)'.
  Type '({ index }: { index: number; }) => ReactNode' is not assignable to type '(props: StarProps) => ReactNode'.
    Types of parameters '__0' and 'props' are incompatible.
      Type 'StarProps' is not assignable to type '{ index: number; }'.
        Types of property 'index' are incompatible.
          Type 'number | undefined' is not assignable to type 'number'.
            Type 'undefined' is not assignable to type 'number'.ts(2322)
````
Thus making the [whole demo](https://github.com/ant-design/ant-design/blob/6a0e8a6c9c6c290f80677444ae136283ec5da414/components/rate/demo/character-function.tsx#L15C15-L15C15) unusable (see [example](https://codesandbox.io/p/sandbox/customize-character-antd-5-12-3-336334?file=%2Fdemo.tsx%3A17%2C11))
This could be fixed like this:

````typescript
<Rate defaultValue={2} character={({ index }: { index?: number }) => index !== undefined && index + 1} />
````

_Originally posted by @Megaemce in https://github.com/ant-design/ant-design/pull/34742#discussion_r1430296942_
            

| Environment | Info |
| --- | --- |
| antd | 5.12.3 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome |

---
I was trying to use the official demo code
https://ant.design/components/rate?theme=dark#design-token

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/46519

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     --      |
| 🇨🇳 Chinese |   --        |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

File: components/rate/demo/character-function.tsx [hunk 1]
```diff
@@ -12,9 +12,9 @@ const customIcons: Record<number, React.ReactNode> = {
 
 const App: React.FC = () => (
   <>
-    <Rate defaultValue={2} character={({ index }: { index: number }) => index + 1} />
+    <Rate defaultValue={2} character={({ index }) => (index || 0) + 1} />
```
Comment (li-jia-nan) [inline components/rate/demo/character-function.tsx:15]: 感觉用类型保护去解 ts 报错更好一点？

```suggestion
    <Rate
      defaultValue={2}
      character={({ index }) => typeof index === 'number' ? index + 1 : 1}
    />
```

File: components/rate/demo/character-function.tsx [hunk 2]
```diff
@@ -12,9 +12,9 @@ const customIcons: Record<number, React.ReactNode> = {
...
     <br />
-    <Rate defaultValue={3} character={({ index }: { index: number }) => customIcons[index + 1]} />
+    <Rate defaultValue={3} character={({ index }) => customIcons[(index || 0) + 1]} />
```
Comment (li-jia-nan) [inline components/rate/demo/character-function.tsx:17]:
```suggestion
    <Rate defaultValue={3} character={({ index = 0 }) => customIcons[index + 1]} />
```

**Review by MadCcc — APPROVED** [review]
