### PR TITLE
fix: Checkbox.Group onChange should not pass removed value

### LINKED ISSUE #16376: 关于checkBoxGroup的key值问题
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/74qnkrljvq)

### Steps to reproduce
例如我删除了某一项，遍历的data变化了，checkboxGroup点击某项却保留了上次的key值，
例子中测试点击3 ，删除，data变化为[1,2]，再次点击其中一项，key值保留上次的3值

### What is expected?
key值应取checkboxGroup域内的选中的值

### What is actually happening?
checkboxGroup点击保留了上次的key值

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.4.1 |
| System | win10 |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

fix #16376 

### 💡 Solution

Register value for filter.

### 📝 Changelog

Fix Checkbox.Group onChange pass removed value.

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/checkbox/Group.tsx [hunk 1]
```diff
@@ -90,6 +96,17 @@ class CheckboxGroup extends React.Component<CheckboxGroupProps, CheckboxGroupSta
     return !shallowEqual(this.props, nextProps) || !shallowEqual(this.state, nextState);
   }
 
+  registerValue = (value: string) => {
+    this.setState(({ registeredValues }) => ({
+      registeredValues: [...registeredValues, value],
+    }));
+  };
+  cancelValue = (value: string) => {
```
Comment (ztplz) [inline components/checkbox/Group.tsx]: 空一行  一起了

**Review by ztplz — APPROVED** [review]
