### PR TITLE
fix(modal):  Modal.xxx onCancel close argument is not a function 

### LINKED ISSUE #36581: Modal.confirm在设置closable为true的情况下，onCancel传入的close函数参数为undefined
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/shi-yong-hooks-huo-de-shang-xia-wen-antd-4-21-7-forked-txz6ce?file=/demo.js)

### Steps to reproduce

modal.confirm  config参数配置closable为true，设置onCancel为车close => close() ，点击右上方的关闭icon

### What is expected?

点击关闭按钮后正常关闭

### What is actually happening?

点击后报错close不是个function

| Environment | Info |
| --- | --- |
| antd | 4.21.7 |
| React | 18.3.0 |
| System | Monterey 12.4 |
| Browser | google |

### PR DESCRIPTION
**Pull request by Wxh16144**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #36581
### 💡 Background and solution

ref: https://github.com/ant-design/ant-design/issues/36581#issuecomment-1189396007

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Modal.confirm `onCancel` argument close is not a function sometimes.  |
| 🇨🇳 Chinese | 修复 Modal.confirm 中 `onCancel(close)` 参数有时候不是 function 的问题。          |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/modal/confirm.tsx [hunk 1]
```diff
@@ -2,6 +2,7 @@ import CheckCircleOutlined from '@ant-design/icons/CheckCircleOutlined';
 import CloseCircleOutlined from '@ant-design/icons/CloseCircleOutlined';
 import ExclamationCircleOutlined from '@ant-design/icons/ExclamationCircleOutlined';
 import InfoCircleOutlined from '@ant-design/icons/InfoCircleOutlined';
+import noop from 'lodash/noop';
```
Comment (afc163) [inline components/modal/confirm.tsx:5]: const noop = () => {};

不用单独引一个外部文件。

Comment (Wxh16144) [reply components/modal/confirm.tsx:5]: 直接写成内联匿名函数么。
_utils/Waring 里面是有导出一个 noop
