### PR TITLE
fix: ConfigProvider locale not working with Modal in some situation

### LINKED ISSUE #18731: ConfigProvider locale do not work in first time
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/config-provider-cn/](https://ant.design/components/config-provider-cn/)
WX20190909-093046@2x

### Steps to reproduce
when init

### What is expected?
it is not work

### What is actually happening?
it is work

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | react |
| System | mac os |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #18731

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix ConfigProvider `locale` not working with Modal in some situation. |
| 🇨🇳 Chinese | 修复 ConfigProvider `locale` 国际化在某些场景下对 `Modal` 不生效的问题。 |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/locale-provider/index.tsx [hunk 1]
```diff
@@ -73,8 +73,8 @@ export default class LocaleProvider extends React.Component<LocaleProviderProps,
     const { locale } = this.props;
     if (prevProps.locale !== locale) {
       setMomentLocale(locale);
+      changeConfirmLocale(locale && locale.Modal);
```
Comment (afc163) [inline components/locale-provider/index.tsx]: 还是需要判断一下是否变化。

**Review by ycjcl868 — APPROVED** [review]

**Review by yoyo837 — APPROVED** [review]
