### PR TITLE
style: fix Upload border color when drag over

### LINKED ISSUE #45640: Upload.Dragger拖入样式失效
### Reproduction link

[https://ant-design.antgroup.com/components/upload-cn#components-upload-demo-drag](https://ant-design.antgroup.com/components/upload-cn#components-upload-demo-drag)

### Steps to reproduce

如上

### What is expected?

拖入border变色

### What is actually happening?

ant-upload-drag-hover失效

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | 16.14.0 |
| System | wing10 |
| Browser | 谷歌 |

### PR DESCRIPTION
**Pull request by Oceansdeep7**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/45640

### 💡 Background and solution

Upload.Dragger拖入文件时，hover样式未触发，通过dragover状态来设置样式

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     fix Upload border color when drag over      |
| 🇨🇳 Chinese |     修复Upload拖拽时border样式失效      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 57b03d0</samp>

Improved hover effect for upload dragger component. Added a new CSS selector in `components/upload/style/dragger.ts` to match the hover state of the dragger element.

### <samp>🤖 Generated by Copilot at 57b03d0</samp>

*  Add hover effect for dragger component ([link](https://github.com/ant-design/ant-design/pull/45663/files?diff=unified&w=0#diff-3b4dbb97ee0c8cfbf0a7cae6e9aafaef93697d8552af9c0a29e5171b2bab7af6L36-R38))

### CODE REVIEW

File: components/upload/style/dragger.ts [hunk 1]
```diff
@@ -33,7 +33,9 @@ const genDraggerStyle: GenerateStyle<UploadToken> = (token) => {
           verticalAlign: 'middle',
         },
 
-        [`&:not(${componentCls}-disabled):hover`]: {
+        [`&:not(${componentCls}-disabled):hover,
+        &-hover:not(${componentCls}-disabled)
+        `]: {
```
Comment (afc163) [inline components/upload/style/dragger.ts:38]:
```suggestion
        [`
          &:not(${componentCls}-disabled):hover,
          &-hover:not(${componentCls}-disabled)
        `]: {
```

File: components/upload/style/dragger.ts [hunk 2]
```diff
@@ -33,7 +33,9 @@ const genDraggerStyle: GenerateStyle<UploadToken> = (token) => {
           verticalAlign: 'middle',
         },
 
-        [`&:not(${componentCls}-disabled):hover`]: {
+        [`&:not(${componentCls}-disabled):hover,
```
Comment (afc163) [inline components/upload/style/dragger.ts:36]: 这行代码还有意义么？

**Review by afc163 — APPROVED** [review]
