### PR TITLE
fix: Segmented style conflict with React DevTools 7.0

### LINKED ISSUE #55251: Segmented jumps from 1st option to the selected option every time
### Reproduction link

[https://ant.design/components/segmented](https://ant.design/components/segmented)

### Steps to reproduce

1. Locate first example (Basic)
2. Click on Monthly (Works correctly)
3. Click on Quarterly
4. You will notice how it jumps back to Daily and then goes to Quarterly

This happens every time and in every example that has more than two options within antd Segmented component page.

### What is expected?

To smoothly transition from the 2nd or higher to the next option selected

### What is actually happening?

It jumps back to the first option and then goes to the selected option.

| Environment | Info |
| --- | --- |
| antd | 5.27.4 |
| React | 19.0 |
| System | MacOS and WindowOS |
| Browser | Chrome, Safari, Edge |

### LINKED ISSUE #55253: Segmented 分段控制器切换动效异常
import { Form, Segmented } from 'antd';

const HomePage = () => {
  const [form] = Form.useForm();
  return (
    <div>
      <Form form={form}>
        <Form.Item name="Segmented" label="Tab选择器" getValueProps=''>
          <Segmented
            options={['Daily', 'Weekly', 'Monthly', 'Quarterly', 'Yearly']}
          />
        </Form.Item>

        <Form.Item label="监听" dependencies={['Segmented']}>
          {({ getFieldValue }) => {
            const value = getFieldValue('Segmented');
            if (value === 'Monthly') {
              return <div>监听成功</div>;
            }

            return <div>正常展示</div>;
          }}
        </Form.Item>
      </Form>
    </div>
  );
};

export default HomePage;
上述为使用方法，当切换时背景色块会从第一个位置移动到选中位置，

### LINKED ISSUE #55325: Segmented 组件切换tab的背景块滑动动画总会从第一个选项开始
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/v5-20-6-s8d79h)

### Steps to reproduce

我已查看过 #55311 的内容，测试发现该问题在 5.21.0 版本上出现，5.20.6 版本上并未出现，怀疑是 #50708 引起的

I have reviewed the content of #55311 and found that the issue occurred on version 5.21.0, but not on version 5.20.6. I suspect it may be caused by #50708

 5.20.6 https://codesandbox.io/p/sandbox/v5-20-6-s8d79h

 5.21.0 https://codesandbox.io/p/sandbox/v5-21-0-sm8n7v

### What is expected?

背景块从当前位置开始运动

### What is actually happening?

背景块总是从第一项开始运动

| Environment | Info |
| --- | --- |
| antd | 5.27.5 |
| React | 18 |
| System | windows |
| Browser | chrome 141 |

### LINKED ISSUE #55404: segmented 分段组件动画在谷歌浏览器上有问题，隐身模式没问题
### Reproduction link

[https://ant.design/components/segmented-cn](https://ant.design/components/segmented-cn)

### Steps to reproduce

1.打开网址
2.点选第一个基础用法
3.不管点选哪个，动画都是从第一个tag出来
4.谷歌浏览器 隐身模式没问题

### What is expected?

效果跟谷歌浏览器隐身模式一样就行

### What is actually happening?

正常模式和隐身模式动画效果不一样

| Environment | Info |
| --- | --- |
| antd | 5.26.4 |
| React | 18 |
| System | mac |
| Browser | 谷歌 版本 141.0.7390.108（正式版本） (arm64) |

### PR DESCRIPTION
**Pull request by afc163**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

close https://github.com/ant-design/ant-design/issues/55325
close https://github.com/ant-design/ant-design/issues/55404
close https://github.com/ant-design/ant-design/issues/55269
close https://github.com/ant-design/ant-design/issues/55253
close https://github.com/ant-design/ant-design/issues/55251
close https://github.com/ant-design/ant-design/issues/55257

ref https://github.com/facebook/react/issues/34866
ref https://github.com/facebook/react/issues/34942

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)! Track your changes, like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Segmented abnormal animation after React DevTools upgrade.          |
| 🇨🇳 Chinese | 修复 Segmented 切换动画总是从第一项移动闪烁的问题。          |

### CODE REVIEW

File: components/segmented/style/index.ts [hunk 1]
```diff
@@ -224,7 +221,6 @@ const genSegmentedStyle: GenerateStyle<SegmentedToken> = (token: SegmentedToken)
         height: '100%',
         padding: `${unit(token.paddingXXS)} 0`,
         borderRadius: token.borderRadiusSM,
-        transition: `transform ${token.motionDurationSlow} ${token.motionEaseInOut}, height ${token.motionDurationSlow} ${token.motionEaseInOut}`,
```
Comment (afc163) [inline components/segmented/style/index.ts:227]: 关键改动是这一行。其他改动是代码优化和 hover/active 时的样式闪烁效果优化。

File: components/segmented/style/index.ts [hunk 2]
```diff
@@ -169,22 +169,21 @@ const genSegmentedStyle: GenerateStyle<SegmentedToken> = (token: SegmentedToken)
...
+          transition: `opacity ${token.motionDurationMid}, background-color ${token.motionDurationMid}`,
           // This is mandatory to make it not clickable or hoverable
           // Ref: https://github.com/ant-design/ant-design/issues/40888
           pointerEvents: 'none',
         },
 
-        [`&:hover:not(${componentCls}-item-selected):not(${componentCls}-item-disabled)`]: {
-          color: token.itemHoverColor,
-          '&::after': {
+        '&:not(&-selected):not(&-disabled)': {
```
Comment (thinkasany) [inline components/segmented/style/index.ts]: 交互看起来好像没什么问题，但是 ci 的 lint 上显示兼容性好像有点问题，再拆一个 ```opacity: 0```？

image

**Review by li-jia-nan — APPROVED** [review]

**Review by zombieJ — APPROVED** [review]

**Review by meet-student — APPROVED** [review]

**Comment by li-jia-nan** [comment]
居然修了这么多issus
