### PR TITLE
fix(badge): fix the style issue in RTL mode

### LINKED ISSUE #38806: v5.x Badge RTL
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/dynamic-antd-5-0-0-forked-x3x9tb?file=/demo.tsx)

### Steps to reproduce

badge position wrong place in RTL.

### What is expected?

--

### What is actually happening?

it most in left top position

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.0.0 |
| System | Windows 11 |
| Browser | Chrome 90 |

### PR DESCRIPTION
**Pull request by Wxh16144**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix: #38806

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     fix the style issue in RTL mode      |
| 🇨🇳 Chinese |      修复RTL模式下的样式问题     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/badge/style/index.tsx [hunk 1]
```diff
@@ -318,6 +327,22 @@ const genSharedBadgeStyle: GenerateStyle<BadgeToken> = (token: BadgeToken): CSSO
...
         },
       },
+
+      // ====================== RTL =======================
+      '&-rtl': {
+        direction: 'rtl',
+
+        [`&${ribbonPrefixCls}-placement-end`]: {
+          [`${ribbonPrefixCls}-corner`]: {
+            borderColor: 'currentcolor currentcolor transparent transparent',
```
Comment (MadCcc) [inline components/badge/style/index.tsx:337]: 这种可以拆成 borderInlineStartColor 等，遵循 logical-properties

**Review by afc163 — APPROVED** [review]
