### PR TITLE
fix: Dropdown `onOpenChange` closure issue

### LINKED ISSUE #54879: [Dropdown] stale closure issue for onOpenChange callback ?
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/other-elements-antd-5-27-2-forked-z2ql3z?file=%2Fdemo.tsx)

### Steps to reproduce

- Open the dropdown
- Click multiple time on increase button to modify amount value
- Click on dropdown or type on enter key 
- The onOpenChange callback if called with initial amount value (and not the updated one)

Note that is you click outisde the menu instead of clicking on it, everything works as expected

### What is expected?

Same behaviour than when you close the dropdown clicking outside the menu: the onOpenChange method should be called with updated amount value.

### What is actually happening?

The onOpenChange method is called with initial amount value

| Environment | Info |
| --- | --- |
| antd | 5.27.2 |
| React | 18 |
| System | Ubuntu |
| Browser | Chrome |

---
The behaviour is different because it's handled by two different methods: onInnerOpenChange and onMenuClick.

```
const onInnerOpenChange = useEvent((nextOpen: boolean) => {
    onOpenChange?.(nextOpen, { source: 'trigger' });
    onVisibleChange?.(nextOpen);
    setOpen(nextOpen);
  });
```

```
const onMenuClick = React.useCallback(() => {
    if (menu?.selectable && menu?.multiple) {
      return;
    }
    onOpenChange?.(false, { source: 'menu' });
    setOpen(false);
  }, [menu?.selectable, menu?.multiple]);
```

Using useEvent instead of useCallback on onMenuClick fixes the issue

### PR DESCRIPTION
**Pull request by zombieJ**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

fix #54879

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)! Track your changes, like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix Dropdown click Menu.Item to trigger `onOpenChange` will get closure issue.       |
| 🇨🇳 Chinese |   修复 Dropdown 的 `onOpenChange` 在点击 Menu.Item 关闭时会遇到闭包的问题。        |

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

**Review by thinkasany — APPROVED** [review]

File: components/dropdown/dropdown.tsx [hunk 1]
```diff
@@ -234,13 +234,13 @@ const Dropdown: CompoundedComponent = (props) => {
...
 
-  const onMenuClick = React.useCallback(() => {
+  const onMenuClick = useEvent(() => {
     if (menu?.selectable && menu?.multiple) {
       return;
     }
     onOpenChange?.(false, { source: 'menu' });
     setOpen(false);
-  }, [menu?.selectable, menu?.multiple]);
+  });
```
Comment (afc163) [inline components/dropdown/dropdown.tsx:243]: 这样改的区别是啥？
