### PR TITLE
ColorPresets: fix duplicate keys

### LINKED ISSUE #44361: [ColorPicker][presets] Encountered two children with the same key
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-9kgrnw)

### Steps to reproduce

Add two identical colors to the preset

### What is expected?

I understand that you may not have imagined what this could be, but this is a fairly normal user experience to have the same colors in the palette. Can you add also the index in the key?

### What is actually happening?

Encountered two children with the same key

| Environment | Info |
| --- | --- |
| antd | 5.8.4 |
| React | 18.2.0 |

---
Or maybe you can add a method in props, so we will be able to define how to generate keys yourself.

### PR DESCRIPTION
**Pull request by xr0master**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

Close #44361

### 📝 Changelog

Bugfix [#44361]: Add the current index to key

---

### <samp>🤖 Generated by Copilot at 080ad90</samp>

Modified the `key` prop of `ColorBlock` to prevent duplicate keys in `ColorPresets`. This improved the rendering and accessibility of the color picker component.

### <samp>🤖 Generated by Copilot at 080ad90</samp>

* Add `index` to `key` prop of `ColorBlock` component to avoid duplicate keys ([link](https://github.com/ant-design/ant-design/pull/44370/files?diff=unified&w=0#diff-8d2a305db0c4945017603df77e97b2bf27dbde09aef2a8e2c2f7d10e67a3a822L62-R64))

### CODE REVIEW

File: components/color-picker/components/ColorPresets.tsx [hunk 1]
```diff
@@ -59,9 +59,9 @@ const ColorPresets: FC<ColorPresetsProps> = ({ prefixCls, presets, value: color,
     children: (
       <div className={`${colorPresetsPrefixCls}-items`}>
         {Array.isArray(preset?.colors) && preset.colors?.length > 0 ? (
-          preset.colors.map((presetColor: Color) => (
+          preset.colors.map((presetColor: Color, index: number) => (
             <ColorBlock
-              key={`preset-${presetColor.toHexString()}`}
+              key={`preset-${index}-${presetColor.toHexString()}`}
```
Comment (afc163) [inline components/color-picker/components/ColorPresets.tsx:64]:
```suggestion
              key={`preset-${presetColor.toHexString()}-${index}`}
```

Comment (xr0master) [reply components/color-picker/components/ColorPresets.tsx:64]: Hi, I thought so, but in this case, the index refers to the preset, not the color. That is, preset-30 means the 30th color in the preset, and red-30 - it sounds like red 30 times repeated.
What do you think?

Comment (afc163) [reply components/color-picker/components/ColorPresets.tsx:64]: You are right about it.

**Comment by afc163** [comment]
eslint rule is broken.

**Comment by RedJue** [comment]
ping

**Comment by xr0master** [comment]
I thought a little. If there is a better solution instead of the index. I understand why the index is not desirable, but in this case, the bad impact is close to zero.

@afc163 @RedJue 
So I will add `// eslint-disable-next-line react/no-array-index-key`, is it fine?

File: components/color-picker/components/ColorPresets.tsx (hunk 1 above)
Comment (xr0master) [inline components/color-picker/components/ColorPresets.tsx:64]:
```suggestion
              // eslint-disable-next-line react/no-array-index-key
              key={`preset-${index}-${presetColor.toHexString()}`}
```

**Comment by RedJue** [comment]
> I thought a little. If there is a better solution instead of the index. I understand why the index is not desirable, but in this case, the bad impact is close to zero.
> 
> @afc163 @RedJue So I will add `// eslint-disable-next-line react/no-array-index-key`, is it fine?

This is only the case for one line, if there are two preset lines, the key will still be duplicated.

**Comment by xr0master** [comment]
@RedJue I'm not sure if I got this. If this is the second preset, then there will be no conflict. Since parents are different nodes.

**Comment by RedJue** [comment]
> @RedJue I'm not sure if I got it. If this is the second preset, then there will be no conflict. Since parents are different nodes.
Yeah, you're right, then I think the `index` key can be added here.

**Comment by RedJue** [comment]
The current branch is behind master, can you rebase it?

**Comment by RedJue** [comment]
Can you add a unit test?

**Comment by xr0master** [comment]
Honestly, I'm having a hard time imagining unit tests for runtime warnings...
Spy on console output? Theoretically, this is possible, but such tests are the main level. They should be added automatically to all tests.
Something like this: https://github.com/thomasbrodusch/vitest-fail-on-console (not my project, just googled it)

**Comment by MadCcc** [comment]
Test case please. Dynamic array should be taken into consideration if `index` is used in `key`

**Comment by xr0master** [comment]
@MadCcc please share the test plan

**Comment by RedJue** [comment]
> @MadCcc please share the test plan
> 
> 
> 
> Update: I mean, what risks do you think are worth checking out?
> 
> In this case, changing the index does not carry risks, since if the color (and, accordingly, the key) matches, the value of the preset component will not change. That is, the test will always pass. But perhaps I'm missing something?

If the preset array is dynamically added, the index of each color block is unstable, causing the key to be unstable, and react will re-render them every time.

**Comment by RedJue** [comment]
This's why not use index as key.

**Comment by xr0master** [comment]
> If the preset array is dynamically added, the index of each color block is unstable, causing the key to be unstable, and react will re-render them every time.

Obviously. If the keys have changed, then react will recreate the nodes. I mentioned it above. So, if the color is added to the preset, then it will not affect it in any way. If a certain color is removed, then all subsequent nodes will be recreated. Even without an index, in any case, react would have to re-sort the nodes. Yes, it's faster than creating nodes, but I don't think this option of removing colors from presets is so popular use case. Minor impact.

> This's why not use index as key.

:) "Criticise if you disagree, suggest if you criticise". 

Or remove `string[]` support and change to `objects[]`. That means break changes.
Or create a `getColorKey` prop to generate keys, but such an API has never been seen in antd, which would also be a strange solution.

In any case, this is a bug in antd, and you are free to solve it however you want guys. I just like to use this library, and so I decided to help a little.

**Comment by RedJue** [comment]
> > If the preset array is dynamically added, the index of each color block is unstable, causing the key to be unstable, and react will re-render them every time.
> 
> Obviously. If the keys have changed, then react will recreate the nodes. I mentioned it above. So, if the color is added to the preset, then it will not affect the performance in any way. If a certain color is removed, then all subsequent nodes will be recreated. Even without an index, in any case, react would have to re-sort the nodes. Yes, it's faster than creating nodes, but I don't think this option of removing colors from presets is so popular use case. Minor impact.
> 
> > This's why not use index as key.
> 
> :) "Criticise if you disagree, suggest if you criticise".
> 
> Or remove `string[]` support and change to `objects[]`. That means break changes. Or create a `getColorKey` prop to generate keys, but such an API has never been seen in antd, which would also be a strange solution.
> 
> In any case, this is a bug in antd, and you are free to solve it however you want guys. I just like to use this library, and so I decided to help a little.

We finally discussed and decided to solve the problem in this way first, and then optimize if there are any performance problems, thanks!

**Review by MadCcc — APPROVED** [review]
