### PR TITLE
fix: Cascader options not open after press ESC and then search

### LINKED ISSUE #26266: Cascader options not opening on search
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-k9rlv?file=/index.js)

### Steps to reproduce
Type "Jin"
Press "Esc" key
Again Type "Jin"

Pop-up won't comes up untill clicked again.

### What is expected?
Options Pop up should be opened as soon as we type something in search

### What is actually happening?
Options pop-up is not coming up Until we click on Cascader.

| Environment | Info |
|---|---|
| antd | undefined |
| React | react 16.04 |
| System | mac os |
| Browser | chrome/ safari |

### PR DESCRIPTION
**Pull request by flyerH**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #26266 

### 💡 Background and solution

image
the options not open after press ESC and then input 'jin'
image
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Cascader options not open after press ESC and then search. |
| 🇨🇳 Chinese | 修复Cascader在按下ESC键，然后通过输入进行搜索时options不展开的问题。 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by xrkffgg — APPROVED** [review]

File: components/cascader/index.tsx [hunk 1]
```diff
@@ -353,7 +353,9 @@ class Cascader extends React.Component<CascaderProps, CascaderState> {
   };
 
   handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
+    const { popupVisible } = this.state;
     const inputValue = e.target.value;
+    if (!popupVisible) this.handlePopupVisibleChange(true);
```
Comment (afc163) [inline components/cascader/index.tsx:358]:
```suggestion
    if (!popupVisible) {
      this.handlePopupVisibleChange(true);
    }
```

**Comment by afc163** [comment]
Good job!

File: components/cascader/index.tsx (hunk 1 above)
Comment (flyerH) [reply components/cascader/index.tsx]: 本来是这么写的，commit时被项目的prettier工具格式化成这样的😂

Comment (afc163) [reply components/cascader/index.tsx]: 那没事了，个人习惯和 prettier 冲突了，以 prettier 为准。
