### PR TITLE
fix: 🐞 Fix selectedRows missing when there is childrenColumnName in Table

### LINKED ISSUE #16614: Table 设置 childrenColumnName，选择子结构好的行数据，时候selectedRows没有
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/zhanghuai/pen/RmpxaN?editors=1010](https://codepen.io/zhanghuai/pen/RmpxaN?editors=1010)

### Steps to reproduce
勾选子结构行数据

### What is expected?
selectedRows 应该有选中的数据

### What is actually happening?
selectedRows是空数组

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | react^16.8.6 |
| System | macos 10.14.4 |
| Browser | chrome 74.0.3729.131 |

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

close #16614

### 📝 Changelog

- English Changelog: 🐞 Fixed Table `selectedRows` argument in `onChange` missing when specified `childrenColumnName`.
- Chinese Changelog (optional): 🐞 修复 Table `onChange` 的 `selectedRows` 参数当指定了 `childrenColumnName` 时为空的问题。

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/table/Table.tsx [hunk 1]
```diff
@@ -1066,10 +1067,12 @@ export default class Table<T> extends React.Component<TableProps<T>, TableState<
   }
 
   getFlatData() {
-    return flatArray(this.getLocalData(null, false));
+    const { childrenColumnName } = this.props;
+    return flatArray(this.getLocalData(null, false), childrenColumnName);
```
Comment (afc163) [inline components/table/Table.tsx]: 关键代码在此。
