### PR TITLE
 fix(Progress): 🐛 fix progress success UI when status is undefined

### LINKED ISSUE #15950: Progress UI inconsistent when status is undefined
```jsx
<Progress percent={100} />
<Progress percent={100} status={undefined} />

// should be same UI
```

https://codesandbox.io/s/qkqryx78v9

image

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

close #15950

### 📝 Changelog

- English Changelog: 🐛 fix progress success UI when status is `undefined` or invalid. #15950
- Chinese Changelog (optional):

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/progress/progress.tsx [hunk 1]
```diff
@@ -61,6 +61,18 @@ export default class Progress extends React.Component<ProgressProps> {
     default: PropTypes.oneOf(['default', 'small']),
   };
 
+  getProgressStatus() {
+    const { successPercent, percent = 0, status } = this.props;
+    const percentNumber = parseInt(
+      successPercent !== undefined ? successPercent.toString() : percent.toString(),
+      10,
+    );
+    if (percentNumber >= 100 && status === undefined) {
```
Comment (ztplz) [inline components/progress/progress.tsx]: 要是用户输错了 还是会这样的
image
https://github.com/ant-design/ant-design/blob/master/components/progress/progress.tsx#L13
再判断下是不是正确的status？ ProgressStatuses.includes(status) ， 不是要求的的status都返回success

File: components/progress/progress.tsx [hunk 2]
```diff
@@ -61,6 +61,18 @@ export default class Progress extends React.Component<ProgressProps> {
     default: PropTypes.oneOf(['default', 'small']),
   };
 
+  getProgressStatus() {
+    const { successPercent, percent = 0, status } = this.props;
+    const percentNumber = parseInt(
+      successPercent !== undefined ? successPercent.toString() : percent.toString(),
+      10,
+    );
+    if (percentNumber >= 100 && ProgressStatuses.indexOf(status!) < 0) {
```
Comment (zombieJ) [inline components/progress/progress.tsx]: 建议把 `ProgressStatuses.indexOf(status!) -> status` 的逻辑提到最上面，这样易读一些。
