### PR TITLE
fix(TimePicker): Remove redundant warnings

### LINKED ISSUE #38185: [antd: RangePicker] `dropdownClassName` is deprecated which will be removed in next major version. Please use `popupClassName` instead.
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-hevf0u?file=/index.js:0-427)

### Steps to reproduce

open provided demo link and see warning in console:
Warning: [antd: RangePicker] `dropdownClassName` is deprecated which will be removed in next major version. Please use `popupClassName` instead. 

but I already use popupClassName:  <TimePicker.RangePicker popupClassName="some-class" />

### What is expected?

no warning should appear

### What is actually happening?

Warning: [antd: RangePicker] `dropdownClassName` is deprecated which will be removed in next major version. Please use `popupClassName` instead. 

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by kiner-tang**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [X] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

- fix: #38185 

### 💡 Background and solution

Remove redundant warnings

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Remove redundant warnings |
| 🇨🇳 Chinese | 移除冗余警告修复使用了`popupClassName`仍报错问题  |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

### CODE REVIEW

File: components/time-picker/index.tsx [hunk 1]
```diff
@@ -23,11 +23,6 @@ export interface TimeRangePickerProps extends Omit<RangePickerTimeProps<Moment>,
 
 const RangePicker = React.forwardRef<any, TimeRangePickerProps>((props, ref) => {
   const { dropdownClassName, popupClassName } = props;
-  warning(
```
Comment (kiner-tang) [inline components/time-picker/index.tsx:26]: `InternalRangePicker` will throw warning, so, we need not throw warning here!

**Review by afc163 — APPROVED** [review]
