### PR TITLE
fix(Tour): solve the Tour title will cover the close button at a certain length issue

### LINKED ISSUE #50919: The Tour title will cover the close button at a certain length
### Reproduction link

[https://codepen.io/mintsweet/pen/xxovrPB?editors=0010](https://codepen.io/mintsweet/pen/xxovrPB?editors=0010)

### Steps to reproduce

Set a longer title that does not wrap

### What is expected?

Separate title and close button

### What is actually happening?

Title will cover close button

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18 |
| System | MacOS 14.6.1 |
| Browser | Chrome 128.0.6613.138 |

### PR DESCRIPTION
**Pull request by kiner-tang**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [X] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

fix #50919

Before: 

image

After:

image
image

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | solve the Tour title will cover the close button at a certain length issue  |
| 🇨🇳 Chinese |  解决 Tour 组件标题过长时会遮挡关闭按钮的问题  |

### CODE REVIEW

File: components/tour/style/index.ts [hunk 1]
```diff
@@ -143,6 +143,7 @@ const genBaseStyle: GenerateStyle<TourToken> = (token) => {
           },
           [`${componentCls}-header`]: {
             padding: `${unit(padding)} ${unit(padding)} ${unit(paddingXS)}`,
+            width: '95%',
```
Comment (li-jia-nan) [inline components/tour/style/index.ts:146]: 感觉这个值比较随意，应该用 calc 计算一下

Comment (kiner-tang) [reply components/tour/style/index.ts:146]: 感觉没必要用 calc 吧，这边并不需要完全精确到多少像素，使用 百分比 我觉得应该就够了

Comment (li-jia-nan) [reply components/tour/style/index.ts:146]: 我的意思是减去按钮的宽度

**Review by afc163 — APPROVED** [review]
