### PR TITLE
fix: update icon color token in Select

### LINKED ISSUE #39618: colorTextDisabled 自定义颜色，导致其他非文字部分颜色改变
### Reproduction link

[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce

colorTextDisabled 自定义颜色，导致其他非文字部分颜色改变
微信截图_20221217211954
微信截图_20221217211839

| Environment | Info |
| --- | --- |
| antd | 5.0.7 |
| React | React 18.2.0 |
| System | Windows |
| Browser | Chrome 103 |

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/39618

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix wrong usage of icon color token in Select.         |
| 🇨🇳 Chinese |  修复 Select 组件 icon 颜色使用的 token.         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

File: components/cascader/style/index.tsx [hunk 1]
```diff
@@ -105,7 +105,7 @@ const genBaseStyle: GenerateStyle<CascaderToken> = (token) => {
                 '&:hover': {
                   background: token.controlItemBgHover,
                 },
-                ' &-disabled': {
```
Comment (afc163) [inline components/cascader/style/index.tsx:108]: 这种感觉应该直接用工具发现和报错。

Comment (MadCcc) [reply components/cascader/style/index.tsx:108]: 结果而言没啥影响，但是这个想要检查出来只能运行时分析了

Comment (MadCcc) [reply components/cascader/style/index.tsx:108]: 反而 string 类型的 cssinjs 好做 lint

**Review by heiyu4585 — APPROVED** [review]
