### PR TITLE
fix(InputNumber): fontSize error

### LINKED ISSUE #41971: InputNumber: class `ant-input-number-input` overrides class `ant-input-number-lg` styles
### Reproduction link

[https://stackblitz.com/edit/react-rzsc9z?file=demo.tsx](https://stackblitz.com/edit/react-rzsc9z?file=demo.tsx)

### Steps to reproduce

Right-click number input, inspect, Computed tab, font-size: 14px

### What is expected?

Font-size should be 16px since the input is large

### What is actually happening?

Large class / props seem to be missing on the input itself

| Environment | Info |
| --- | --- |
| antd | 5.4.5 |
| React | 18.2 |
| System | Windows 10 19045.2846 |
| Browser | Chrome 111.0.5563.147 |

### PR DESCRIPTION
**Pull request by Wxh16144**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fixed #41971 

### 💡 Background and solution

Fix bug caused by #41940 PR, so sorry😢

Be sure to keep an eye on the argos CI results...

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    fix InputNumber font-size error      |
| 🇨🇳 Chinese |    修复 InputNumber 字体样式错误       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

File: components/input-number/style/index.ts [hunk 1]
```diff
@@ -154,6 +154,7 @@ const genInputNumberStyles: GenerateStyle<InputNumberToken> = (token: InputNumbe
             outline: 0,
             transition: `all ${motionDurationMid} linear`,
             appearance: 'textfield',
+            fontSize: 'inherit',
```
Comment (yoyo837) [inline components/input-number/style/index.ts:157]: 建议将上个PR注释在这说明一下, 如何?

**Review by afc163 — APPROVED** [review]
