### PR TITLE
fix: Adds aria-* to TreeSelect

### LINKED ISSUE #40055: TreeSelect component should support 'aria-label' option prop.
### What problem does this feature solve?

The <Select /> component supports an 'aria-label' option prop, which is useful when the label prop is a React component (and therefore cannot be read by the screen reader). However, the <TreeSelect /> component does not seem to support an 'aria-label' prop - instead, the value prop is read by the screen reader in every case. Please reference the following CodeSandbox examples using a screen reader:

[Example #1 - Select component uses 'aria-label' prop as expected](https://codesandbox.io/s/basic-usage-antd-5-1-2-forked-fv0zgh?file=/demo.tsx)

[Example #2 - TreeSelect does not use 'aria-label' prop](https://codesandbox.io/s/g5wpqd?file=/demo.tsx)

### What does the proposed API look like?

Add 'aria-label' as a supported option property on tree nodes.

### PR DESCRIPTION
**Pull request by guan404ming**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

1. close #40055

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Adds aria-* to TreeSelect      |
| 🇨🇳 Chinese |      添加 aria-* 到 TreeSelect     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 8b2bbea</samp>

This pull request enhances the accessibility of the `TreeSelect` component by adding the `aria-label` prop, which allows users to specify custom labels for the tree nodes. It also adds a test case to verify the functionality of the new prop.

### <samp>🤖 Generated by Copilot at 8b2bbea</samp>

*  Add `aria-label` prop to `TreeSelect` component to support accessibility labels ([link](https://github.com/ant-design/ant-design/pull/41978/files?diff=unified&w=0#diff-f4ebf787ec0bc13112f49b0d9a2df0bfa73f8ea80cec9a6c92d311e120fa6ffeR67), [link](https://github.com/ant-design/ant-design/pull/41978/files?diff=unified&w=0#diff-f4ebf787ec0bc13112f49b0d9a2df0bfa73f8ea80cec9a6c92d311e120fa6ffeR75), [link](https://github.com/ant-design/ant-design/pull/41978/files?diff=unified&w=0#diff-f4ebf787ec0bc13112f49b0d9a2df0bfa73f8ea80cec9a6c92d311e120fa6ffeR261), [link](https://github.com/ant-design/ant-design/pull/41978/files?diff=unified&w=0#diff-d4c24db61ead898cb9be2edaa49ab821f7fc94aad2b3ebdd14723614d742aebcR68-R79))
  * Define `aria-label` prop in `TreeSelectProps` interface in `components/tree-select/index.tsx` ([link](https://github.com/ant-design/ant-design/pull/41978/files?diff=unified&w=0#diff-f4ebf787ec0bc13112f49b0d9a2df0bfa73f8ea80cec9a6c92d311e120fa6ffeR67))
  * Assign `aria-label` prop to `ariaLabel` variable in `InternalTreeSelect` function in `components/tree-select/index.tsx` ([link](https://github.com/ant-design/ant-design/pull/41978/files?diff=unified&w=0#diff-f4ebf787ec0bc13112f49b0d9a2df0bfa73f8ea80cec9a6c92d311e120fa6ffeR75))
  * Pass `ariaLabel` variable to `rc-tree-select` component in `InternalTreeSelect` function in `components/tree-select/index.tsx` ([link](https://github.com/ant-design/ant-design/pull/41978/files?diff=unified&w=0#diff-f4ebf787ec0bc13112f49b0d9a2df0bfa73f8ea80cec9a6c92d311e120fa6ffeR261))
  * Add test case to check `aria-label` prop in `components/tree-select/__tests__/index.test.tsx` ([link](https://github.com/ant-design/ant-design/pull/41978/files?diff=unified&w=0#diff-d4c24db61ead898cb9be2edaa49ab821f7fc94aad2b3ebdd14723614d742aebcR68-R79))

### CODE REVIEW

**Comment by yoyo837** [comment]
Could we support aria-*？

**Comment by guan404ming** [comment]
I have fix it !!!

**Comment by guan404ming** [comment]
> Could we support aria-*？

I have done this ~~~

File: components/tree-select/index.tsx [hunk 1]
```diff
@@ -64,6 +64,7 @@ export interface TreeSelectProps<
   status?: InputStatus;
   switcherIcon?: SwitcherIcon | RcTreeSelectProps<ValueType, OptionType>['switcherIcon'];
   rootClassName?: string;
+  [key: `aria-${string}`]: string | boolean | number | undefined;
```
Comment (afc163) [inline components/tree-select/index.tsx:67]: This will lose type for each aria attribute: https://use-form.netlify.app/interfaces/_node_modules__types_react_index_d_.react.ariaattributes.html

Comment (guan404ming) [reply components/tree-select/index.tsx]: I have update the type definition. Thanks very much to provide me with this reference ~~

**Review by afc163 — APPROVED** [review]
