### PR TITLE
fix: Modal conflicting props classNames.wrapper and centered

### LINKED ISSUE #47041: Modal classNames wrapper disables centered option
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-zlrmmz)

### Steps to reproduce

Build a Modal with the `centered` option. Add the `classNames` option and include a value for the `wrapper` key

### What is expected?

Modal is centered

### What is actually happening?

Modal is not centered

| Environment | Info |
| --- | --- |
| antd | 5.13.1 |
| React | react 18 |
| System | macOS 14.1.2 |
| Browser | Chrome 120 |

### PR DESCRIPTION
**Pull request by sunsunmonkey**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

close https://github.com/ant-design/ant-design/issues/47041

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix Modal conflicting props bettween `classNames.wrapper` and `centered`.     |
| 🇨🇳 Chinese |   修复 Modal 自定义 `classNames.wrapper` 时 `centered` 属性不生效的问题。     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/modal/Modal.tsx [hunk 1]
```diff
@@ -144,9 +144,9 @@ const Modal: React.FC<ModalProps> = (props) => {
             className={classNames(hashId, className, modal?.className)}
             style={{ ...modal?.style, ...style }}
             classNames={{
-              wrapper: wrapClassNameExtended,
               ...modal?.classNames,
               ...modalClassNames,
+              wrapper: `${wrapClassNameExtended} ${modalClassNames?.wrapper || ''}`,
```
Comment (afc163) [inline components/modal/Modal.tsx:149]:
```suggestion
              wrapper: classNames(wrapClassNameExtended, modalClassNames?.wrapper),
```

**Review by afc163 — APPROVED** [review]
