### PR TITLE
fix: radio should work in tree

### LINKED ISSUE #44224: Radio Group not work in Tree
### Reproduction link

[https://9l29gc.csb.app/](https://9l29gc.csb.app/)

### Steps to reproduce

Click an unchecked radio 

### What is expected?

It was work in v5.8.1 
https://5jhldf.csb.app/

### What is actually happening?

Once clicked the radio you can find that nothing happened and even the click event are not trigged.

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | 18 |
| System | Windows |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/44224

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix Radio that not work in Tree title.       |
| 🇨🇳 Chinese |     修复 Radio 组件组合 Tree 组件后失效的问题。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 609c6ad</samp>

Simplified the radio input style by using shorthand properties and removing unnecessary ones in `components/radio/style/index.tsx`.

### <samp>🤖 Generated by Copilot at 609c6ad</samp>

*  Simplify the radio input style by using `inset: 0` and removing unnecessary properties ([link](https://github.com/ant-design/ant-design/pull/44380/files?diff=unified&w=0#diff-a741439225c8413e967262511dad718192a7a5154ee037fa3c679681b95372afL226-R230))

### CODE REVIEW

**Review by yoyo837 — APPROVED** [review]

File: components/radio/style/index.tsx [hunk 1]
```diff
@@ -223,14 +223,7 @@ const getRadioBasicStyle: GenerateStyle<RadioToken> = (token) => {
...
         position: 'absolute',
-        insetBlockStart: 0,
-        insetInlineEnd: 0,
-        insetBlockEnd: 0,
-        insetInlineStart: 0,
-        width: 0,
-        height: 0,
-        padding: 0,
-        margin: 0,
+        inset: 0,
```
Comment (Yuiai01) [inline components/radio/style/index.tsx:226]: 好神奇

Comment (ooPG233) [reply components/radio/style/index.tsx:226]: 确实
