### PR TITLE
type(flex): fix missing preset size support for gap

### LINKED ISSUE #47187: `Flex` 组件会给子元素 `a` 增加过多样式，`gap` 属性的 `SizeType` 没有 `ts` 提示
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/ji-ben-bu-ju-antd-5-13-1-forked-mf662v?file=%2Fdemo.tsx%3A11%2C3)

### Steps to reproduce

https://codesandbox.io/p/sandbox/ji-ben-bu-ju-antd-5-13-1-forked-mf662v?file=%2Fdemo.tsx%3A11%2C3

### What is expected?

不希望 `Flex` 组件的子元素 `a` 自带样式，`gap` 需要类型提示

### What is actually happening?

`Flex` 组件会给子元素 `a` 增加过多样式，`gap` 属性的 `SizeType` 没有 `ts` 提示

| Environment | Info |
| --- | --- |
| antd | 5.13.2 |
| React | 18.2.0 |
| System | MacOS 12.6 |
| Browser | Chrome 121.0.6167.85 |

### PR DESCRIPTION
**Pull request by ayangweb**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

fix #47187

### 💡 Background and Solution

image

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)! Track your changes, like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     fix missing preset size support for `gap`      |
| 🇨🇳 Chinese |       修复 `gap` 缺少预设尺寸的问题     |

### CODE REVIEW

File: components/flex/demo/gap.tsx [hunk 1]
```diff
@@ -1,11 +1,10 @@
 import React from 'react';
 import { Button, Flex, Radio, Slider } from 'antd';
-import type { ConfigProviderProps } from 'antd';
 
-type SizeType = ConfigProviderProps['componentSize'];
+import type { FlexProps } from '../interface';
```
Comment (li-jia-nan) [inline components/flex/demo/gap.tsx]: demo 里面不要用相对路径

File: components/flex/interface.ts [hunk 2]
```diff
@@ -11,6 +12,6 @@ export interface FlexProps<P = AnyObject> extends React.HTMLAttributes<HTMLEleme
   justify?: React.CSSProperties['justifyContent'];
   align?: React.CSSProperties['alignItems'];
   flex?: React.CSSProperties['flex'];
-  gap?: React.CSSProperties['gap'] | SizeType;
+  gap?: LiteralUnion<GapSize> | number;
```
Comment (li-jia-nan) [inline components/flex/interface.ts]: 感觉这个 React.CSSProperties['gap'] 不能改，大的类型收窄成小的类型，breaking 了

Comment (ayangweb) [reply components/flex/interface.ts]:
```ts
export type Primitive = null | undefined | string | number | boolean | symbol | bigint;

/** https://github.com/Microsoft/TypeScript/issues/29729 */
export type LiteralUnion<T extends string | undefined, U extends Primitive = string> =
  | T
  | (U & Record<never, never>);

gap?: LiteralUnion<SizeType, React.CSSProperties['gap']>;
```

如果进行以上改造，不影响功能，看看是否可行？

image

**Review by afc163 — APPROVED** [review]
