### PR TITLE
fix: tabs overflow unexpected height

### LINKED ISSUE #40482: Tabs nav-more button adds an extra height
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/slide-antd-5-1-7-forked-51668t?file=/demo.tsx)

### Steps to reproduce

The overflow is already visible

### What is expected?

For Tabs to not exceed expected height

### What is actually happening?

Tabs parent might have overflow: scroll, or Tabs might be at the full height of the page.
Tabs button .ant-tabs-nav-more has :after rule, which translates it below the button, what causes the extra 5px height

| Environment | Info |
| --- | --- |
| antd | 5.1.7 |
| React | 18 |
| System | Windows 10 |
| Browser | Firefox, Chrome |

---
In the example, I added css with background-color to the :after element on hover, for better visualization

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/40482

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix Tabs more button unexpected height.       |
| 🇨🇳 Chinese |    修复 Tabs 组件更多按钮高度错误。       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

File: components/tabs/style/index.ts [hunk 1]
```diff
@@ -773,21 +773,22 @@ const genTabsStyle: GenerateStyle<TabsToken> = (token: TabsToken): CSSObject =>
...
+          //   },
+          //   bottom: 0,
+          //   left: {
+          //     _skip_check_: true,
+          //     value: 0,
+          //   },
+          //   height: token.controlHeightLG / 8,
+          //   transform: 'translateY(100%)',
+          //   content: "''",
+          // },
```
Comment (afc163) [inline components/tabs/style/index.ts:791]: 直接删了吧

**Review by Wxh16144 — APPROVED** [review]

**Review by li-jia-nan — APPROVED** [review]
