### PR TITLE
fix: Avatar.Group key lost

### LINKED ISSUE #26087: antd Avatar.group doesn't accept key
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/0th77)

### Steps to reproduce
copy paste the code from the official docs

### What is expected?
not to get the warning: "Each child in a list should have a unique "key" prop.

Check the render method of `Group"

### What is actually happening?
get the warning: "Each child in a list should have a unique "key" prop.

Check the render method of `Group"

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | latest |
| System | windows |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by xrkffgg**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
fix https://github.com/ant-design/ant-design/issues/26087

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix the missing `key` of Avatar.Group.     |
| 🇨🇳 Chinese | 修复 Avatar.Group `key` 缺失的问题。          |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/avatar/group.tsx [hunk 1]
```diff
@@ -28,13 +29,19 @@ const Group: React.FC<GroupProps> = props => {
...
   const { children, maxPopoverPlacement = 'top' } = props;
-  const childrenWithProps = toArray(children);
+  const childrenWithProps = toArray(children).map((child, index) => {
+    return cloneElement(child, {
+      key: `avatar-key-${index}`,
+    });
+  });
+
   const numOfChildren = childrenWithProps.length;
   if (maxCount && maxCount < numOfChildren) {
```
Comment (afc163) [inline components/avatar/group.tsx:39]: 没进 if 的时候直接用 children 就可以了吧？没必要 toArray 一下。

File: components/avatar/group.tsx [hunk 2]
```diff
@@ -51,7 +58,7 @@ const Group: React.FC<GroupProps> = props => {
   }
   return (
     <div className={cls} style={props.style}>
-      {children}
+      {childrenWithProps}
```
Comment (xrkffgg) [inline components/avatar/group.tsx:61]:
```suggestion
      {children}
```
