### PR TITLE
fix: fix Table filter behavior when filterDropdown is undefined

### LINKED ISSUE #49025: Ant Design Table: filterDropdown undefined, filters and filteredValue not working together
### Reproduction link

[Edit on StackBlitz](https://stackblitz.com/edit/vitejs-vite-dg18zf?file=src%2FApp.tsx)

### Steps to reproduce

1. Apply filter on column "Check"
2. Re-open filter

### What is expected?

Filter should display selected option.

### What is actually happening?

I applied a filter on the column “Check” and it worked fine. However, when I re-open the filter, the selected option is not displayed. This only happens when `filterDropdown` is undefined and both `filters` and `filteredValue` fields are populated.

| Environment | Info |
| --- | --- |
| antd | 5.17.3 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome |

---
It is a layout bug only, not a functionality bug. If you comment the line with "filterDropdown: undefined" (line number 65 in the reproduction link), it works as expected.

### PR DESCRIPTION
**Pull request by afc163**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

close https://github.com/ant-design/ant-design/issues/49025

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Table filter menu selection state loss when `column.filterDropdown` is set to `undefined`.    |
| 🇨🇳 Chinese | 修复 Table `column.filterDropdown` 指定为 `undefined` 导致筛选菜单选中状态丢失的问题。       |

## Summary by CodeRabbit

- **测试**
  - 增加了针对表格过滤的测试场景，确保在未提供自定义过滤选项时依然能正确展示过滤结果，从而提升了整体功能的稳定性。

### CODE REVIEW

File: components/table/hooks/useFilter/index.tsx [hunk 1]
```diff
@@ -34,11 +34,11 @@ const collectFilterStates = <RecordType extends AnyObject = AnyObject>(
   (columns || []).forEach((column, index) => {
     const columnPos = getColumnPos(index, pos);
 
-    if (column.filters || 'filterDropdown' in column || 'onFilter' in column) {
+    if (column.filters || typeof column.filterDropdown !== 'undefined' || 'onFilter' in column) {
```
Comment (zombieJ) [inline components/table/hooks/useFilter/index.tsx:37]: 如果是 undefined 判断的话直接 `!== undefined` 如何。`column.filterDropdown` 应该是不需要安全检查的~

**Review by zombieJ — APPROVED** [review]
