### PR TITLE
fix: tailwindcss reset Image style

### LINKED ISSUE #39913: Bug: 在引入 tailwindcss 后，Image 组件的预览样式会出现问题（预览的图片偏移了，都在左下角，且看不全了） ❌
### Reproduction link

[https://stackblitz.com/edit/vitejs-vite-s5eias](https://stackblitz.com/edit/vitejs-vite-s5eias)

### Steps to reproduce

打开这个链接后，点击加载出来的图片组件，可以看到，预览的图片样式出现问题

### What is expected?

正常预览

### What is actually happening?

预览样式存在问题（图片偏移了，都在左下角，且看不全了），应该是被 tailwind 影响了，index.css中只要不引入 下面的就没事。
``` 
@tailwind base;
@tailwind components;
@tailwind utilities; 
```

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 18.2.0 |
| System | macos |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #39913

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Resolve Image preview style conflict with TailwindCSS.        |
| 🇨🇳 Chinese |     解决 Image 预览样式会被 TailwindCSS 影响的问题。       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/image/style/index.ts [hunk 1]
```diff
@@ -197,6 +197,9 @@ export const genImagePreviewStyle: GenerateStyle<ImageToken> = (token: ImageToke
           '&-wrapper': {
             ...genBoxStyle(),
             transition: `transform ${motionDurationSlow} ${motionEaseOut} 0s`,
+            display: 'flex',
```
Comment (yoyo837) [inline components/image/style/index.ts:200]: 不加注释讲一下为什么后续怕是容易被删哦 😂

**Review by li-jia-nan — APPROVED** [review]
