### PR TITLE
fix: InputNumber in Form with hasFeedback should not lose focus

### LINKED ISSUE #45612: Form input losing focus after first character entered with hasFeedback
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/customized-validation-antd-5-10-3-forked-2xmft3?file=/demo.tsx)

### Steps to reproduce

Create a form item with "InputNumber" and item props "hasFeedback" with a required rule, WITH "name", and WITHOUT "validateStatus".
In this instance you get a form item with a red asterisk (as required) and no validation indicator shown yet.

### What is expected?

The input shouldn't lose focus when the validation indicator first appears and should be able to enter more than one character.

### What is actually happening?

When you start typing in the input after you enter the first character the validation indicator appears and the input loses focus so you can't enter any more characters without giving the input focus again.  (This was picked up in our unit tests after migrating to v5).
Note once the validation indicator is there everything works as expected.
Note removing the "name" prop seems to fix the issue in terms of entering multiple characters, though it also results in the red asterisk not showing and the validation indicator not showing?

Here the form items are identical except one has the name prop set.
changes

| Environment | Info |
| --- | --- |
| antd | 5.10.3 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Chrome Version 119.0.6045.106 (Official Build) (64-bit) |

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/45612

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix InputNumber in Form with `hasFeedback` that will lose focus when feedback icon appear.         |
| 🇨🇳 Chinese |      修复 InputNumber 组件在 Form 组件中使用并且启用 `hasFeedback` 时，反馈图标出现会使 InputNumber 失去焦点的问题。     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 362b2db</samp>

Improved form testing and fixed input number warning. Added a test case for `InputNumber` with `hasFeedback` and refactored the suffix icon logic in `components/input-number/index.tsx`. Fixed a warning caused by passing a boolean to the `suffix` prop of `Input`.

### <samp>🤖 Generated by Copilot at 362b2db</samp>

* Fix the issue of suffix icon disappearing in `InputNumber` with `hasFeedback` prop ([link](https://github.com/ant-design/ant-design/pull/45632/files?diff=unified&w=0#diff-6c85e13d1b03c66a69812b7717bd3695471bc2a1a381475e085c9dcf28662faaR106-R107), [link](https://github.com/ant-design/ant-design/pull/45632/files?diff=unified&w=0#diff-6c85e13d1b03c66a69812b7717bd3695471bc2a1a381475e085c9dcf28662faaL117-R119))
* Import `act` function to wrap `fireEvent` calls in form tests and ensure consistent assertions ([link](https://github.com/ant-design/ant-design/pull/45632/files?diff=unified&w=0#diff-f3bb49bfe69c75aa977732eec74dfe67b8b00e00fc5e008c4f1d3835ae296eacL13-R13))
* Add a test case for `InputNumber` with `hasFeedback` prop to check the suffix icon and focused style ([link](https://github.com/ant-design/ant-design/pull/45632/files?diff=unified&w=0#diff-f3bb49bfe69c75aa977732eec74dfe67b8b00e00fc5e008c4f1d3835ae296eacR2074-R2104))

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

File: components/input-number/index.tsx [hunk 1]
```diff
@@ -103,6 +103,9 @@ const InputNumber = React.forwardRef<HTMLInputElement, InputNumberProps>((props,
   );
   const wrapperClassName = `${prefixCls}-group`;
 
+  // eslint-disable-next-line react/jsx-no-useless-fragment
```
Comment (crazyair) [inline components/input-number/index.tsx:106]: <> 这个应该使用比较频繁的，可以整体把规则删掉

**Review by zombieJ — APPROVED** [review]

File: components/input-number/index.tsx (hunk 1 above)
Comment (MadCcc) [reply components/input-number/index.tsx:106]: 开着吧，这里是特殊用法，为了保持 dom 做的特殊处理

**Review by kiner-tang — APPROVED** [review]

**Review by crazyair — APPROVED** [review]
