### PR TITLE
fix: Button default event handler

### LINKED ISSUE #43654: Events type lost on the Button component
### Reproduction link

[https://antd-broken-onclick--joelcampospi.repl.co/](https://antd-broken-onclick--joelcampospi.repl.co/)

### Steps to reproduce

Use the onClick event of a Button component. The type of the parameter of the onClick function is now 'any' instead of the expected Event type.

### What is expected?

To have a valid Event type for the parameter of the onClick event.

### What is actually happening?

An 'any' type is being inferred

| Environment | Info |
| --- | --- |
| antd | 5.7.1 |
| React | 18.2.0 |
| System | WSL Ubuntu 22 |
| Browser | Firefox and Edge |

---
This didn't happened on the 5.7.0 version, so it might have broken because of some changes in the latest release (5.7.0 -> 5.7.1).

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #43654

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix Button `onClick` missing `event` definition.       |
| 🇨🇳 Chinese |   修复 Button `onClick` 事件丢失 `event` 定义的问题。     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 00f9aff</samp>

This pull request enhances the Button component by simplifying its type definitions, adding more test cases, and updating the deprecation notice for version 5.7.1.

### <samp>🤖 Generated by Copilot at 00f9aff</samp>

*  Simplify the type definitions for the ButtonProps by merging the AnchorButtonProps and NativeButtonProps into one interface ([link](https://github.com/ant-design/ant-design/pull/43666/files?diff=unified&w=0#diff-463cd38ab465e1f3b90463a403d8e8399f926361436eaa9adb8a76a8bf9d4140L58-R67))
* Remove the unnecessary type casting of props and rest as InternalButtonProps or NativeButtonProps, since they are already typed as ButtonProps ([link](https://github.com/ant-design/ant-design/pull/43666/files?diff=unified&w=0#diff-463cd38ab465e1f3b90463a403d8e8399f926361436eaa9adb8a76a8bf9d4140L128-R121), [link](https://github.com/ant-design/ant-design/pull/43666/files?diff=unified&w=0#diff-463cd38ab465e1f3b90463a403d8e8399f926361436eaa9adb8a76a8bf9d4140L221-R214), [link](https://github.com/ant-design/ant-design/pull/43666/files?diff=unified&w=0#diff-463cd38ab465e1f3b90463a403d8e8399f926361436eaa9adb8a76a8bf9d4140L283-R276))
* Add more test cases for the Button component, covering different props, types, and refs, to improve the code coverage and ensure the expected behavior ([link](https://github.com/ant-design/ant-design/pull/43666/files?diff=unified&w=0#diff-276fe24dfac9bfa7de4a29f91e72acd80a99b1034b459bc7b7ebf2db5c47805cL354-R386))
* Add a new entry to the DEPRECIATED_VERSION object in `scripts/post-script.js`, mapping the version 5.7.1 to a GitHub issue link, to inform the users of the deprecated features or breaking changes in that version and provide a reference for the migration guide ([link](https://github.com/ant-design/ant-design/pull/43666/files?diff=unified&w=0#diff-0c429b9a01f20777bce85b2ad2472fe50f00b4ef8a404d56852f3d4dd15e905dR42))

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

File: components/button/button.tsx [hunk 1]
```diff
@@ -55,22 +55,15 @@ export interface BaseButtonProps {
...
-  target?: React.HTMLAttributeAnchorTarget;
-  onClick?: React.MouseEventHandler<HTMLAnchorElement>;
-} & BaseButtonProps &
-  Omit<React.AnchorHTMLAttributes<HTMLAnchorElement | HTMLButtonElement>, 'type' | 'onClick'>;
-
-export type NativeButtonProps = {
-  htmlType?: ButtonHTMLType;
-  onClick?: React.MouseEventHandler<HTMLButtonElement>;
-} & BaseButtonProps &
-  Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'type' | 'onClick'>;
```
Comment (afc163) [inline components/button/button.tsx:69]: https://github.com/ant-design/ant-design/issues/43711

ButtonHTMLAttributes 没了
