### PR TITLE
fix: optimize the type definition of Modal 

### LINKED ISSUE #41735: 使用5.4.0版本的modal组件，afterOpenChange属性typescript报错
### Reproduction link

[https://ant.design/components/modal-cn](https://ant.design/components/modal-cn)

### Steps to reproduce

无

### What is expected?

能正常使用该属性

### What is actually happening?

使用该属性，ts报错

| Environment | Info |
| --- | --- |
| antd | 5.4.0 |
| React | 18.2 |
| System | mac |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by MuxinFeng**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/41735

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Optimize the type definition of Modal     |
| 🇨🇳 Chinese |     完善 Modal 的类型定义      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 58acf10</samp>

This pull request adds a new prop `afterOpenChange` to the `Modal` and `ConfirmDialog` components, and tests its functionality. The prop allows users to specify a callback function that runs after the modal transition finishes.

### <samp>🤖 Generated by Copilot at 58acf10</samp>

*  Add `afterOpenChange` prop to `Modal` and `ConfirmDialog` components, which is a function that is called after the modal animation ends when the modal is opened or closed ([link](https://github.com/ant-design/ant-design/pull/41742/files?diff=unified&w=0#diff-a3edcd43b644d0539a67f65e68ba30d6acb77a12531a6a71d1e26a008a9d752cR52-R53), [link](https://github.com/ant-design/ant-design/pull/41742/files?diff=unified&w=0#diff-d3734257bd9f28b52a331a7cc2fb5a3efd91c2fc71be29356d2fb171768ba9a3R135), [link](https://github.com/ant-design/ant-design/pull/41742/files?diff=unified&w=0#diff-d3734257bd9f28b52a331a7cc2fb5a3efd91c2fc71be29356d2fb171768ba9a3R200)).

### CODE REVIEW

File: components/modal/ConfirmDialog.tsx [hunk 1]
```diff
@@ -196,6 +197,7 @@ const ConfirmDialog: React.FC<ConfirmDialogProps> = (props) => {
         width={width}
         zIndex={zIndex}
         afterClose={afterClose}
+        afterOpenChange={afterOpenChange}
```
Comment (afc163) [inline components/modal/ConfirmDialog.tsx:200]: 这就不只是修类型了把，confirm 用法之前就不支持 afterOpenChange

File: components/modal/Modal.tsx [hunk 2]
```diff
@@ -49,6 +49,8 @@ export interface ModalProps {
   /** 点击模态框右上角叉、取消按钮、Props.maskClosable 值为 true 时的遮罩层或键盘按下 Esc 时的回调 */
   onCancel?: (e: React.MouseEvent<HTMLButtonElement>) => void;
   afterClose?: () => void;
+  /** 打开和关闭 Modal 时动画结束后的回调 */
```
Comment (yoyo837) [inline components/modal/Modal.tsx:52]: 代码注释尽量英文或者双语吧?

File: components/modal/__tests__/Modal.test.tsx [hunk 3]
```diff
@@ -126,4 +126,5 @@ describe('Modal', () => {
     render(<Modal open footer={<div className="custom-footer">footer</div>} />);
     expect(document.querySelector('.custom-footer')).toBeTruthy();
   });
+
```
Comment (afc163) [inline components/modal/__tests__/Modal.test.tsx:129]: 多了个空行。

**Review by afc163 — APPROVED** [review]
