### PR TITLE
types: export DatePickRef and RangePickerRef (close #33417)

### LINKED ISSUE #33417: Incorrect types for DatePicker
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-0oj2e?file=/index.tsx)

### Steps to reproduce
import React, { forwardRef } from 'react'
import { DatePicker as AntDatePicker, DatePickerProps as AntDatePickerProps } from 'antd'
import cl from 'classnames'

import styles from './styles.module.scss'

type DatePickerProps = AntDatePickerProps

const DatePicker = forwardRef<AntDatePicker, DatePickerProps>(({ className, ...props }, ref) => {
	return <AntDatePicker {...props} className={cl(styles.datePicker, className)} ref={ref} />
})

export default DatePicker

### What is expected?
no any TS errors 

### What is actually happening?
typescript(4.1.2)  return the error: TS2749: 'AntDatePicker' refers to a value, but is being used as a type here. Did you mean 'typeof AntDatePicker'?

| Environment | Info |
|---|---|
| antd | 4.16.10 |
| React | 17.0.2 |
| System | - |
| Browser | - |

### PR DESCRIPTION
**Pull request by Amour1688**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #33417

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix DatePicker `ref` TypeScript definition.         |
| 🇨🇳 Chinese | 修复 DatePicker `ref` TypeScript 定义。          |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
看看 ci

File: components/date-picker/generatePicker/interface.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
+import type { ComponentClass, ForwardedRef, Component } from 'react';
```
Comment (acfasj) [inline components/date-picker/generatePicker/interface.ts:1]: image

有两个interface了, 旧的删掉吧

Comment (afc163) [reply components/date-picker/generatePicker/interface.ts:1]: @Amour1688
