### PR TITLE
fix: RangePicker time column sometime not scroll

### LINKED ISSUE #47526: RangePicker showTime 时分秒位置异常
### Reproduction link

[https://stackblitz.com/edit/react-asmdwg?file=demo.tsx](https://stackblitz.com/edit/react-asmdwg?file=demo.tsx)

### Steps to reproduce

1. 开始时间设置 0点0分0秒，结束时间设置 23点59分59秒
2. 再次点击开始时间

### What is expected?

时分秒滚动位置应该与当前激活的日期一致

### What is actually happening?

开始时间的时分秒没有显示0点，而是显示的23点

| Environment | Info |
| --- | --- |
| antd | 5.14.1 |
| React | latest |
| System | mac |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #47526

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix DatePicker.RangePicker time column sometime not scroll to the target time value.       |
| 🇨🇳 Chinese |    修复 DatePicker.RangePicker 的时间列有时不会滚动到正确位置的问题。       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

File: components/date-picker/style/panel.ts [hunk 1]
```diff
@@ -629,14 +629,6 @@ export const genPanelStyle = (token: SharedPickerToken): CSSObject => {
...
         },
       },
-      // https://github.com/ant-design/ant-design/issues/39227
-      [`&-datetime-panel ${componentCls}-time-panel-column:after`]: {
-        height: token
-          .calc(timeColumnHeight)
-          .sub(timeCellHeight)
-          .add(token.calc(paddingXXS).mul(2))
-          .equal(),
-      },
```
Comment (yoyo837) [inline components/date-picker/style/panel.ts:639]: 不需要用例吗？

**Review by crazyair — APPROVED** [review]

File: components/date-picker/style/panel.ts (hunk 1 above)
Comment (zombieJ) [reply components/date-picker/style/panel.ts:639]: 这个是 CSS...
