### PR TITLE
fix: test antd dark theme component

### LINKED ISSUE #19971: 4.0 dark theme issues
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

related: https://github.com/ant-design/ant-design/pull/19968

- [x] Empty svg image use className add style
- [x]  progress fill use className
- [x] dark theme usage document

### What does the proposed API look like?
antd 4.0 dark theme

### PR DESCRIPTION
**Pull request by ycjcl868**
only for dark component preview, not merge before removing `[WIP]`

Close #19971.

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by zombieJ** [comment]
简洁了很多👍

File: components/progress/progress.tsx [hunk 1]
```diff
@@ -49,7 +49,8 @@ export default class Progress extends React.Component<ProgressProps> {
     type: 'line',
     percent: 0,
     showInfo: true,
-    trailColor: '#f3f3f3',
+    // null for different theme definition
+    trailColor: null,
```
Comment (ycjcl868) [inline components/progress/progress.tsx]: @zombieJ  trailColor 传 null 目的是避免  rc-progress 使用 `defaultProps` ，将 trail color 加到 style 上。

File: components/steps/style/index.less [hunk 2]
```diff
@@ -5,7 +5,6 @@
 @process-icon-color: @primary-color;
 @process-title-color: @heading-color;
 @process-description-color: @text-color;
-@process-tail-color: @border-color-split;
```
Comment (ycjcl868) [inline components/steps/style/index.less]: put into `default.less` for theme

**Review by zombieJ — APPROVED** [review]
