### PR TITLE
fix(drawer): improve accessibility (aria-labelledby)

### LINKED ISSUE #55682: Drawer component is missing accessible name (aria-dialog-name violation)
### Reproduction link

[Edit on StackBlitz](https://stackblitz.com/edit/cxs1uwrm)

### Steps to reproduce

	1.	Use <Drawer open={true}>...</Drawer> in a React component.
	2.	Run an accessibility audit (e.g. Lighthouse, axe, WAVE).
	3.	Observe that the drawer root element .ant-drawer-content triggers a “aria-dialog-name” violation.

### What is expected?

Every element with role="dialog" or aria-modal="true" should have an accessible name via one of the following:
	•	aria-label="..."
	•	aria-labelledby="..."
	•	or a visible title element.

Ant Design should automatically add a name to the Drawer when the title prop is provided.

### What is actually happening?

The rendered <div class="ant-drawer-content" aria-modal="true" role="dialog"> has no accessible name (missing aria-label, aria-labelledby, or title attribute).
This results in a WCAG 2.1 1.3.1 / 4.1.2 violation (“ARIA dialog nodes must have an accessible name”).

| Environment | Info |
| --- | --- |
| antd | 5.28.1 |
| React | react: 17.0.2 |
| System | macOS 15.6.1 |
| Browser | Chromium Version 141.0.7390.37 (Offizieller Build) (arm64) |

---
This issue affects screen reader users because the Drawer dialog is announced without a name, making it unclear what context or content is active.
Tested using axe-core 4.10.1 and Lighthouse.

### PR DESCRIPTION
**Pull request by rxy001**
### 🤔 This is a ...

- [ ] 🆕 New feature
- [ ] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [x] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

fix #55682 

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)! Track your changes, like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  fix(drawer): improve accessibility (aria-labelledby)   |
| 🇨🇳 Chinese |  fix(drawer): improve accessibility (aria-labelledby)   |

### CODE REVIEW

**Review by meet-student — APPROVED** [review]

**Review by meet-student — CHANGES_REQUESTED** [review]
看下 AI 的评论

File: components/drawer/index.tsx [hunk 1]
```diff
@@ -82,6 +83,9 @@ const Drawer: React.FC<DrawerProps> & {
     ...rest
   } = props;
 
+  const id = React.useId();
+  const titleId = rest.title ? id : undefined;
+
```
[the remark this answers is not in the document]
Comment (meet-student) [reply components/drawer/index.tsx]: 这个 用 rc 的

File: components/drawer/index.tsx [hunk 2]
```diff
@@ -82,6 +83,9 @@ const Drawer: React.FC<DrawerProps> & {
     ...rest
   } = props;
 
+  const id = React.useId();
```
Comment (meet-student) [inline components/drawer/index.tsx]: 叫 ariaId 吧
下面都透穿这个, 可读性好点

Comment (rxy001) [reply components/drawer/index.tsx]: 意思是将 titleId 都改成 ariaId ？

Comment (meet-student) [reply components/drawer/index.tsx]: 嗯呐

**Review by meet-student — APPROVED** [review]

File: components/drawer/index.tsx [hunk 3]
```diff
@@ -82,6 +84,9 @@ const Drawer: React.FC<DrawerProps> & {
     ...rest
   } = props;
 
+  let ariaId: string | undefined = useId();
+  ariaId = rest.title ? ariaId : undefined;
```
Comment (cgaube) [inline components/drawer/index.tsx:88]: issue: if someone add a `aria-label="Something"`  to the drawer component this mess everything up 

We need to make sure to add the ariaId only if needed ! 

Another problem because of this PR is that in tests the useId always return `test-id` and if you have more than one component in your test that use useId then you have a bunch of conflicts !

```
const notificationSettingsDrawer = screen.getByRole('dialog', {
        name: 'Notification Settings',   
      })
```
wont work anymore if other component use  useId somewhere else  (for example if one drawer open another drawer !

Comment (cgaube) [reply components/drawer/index.tsx:88]: ```<div class="ant-drawer-section" role="dialog" aria-labelledby="_r_u_" aria-modal="true" aria-label="TOTALLY IGNORED"></div>```

Comment (cgaube) [reply components/drawer/index.tsx:88]: Workaround

```
    <Drawer
      aria-label="DONT IGNORE ME"
      aria-labelledby='' <------- add this to skip this PR code 
      title="Dialog title"
```
