### PR TITLE
fix: Splitter ptg not fully cover

### LINKED ISSUE #55587: Splitter组件拖动宽度后，父容器宽度变化时，Panel总宽度之和没变化
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/strange-sound-lq7jnw)

### Steps to reproduce

1.拖动分割线
2.增加父容器宽度

### What is expected?

Panel总宽度之和等于Splitter宽度

### What is actually happening?

父容器宽度变化时，Panel总宽度之和没变化

| Environment | Info |
| --- | --- |
| antd | 5.28.0 |
| React | 18.3.1 |
| System | win10 20H2 |
| Browser | Chromium 134.0.6998.136 |

### PR DESCRIPTION
**Pull request by zombieJ**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

resolve #55587
close #55590

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)! Track your changes, like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix Splitter failing to fill its container when the sum of panel proportions is not 1.      |
| 🇨🇳 Chinese |     修复 Splitter 在 Panel 总占比不为 1 时出现占不满的情况。      |

### CODE REVIEW

**Review by afc163 — DISMISSED** [review]

File: components/splitter/hooks/sizeUtil.ts [hunk 1]
```diff
@@ -19,6 +19,13 @@ export function autoPtgSizes(
   const restPtg = 1 - currentTotalPtg;
   const undefinedCount = undefinedIndexes.length;
 
+  // If all sizes are defined but don't sum to 1, scale them.
+  if (undefinedIndexes.length === 0 && currentTotalPtg !== 1) {
+    const scale = 1 / currentTotalPtg;
+    // We know `size` is a number here because undefinedIndexes is empty.
+    return ptgSizes.map((size) => (size as number) * scale);
+  }
```
Comment (afc163) [inline components/splitter/hooks/sizeUtil.ts:32]: +1

**Review by MadCcc — APPROVED** [review]
