### PR TITLE
fix: Dropdown overlay string issue

### LINKED ISSUE #26134: Dropdown overlay as string wrong output
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/adoring-poincare-2w56x)

### Steps to reproduce
hover orver dropdown

### What is expected?
To show the same string as overlay prop

### What is actually happening?
the dropdown shows "overlayNode" string instead

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 6.12 |
| System | windows |
| Browser | any |

---
Even though using string as overlay is not documented, I'm sure it wasn't intended to show "overlayNode" there

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #26134

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Dropdown render issue when `overlay` is string. |
| 🇨🇳 Chinese | 修复 Dropdown `overlay` 是 string 时渲染错误的问题。   |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/dropdown/dropdown.tsx [hunk 1]
```diff
@@ -87,7 +87,7 @@ const Dropdown: DropdownInterface = props => {
       overlayNode = overlay;
     }
     overlayNode = React.Children.only(
-      typeof overlayNode === 'string' ? <span>overlayNode</span> : overlayNode,
+      typeof overlayNode === 'string' ? <span>{overlayNode}</span> : overlayNode,
```
Comment (afc163) [inline components/dropdown/dropdown.tsx:90]: 低级错误..

**Review by xrkffgg — APPROVED** [review]
