### PR TITLE
fix(Descriptions): nested Descriptions are affected by the external border style

### LINKED ISSUE #43446: Nest Description borderless inside a bordered creates UI bug
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/border-antd-5-6-4-forked-klsv8h?file=/demo.tsx)

### Steps to reproduce

1. create a bordered description <Descriptions bordered/>
2. in one of the <Descriptions.Item /> create another description but borderless <Descriptions bordered={false}  />

### What is expected?

expected the inner <Descriptions /> to be borderless

### What is actually happening?

introduced weird UI

| Environment | Info |
| --- | --- |
| antd | 5.6.4 |
| React | latest |
| System | all |
| Browser | all |

### PR DESCRIPTION
**Pull request by Yuiai01**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/43446
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix ` Descriptions` nested` Descriptions` are affected by the external border style           |
| 🇨🇳 Chinese | 修复 `Descriptions` 组件嵌套的 `Descriptions` 组件会受到外部边框样式影响          |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at c4611a0</samp>

This pull request adds a new feature to the `Descriptions` component that allows it to have a rimless appearance. It also improves the CSS styling of the bordered and rimless layouts and updates the test file accordingly. The changes affect the files `components/descriptions/index.tsx`, `components/descriptions/style/index.ts`, and `components/descriptions/__tests__/index.test.tsx`.

### <samp>🤖 Generated by Copilot at c4611a0</samp>

*  Add support for rimless descriptions with `bordered` prop ([link](https://github.com/ant-design/ant-design/pull/43454/files?diff=unified&w=0#diff-fa6188100c10d4e92a00d60fe3e3de4bfa896ad3563c67bba6ecdc141b8c4c9aR173), [link](https://github.com/ant-design/ant-design/pull/43454/files?diff=unified&w=0#diff-83d49477d5a3e84b0fcf24f108ae5c1c434b5e3842be98fbecddeb76bc5dd169L47-R47), [link](https://github.com/ant-design/ant-design/pull/43454/files?diff=unified&w=0#diff-83d49477d5a3e84b0fcf24f108ae5c1c434b5e3842be98fbecddeb76bc5dd169L53-R93))
  - Use new class name `${prefixCls}-rimless` to apply different styles to the `Descriptions` component based on the `bordered` prop ([link](https://github.com/ant-design/ant-design/pull/43454/files?diff=unified&w=0#diff-fa6188100c10d4e92a00d60fe3e3de4bfa896ad3563c67bba6ecdc141b8c4c9aR173))
  - Modify CSS selector for bordered descriptions to target direct child of `${componentCls}-view` and avoid conflicts with rimless descriptions ([link](https://github.com/ant-design/ant-design/pull/43454/files?diff=unified&w=0#diff-83d49477d5a3e84b0fcf24f108ae5c1c434b5e3842be98fbecddeb76bc5dd169L47-R47))
  - Restructure CSS rules for bordered descriptions to nest them under `${componentCls}-row` and add rules for rimless descriptions to unset padding for middle and small sizes ([link](https://github.com/ant-design/ant-design/pull/43454/files?diff=unified&w=0#diff-83d49477d5a3e84b0fcf24f108ae5c1c434b5e3842be98fbecddeb76bc5dd169L53-R93))
* Add test case for nested `Descriptions` components with `bordered` prop ([link](https://github.com/ant-design/ant-design/pull/43454/files?diff=unified&w=0#diff-12b6ba8cb14a965604bc8d300d6519622043ad3cf7dee78356a3305af26831e0R282-R295))
  - Check that the `bordered` prop of the parent `Descriptions` component does not affect the nested `Descriptions` components within an `Item` ([link](https://github.com/ant-design/ant-design/pull/43454/files?diff=unified&w=0#diff-12b6ba8cb14a965604bc8d300d6519622043ad3cf7dee78356a3305af26831e0R282-R295))
  - Use `components/descriptions/__tests__/index.test.tsx` file to add the test case ([link](https://github.com/ant-design/ant-design/pull/43454/files?diff=unified&w=0#diff-12b6ba8cb14a965604bc8d300d6519622043ad3cf7dee78356a3305af26831e0R282-R295))
* Remove extra space at the end of test description for consistency and readability ([link](https://github.com/ant-design/ant-design/pull/43454/files?diff=unified&w=0#diff-12b6ba8cb14a965604bc8d300d6519622043ad3cf7dee78356a3305af26831e0L272-R272))
  - Use `components/descriptions/__tests__/index.test.tsx` file to remove the space ([link](https://github.com/ant-design/ant-design/pull/43454/files?diff=unified&w=0#diff-12b6ba8cb14a965604bc8d300d6519622043ad3cf7dee78356a3305af26831e0L272-R272))

### CODE REVIEW

File: components/descriptions/index.tsx [hunk 1]
```diff
@@ -170,6 +170,7 @@ function Descriptions({
           prefixCls,
           {
             [`${prefixCls}-${mergedSize}`]: mergedSize && mergedSize !== 'default',
+            [`${prefixCls}-rimless`]: !bordered,
```
Comment (li-jia-nan) [inline components/descriptions/index.tsx:173]: 这个className命名可以参考其它地方，叫做 `xxxx-borderless`，其次这里用了 `bordered`，也用了 `!bordered`，建议改成三元表达式

Comment (Yuiai01) [reply components/descriptions/index.tsx:173]: > 这个className命名可以参考其它地方，叫做 `xxxx-borderless`，其次这里用了 `bordered`，也用了 `!bordered`，建议改成三元表达式

好～

File: components/descriptions/index.tsx [hunk 2]
```diff
@@ -170,9 +170,9 @@ function Descriptions({
           prefixCls,
           {
             [`${prefixCls}-${mergedSize}`]: mergedSize && mergedSize !== 'default',
-            [`${prefixCls}-bordered`]: !!bordered,
             [`${prefixCls}-rtl`]: direction === 'rtl',
           },
+          `${prefixCls}-${bordered ? 'bordered' : 'borderless'}`,
```
Comment (MadCcc) [inline components/descriptions/index.tsx:175]: 如果都使用子代选择器的话就不需要添加 `borderless` 了吧

Comment (Yuiai01) [reply components/descriptions/index.tsx]: 改好了～

**Comment by Yuiai01** [comment]
> 和我之前解决 #39183 一样, PR #39212. 其他样式是不是也需要修复一下? 还是分开修

看起来是一类问题，要不一起修了？

**Review by MadCcc — APPROVED** [review]

**Review by kiner-tang — APPROVED** [review]
