### PR TITLE
Fix(Table): Hide emptyType in `Table` when `loading` prop is true

### LINKED ISSUE #9069: Hide text in `Table` when `loading` prop is true
### Version
3.1.4

### Environment
OS X High Sierra, Chrome 63

### Reproduction link
[https://codepen.io/anon/pen/OzdLrR?editors=0010](https://codepen.io/anon/pen/OzdLrR?editors=0010)

### Steps to reproduce
Render a table with no data with the `loading` prop as `true` (see codepen link)

### What is expected?
`locale.emptyText` placeholder text does not show, because the table is still loading

### What is actually happening?
The loading spinner and the `locale.emptyText` placeholder are both visible

---
Originally reported here: https://github.com/ant-design/ant-design/issues/8788

### PR DESCRIPTION
**Pull request by sallen450**
First of all, thank you for your contribution! :-)

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

* [x] Make sure that you propose PR to right branch: bugfix for `master`, feature for latest active branch `feature-x.x`.
* [x] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [x] Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

Extra checklist:

* [x] Make sure that you add at least one unit test for the bug which you had fixed.

fixed #9069

### CODE REVIEW

File: components/table/Table.tsx [hunk 1]
```diff
@@ -948,7 +949,7 @@ export default class Table<T> extends React.Component<TableProps<T>, TableState<
         className={classString}
         expandIconColumnIndex={expandIconColumnIndex}
         expandIconAsCell={expandIconAsCell}
-        emptyText={locale.emptyText}
+        emptyText={emptyText}
```
Comment (nikogu) [inline components/table/Table.tsx]: 1. `const { ... loading ... } = this.props;`
2. `emptyText={loading  && locale.emptyText}`

Comment (sallen450) [reply components/table/Table.tsx]: fixed

2 should be `emptyText={!loading && locale.emptyText}`

**Comment by anneyangyue** [comment]
How to display images when the table content is empty?
