### PR TITLE
style: fix Table filter dropdown broken style

### LINKED ISSUE #39799: table 树型筛选菜单 选中颜色错误
### Reproduction link

https://ant.design/components/table-cn#components-table-demo-filter-in-tree

### Steps to reproduce

image

table 树型筛选菜单 选中颜色错误

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | React 18.2.0 |
| System | Windows |
| Browser | Chrome 103 |

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close #39799

### 💡 Background and solution

before | after
--- | ---
图片 | 图片

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Table filter dropdown wrong active background and dropdown shadow style.          |
| 🇨🇳 Chinese |  修复 Table 筛选菜单选中背景色和菜单阴影样式。         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/tree/style/index.tsx [hunk 1]
```diff
@@ -283,7 +283,7 @@ export const genBaseStyle = (prefixCls: string, token: TreeToken): CSSObject =>
         },
 
         [`&${treeCls}-node-selected`]: {
-          backgroundColor: token.controlOutline,
+          backgroundColor: token.controlItemBgActive,
```
Comment (afc163) [inline components/tree/style/index.tsx:286]: 这里用的也不对。

**Review by MadCcc — APPROVED** [review]
