### PR TITLE
fix: Cascader className duplicate

### LINKED ISSUE #27168: set className in cascader, there will tow classname the same in dom
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/wukong1995/pen/abZdVrb](https://codepen.io/wukong1995/pen/abZdVrb)

### Steps to reproduce
检查元素，查看dom节点

### What is expected?
one class

### What is actually happening?
 tow class the same

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.13.1 |
| System | macos |
| Browser | chrome lastest |

### PR DESCRIPTION
**Pull request by huntdream**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
close ant-design/ant-design#27168

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix `Cascader` className duplicate        |
| 🇨🇳 Chinese |     修复`Cascader` 类名重复      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/cascader/index.tsx [hunk 1]
```diff
@@ -642,12 +642,19 @@ class Cascader extends React.Component<CascaderProps, CascaderState> {
         );
 
         const getPopupContainer = props.getPopupContainer || getContextPopupContainer;
-        const rest = omit(props, ['inputIcon', 'expandIcon', 'loadingIcon', 'bordered']);
+        const rest = omit(props, [
+          'inputIcon',
+          'expandIcon',
+          'loadingIcon',
+          'bordered',
+          'className',
```
Comment (yoyo837) [inline components/cascader/index.tsx:650]: Why not omit it from the `input`?

Comment (huntdream) [reply components/cascader/index.tsx:650]: 考虑过这个，本来没必要从`input`里面加，但是偏偏加了，我觉得可能是有意这样做的，没考虑太多，所以就直接从props里面omit了
