### PR TITLE
fix: select type definition

### LINKED ISSUE #12793: Typescript Error for Auto-complete
- [ x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.2

### Environment

- mac OS 10.13  
- Intellij IDE 2018.2  
- react 16.4.2  
- typescript 3.0.1

### Reproduction link
[https://gist.github.com/jon-r/3078a56733440dcdf8d87c98219450b2](https://gist.github.com/jon-r/3078a56733440dcdf8d87c98219450b2)

### Steps to reproduce
The `onFocus` type does not exist in the AutoComplete prop interface.
Pasting the demo gist into an existing react tsx project will raise a type error

### What is expected?
that onFocus is a valid prop

### What is actually happening?
TS2339 'on focus does not exist on ... AutoCompleteProps'

### PR DESCRIPTION
**Pull request by muzea**
try to fix https://github.com/ant-design/ant-design/issues/12793

[There are some weird type definitions here](https://github.com/ant-design/ant-design/blob/master/components/date-picker/wrapPicker.tsx#L56),  Is it wrong?

### CODE REVIEW

**Comment by yesmeck** [comment]
Should change 
`handleFocus = (e: React.FocusEventHandler<HTMLInputElement>)` 
to 
`handleFocus: React.FocusEventHandler<HTMLInputElement> = (e)`

File: components/auto-complete/index.tsx [hunk 1]
```diff
@@ -31,8 +31,8 @@ export interface AutoCompleteProps extends AbstractSelectProps {
   optionLabelProp?: string;
   onChange?: (value: SelectValue) => void;
   onSelect?: (value: SelectValue, option: Object) => any;
-  onBlur?: () => any;
-  onFocus?: () => any;
+  onBlur?: React.FocusEventHandler<HTMLDivElement>;
+  onFocus?: React.FocusEventHandler<HTMLDivElement>;
   children?: ValidInputElement |
```
Comment (zombieJ) [inline components/auto-complete/index.tsx]: Select 的 `onBlur` 和 `onFocus` 不是标准的 `FocusEventHandler`。
onFocus 没有 arguments，onBlur 的 argument 是 Select 的 value

Comment (muzea) [reply components/auto-complete/index.tsx]: 还真是，我.......
改一下吧
