### PR TITLE
style: fix Switch as children of Form.Item not align center

### LINKED ISSUE #54042: The Switch and label inside the Form are not centered
### Reproduction link

[https://ant.design/components/form-cn](https://ant.design/components/form-cn)

### Steps to reproduce

Image

Image

### What is expected?

Switch 和 label 对齐

### What is actually happening?

Switch 和 label 没有对齐

| Environment | Info |
| --- | --- |
| antd | 5.26.0 |
| React | 18.3.1 |
| System | Windows |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by afc163**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [x] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

fix https://github.com/ant-design/ant-design/issues/54042
close https://github.com/ant-design/ant-design/pull/54047
close https://github.com/react-component/switch/pull/159

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

还是要针对性的修复，对 form item 内只有 Switch 或 Rate 组件元素时，将容器调为 flex 从而避免多余文本节点和  Switch/Rate 混排时的排版问题。

图片

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)! Track your changes, like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Switch/Rate is not align centerly in Form.Item.       |
| 🇨🇳 Chinese | 修复 Form 下 Switch/Rate 组件没有居中对齐的问题。          |

### CODE REVIEW

**Comment by wanpan11** [comment]
还是会影响其他的
image

**Comment by afc163** [comment]
Slider 也影响了，我看看。

**Comment by wanpan11** [comment]
看着好像可以了 

这个合了在康康 https://github.com/ant-design/ant-design/pull/54122

File: components/form/style/index.ts [hunk 1]
```diff
@@ -337,6 +337,12 @@ const genFormItemStyle: GenerateStyle<FormToken> = (token) => {
           '&-content': {
             flex: 'auto',
             maxWidth: '100%',
+
+            // remove impact of whitespaces
```
Comment (afc163) [inline components/form/style/index.ts]:
```suggestion
            // Fix https://github.com/ant-design/ant-design/issues/54042
            // Remove impact of whitespaces
```

**Review by wanpan11 — APPROVED** [review]

**Comment by crazyair** [comment]
最后还是妥协了
