### PR TITLE
fix: Popconfirm margin problem when icon is null

### LINKED ISSUE #42417: Popconfirm 的 title 是否可以改成 选填参数 &  自带的 ico 是否可以增加 让它不显示的参数和自定义图标
### What problem does this feature solve?

使用上可能只需要底部的按钮与 placement 这种各方位显示的功能，title 必穿与自带的 ico 可能有些局限性

### What does the proposed API look like?

  title?: React.ReactNode | RenderFunction;

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/42417#issuecomment-1550637349

### 💡 Background and solution

重构了 Popconfirm 的 dom 结构，如果手动覆盖样式可能会被影响。

核心改动在：https://github.com/ant-design/ant-design/pull/42433/files#diff-d57f0a697c7d1520b5a3174edf0317ae67cb31369b7ca569afa32ce074e2c770

| before | after |
| --- | --- |
| 图片 | 图片  |

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Refactor Popconfirm DOM structure to fix extra margin before `title` and `description` when `icon={null}`.           |
| 🇨🇳 Chinese | 重构 Popconfirm DOM 结构以解决 `icon={null}` 时 `title` 和 `description` 的多余 margin 问题。  |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 69e3c73</samp>

This pull request enhances the popconfirm component by refactoring its message rendering, improving its style and alignment, and fixing a test file typo. It affects the files `components/popconfirm/PurePanel.tsx`, `components/popconfirm/style/index.tsx`, and `components/popconfirm/__tests__/index.test.tsx`.

### <samp>🤖 Generated by Copilot at 69e3c73</samp>

*  Simplify and improve the rendering and styling of the popconfirm message ([link](https://github.com/ant-design/ant-design/pull/42433/files?diff=unified&w=0#diff-d57f0a697c7d1520b5a3174edf0317ae67cb31369b7ca569afa32ce074e2c770R62-R63), [link](https://github.com/ant-design/ant-design/pull/42433/files?diff=unified&w=0#diff-d57f0a697c7d1520b5a3174edf0317ae67cb31369b7ca569afa32ce074e2c770L67-R75), [link](https://github.com/ant-design/ant-design/pull/42433/files?diff=unified&w=0#diff-a6dc7f42c927c99f13026e3643a664c670f818173ebe7b5bc7e98571abc1ea66L18-R21), [link](https://github.com/ant-design/ant-design/pull/42433/files?diff=unified&w=0#diff-a6dc7f42c927c99f13026e3643a664c670f818173ebe7b5bc7e98571abc1ea66L35-L36), [link](https://github.com/ant-design/ant-design/pull/42433/files?diff=unified&w=0#diff-a6dc7f42c927c99f13026e3643a664c670f818173ebe7b5bc7e98571abc1ea66L46-R62))
  - Extract renderTitle and renderDescription variables from title and description props in `PurePanel.tsx` ([link](https://github.com/ant-design/ant-design/pull/42433/files?diff=unified&w=0#diff-d57f0a697c7d1520b5a3174edf0317ae67cb31369b7ca569afa32ce074e2c770R62-R63))
  - Wrap title and description in a separate div with the class `${prefixCls}-message-text` and render them only if truthy in `PurePanel.tsx` ([link](https://github.com/ant-design/ant-design/pull/42433/files?diff=unified&w=0#diff-d57f0a697c7d1520b5a3174edf0317ae67cb31369b7ca569afa32ce074e2c770L67-R75))
  - Add marginXXS token to the token object in `style/index.tsx` ([link](https://github.com/ant-design/ant-design/pull/42433/files?diff=unified&w=0#diff-a6dc7f42c927c99f13026e3643a664c670f818173ebe7b5bc7e98571abc1ea66L18-R21))
  - Remove redundant color and fontSize styles from the `${componentCls}-message` selector in `style/index.tsx` ([link](https://github.com/ant-design/ant-design/pull/42433/files?diff=unified&w=0#diff-a6dc7f42c927c99f13026e3643a664c670f818173ebe7b5bc7e98571abc1ea66L35-L36))
  - Adjust margin and font-weight of the icon, title, and description elements in `style/index.tsx` ([link](https://github.com/ant-design/ant-design/pull/42433/files?diff=unified&w=0#diff-a6dc7f42c927c99f13026e3643a664c670f818173ebe7b5bc7e98571abc1ea66L46-R62))
* Fix a typo and remove unnecessary innerHTML property in the test file `__tests__/index.test.tsx` ([link](https://github.com/ant-design/ant-design/pull/42433/files?diff=unified&w=0#diff-dfb6f01788186a5363498f0b24d48dbb55493cc5de43b306f1ad5e730b8df362L76-R76))
  - Replace the duplicated snapshot assertion with the correct one ([link](https://github.com/ant-design/ant-design/pull/42433/files?diff=unified&w=0#diff-dfb6f01788186a5363498f0b24d48dbb55493cc5de43b306f1ad5e730b8df362L76-R76))
  - Remove innerHTML from the querySelector argument, since the snapshot matcher can handle the whole element ([link](https://github.com/ant-design/ant-design/pull/42433/files?diff=unified&w=0#diff-dfb6f01788186a5363498f0b24d48dbb55493cc5de43b306f1ad5e730b8df362L76-R76))

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

**Review by kiner-tang — APPROVED** [review]

File: components/popconfirm/PurePanel.tsx [hunk 1]
```diff
@@ -59,22 +59,18 @@ export const Overlay: React.FC<OverlayProps> = (props) => {
...
     <div className={`${prefixCls}-inner-content`} onClick={onPopupClick}>
       <div className={`${prefixCls}-message`}>
         {icon && <span className={`${prefixCls}-message-icon`}>{icon}</span>}
-        <div
-          className={classNames(`${prefixCls}-message-title`, {
-            [`${prefixCls}-message-title-only`]: !!description,
-          })}
-        >
-          {getRenderPropValue(title)}
+        <div className={`${prefixCls}-message-text`}>
```
Comment (MadCcc) [inline components/popconfirm/PurePanel.tsx:69]: 好像没有这个 classname 相关的样式？

Comment (afc163) [reply components/popconfirm/PurePanel.tsx:69]: 确实没有，放个 div 也行。但是为了有点语义表达，还是放一个 className。
