### PR TITLE
fix: Transfer selectInvert should be corrected

### LINKED ISSUE #47108: Transfer 穿梭框反选当页功能异常
### Reproduction link

[https://ant-design.antgroup.com/components/transfer-cn#components-transfer-demo-table-transfer](https://ant-design.antgroup.com/components/transfer-cn#components-transfer-demo-table-transfer)

#### Transfer 包含表格分页场景

- 确保有一边的表格数据大于 10 条
- 选择左上角 `全选所有` 下拉按钮，则表格数据将全部勾选，符合预期
- 选择左上角 `反选当页` 下拉按钮，则表格数据将全部取消勾选，不符合预期

### What is expected?

选择左上角 `反选当页` 下拉按钮后，取消勾选的应该只有当前页面的数据取消勾选，而非全部数据取消勾选

### What is actually happening?

选择左上角 `反选当页` 下拉按钮后，全部数据取消勾选

| Environment | Info |
| --- | --- |
| antd | 5.13.1 |
| React | 18.0.0 |
| System | macos |
| Browser | chrome:120.0.6099.199 (x86_64) |

---
`4.x.x` 版本同样存在问题

### PR DESCRIPTION
**Pull request by linxianxi**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix https://github.com/ant-design/ant-design/issues/47108

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fixed Transfer inverting current page error        |
| 🇨🇳 Chinese |  修复 Transfer 反选当页错误的问题         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/transfer/list.tsx [hunk 1]
```diff
@@ -343,22 +343,19 @@ const TransferList = <RecordType extends KeyWiseTransferItem>(
         key: 'selectInvert',
         label: selectInvert,
         onClick() {
-          const availableKeys = getEnabledItemKeys(
-            pagination
-              ? (listBodyRef.current?.items || []).map((entity) => entity.item)
-              : filteredItems,
+          const availablePageItemKeys = getEnabledItemKeys(
```
Comment (zombieJ) [inline components/transfer/list.tsx:346]: `selectInvert` 不跟 pagination 判断，我感觉更像是文案错误的样子。

**Review by afc163 — APPROVED** [review]
