### PR TITLE
fix(Table): fix duplicated filter dropdowns and tooltips is shown when Table is sticky

### LINKED ISSUE #42511: Antd5 Table 组件在存在scroll 属性时，每次强制刷新页面时表头渲染会出现白屏的情况；以及空数据下表头宽度突变！
### Reproduction link

[https://github.com/xinbo97/AntdIssue/tree/master](https://github.com/xinbo97/AntdIssue/tree/master)

### Steps to reproduce

1、进入master分支启动项目后，当Table组件出现后，强制刷新页面；
2、会发现在有数据的情况下，表头的渲染会出现短暂的白屏；
3、会发现在空数据的情况下，表头单元格会出现宽度突变， 表身部分会出现一道横线并且转瞬即逝；
4、建议打开开发者工具中 performance 分栏进行录制查看此两个bug

### What is expected?

1、有数据条件下表头渲染不会出现白屏；
2、空数据条件下表头宽度不突变，并且表身不会出现横线

### What is actually happening?

1、有数据的情况下，表头的渲染会出现短暂的白屏；
2、空数据的情况下，表头单元格会出现宽度突变， 表身部分会出现一道横线并且转瞬即逝；

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | react18.x |
| System | macOS 12.6 (21G115) |
| Browser | chrome 107.0.5304.110（正式版本） (arm64) |

---
注意，这种情况只在强制刷新页面时会复现

### LINKED ISSUE #42544: antd5 Table组件当固定列存在筛选项时，强制刷新后固定列宽度异常
### Reproduction link

[https://github.com/xinbo97/AntdIssue/tree/master](https://github.com/xinbo97/AntdIssue/tree/master)

### Steps to reproduce

1、设置Table组件固定列，并在其中一个固定列上设置soter排序属性；
2、强制刷新页面；
3、发现设置有sorter属性的那个固定列宽度变窄，出现异常；
4、当鼠标移入Table里时，宽度又恢复正常；

### What is expected?

期望强制刷新后固定列宽度正常！

### What is actually happening?

强制刷新页面，发现设置有sorter属性的那个固定列宽度变窄，出现异常；

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | react18.x |
| System | macOS 12.6 (21G115) |
| Browser | chrome 107.0.5304.110（正式版本） (arm64) |

---
必须强制刷新页面以及固定列上有sorter排序项才会复现，建议结合performance进行录制；
git仓库里master分支下imgs文件夹有bug截图；

### LINKED ISSUE #54906: Duplicated filterDropdown and tooltip is shown when Table is sticky
Reproduce: https://codesandbox.io/p/sandbox/zi-ding-yi-shai-xuan-cai-dan-antd-5-27-3-forked-ygr8ft?file=%2Fdemo.tsx%3A51%2C16

Image

ref: https://github.com/ant-design/ant-design/issues/54889#issuecomment-3260099825

### PR DESCRIPTION
**Pull request by afc163**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

- close https://github.com/ant-design/ant-design/issues/54906

---

- close https://github.com/ant-design/ant-design/issues/42511
- close https://github.com/ant-design/ant-design/issues/42544

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

https://github.com/ant-design/ant-design/issues/54906 解决方法：

1. 给 rc-table 增加一个 `measureRowRender` 属性 https://github.com/react-component/table/pull/1347
2. 在 antd 这层用 `measureRowRender` 包裹 ConfigProvider，从而使 MeasureRow 里的各类弹层组件在视觉上不可见。
   ```jsx
   measureRowRender={(measureRow: React.ReactNode) => (
     <ConfigProvider getPopupContainer={(node) => node as HTMLElement}>
       {measureRow}
     </ConfigProvider>
   )}
   ```

| Before ❌ | After ✅ |
| --- | --- |
| 图片 <br /> 出现两次 | 图片 <br /> 只出现一次 |

---

另外还通过 https://github.com/react-component/table/pull/1345 修复了列头渲染空白的问题。

close https://github.com/ant-design/ant-design/issues/42511
close https://github.com/ant-design/ant-design/issues/42544

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)! Track your changes, like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Table duplicated filter dropdowns and tooltips display when using `sticky` or `scroll.y`. <br />Fix Table header not rendering at the initial stage.          |
| 🇨🇳 Chinese | 修复 Table 在使用 `sticky` 或 `scroll.y` 时出现重复的筛选下拉框和提示气泡显示的问题。<br /> 修复 Table 渲染初始阶段列头不显示的问题。 |

### CODE REVIEW

File: components/table/InternalTable.tsx [hunk 1]
```diff
@@ -618,6 +619,11 @@ const InternalTable = <RecordType extends AnyObject = AnyObject>(
           internalRefs={internalRefs}
           transformColumns={transformColumns as any}
           getContainerWidth={getContainerWidth}
+          measureRowRender={(measureRow: React.ReactNode) => (
```
Comment (li-jia-nan) [inline components/table/InternalTable.tsx:622]: 这是新属性吗？要放在 master 分支吗？

File: components/table/index.zh-CN.md [hunk 2]
```diff
@@ -112,6 +112,7 @@ const columns = [
 <code src="./demo/dynamic-settings.tsx">动态控制表格属性</code>
 <code src="./demo/selections-debug.tsx" debug>带下拉箭头的表头</code>
 <code src="./demo/component-token.tsx" debug>组件 Token</code>
+<code src="./demo/measure-row-render.tsx" debug>measureRowRender</code>
```
Comment (li-jia-nan) [inline components/table/index.zh-CN.md:115]: 这里应该是中文

File: components/table/InternalTable.tsx (hunk 1 above)
Comment (afc163) [reply components/table/InternalTable.tsx:622]: 这个属性不透给 antd 用户。

File: components/table/index.zh-CN.md (hunk 2 above)
Comment (afc163) [reply components/table/index.zh-CN.md:115]: debug 没关系

**Review by crazyair — APPROVED** [review]

**Review by li-jia-nan — APPROVED** [review]

File: components/table/InternalTable.tsx (hunk 1 above)
Comment (crazyair) [reply components/table/InternalTable.tsx:622]: React.ReactNode 类型不用加
