### PR TITLE
fix(Breadcrumb): custom itemRender style for 6.x

### LINKED ISSUE #56248: 5.29.2 Breadcrumb 链接颜色显示错误
### Reproduction link

无

### Steps to reproduce

v5.29.1

Image

---

v5.29.2

Image

### What is expected?

和5.29.1显示一致

### What is actually happening?

使用的是`pro-layout`，面包屑链接颜色变化

| Environment | Info |
| --- | --- |
| antd | 5.29.2 |
| React | 18.3.1 |
| System | MacOS |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by guoyunhe**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

Fix #56248 

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)! Track your changes, like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix(Breadcrumb): custom itemRender style |
| 🇨🇳 Chinese | fix(Breadcrumb): 自定义 itemRender 样式 |

### CODE REVIEW

File: components/breadcrumb/BreadcrumbItem.tsx [hunk 1]
```diff
@@ -86,7 +87,10 @@ export const InternalBreadcrumbItem: React.FC<BreadcrumbItemProps> = (props) =>
   if (isNonNullable(link)) {
     return (
       <>
-        <li className={mergedClassNames?.item} style={mergedStyles?.item}>
+        <li
+          className={clsx(`${prefixCls}-item`, mergedClassNames?.item)}
+          style={mergedStyles?.item}
+        >
```
Comment (afc163) [inline components/breadcrumb/BreadcrumbItem.tsx:93]: > @afc163 应该是因为自定义 itemRender 缺了 ${componentCls}-link 这个类，我修复一下

我看你的修复方式不是补 link 这个类，而是新增了 item 这个类，对么？

Comment (guoyunhe) [reply components/breadcrumb/BreadcrumbItem.tsx:93]: 是的，因为 -link 类在自定义 itemRender 的情况下几乎肯定会丢，不可靠。而上一级 li 上的 -item 类是不变的。

**Review by afc163 — APPROVED** [review]
