### PR TITLE
fix: suffix of InputNumber moves left after the mouse enters when it is disabled

### LINKED ISSUE #53181: InputNumber suffix   disabled，鼠标移入 suffix 会往前移动
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/bu-ke-yong-antd-5-24-3-forked-qhqt9p?file=%2Fdemo.tsx%3A10%2C1)

### Steps to reproduce

鼠标移入

### What is expected?

不移动

### What is actually happening?

移动

| Environment | Info |
| --- | --- |
| antd | 5.24.3 |
| React | latest |
| System | mac |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by yellowryan**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

fixed [#53181](https://github.com/ant-design/ant-design/issues/53181)

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     🐞Fixed the issue that the suffix of InputNumber moves left after the mouse enters when it is disabled      |
| 🇨🇳 Chinese |    🐞修复 InputNumber在禁用状态下鼠标划入后suffix出现左移的问题       |

## Summary by CodeRabbit

- **测试**
  - 新增测试用例验证禁用状态下不显示控制按钮，确保组件行为符合预期。
- **新功能**
  - 优化了在禁用或不显示控制按钮时的视觉反馈，提升用户界面的直观性和一致性。
- **样式**
  - 改进了样式导入格式，提高可读性。

### CODE REVIEW

File: components/input-number/style/index.ts [hunk 1]
```diff
@@ -476,6 +483,10 @@ const genAffixWrapperStyles: GenerateStyle<InputNumberToken> = (token: InputNumb
       [`&:not(${componentCls}-affix-wrapper-without-controls):hover ${componentCls}-suffix`]: {
```
Comment (coding-ice) [inline components/input-number/style/index.ts:483]: ``

**Review by coding-ice — CHANGES_REQUESTED** [review]

**Comment by coding-ice** [comment]
加一个 :not 的类，会不会更好一些

**Comment by yellowryan** [comment]
> 加一个 :not 的类，会不会更好一些

嗯， 这样也不错 我改了

File: components/input-number/__tests__/suffix.test.tsx [hunk 2]
```diff
@@ -24,4 +24,13 @@ describe('suffix', () => {
       container.querySelector('.ant-input-number-affix-wrapper-without-controls'),
     ).toBeTruthy();
   });
+
+  it('should not show the control buttons when inputNumber is disabled', () => {
+    const { container } = render(<InputNumber suffix="RMB" style={{ width: '100%' }} disabled />);
+    const suffix = container.querySelector('.ant-input-number-suffix')!;
+    const prevMarginInlineEnd = window.getComputedStyle(suffix).marginInlineEnd;
+    fireEvent.mouseEnter(container.querySelector('.ant-input-number-affix-wrapper')!);
+    const currentMarginInlineEnd = window.getComputedStyle(suffix).marginInlineEnd;
```
Comment (afc163) [inline components/input-number/__tests__/suffix.test.tsx:33]: 看看这个算出来是多少？jsdom 里都是 0 吧？

File: components/input-number/style/index.ts [hunk 3]
```diff
@@ -337,6 +342,8 @@ const genInputNumberStyles: GenerateStyle<InputNumberToken> = (token: InputNumbe
         '&-disabled, &-readonly': {
           [`${componentCls}-handler-wrap`]: {
             display: 'none',
+            width: 0,
+            overflow: 'hidden',
```
Comment (coding-ice) [inline components/input-number/style/index.ts:346]: 这两行有啥特殊的意义吗，感觉是可以不用了

File: components/input-number/__tests__/suffix.test.tsx (hunk 2 above)
Comment (yellowryan) [reply components/input-number/__tests__/suffix.test.tsx:33]: 屏幕截图 2025-03-18 142158

Comment (yellowryan) [reply components/input-number/__tests__/suffix.test.tsx:33]: 这样是符合预期的吧

File: components/input-number/__tests__/suffix.test.tsx [hunk 4]
```diff
@@ -24,4 +24,13 @@ describe('suffix', () => {
...
+    expect(currentMarginInlineEnd).toEqual(prevMarginInlineEnd);
```
Comment (thinkasany) [inline components/input-number/__tests__/suffix.test.tsx:34]:
```suggestion
    expect(
      getComputedStyle(container.querySelector('.ant-input-number-suffix')!).marginInlineEnd,
    ).toEqual('11px');
    fireEvent.mouseEnter(container.querySelector('.ant-input-number-affix-wrapper')!);
    expect(
      getComputedStyle(container.querySelector('.ant-input-number-suffix')!).marginInlineEnd,
    ).toEqual('11px');
```

Comment (thinkasany) [reply components/input-number/__tests__/suffix.test.tsx:34]: before： 去掉 disabled
8d1dba6c2a6698f0294768444d9b8501

after:  加上 disabled
97716855ef4ddb1fbfe96e96b65a2a24

File: components/input-number/__tests__/suffix.test.tsx [hunk 5]
```diff
@@ -24,4 +24,13 @@ describe('suffix', () => {
...
+  });
```
Comment (afc163) [inline components/input-number/__tests__/suffix.test.tsx:35]: 图片

这个用例我直接在 master 上跑也能过，看上去不能起到测试验证的作用。

File: components/input-number/style/index.ts [hunk 6]
```diff
@@ -473,9 +478,10 @@ const genAffixWrapperStyles: GenerateStyle<InputNumberToken> = (token: InputNumb
         width: token.handleWidth,
         opacity: 1,
       },
-      [`&:not(${componentCls}-affix-wrapper-without-controls):hover ${componentCls}-suffix`]: {
-        marginInlineEnd: token.calc(token.handleWidth).add(paddingInline).equal(),
-      },
+      [`&:not(${componentCls}-affix-wrapper-without-controls):not(${componentCls}-affix-wrapper-disabled):hover ${componentCls}-suffix`]:
```
Comment (coding-ice) [inline components/input-number/style/index.ts:481]: 这里可以去掉了

**Comment by yellowryan** [comment]
怎么有lint错误了 0.o

**Comment by thinkasany** [comment]
> 怎么有lint错误了 0.o

fix by https://github.com/ant-design/ant-design/pull/53266

原因： ci 默认会升级依赖，以保证及时发现问题，没有锁包。
image

**Review by coding-ice — APPROVED** [review]

**Review by thinkasany — APPROVED** [review]

**Review by MadCcc — APPROVED** [review]
