### PR TITLE
fix: ConfigProvider rerender unexpectedly when switching some language

### LINKED ISSUE #31592: 使用了 ConfigProvider 组件，在越南语和中文之间切换语言，所有组件会被销毁重新创建，导致组件状态不能被保持
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-oh5by?file=/index.js)

### Steps to reproduce
1、点击上面 codesandbox 例子中切换语言的按钮，
2、查看 console 日志，子组件不断销毁重新渲染。

### What is expected?
正常应该不会销毁子组件，能保持组件的状态，不触发组件重新创建渲染。

### What is actually happening?
销毁了子组件，使得组件重新创建，所有组件状态重置了。

| Environment | Info |
|---|---|
| antd | 4.16.0 |
| React | 17.0.1 |
| System | macOS Catalina v10.15.7 |
| Browser | chrome 91.0.4472.164 |

---
目前发现，在中英文之间切换是正常的，但是在越南语、泰语和中文之间切换就会出现这样的问题。

### PR DESCRIPTION
**Pull request by Map1en**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
close #31592

### 💡 Background and solution
修复了ConfigProvide在切换某些语言时下级组件状态不能被保持的问题

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix ConfigProvide could not maintain the state of components when switching some lang      |
| 🇨🇳 Chinese |     修复了ConfigProvide在切换某些语言时下级组件状态不能被保持的问题      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
来个测试用例？

File: components/config-provider/index.tsx [hunk 1]
```diff
@@ -187,16 +188,21 @@ const ProviderChildren: React.FC<ProviderChildrenProps> = props => {
...
   let validateMessages: ValidateMessages = {};
 
-  if (locale && locale.Form && locale.Form.defaultValidateMessages) {
-    validateMessages = locale.Form.defaultValidateMessages;
+  if (locale) {
+    if (locale.Form && locale.Form.defaultValidateMessages) {
+      validateMessages = locale.Form.defaultValidateMessages;
+    } else {
+      validateMessages = defaultLocale.Form!.defaultValidateMessages;
+    }
```
Comment (afc163) [inline components/config-provider/index.tsx:205]:
```suggestion
    validateMessages = locale.Form?.defaultValidateMessages || defaultLocale.Form?.defaultValidateMessages;
```
