### PR TITLE
fix: Dropdown submenu wrong position

### LINKED ISSUE #40320: Dropdown submenu popup does not align
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/dropdown-submenu-antd-5-1-5-forked-tovhxt?file=/demo.tsx)

### Steps to reproduce

hover over Dropdown's submenu 

### What is expected?

For Dropdown submenu popup to align with submenu item, just like Menu submenu popup

### What is actually happening?

Dropdown's submenu popup has extra margin and is too far from the Dropdown

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 18 |
| System | windows |
| Browser | Firefox, Chrome |

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/40320

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix Dropdown submenu wrong position.         |
| 🇨🇳 Chinese |  修复 Dropdown 子菜单位置不正确的问题。  |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/dropdown/style/index.ts [hunk 1]
```diff
@@ -323,6 +319,7 @@ const genBaseStyle: GenerateStyle<DropdownToken> = (token) => {
             lineHeight: token.lineHeight,
             cursor: 'pointer',
             transition: `all ${motionDurationMid}`,
+            borderRadius: token.borderRadiusSM,
```
Comment (afc163) [inline components/dropdown/style/index.ts:322]: 顺手修了个 hover 的圆角问题。

File: components/dropdown/style/index.ts [hunk 2]
```diff
@@ -253,12 +253,9 @@ const genBaseStyle: GenerateStyle<DropdownToken> = (token) => {
...
         transformOrigin: '0 0',
 
-        'ul,li': {
+        'ul, li': {
           listStyle: 'none',
-        },
-
-        ul: {
-          marginInline: '0.3em',
+          margin: 0,
```
Comment (afc163) [inline components/dropdown/style/index.ts:258]: ul 边框没重置掉。

**Review by li-jia-nan — APPROVED** [review]
