### PR TITLE
fix: Upload with maxCount not trigger onChange

### LINKED ISSUE #43190: antd@5.6.2 以后 Upload 组件在配置 maxCount 后，点击删除不触发 onChange 回调
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/xian-zhi-shu-liang-antd-5-6-3-forked-748wqr?file=/demo.tsx)

### Steps to reproduce

1. 点击上传文件，比如上传两个
2. 上传完成后，点击删除，UI 删除了，但是没触发 onChange 的 console
3. 移除 maxCount 配置，重复 1、2 步骤，将正常触发 onChange 回调

### What is expected?

Upload 组件在配置 maxCount 后，点击删除正常触发 onChange 回调

### What is actually happening?

不触发

| Environment | Info |
| --- | --- |
| antd | 5.6.2 |
| React | ^18.0.0 |
| System | macos 13.4.1 |
| Browser | 5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 |

### Extra Info
https://github.com/ant-design/ant-design/assets/11768879/1987ca0d-92a1-41d5-bd39-40dc1784f42e

### Debug Info
初步确认与 PR #43034  的改动有关，其中 [components/upload/Upload.tsx 138 行](https://github.com/BoyYangzai/ant-design/commit/53c3bc9d9e5124ce1813b764c478acc02c03d3b6#diff-a2e7152a9f97730a600f9bda0bf15029cce0148818a6ee8d2a037fafc101427dR138) cloneList 是已经删除后的文件数组，所以肯定找不到当前删除的数组，继而不触发 onChange 回调。
> trace 后发现 `handleRemove` 方法中 mergedFileList 是删除前的数组。

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #43190

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      Fix Upload with `maxCount` will skip `onChange` when remove file.     |
| 🇨🇳 Chinese |     修复 Upload 配置 `maxCount` 后删除文件不会触发 `onChange` 的问题。    |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at d80fe27</samp>

This pull request fixes a bug in the `Upload` component that prevented the `onChange` event from firing when the file list reached the `maxCount` limit. It also adds a test case for the bug and a link to the issue in the deprecated version warning.

### <samp>🤖 Generated by Copilot at d80fe27</samp>

* Fix bug in Upload component that prevented `onChange` event from firing when file list exceeded `maxCount` prop ([link](https://github.com/ant-design/ant-design/pull/43193/files?diff=unified&w=0#diff-a2e7152a9f97730a600f9bda0bf15029cce0148818a6ee8d2a037fafc101427dL116-R116))
* Add test case to verify bug fix and ensure correct behavior of Upload component with `maxCount` prop ([link](https://github.com/ant-design/ant-design/pull/43193/files?diff=unified&w=0#diff-72ea20f11250bb41ad13135c67af7e612d56bd43c8e24ad4db9c782f58306ac7R780-R816))
* Add link to issue #28394 to `DEPRECIATED_VERSION` object in `scripts/post-script.js` to inform users of deprecated versions about the bug and the fix ([link](https://github.com/ant-design/ant-design/pull/43193/files?diff=unified&w=0#diff-0c429b9a01f20777bce85b2ad2472fe50f00b4ef8a404d56852f3d4dd15e905dR41))

### CODE REVIEW

**Review by MadCcc — APPROVED** [review]

File: scripts/post-script.js [hunk 1]
```diff
@@ -38,6 +38,7 @@ const DEPRECIATED_VERSION = {
     'https://github.com/ant-design/ant-design/pull/41993',
   ],
   '5.6.2': ['https://github.com/ant-design/ant-design/issues/43113'],
+  '5.6.3': ['https://github.com/ant-design/ant-design/issues/43190'],
```
Comment (kiner-tang) [inline scripts/post-script.js:41]: 这个有什么用呀？

**Review by kiner-tang — APPROVED** [review]

File: scripts/post-script.js (hunk 1 above)
Comment (zombieJ) [reply scripts/post-script.js:41]: 打 tag 的时候 `conch` version 会跳过
