### PR TITLE
fix: RangePicker allowClear does not disable the clear button

### LINKED ISSUE #44012: RangePicker allowClear does not disable the clear button
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-fvmwk6?file=/index.js)

### Steps to reproduce

Set `allowClear` to `false` in a `DatePicker` or `RangePicker`.

### What is expected?

The "clear" button ("ant-picker-clear" containing "close-circle") should not be present and the picker should reject empty values.

### What is actually happening?

The "clear" button is still present and allows the user to clear the picker.

| Environment | Info |
| --- | --- |
| antd | 5.8.1 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Chrome 115.0.5790.111 |

### PR DESCRIPTION
**Pull request by bartpio**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

Fix #44012

### 💡 Background and solution

A regression was introduced in 24697bbb06a6be10dd150ac7f50bca01f88bb0b0 that results in `generatePicker` and `generateRangePicker` building the final `allowClear` prop solely from the `clearIcon` prop, without respecting `allowClear===false`. This makes it impossible for the library user to make a date picker non-clearable.

The proposed solution uses `allowClear`, as provided to the date picker, when it is `false` or an object bearing `clearIcon`. Otherwise, the final `allowClear` prop is built from the `clearIcon` prop.

~~The proposed solution skips building an icon-bearing `allowClear` prop, when the `allowClear` prop on the date picker is set to `false`, and the `clearIcon` prop on the date picker is undefined.~~

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Disable DatePicker and RangePicker clear button when allowClear prop is false |
| 🇨🇳 Chinese | 当allowClear属性为false时禁用DatePicker和RangePicker清除按钮 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 025ada1</samp>

The pull request adds a new feature to the `DatePicker` and `RangePicker` components that allows users to customize the clear icon. The pull request also improves the testing of these components by using new modules, components, and utilities. The pull request modifies the files `components/date-picker/generatePicker/generateRangePicker.tsx`, `components/date-picker/generatePicker/generateSinglePicker.tsx`, `components/date-picker/util.ts`, `components/date-picker/__tests__/DatePicker.test.tsx`, `components/date-picker/__tests__/RangePicker.test.tsx`, and `components/date-picker/__tests__/utils.ts`.

### <samp>🤖 Generated by Copilot at 025ada1</samp>

*  Add the `allowClear` prop to the `DatePicker` and `RangePicker` components, which can be a boolean or an object that specifies the `clearIcon` ([link](https://github.com/ant-design/ant-design/pull/44015/files?diff=unified&w=0#diff-fba17c237c150271f91ee2ca848654484ecbbbcc71b010a8947620e945e10e34R58), [link](https://github.com/ant-design/ant-design/pull/44015/files?diff=unified&w=0#diff-fba17c237c150271f91ee2ca848654484ecbbbcc71b010a8947620e945e10e34L144-R150), [link](https://github.com/ant-design/ant-design/pull/44015/files?diff=unified&w=0#diff-678a0178404ab41221775c01d203e79ccb84496e2f0b7cf4ef38222d7a7b562bR63), [link](https://github.com/ant-design/ant-design/pull/44015/files?diff=unified&w=0#diff-678a0178404ab41221775c01d203e79ccb84496e2f0b7cf4ef38222d7a7b562bL180-R186), [link](https://github.com/ant-design/ant-design/pull/44015/files?diff=unified&w=0#diff-64d79cd59dfc100bce2821bc07efac6651fb728fd8473b730597a06dd0815dceR163-R178))
* Import the `mergeAllowClear` function from the `util.ts` module in the `generateSinglePicker.tsx` and `generateRangePicker.tsx` modules, which handles the logic of the `allowClear` prop ([link](https://github.com/ant-design/ant-design/pull/44015/files?diff=unified&w=0#diff-fba17c237c150271f91ee2ca848654484ecbbbcc71b010a8947620e945e10e34L21-R26), [link](https://github.com/ant-design/ant-design/pull/44015/files?diff=unified&w=0#diff-678a0178404ab41221775c01d203e79ccb84496e2f0b7cf4ef38222d7a7b562bL22-R27), [link](https://github.com/ant-design/ant-design/pull/44015/files?diff=unified&w=0#diff-64d79cd59dfc100bce2821bc07efac6651fb728fd8473b730597a06dd0815dceL6-R6))
* Add test cases for the `allowClear` prop in the `DatePicker.test.tsx` and `RangePicker.test.tsx` modules, which verify the existence and appearance of the clear icon ([link](https://github.com/ant-design/ant-design/pull/44015/files?diff=unified&w=0#diff-7fdce5d71fac3793bf16cbc035559eeb8d5565c0db96d0b9399b5265a8c471b4R318-R344), [link](https://github.com/ant-design/ant-design/pull/44015/files?diff=unified&w=0#diff-61e007e24e1181d91ff9aeec9b59be8e62bfdc29445d1f3e41fb8e6a1923d7d6R131-R164))
* Import new modules and components for testing, such as `userEvent`, `screen`, `waitFor`, and `CloseCircleFilled` in the `DatePicker.test.tsx` and `RangePicker.test.tsx` modules, and use them in the new test cases ([link](https://github.com/ant-design/ant-design/pull/44015/files?diff=unified&w=0#diff-7fdce5d71fac3793bf16cbc035559eeb8d5565c0db96d0b9399b5265a8c471b4L8-R15), [link](https://github.com/ant-design/ant-design/pull/44015/files?diff=unified&w=0#diff-61e007e24e1181d91ff9aeec9b59be8e62bfdc29445d1f3e41fb8e6a1923d7d6L5-R13), [link](https://github.com/ant-design/ant-design/pull/44015/files?diff=unified&w=0#diff-f436452bf954f2673ea2939da48fdd846304fddaaaa376bf73cbfed410ebd47cL2-R2))
* Add utility functions for querying and asserting the clear icon element in the `utils.ts` module, and use them in the new test cases ([link](https://github.com/ant-design/ant-design/pull/44015/files?diff=unified&w=0#diff-f436452bf954f2673ea2939da48fdd846304fddaaaa376bf73cbfed410ebd47cR28-R35))

### CODE REVIEW

File: components/date-picker/util.ts [hunk 1]
```diff
@@ -160,3 +160,14 @@ export function getTimeProps<DateType, DisabledTime>(
     showTime: showTimeObj,
   };
 }
+
+export type MergeAllowClearProps = Pick<PickerProps<unknown>, 'clearIcon' | 'allowClear'>;
+
+export function mergeAllowClear(
+  { clearIcon, allowClear }: MergeAllowClearProps,
```
Comment (kiner-tang) [inline components/date-picker/util.ts:167]: It is recommended that you do not pass parameters as objects, as this is not conducive to code compression.

Comment (bartpio) [reply components/date-picker/util.ts]: Addressed (if my understanding was correct).

**Comment by bartpio** [comment]
@kiner-tang thanks for reviewing! I rebased to latest master, and it looks like the preview deploy had some kind of [transient failure](https://github.com/ant-design/ant-design/actions/runs/5758832887/job/15611937480)

File: components/date-picker/util.ts [hunk 2]
```diff
@@ -160,3 +160,19 @@ export function getTimeProps<DateType, DisabledTime>(
...
+  allowClear: AllowClear,
+  clearIcon: ClearIcon,
+  defaultClearIcon: NonNullable<ClearIcon>,
+) {
+  if (allowClear === false) {
+    return false;
+  }
+
+  const defaults = { clearIcon: clearIcon ?? defaultClearIcon };
+  return typeof allowClear === 'object' && allowClear ? { ...defaults, ...allowClear } : defaults;
```
Comment (kiner-tang) [inline components/date-picker/util.ts:177]:
```suggestion
  return typeof allowClear === 'object'  ? { ...defaults, ...allowClear } : defaults;
```
If `typeof allowClear === 'object'` holds, does that mean that allowClear must be truthy? Because our allowClear is non-null.

Comment (bartpio) [reply components/date-picker/util.ts]: That's right. Fixed.

I verified that this scenario is rejected by typescript:

```tsx
<DatePicker value={somepoint} allowClear={null} />
```

**Comment by bartpio** [comment]
@kiner-tang We are getting a [screenshot discrepancy](https://app.argos-ci.com/ant-design/ant-design/builds/10501/54185668) now. It looks like the newer screenshot is of a larger viewport. Any suggestion on how to address?

**Comment by kiner-tang** [comment]
> @kiner-tang We are getting a [screenshot discrepancy](https://app.argos-ci.com/ant-design/ant-design/builds/10501/54185668) now. It looks like the newer screenshot is of a larger viewport. Any suggestion on how to address?

It doesn't matter! That maybe a bug of argos!

**Review by kiner-tang — APPROVED** [review]
