### PR TITLE
fix: event should be optional

### LINKED ISSUE #51418: (#51074)重构UploadList导致的组件内部报错 of undefined (reading 'preventDefault')  at onInternalPreview
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/holy-hooks-3wwl63)

### Steps to reproduce

> [refactor: refactor components/upload/UploadList/index.tsx (#51074)](https://github.com/ant-design/ant-design/pull/51074)

这次提交的重构内容，由于去掉了onInternalPreview方法的第二个参数的?:可选参数，以及e?.preventDefault();的可选调用。
影响了按照之前版本使用itemRender调用preview方法。导致了组件内部这个错误。

注：这个问题会导致很多，自定itemRender调用preview无法使用的情况。

image

### What is expected?

能够调用预览方法
```javascript
  const onInternalPreview = (file: UploadFile, e: React.SyntheticEvent<HTMLElement>) => {
    if (!onPreview) {
      return;
    }
    e.preventDefault();  // TODO  error
    return onPreview(file);
  };
```

### What is actually happening?

```javascript
Uncaught TypeError: Cannot read properties of undefined (reading 'preventDefault')
    at onInternalPreview (/node_modules/antd/es/upload/UploadList/index.js:65:7)
    at onClick (/index.tsx:92:31)
```

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18 |
| System | win mac |
| Browser | ^ |

---
运维内网npm包依赖更新，内部二次封装antd组件。
开发人员使用二次封装，更新后的antd导致的问题。

### PR DESCRIPTION
**Pull request by yoyo837**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

fix https://github.com/ant-design/ant-design/issues/51418

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix Upload `itemRender` with `action.preview` crash.     |
| 🇨🇳 Chinese |     修复 Upload `itemRender` 调用 `action.preview` 会导致崩溃的问题。    |

### CODE REVIEW

File: components/upload/interface.ts [hunk 1]
```diff
@@ -77,7 +77,7 @@ export type ItemRender<T = any> = (
   fileList: Array<UploadFile<T>>,
   actions: {
     download: () => void;
-    preview: () => void;
+    preview: (e?: React.SyntheticEvent<HTMLElement>) => void;
```
Comment (zombieJ) [inline components/upload/interface.ts:80]: 这个不用，用户本来就没有这个 event 的契机的

Comment (yoyo837) [reply components/upload/interface.ts]: 撤回了

**Review by zombieJ — APPROVED** [review]
