### PR TITLE
fix: Dropdown should not display when items is empty array

### LINKED ISSUE #47373: Dropdown style problem with emtpy items
### Reproduction link

[https://codepen.io/afc163/pen/MWxXxxz?editors=0010](https://codepen.io/afc163/pen/MWxXxxz?editors=0010)

### Steps to reproduce

```
  <Dropdown
    menu={{
      items: [],
    }}
  >
```

### What is expected?

There is no dropdown node.

### What is actually happening?

A small dropdown node without content.

图片

| Environment | Info |
| --- | --- |
| antd | 5.14.0 |
| React | All |
| System | All |
| Browser | All |

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 💡 Background and solution

close https://github.com/ant-design/ant-design/issues/47373

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix Dropdown should not display when items is empty array        |
| 🇨🇳 Chinese |   修复 Dropdown `menu.items` 为空时依然显示的问题。        |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by li-jia-nan — DISMISSED** [review]

**Comment by MadCcc** [comment]
还是会有阴影
image

File: components/dropdown/style/index.ts [hunk 1]
```diff
@@ -194,6 +194,10 @@ const genBaseStyle: GenerateStyle<DropdownToken> = (token) => {
           boxShadow: token.boxShadowSecondary,
           ...genFocusStyle(token),
 
+          '&:empty': {
+            padding: 0,
```
Comment (afc163) [inline components/dropdown/style/index.ts:198]:
```suggestion
            padding: 0,
            boxShadow: 'none',
```

**Comment by zombieJ** [comment]
印象里，windows 的菜单空的时候右击还会显示。但是有个 `[空]`，来表示交互是有效的。（图找了一圈没找到。。。）

**Review by li-jia-nan — APPROVED** [review]
