### PR TITLE
fix: InputNumber should support `className`

### LINKED ISSUE #591: `InputNumber` 实现缺陷
https://github.com/ant-design/ant-design/blob/master/components/input-number/index.jsx#L18

如果用户设置了 `className` 就会把 `InputNumber` 的 `sizeClass` 覆盖了。

### PR DESCRIPTION
**Pull request by benjycui**
Close: https://github.com/ant-design/ant-design/issues/591

### CODE REVIEW

File: components/input-number/index.jsx [hunk 1]
```diff
@@ -1,5 +1,6 @@
-import InputNumber from 'rc-input-number';
 import React from 'react';
+import classNames from 'classNames';
```
Comment (afc163) [inline components/input-number/index.jsx]: 是 `classnames` 吧？

Comment (benjycui) [inline components/input-number/index.jsx]: 更新了，怎么本地跑没错。。。
