### PR TITLE
fix: Safari Badge scroll number missing

### LINKED ISSUE #50506: Badge animation in safari
### Reproduction link

[https://ant.design/~demos/badge-demo-change](https://ant.design/~demos/badge-demo-change)

### Steps to reproduce

- open example in Safari browser
- press increase counter

### What is expected?

When I increase the counter, the number appears smoothly.

### What is actually happening?

When I increase the counter, the number disappears and suddenly appears. Аnimation is different from decreasing counter.

| Environment | Info |
| --- | --- |
| antd | 5.20.2 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Safari |

---
Number change animation looks different in Safari browser. When I increase the counter, the number disappears, but in other browsers it moves

https://github.com/user-attachments/assets/87522321-d34f-4ce4-b35b-dfda1b21dc4e

https://github.com/user-attachments/assets/ff72e297-ac86-4894-a969-7cd4a0ab4a3b

### PR DESCRIPTION
**Pull request by zombieJ**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

- fix #50506

### 💡 Background and Solution

SB Safari，试了各种方法都不行。测试下来如果 transform dom 下含有太多 `position: absolute` 子元素会导致元素直接不渲染。用切割把滚动项按照方向进行切割（原本一个 offset 就行，现在要根据方向做不同的 offset）。

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix Badge `count` motion missing in Safari.       |
| 🇨🇳 Chinese |     修复 Badge `count` 在 Safari 下动画丢失的问题。      |

### CODE REVIEW

**Review by li-jia-nan — DISMISSED** [review]

File: components/badge/SingleNumber.tsx [hunk 1]
```diff
@@ -79,23 +79,29 @@ const SingleNumber: React.FC<Readonly<SingleNumberProps>> = (props) => {
...
     }
 
+    const unit = prevCount < count ? 1 : -1;
+
     // Fill with number unit nodes
     const prevIndex = unitNumberList.findIndex((n) => n % 10 === prevValue);
-    unitNodes = unitNumberList.map((n, index) => {
+
+    // Cut list
+    const cutUnitNumberList =
```
Comment (li-jia-nan) [inline components/badge/SingleNumber.tsx:88]: 需要把 issue 链接贴在这里么大佬？

Comment (zombieJ) [reply components/badge/SingleNumber.tsx:88]: 不用了，PR comment 上写了。

**Review by li-jia-nan — APPROVED** [review]
