### PR TITLE
 demo: simplify transfer table example 

### LINKED ISSUE #39403: Transfer "Invert current page" wrongly inverted all items
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/mcuz99)

### Steps to reproduce

Click "select all" in the title dropdown, and then click "invert current page"

### What is expected?

should just invert current page items

### What is actually happening?

wrongly inverted all items

| Environment | Info |
| --- | --- |
| antd | 5.0.4 |
| React | react |
| System | mac |
| Browser | chrome |

### LINKED ISSUE #48241: TableTransfer 反选当前页无效
### Reproduction link

[Edit on StackBlitz](https://stackblitz.com/run?file=demo.tsx)

### Steps to reproduce

// 请看ant官方提供的transferTable案例
// https://ant.design/components/transfer-cn#transfer-demo-table-transfer

### What is expected?

修复bug

### What is actually happening?

功能未按预期执行

| Environment | Info |
| --- | --- |
| antd | 5.16.0 |
| React | 18.2 |
| System | macOS:14.3.1 |
| Browser | chorm:122.0.6261.94 |

### PR DESCRIPTION
**Pull request by afc163**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix https://github.com/ant-design/ant-design/issues/48241
fix https://github.com/ant-design/ant-design/issues/39403
close https://github.com/ant-design/ant-design/pull/48248/

### 💡 Background and solution

https://github.com/ant-design/ant-design/pull/48248/ is trying to fix table transfer invert select function, but it make transfer's inplementation involved with Table's code.

This PR demonstrate a simpler demo of table transfer and use Table selection ability instead Transfer's.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Improve Transfer demo code of using Table.        |
| 🇨🇳 Chinese |  优化 Transfer 内使用 Table 的演示案例代码。         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/transfer/demo/table-transfer.tsx [hunk 1]
```diff
@@ -34,28 +31,20 @@ const TableTransfer = ({ leftColumns, rightColumns, ...restProps }: TableTransfe
...
-            ? difference(treeSelectedKeys, listSelectedKeys)
-            : difference(listSelectedKeys, treeSelectedKeys);
-          onItemSelectAll(diffKeys as string[], selected);
-        },
-        onSelect({ key }, selected) {
-          onItemSelect(key as string, selected);
+        getCheckboxProps: () => ({ disabled: listDisabled }),
+        onChange(selectedRowKeys) {
+          onItemSelectAll(selectedRowKeys, 'replace');
         },
```
Comment (afc163) [inline components/transfer/demo/table-transfer.tsx:45]: 一行代码完成了状态同步。

File: components/transfer/demo/table-transfer.tsx [hunk 2]
```diff
@@ -85,80 +74,62 @@ const mockData: RecordType[] = Array.from({ length: 20 }).map((_, i) => ({
...
-
   return (
     <>
       <TableTransfer
         dataSource={mockData}
         targetKeys={targetKeys}
         disabled={disabled}
-        showSearch={showSearch}
+        showSearch
+        showSelectAll={false}
```
Comment (afc163) [inline components/transfer/demo/table-transfer.tsx:119]: 关掉 Transfer 自带的选择能力，直接用 Table 的，实现更简单，能力更完整。

File: components/transfer/demo/table-transfer.tsx (hunk 1 above)
Comment (xiaozisong) [reply components/transfer/demo/table-transfer.tsx:45]: 还是菜 还得学  当时陷入了逻辑怪圈  学到了163老师

**Review by zombieJ — APPROVED** [review]
