### PR TITLE
fix(Splitter): try recover history size when collapsed

### LINKED ISSUE #51152: Splitter在折叠后恢复时"flexBasis"的值不应该是"min"值或历史值吗
### Reproduction link

[Edit on StackBlitz](https://stackblitz.com/edit/react-hserml?file=demo.tsx)

https://github.com/user-attachments/assets/9b28664b-ab95-4a45-bb25-8d7d257ab0cd

### Steps to reproduce

当点击折叠时，实际为0，但stackblitz上为最小值，但点击展开时，实际为容器最小值，期望应该是设定最小值或上一个状态值

### What is expected?

设置collapsible时，折叠恢复应该为上一个状态值

### What is actually happening?

实际为容器最小值

| Environment | Info |
| --- | --- |
| antd | 5.21.0 |
| React | 18.3.1 |
| System | mac os 15.0 |
| Browser | Chrome 129.0.6668.90 |

### PR DESCRIPTION
**Pull request by jjlstruggle**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 展开时尝试恢复为历史值

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [x] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

fix: #51152 
close #51371

### 💡 Background and Solution

展开时尝试恢复为历史值

### 📝 Change Log

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     try recover history size when collapsed      |
| 🇨🇳 Chinese |   展开时尝试恢复为历史值        |

### CODE REVIEW

File: components/splitter/hooks/useResize.ts [hunk 1]
```diff
@@ -140,9 +142,26 @@ export default function useResize(
...
+          currentCacheCollapsedSize >= currentSizeMin;
+      }
+
+      if (shouldUseCache) {
+        currentSizes[targetIndex] = targetCacheCollapsedSize;
+        currentSizes[currentIndex] = currentCacheCollapsedSize;
+      } else {
+        currentSizes[currentIndex] -= halfOffset;
+        currentSizes[targetIndex] += halfOffset;
+      }
```
Comment (afc163) [inline components/splitter/hooks/useResize.ts:164]:
```suggestion
    const shouldUseCache = 
      targetCacheCollapsedSize &&
      targetCacheCollapsedSize <= targetSizeMax &&
      targetCacheCollapsedSize >= targetSizeMin &&
      currentCacheCollapsedSize <= currentSizeMax &&
      currentCacheCollapsedSize >= currentSizeMin;

    if (shouldUseCache) {
      currentSizes[targetIndex] = targetCacheCollapsedSize;
      currentSizes[currentIndex] = currentCacheCollapsedSize;
    } else {
      currentSizes[currentIndex] -= halfOffset;
      currentSizes[targetIndex] += halfOffset;
    }
```

File: components/splitter/hooks/useResize.ts [hunk 2]
```diff
@@ -140,10 +142,24 @@ export default function useResize(
       const limitStart = Math.max(currentSizeMin, totalSize - targetSizeMax);
       const limitEnd = Math.min(currentSizeMax, totalSize - targetSizeMin);
       const halfOffset = (limitEnd - limitStart) / 2;
-
+      const targetCacheCollapsedSize = cacheCollapsedSize.current[index];
```
Comment (afc163) [inline components/splitter/hooks/useResize.ts:145]:
```suggestion

      const targetCacheCollapsedSize = cacheCollapsedSize.current[index];
```

File: components/splitter/hooks/useResize.ts [hunk 3]
```diff
@@ -141,9 +143,24 @@ export default function useResize(
...
+      currentCacheCollapsedSize <= currentSizeMax &&
+      currentCacheCollapsedSize >= currentSizeMin;
+
+    if (shouldUseCache) {
+      currentSizes[targetIndex] = targetCacheCollapsedSize;
+      currentSizes[currentIndex] = currentCacheCollapsedSize;
+    } else {
       currentSizes[currentIndex] -= halfOffset;
       currentSizes[targetIndex] += halfOffset;
     }
```
Comment (afc163) [inline components/splitter/hooks/useResize.ts:162]:
```suggestion
      const shouldUseCache = 
        targetCacheCollapsedSize &&
        targetCacheCollapsedSize <= targetSizeMax &&
        targetCacheCollapsedSize >= targetSizeMin &&
        currentCacheCollapsedSize <= currentSizeMax &&
        currentCacheCollapsedSize >= currentSizeMin;

      if (shouldUseCache) {
        currentSizes[targetIndex] = targetCacheCollapsedSize;
        currentSizes[currentIndex] = currentCacheCollapsedSize;
      } else {
        currentSizes[currentIndex] -= halfOffset;
        currentSizes[targetIndex] += halfOffset;
      }
```

**Review by afc163 — APPROVED** [review]
