### PR TITLE
fix(drawer): support closable placement configuration from ConfigProvider

### LINKED ISSUE #55963: Drawer: closable placement config in ConfigProvider doesn't work
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/new-waterfall-sljsdg)

### Steps to reproduce

1. override `closable` Drawer property with `placement: 'end'` in `ConfigProvider`
    ```
    <ConfigProvider drawer={{ closable: { placement: 'end' } }}>...</ConfigProvider/>
    ```
2. render `Drawer` component

### What is expected?

Close icon should be placed at the end.

### What is actually happening?

Close icon is placed at the start because `placement` is not retrieved from context, only from component props [https://github.com/ant-design/ant-design/blob/1b271fcafd3241dba0e1db785e41aca89a993dfd/components/drawer/DrawerPanel.tsx#L100](https://github.com/ant-design/ant-design/blob/1b271fcafd3241dba0e1db785e41aca89a993dfd/components/drawer/DrawerPanel.tsx#L100).

| Environment | Info |
| --- | --- |
| antd | 6.0.0 |
| React | 18.3.1 |
| System | Windows 11 |
| Browser | Google Chrome 142.0.7444.176 |

---
Also it would be nice to update `ConfigProvider` documentation of `drawer` component config (add `closable` property).
Image

### PR DESCRIPTION
**Pull request by meet-student**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - close #55963

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)! Track your changes, like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   support closable placement configuration from ConfigProvider        |
| 🇨🇳 Chinese |    修复 closable placement 配置在 ConfigProvider 组件下失效      |

### CODE REVIEW

**Comment by Pareder** [comment]
@meet-student What is left to do for this PR to be merged?

**Comment by meet-student** [comment]
@zombieJ  cc

**Comment by Pareder** [comment]
@meet-student As I see `closable` prop should also be added to ConfigProvider documentation https://ant.design/components/config-provider#component-config.

**Comment by meet-student** [comment]
> @meet-student As I see `closable` prop should also be added to ConfigProvider documentation [ant.design/components/config-provider#component-config](https://ant.design/components/config-provider#component-config).

ok  await.

thinks

File: components/drawer/DrawerPanel.tsx [hunk 1]
```diff
@@ -91,14 +95,16 @@ const DrawerPanel: React.FC<DrawerPanelProps> = (props) => {
...
 
-  let closablePlacement: string | undefined;
-  if (closable === false) {
-    closablePlacement = undefined;
-  } else if (closable === undefined || closable === true) {
-    closablePlacement = 'start';
-  } else {
-    closablePlacement = closable?.placement === 'end' ? 'end' : 'start';
-  }
+  const closablePlacement = React.useMemo<'start' | 'end' | undefined>(() => {
```
Comment (zombieJ) [inline components/drawer/DrawerPanel.tsx:102]: 这个合并逻辑对 useMergeSemantic 里的 props 不需要合并过去的么？

Comment (meet-student) [reply components/drawer/DrawerPanel.tsx:102]:
```
 closable: closable ?? contextClosable,
```
done

**Review by zombieJ — APPROVED** [review]
