### PR TITLE
fix: fix upload error style

### LINKED ISSUE #19687: upload error 展示
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/#components-upload-demo-picture-card](https://ant.design/components/upload-cn/#components-upload-demo-picture-card)

### Steps to reproduce
把 picture-card.md 的图片改成 error，url 注释
```
{
  uid: '-1',
  name: 'image.png',
  status: 'error',
  // url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
},
```
现在看到的效果是图标在偏上而且鼠标移上去没有错误提示
image

### What is expected?

image

### What is actually happening?
-

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 最新 |
| System | mac |
| Browser | 最新 |

### PR DESCRIPTION
**Pull request by crazyair**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog
close #19687

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   fix picture-card error tooltip        |
| 🇨🇳 Chinese |    修复 picture-card error 工具提示       |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/upload/demo/picture-card.md](https://github.com/qq645381995/ant-design/blob/fix-upload-error-style/components/upload/demo/picture-card.md)
[View rendered components/upload/demo/picture-style.md](https://github.com/qq645381995/ant-design/blob/fix-upload-error-style/components/upload/demo/picture-style.md)

### CODE REVIEW

File: components/upload/UploadList.tsx [hunk 1]
```diff
@@ -226,28 +226,27 @@ export default class UploadList extends React.Component<UploadListProps, any> {
...
           {actions}
           <Animate transitionName="fade" component="">
             {progress}
           </Animate>
         </div>
       );
+
+      return (
+        <div key={file.uid} className={infoUploadingClass}>
+          {file.status === 'error' ? <Tooltip title={message}>{dom}</Tooltip> : <span>{dom}</span>}
```
Comment (shaodahong) [inline components/upload/UploadList.tsx]: `Tooltip` should have some space

image

Comment (qq645381995) [reply components/upload/UploadList.tsx]: ok
