### PR TITLE
fix className ts definition

### LINKED ISSUE #14649: Affix is missing className prop (among others)
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/affix/](https://ant.design/components/affix/)

### Steps to reproduce
* Import the Affix component in Typescript
* Render it with a className prop
* Confirm you get typescript error, despite Affix displaying the added class

### What is expected?
It shouldn't have a type error

### What is actually happening?
It shows a type error

| Environment | Info |
|---|---|
| antd | 3.9.3 |
| React | 16.5.2 |
| System | macOS |
| Browser | Chrome 71 |

---
Affix should either explicitly define commonly used div props such as className, or should extend the div component props since it's just doing an object spread.

### PR DESCRIPTION
**Pull request by ycjcl868**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch.
Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

Close #14649.

### This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
> 3. Related issue link.

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

File: components/affix/index.tsx [hunk 1]
```diff
@@ -55,6 +55,7 @@ export interface AffixProps {
   /** 设置 Affix 需要监听其滚动事件的元素，值为一个返回对应 DOM 元素的函数 */
   target?: () => Window | HTMLElement | null;
   prefixCls?: string;
+  className?: string;
```
Comment (ztplz) [inline components/affix/index.tsx]: 这个加了有啥用  设置样式已经有style了

Comment (ycjcl868) [reply components/affix/index.tsx]: 用在组件 fixed 之前的吧，本来就是 ...props ，只是 ts 里没 className 的定义

Comment (yesmeck) [reply components/affix/index.tsx]: 继承一下 HTMLDivElement 吧。
