### PR TITLE
fix(form): remove hardcoded SimSun font from required label

### LINKED ISSUE #57272: bug: Form.Item label height inconsistency (fractional pixels) due to hardcoded SimSun font
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/lp7kz2)

### Steps to reproduce

1. Create an Ant Design Form with two Form.Item components.
2. Add the `required` prop to the first Form.Item.
3. Open Browser Developer Tools (F12).
4. Inspect the `.ant-form-item-label` element for both items.
5. Compare the "Computed" height of the label containers.

### What is expected?

The height of the Form.Item label should be consistent regardless of whether the `required` prop is used. Both labels should have the same height (e.g., exactly 30px) to maintain a perfect layout grid.

### What is actually happening?

The `required` asterisk (`::before`) has a hardcoded `font-family: SimSun, sans-serif`. 

Because the SimSun font has different metrics (ascender/descender) than the default system font, the browser expands the label container height by fractional pixels. 

In my environment:
- Standard label height: 30px
- Required label height: 30.38px

This causes sub-pixel rendering issues and breaks vertical alignment in complex or dense forms.

| Environment | Info |
| --- | --- |
| antd | 6.3.2 |
| React | 18.2.0 |
| System | Windows 10/11 |
| Browser | Chrome (latest) |

---
Hardcoding a specific font family like SimSun in v6 seems to be an old workaround (for older browsers) that has become technical debt. It contradicts the new design token system in v6, where everything should be customizable via CSS variables. 

On Windows systems where SimSun is installed, this bug is consistently reproducible.

### PR DESCRIPTION
**Pull request by maver1cus**
### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [x] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

fix #57272

### 💡 Background and Solution

The hardcoded `SimSun` font-family in Form required labels causes sub-pixel rendering issues on Windows (e.g., label height becomes 30.38px instead of 30px). This leads to vertical misalignment in forms.

**Solution:** Changed `fontFamily` from `SimSun, sans-serif` to `inherit` in `components/form/style/index.ts`. This ensures the asterisk uses the project's default font and maintains consistent line-height.

### 📝 Change Log

| Language    | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix(Form): Remove hardcoded SimSun font from required asterisk to fix label height inconsistency |
| 🇨🇳 Chinese | fix(Form): 移除必填标记的硬编码 SimSun 字体，修复标签高度不一致的问题 |

### CODE REVIEW

**Comment by afc163** [comment]
Check https://github.com/ant-design/ant-design/pull/57274

File: components/form/style/index.ts [hunk 1]
```diff
@@ -273,7 +273,7 @@ const genFormItemStyle: GenerateStyle<FormToken, CSSObject> = (token) => {
               marginInlineEnd: token.marginXXS,
               color: labelRequiredMarkColor,
               fontSize: token.fontSize,
-              fontFamily: 'SimSun, sans-serif',
+              fontFamily: 'inherit',
```
Comment (afc163) [inline components/form/style/index.ts]:
```suggestion
              fontFamily: sans-serif,
```

How about that?

Comment (maver1cus) [reply components/form/style/index.ts]: Done! Applied the suggested change to use sans-serif. Thanks for the review!

**Review by afc163 — APPROVED** [review]
