### PR TITLE
fix: Checkbox indeterminate style

### LINKED ISSUE #50074: Collapse组件items label中使用Checkbox组件indeterminate状态时样式错误
### Reproduction link

[Edit on StackBlitz](https://stackblitz.com/edit/react-whnfh3?file=demo.tsx)

### Steps to reproduce

Collapse中选中一个子项->此时Collapse label上的Checkbox会处于indeterminate状态，鼠标悬上去样式会出现蓝色背景

### What is expected?

在Collapse label中使用Checkbox并设置indeterminate状态时，样式正常显示

### What is actually happening?

在Collapse label中使用Checkbox并设置indeterminate状态时，样式未正常显示

| Environment | Info |
| --- | --- |
| antd | 5.19.3 |
| React | 18.3.1 |
| System | windows |
| Browser | Chrome 126.0.6478.183 |

### PR DESCRIPTION
**Pull request by afc163**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/50074

### 💡 Background and solution

优先级又不够了。

### 📝 Changelog

- Use a developer-oriented tone and narrative style.
- Describe the user's first-hand experience of the issue and its impact on developers, rather than your solution approach.
- Refer to: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix Checkbox `indeterminate` hover style.          |
| 🇨🇳 Chinese |  修复 Checkbox `indeterminate` 状态的 hover 样式。         |

### CODE REVIEW

File: components/checkbox/style/index.ts [hunk 1]
```diff
@@ -189,8 +189,8 @@ export const genCheckboxStyle: GenerateStyle<CheckboxToken> = (token) => {
         '&-indeterminate': {
           // Wrapper > Checkbox > inner
           [`${checkboxCls}-inner`]: {
-            backgroundColor: token.colorBgContainer,
-            borderColor: token.colorBorder,
+            backgroundColor: `${token.colorBgContainer} !important`,
```
Comment (li-jia-nan) [inline components/checkbox/style/index.ts:192]: 可以通过加选择器权重来解吗？

Comment (afc163) [reply components/checkbox/style/index.ts:192]: 试过，非常难加，改完后代码异常复杂，优先级地狱。

**Review by li-jia-nan — APPROVED** [review]

**Comment by waka3** [comment]
image
 这段代码照成样式覆盖，checkbox的半选效果出不来
