### PR TITLE
fix: Steps keyboard switch

### LINKED ISSUE #43634: Clickable Steps cannot be used with keyboard
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/w4txmc)

### Steps to reproduce

1. Tab to a clickable step. Notice there is no focus highlight.
2. Press enter.

### What is expected?

Interactive elements should respond to both keyboard and mouse events.

### What is actually happening?

Steps do not respond to keyboard enter. They are using `div`s instead of `button` elements.

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Firefox 115 |

---
There's a PR sent to fix this, but no response from maintainers. https://github.com/react-component/steps/pull/238

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #43634

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix Steps with clickable can not trigger by keyboard.        |
| 🇨🇳 Chinese |  修复 Steps 配置可点击时不能通过键盘操作的问题。         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 5b4ce3b</samp>

Improved the keyboard accessibility and alignment of the `Steps` component. Updated the `rc-steps` dependency and added a focus outline style to the steps item icon in `components/steps/style/index.tsx`.

### <samp>🤖 Generated by Copilot at 5b4ce3b</samp>

*  Add focus outline style to steps item icon for keyboard accessibility ([link](https://github.com/ant-design/ant-design/pull/43644/files?diff=unified&w=0#diff-7c302bb80b5f306d72c03ca5e5fe2961248a1cdf0f41329ce9e3307110aa29d6L3-R3), [link](https://github.com/ant-design/ant-design/pull/43644/files?diff=unified&w=0#diff-7c302bb80b5f306d72c03ca5e5fe2961248a1cdf0f41329ce9e3307110aa29d6R174), [link](https://github.com/ant-design/ant-design/pull/43644/files?diff=unified&w=0#diff-7c302bb80b5f306d72c03ca5e5fe2961248a1cdf0f41329ce9e3307110aa29d6L192-R204))
  - Import `genFocusOutline` function from `../../style` to generate outline style ([link](https://github.com/ant-design/ant-design/pull/43644/files?diff=unified&w=0#diff-7c302bb80b5f306d72c03ca5e5fe2961248a1cdf0f41329ce9e3307110aa29d6L3-R3))
  - Define `stepItemIconCls` variable to store class name of icon element ([link](https://github.com/ant-design/ant-design/pull/43644/files?diff=unified&w=0#diff-7c302bb80b5f306d72c03ca5e5fe2961248a1cdf0f41329ce9e3307110aa29d6R174))
  - Apply `genFocusOutline` function to icon element when container element is focused with `:focus-visible` pseudo-class ([link](https://github.com/ant-design/ant-design/pull/43644/files?diff=unified&w=0#diff-7c302bb80b5f306d72c03ca5e5fe2961248a1cdf0f41329ce9e3307110aa29d6L192-R204))
* Update `rc-steps` dependency to fix icon alignment bug ([link](https://github.com/ant-design/ant-design/pull/43644/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L147-R147))
  - Bump `rc-steps` version from 6.0.0 to 6.0.1 in `package.json` ([link](https://github.com/ant-design/ant-design/pull/43644/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L147-R147))

### CODE REVIEW

**Review by kiner-tang — APPROVED** [review]

File: components/steps/style/index.tsx [hunk 1]
```diff
@@ -189,12 +190,18 @@ const genStepsItemStyle: GenerateStyle<StepsToken, CSSObject> = (token) => {
     },
     [`${stepsItemCls}-container`]: {
       outline: 'none',
+
+      [`&:focus-visible`]: {
+        [stepItemIconCls]: {
+          ...genFocusOutline(token),
+        },
+      },
```
Comment (MadCcc) [inline components/steps/style/index.tsx:198]:
```suggestion
      [stepItemIconCls]: {
        ...genFocusStyle(token),
      },
```
直接用这个？这个包含了 focus-visible
image

**Review by MadCcc — APPROVED** [review]
