### PR TITLE
fix: improve message().then type

### LINKED ISSUE #28160: Shoudl MessageType of message be changed?
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
code: 
```
1, tsx
2, code like `message.warn('bla...').then(() => {// some code here})`
```
It report an error: 
```
TS2554: Expected 2 arguments, but got 1. An argument for 'reject' was not provided.
```
caused by the signature of MessageType:
```
export interface MessageType {
    (): void;
    then: (fill: ThenableArgument, reject: ThenableArgument) => Promise<void>;
    promise: Promise<void>;
}
```

### What does the proposed API look like?
```
// I copy Promise.then signature in Webstorm lib.es5.d.ts
export interface MessageType {
    (): void;
    then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): PromiseLike<TResult1 | TResult2>;
    promise: Promise<void>;
}
```
or I think the reject is not needed, cause message doesn't have reject action.

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #28160 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Improve `message().then` TS definition. |
| 🇨🇳 Chinese | 优化 `message().then` 的 TS 定义。  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/message/index.tsx [hunk 1]
```diff
@@ -106,11 +106,7 @@ export interface ThenableArgument {
   (val: any): void;
 }
 
-export interface MessageType {
-  (): void;
```
Comment (paranoidjk) [inline components/message/index.tsx:110]: image

少了 function 的类型，业务代码会挂的

Comment (afc163) [reply components/message/index.tsx:110]: 把这个给漏了，来个 PR 修复一下。
