### PR TITLE
fix: border style of Input.Search when allowClear

### LINKED ISSUE #27296: Input.Search hover border right lost when allowclear
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/sousuokuang-ant-design-demo-forked-w8id2)

### Steps to reproduce
- Hover the first

### What is expected?
border normal

### What is actually happening?
border unnormal

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | The latest |
| System | mac |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by xrkffgg**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution
close https://github.com/ant-design/ant-design/issues/27296

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix the problem of unnormal border style when Input.Search activates `allowClear`.          |
| 🇨🇳 Chinese |  修复 Input.Search 激活`allowClear`时边框样式异常的问题。         |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/input/demo/group.md](https://github.com/ant-design/ant-design/blob/kk/components/input/demo/group.md)
[View rendered components/input/demo/search-input.md](https://github.com/ant-design/ant-design/blob/kk/components/input/demo/search-input.md)

### CODE REVIEW

**Review by hengkx — APPROVED** [review]

File: components/input/Search.tsx [hunk 1]
```diff
@@ -125,6 +125,7 @@ const Search = React.forwardRef<Input, SearchProps>((props, ref) => {
         {
           [`${prefixCls}-rtl`]: direction === 'rtl',
           [`${prefixCls}-${size}`]: !!size,
+          [`${prefixCls}-button`]: !!enterButton,
```
Comment (zombieJ) [inline components/input/Search.tsx:128]: `-with-button` 好了
