### PR TITLE
fix(Form): switch should be trigger by form label

### LINKED ISSUE #15549: Form.item label can't control Swtich
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/vnoo153ol3)

### Steps to reproduce
1. Click Switch label

### What is expected?
Switch can be controlled by label

### What is actually happening?
label can't control Swtich

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.1 |
| System | Windows10 |
| Browser | Chrome/72.0.3626.121 |

---
Switch switch cannot be controlled by clicking Form.Items label.

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

close #15549

### 📝 Changelog

- English Changelog: Fix switch cannot be triggered by form label.
- Chinese Changelog (optional):

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/form/FormItem.tsx [hunk 1]
```diff
@@ -304,26 +304,16 @@ export default class FormItem extends React.Component<FormItemProps, any> {
...
-      // Only prevent in default situation
-      // Avoid preventing event in `label={<a href="xx">link</a>}``
-      if (typeof label === 'string') {
-        e.preventDefault();
-      }
-
-      if (control.focus) {
-        control.focus();
-      }
+    if (control && control.focus) {
```
Comment (Nbsaw) [inline components/form/FormItem.tsx]: Ternary ?

``` js
control && control.focus && control.focus();
```

Comment (afc163) [reply components/form/FormItem.tsx]: It is more extendable for adding other statements someday.
