### PR TITLE
fix: Layout zero width trigger missing style

### LINKED ISSUE #51224: Layout.Sider 特殊 trigger 的定位样式错误
### Reproduction link

[https://ant-design.antgroup.com/~demos/layout-demo-responsive](https://ant-design.antgroup.com/~demos/layout-demo-responsive)

### Steps to reproduce

使用官方文档的 demo 代码

### What is expected?

trigger 的定位在正确的位置

### What is actually happening?

trigger 的定位在下方

| Environment | Info |
| --- | --- |
| antd | 5.21.0 |
| React | 18 |
| System | win11 |
| Browser | Chrome 131.0.6770.0 |

### PR DESCRIPTION
**Pull request by afc163**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

close https://github.com/ant-design/ant-design/issues/51224

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix Layout missing style of zero width trigger.         |
| 🇨🇳 Chinese | 修复 Layout 切换侧边栏按钮样式丢失的问题。          |

### CODE REVIEW

File: components/layout/style/sider.ts [hunk 1]
```diff
@@ -109,10 +105,7 @@ const genSiderStyle: GenerateStyle<LayoutToken, CSSObject> = (token) => {
 
           '&-right': {
             insetInlineStart: token.calc(zeroTriggerWidth).mul(-1).equal(),
-            borderStartStartRadius: borderRadius,
-            borderStartEndRadius: 0,
-            borderEndEndRadius: 0,
-            borderEndStartRadius: borderRadius,
+            borderRadius: `${borderRadiusLG} 0 0 ${borderRadiusLG}`,
```
Comment (li-jia-nan) [inline components/layout/style/sider.ts:108]: 这个得加单位吧？

File: components/layout/style/sider.ts [hunk 2]
```diff
@@ -87,11 +87,7 @@ const genSiderStyle: GenerateStyle<LayoutToken, CSSObject> = (token) => {
           alignItems: 'center',
           justifyContent: 'center',
           background: siderBg,
-          borderStartStartRadius: 0,
-          borderStartEndRadius: borderRadius,
-          borderEndEndRadius: borderRadius,
-          borderEndStartRadius: 0,
-
+          borderRadius: `0 ${borderRadiusLG} ${borderRadiusLG} 0`,
```
Comment (li-jia-nan) [inline components/layout/style/sider.ts:90]: 这个得加单位吧？

**Review by li-jia-nan — APPROVED** [review]

**Comment by slow123top** [comment]
learn more
