### PR TITLE
type: remove useless internal tag

### LINKED ISSUE #39752: 主题 Token Typescript 类型  HeightMapToken 缺少值
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-2nrlkn?file=/index.js)

### Steps to reproduce

```
import { genComponentStyleHook } from "antd/es/theme/internal";

export default genComponentStyleHook("DatePicker", (token) => {
  const { controlHeightSM, antCls, controlHeight } = token || {};

  return {
    [`${antCls}-demo`]: {
      height: controlHeightSM || controlHeight * 0.75
    }
  };
});
```

### What is expected?

```js
export interface HeightMapToken {
  controlHeightXS: number;
  controlHeightSM: number;
  controlHeightLG: number;
}
```

### What is actually happening?

```js
export interface HeightMapToken {

}
```

| Environment | Info |
| --- | --- |
| antd | 5.1.0 |
| React | 18.2.0 |
| System | mac |
| Browser | Google Chrome 108.0.5359.124 |

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/39752

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix missing type defination for Design Token.        |
| 🇨🇳 Chinese |    修复部分 Design Token 缺少类型提示的问题。       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Review by afc163 — APPROVED** [review]

File: components/theme/interface/maps/style.ts [hunk 1]
```diff
@@ -33,7 +33,6 @@ export interface StyleMapToken {
   borderRadiusLG: number;
   /**
    * @default 4
-   * @internal
```
Comment (afc163) [inline components/theme/interface/maps/style.ts:36]: 如果要暴露出去，最好写一下用处。
