### PR TITLE
fix: dev ssr

### LINKED ISSUE #39065: SSR Warning: Prop `className` did not match with Avatar
### Steps to reproduce

try to import Avatar to server component in Nextjs

### What is expected?

This warning should be remove

### What is actually happening?

The message warning in console:

`Warning: Prop `className` did not match. Server: "ant-avatar ant-avatar-circle ant-avatar-image ant-avatar-icon css-dev-only-do-not-override-6w1yu4" Client: "ant-avatar ant-avatar-circle ant-avatar-image ant-avatar-icon css-dev-only-do-not-override-1x6ld8w"`

image

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | React lastest version |
| System | Windows 10 |
| Browser | Chrome lastest version |

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/39065

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix ssr warning in dev caused by dynamic hashId.       |
| 🇨🇳 Chinese |    修复 dev 下动态 hashId 导致的 ssr 注水失败的问题。       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/theme/internal.tsx [hunk 1]
```diff
@@ -57,8 +57,7 @@ export const DesignTokenContext = React.createContext<{
 // ================================== Hook ==================================
 // In dev env, we refresh salt per hour to avoid user use this
```
Comment (yoyo837) [inline components/theme/internal.tsx:58]: 那么注释是不是也⏫

**Review by yoyo837 — APPROVED** [review]

**Review by zombieJ — APPROVED** [review]
