### PR TITLE
fix: use dotActiveWidth token

### LINKED ISSUE #55614: Carousel component identifier does not have an active state style in portrait mode.
### Reproduction link

[https://ant.design/components/carousel-cn#carousel-demo-arrows](https://ant.design/components/carousel-cn#carousel-demo-arrows)

### Steps to reproduce

https://ant.design/components/carousel-cn#carousel-demo-arrows

Image

### What is expected?

和横排一样

### What is actually happening?

和横排不一样

| Environment | Info |
| --- | --- |
| antd | 5.28.0 |
| React | 18.3.1 |
| System | Windows |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by wanpan11**
- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

- close https://github.com/ant-design/ant-design/issues/55614

### 💡 Background and Solution

image

竖排标识符没有使用 dotActiveWidth

### 📝 Change Log
| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      修复竖排标识符激活态宽度异常     |
| 🇨🇳 Chinese |      修复了激活状态下垂直标识符宽度异常的问题。     |

### CODE REVIEW

**Review by afc163 — APPROVED** [review]

File: components/carousel/style/index.ts [hunk 1]
```diff
@@ -416,8 +416,12 @@ const genCarouselVerticalStyle: GenerateStyle<CarouselToken> = (token) => {
 
           '&.slick-active': {
             ...reverseSizeOfDot,
+            height: token.dotActiveWidth,
 
-            button: reverseSizeOfDot,
+            button: {
+              ...reverseSizeOfDot,
+              height: token.dotActiveWidth,
```
Comment (afc163) [inline components/carousel/style/index.ts:423]: 这个 height 用 dotActiveWidth 就有点怪，要不加一个 dotActiveHeight。

Comment (wanpan11) [reply components/carousel/style/index.ts:423]: 感觉 master 先不加了吧，加的话好像会 breaking。
之前定义过 dotActiveWidth  的就失效了

next 分支
把 dotActiveWidth 改成 dotActiveSize 咋样
再就是 dotHeight dotWidth 感觉也有点歧义
 
image

Comment (meet-student) [reply components/carousel/style/index.ts:423]: 我觉得一个就好了吧,  指是位置，dot 转了下
