### PR TITLE
fix: 🐛 duplicated icons when Tree showLine is true 

### LINKED ISSUE #20090: TreeNode 设置自定义 icon 后还显示默认的图标
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/baizn/pen/wvBaGbj?&editable=true&editors=001](https://codepen.io/baizn/pen/wvBaGbj?&editable=true&editors=001)

### Steps to reproduce
TreeNode已经定义了 icon 属性，但还是显示了默认的图标。

### What is expected?
不显示默认到的图标，连线的地方是自定义的icon中的图标
image

### What is actually happening?
显示的是默认到的图标
image

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 0.16.x |
| System | mac |
| Browser | chorme最新 |

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #20090

### 💡 Background and solution

```jsx
      <Tree showIcon showLine defaultExpandedKeys={['0-0-0']} onSelect={this.onSelect}>
        <TreeNode title="parent 1" key="0-0">
          <TreeNode icon={<Icon type="form" />} title="parent 1-0" key="0-0-0">
            <TreeNode icon={<Icon type="form" />} title="leaf" key="0-0-0-0" />
            <TreeNode title="leaf" key="0-0-0-1" />
            <TreeNode title="leaf" key="0-0-0-2" />
          </TreeNode>
          <TreeNode title="parent 1-1" key="0-0-1">
            <TreeNode title="leaf" key="0-0-1-0" />
          </TreeNode>
          <TreeNode title="parent 1-2" key="0-0-2">
            <TreeNode title="leaf" key="0-0-2-0" />
            <TreeNode title="leaf" key="0-0-2-1" />
          </TreeNode>
        </TreeNode>
      </Tree>
```

image

fixed to

image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Tree duplicated icons when showLine is true.  |
| 🇨🇳 Chinese | 修复 Tree `showLine` 为 `true` 时展示多余图标的问题。 |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/tree/Tree.tsx [hunk 1]
```diff
@@ -239,6 +239,9 @@ export default class Tree extends React.Component<TreeProps, any> {
       <RcTree
         ref={this.setTreeRef}
         {...props}
+        // Hide icon in node when showLine is true, show icon in line always
+        // https://github.com/ant-design/ant-design/issues/20090
+        showIcon={showLine ? false : showIcon}
         prefixCls={prefixCls}
```
Comment (yoyo837) [inline components/tree/Tree.tsx]: `showLine ? false : showIcon` === `false`

**Comment by afc163** [comment]
cause https://github.com/ant-design/ant-design/issues/20192 and fixed in #20196
