### PR TITLE
fix(Transfer): Prioritize using the disabled property of the Transfer component

### LINKED ISSUE #55972: form表单里面的穿梭框组件
### Reproduction link

[https://5x.ant.design/components/form-cn#form-demo-disabled](https://5x.ant.design/components/form-cn#form-demo-disabled)

### Steps to reproduce

给整个form设置disabled属性，单独给穿梭框组件 `<Transfer />` 设置 `disabled={false}`，穿梭框组件的样式有问题，部分checked组件显示的样式还是disabled状态，部分显示正常

### What is expected?

穿梭框组件设置disabled={false} 的时候，穿梭框组件内部的所有按钮都是非disabled状态

### What is actually happening?

穿梭框组件的样式有问题，部分勾选框显示的是disabled状态，部分正常

| Environment | Info |
| --- | --- |
| antd | 5.29.1 |
| React | 18.2.0 |
| System | mac |
| Browser | 谷歌 142.0.7444.176 |

[](blob:https://h16s2p02bsi.feishu.cn/6677ad01-a99e-417a-97ef-c9c490386a6d)

### PR DESCRIPTION
**Pull request by zenggpzqbx**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - fix #55972

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)! Track your changes, like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Prioritize using the disabled property of the Transfer component          |
| 🇨🇳 Chinese |  优先使用Transfer组件的disabled属性         |

### CODE REVIEW

File: components/transfer/ListItem.tsx [hunk 1]
```diff
@@ -36,9 +36,14 @@ const ListItem = <RecordType extends KeyWiseTransferItem>(props: ListItemProps<R
     onRemove,
     showRemove,
   } = props;
-
+  const mergedDisabled = React.useMemo(() => {
+    if (disabled) {
+      return true;
+    }
+    return item?.disabled ?? disabled;
+  }, [disabled, item?.disabled]);
```
Comment (afc163) [inline components/transfer/ListItem.tsx]: 不需要 memo，此处没有性能提升效果。

**Comment by afc163** [comment]
需要一个测试用例，防止后续改挂。

**Comment by afc163** [comment]
lint 挂了

**Comment by zenggpzqbx** [comment]
> lint 挂了

我自己手动格式化了一下。代码已提交。

File: components/transfer/ListItem.tsx [hunk 2]
```diff
@@ -36,9 +36,9 @@ const ListItem = <RecordType extends KeyWiseTransferItem>(props: ListItemProps<R
     onRemove,
     showRemove,
   } = props;
-
+  const mergedDisabled = disabled ? true : (item?.disabled ?? disabled);
```
Comment (afc163) [inline components/transfer/ListItem.tsx]:
```suggestion
  const mergedDisabled = disabled || item?.disabled;
```

Comment (zenggpzqbx) [reply components/transfer/ListItem.tsx]: webstorm64_Rtqyuhv8h6
合并完代码后怎么这么多的snapshot，该如何处理呢，需要我一块提交上去吗

Comment (thinkasany) [reply components/transfer/ListItem.tsx]: 合并完之后，可能本地依赖变了，需要重新 install 一下

Comment (zenggpzqbx) [reply components/transfer/ListItem.tsx]: webstorm64_RsdiNgw5Sg
给分依赖吧，下载到这里彻底下不下来了，原先的有些依赖都弃用了

Comment (thinkasany) [reply components/transfer/ListItem.tsx]: 用镜像了吗
https://npmmirror.com/

Comment (zenggpzqbx) [reply components/transfer/ListItem.tsx]: 用的就是这个https://registry.npmmirror.com/

Comment (zenggpzqbx) [reply components/transfer/ListItem.tsx]: 现在好了，代码已改完提交。起了个早下载就好了，估计还是网络的问题。

**Review by afc163 — APPROVED** [review]

File: components/transfer/ListItem.tsx [hunk 3]
```diff
@@ -36,9 +36,9 @@ const ListItem = <RecordType extends KeyWiseTransferItem>(props: ListItemProps<R
     onRemove,
     showRemove,
   } = props;
-
+  const mergedDisabled = disabled || item?.disabled;
   const classes = clsx(`${prefixCls}-content-item`, classNames.item, {
-    [`${prefixCls}-content-item-disabled`]: disabled || item.disabled,
+    [`${prefixCls}-content-item-disabled`]: mergedDisabled,
     [`${prefixCls}-content-item-checked`]: checked && !item.disabled,
```
[the remark this answers is not in the document]
Comment (afc163) [reply components/transfer/ListItem.tsx:42]: 看看这个。

[the remark this answers is not in the document]
Comment (zenggpzqbx) [reply components/transfer/ListItem.tsx:42]: chrome_BJkWXMdAv5
确实是有问题的，选择条目后在禁用，会有一个选中的背景色没去掉，我已修改并提交

[the remark this answers is not in the document]
Comment (zenggpzqbx) [reply components/transfer/ListItem.tsx:42]: 代码已经合并了，这种情况我是应该新建pr关联到这个issue还是自己提个issue,并提交pr

[the remark this answers is not in the document]
Comment (afc163) [reply components/transfer/ListItem.tsx:42]: 直接提交 PR 吧。
