### PR TITLE
fix: ConfirmDialog passing wrong footer prop

### LINKED ISSUE #41170: Confirm Modal has an empty div below confirm buttons
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-zjshu0?file=/index.js:940-950)

### Steps to reproduce

Click on a 'Confirm Modal' button and look at the confirm buttons position. I added Default Modal for a comparison.

### What is expected?

Styles of the modal are the same when opening with `confirm` function or `<Modal>` component.

### What is actually happening?

When opening a Modal with `confirm` function, confirm buttons are too distant from the bottom edge of the Modal. 
There's an empty `div` element (ant-modal-footer) that has a 12px top-margin that is causing misalignment.

| Environment | Info |
| --- | --- |
| antd | 5.3.0 |
| React | react v18.2.0 |
| System | Windows 11 Pro 21H2 |
| Browser | Latest Chrome and Firefox |

### PR DESCRIPTION
**Pull request by Svudec**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

Fixes #41170 

### 💡 Background and solution

`<ConfirmDialog>` component was passing an empty string as a `footer` prop to the `<Dialog>` component.

That was wrong as `<Dialog>` component is rendering that empty string in a `<div>` element wrapper that has a margin-top attribute as shown in the screenshot in the referenced issue. 
`<ConfirmDialog>` should pass a `null` value for footer prop. That way a footer wrapper `div` won't be rendered.

BEFORE CHANGE: 
image

AFTER CHANGE:
image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | [Modal] Fixed too large bottom margin when using `confirm()` to open a Modal |
| 🇨🇳 Chinese | [Modal] 修复使用 `confirm()` 打开 Modal 时下边距过大的问题   |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by Wxh16144 — COMMENTED** [review]
don't forget to supplement test cases https://github.com/Svudec/ant-design/pull/1

File: components/input-number/style/index.ts [hunk 1]
```diff
@@ -263,10 +263,6 @@ const genInputNumberStyles: GenerateStyle<InputNumberToken> = (token: InputNumbe
           [`${componentCls}-handler-wrap`]: {
             display: 'none',
           },
-
-          [`${componentCls}-input`]: {
-            color: 'inherit',
-          },
```
Comment (Wxh16144) [inline components/input-number/style/index.ts:269]: need revert ~

**Review by Wxh16144 — DISMISSED** [review]

File: components/input-number/style/index.ts (hunk 1 above)
Comment (Svudec) [reply components/input-number/style/index.ts]: I've overridden this file with the one from the master branch.

**Review by afc163 — APPROVED** [review]

**Review by afc163 — APPROVED** [review]
