### PR TITLE
fix: Typography warning for `ref` error

### LINKED ISSUE #19064: 使用Typography.Text组件产生warning
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-kgnlf?fontsize=14)

### Steps to reproduce
直接打开看console

### What is expected?
无warning

### What is actually happening?
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | 16.8.6 |
| System | win10 |
| Browser | Chromium 74.0.3729.169 |

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix #19064
ref #19066

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      Fix Typography warning for `ref` error.     |
| 🇨🇳 Chinese |    修复 Typography 提示获取不到 `ref` 的错误信息。        |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/typography/Typography.tsx [hunk 1]
```diff
@@ -13,38 +15,68 @@ export interface TypographyProps {
...
+          </Component>
+        );
+      }}
+    </ConfigConsumer>
+  );
+};
+
+let RefTypography;
+
+if (React.forwardRef) {
```
Comment (shaodahong) [inline components/typography/Typography.tsx]: 一开始我是考虑 `forwardRef` 有兼容性问题，所以没有这样修，4.0 都不需要这样写，感觉需要个 to-do

Comment (zombieJ) [reply components/typography/Typography.tsx]: 嗯，这些 4.0 发布后再清理就行了。否则每周 4.0 merge master 都一堆冲突。

**Comment by zombieJ** [comment]
新版 eslint-plugin-react 有 bug：https://github.com/yannickcr/eslint-plugin-react/issues/2423
本地降低测试通过，可以合并。
