### PR TITLE
fix: use Object.prototype.toString to check object

### LINKED ISSUE #20528: message.*存在bug，使用typeof做出类型校验，从而引发后边代码错误，源码存在缺陷
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://*.*](http://*.*)

## 在调用 message.* 任意方法，参数传入 null 报错

在antd/message源码中，ts 类型限制参数可以传入 null

但是这段代码因为参数是 null 导致报错，typeof null 返回的是 "object"

```js
function isArgsProps(content) {
  return _typeof(content) === 'object' && !!content.content;
}
```

### What is expected?
请多加测试

### What is actually happening?
代码报错

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.3.2 |
| System | mac |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by DiamondYuan**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/20528

### 💡 Background and solution

use Object.prototype.toString instead of typeof

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/message/index.tsx [hunk 1]
```diff
@@ -66,7 +66,7 @@ function notice(args: ArgsProps): MessageType {
     loading: 'loading',
   }[args.type];
 
-  const target = args.key || key++;
+  const target = key++;
```
Comment (afc163) [inline components/message/index.tsx]: 这里改错了，target 对不上了。
