### PR TITLE
fix: Slider formatter returns fixed content, Tooltip position abnormal after dragging

### LINKED ISSUE #53435: Slider 固定 formatter 拖拽后 Tooltip 位置异常
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/dai-shu-ru-kuang-de-hua-kuai-antd-5-24-4-forked-xml94x?file=%2Fdemo.tsx%3A8%2C16-8%2C25)

### Steps to reproduce

查看 demo

### What is expected?

位置没问题

### What is actually happening?

位置有问题

| Environment | Info |
| --- | --- |
| antd | 5.24.6 |
| React | latest |
| System | mac |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by EmilyyyLiu**
### 🤔 This is a ...

- [X] 🐞 Bug fix

### 🔗 Related Issues

fix https://github.com/ant-design/ant-design/issues/53435

### 📝 Change Log

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     fix:Slider formatter returns fixed content,Tooltip position abnormal after dragging     |
| 🇨🇳 Chinese |    修复 Slider 固定 formatter ，拖拽后 Tooltip 位置异常      |

### CODE REVIEW

File: components/slider/SliderTooltip.tsx [hunk 1]
```diff
@@ -39,7 +40,7 @@ const SliderTooltip = React.forwardRef<SliderRef, SliderTooltipProps>((props, re
     }
 
     return cancelKeepAlign;
-  }, [mergedOpen, props.title]);
+  }, [mergedOpen, props.title, value]);
```
Comment (zombieJ) [inline components/slider/SliderTooltip.tsx:43]: 测试用例加一个

**Review by zombieJ — APPROVED** [review]
