### PR TITLE
Fix matchMedia not present in jest test or react-snapshot

### LINKED ISSUE #3308: Issue running tests when include ant components
Pls, can you helpme?

Your project includes the enquirejs dependency. But I have issues when try to run tests into my project because 

```
matchMedia not present, legacy browsers require a polyfill
```

I don't know how to solve this issue.

this is my code

```
import React from 'react';
import { shallow } from 'enzyme';
import { expect } from 'chai';

// Import components for testing here
import NavbarCrm from '../NavbarCrmComponent';

describe('<NavbarCrm />', function () {

  if (typeof window !== 'undefined') {
    var matchMediaPolyfill = function matchMediaPolyfill(mediaQuery) {
      return {
        media: mediaQuery,
        matches: false,
        addListener: function addListener() {},
        removeListener: function removeListener() {}
      };
    };
    window.matchMedia = window.matchMedia || matchMediaPolyfill;
  }

  it('should have props for heading and children', function (done) {
    const wrapper = shallow(<Menu />);
    expect(wrapper.props().classes).to.be.defined;
    expect(wrapper.props().children).to.be.defined;
    done();
  });
});

```

I tried in all methods. Above, below but the same error ever. 

Can U help me?

I cant to solve the issue putting 

```
if (typeof window !== 'undefined') {
    var matchMediaPolyfill = function matchMediaPolyfill(mediaQuery) {
      return {
        media: mediaQuery,
        matches: false,
        addListener: function addListener() {},
        removeListener: function removeListener() {}
      };
    };
    window.matchMedia = window.matchMedia || matchMediaPolyfill;
  }
```

I include the above code in the line 49826 located at andt.js file into my node_modules And the problem is over. but this is not a good solution.

into **enquirejs/src/include/wrap.js** into the dist file for npm installed module. But it isn't a pretty solution.

### LINKED ISSUE #6560: matchMedia not present, legacy browsers require a polyfill
### Version
2.11.1

### Environment
win10, chrome 59, react 15.5.4

### Reproduction link
[https://github.com/ant-design/create-react-app-antd](https://github.com/ant-design/create-react-app-antd)

### Steps to reproduce
1. download this repository:
https://github.com/ant-design/create-react-app-antd

2. type "yarn" to install all dependences.
3. type "yarn run test"

4. the error will pops up.

### What is expected?
the test passed

### What is actually happening?
Error: matchMedia not present, legacy browsers require a polyfill

---
在最新版本2.11.1中还是没有解决这个问题。

我现在只能手动patch这个文件：
node_modules/antd/lib/carousel/index.js

把如下这段代码：
window.matchMedia = window.matchMedia || function() {
    return {
        matches : false,
        addListener : function() {},
        removeListener: function() {}
    };
};

放在require('react-slick')前面，就可以解决这个问题。

### LINKED ISSUE #7341: Integrating with react-snapshot will cause "matchMedia not present" error with Carousel component
### Version
2.12.7

### Environment
react 15.6.1

### Reproduction link
[https://github.com/Songkeys/create-react-app-with-react-snapshot-and-antd](https://github.com/Songkeys/create-react-app-with-react-snapshot-and-antd)

### Steps to reproduce
First, I followed the [use with create react app](https://ant.design/docs/react/use-with-create-react-app) to integrate `antd` with `create-react-app`. Then, I setup [react-snapshot](https://github.com/geelen/react-snapshot) correctly. Everything works fine with `App.js` code below:

```
import React, { Component } from 'react';
import Button from 'antd/lib/button';
import './App.css';

export default class App extends Component {
  render() {
    return (
      <div>
          <Button>123</Button>
      </div>
    );
  }
}
```

And the log printed in the terminal when use `yarn build` with `react-snapshot` showed success:
```
❯ yarn build
yarn build v0.27.5
$ react-scripts build && react-snapshot
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  56.22 KB (-9.17 KB)  build/static/js/main.061f03aa.js
  46.39 KB             build/static/css/main.10ddcd22.css

The project was built assuming it is hosted at the server root.
To override this, specify the homepage in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  serve -s build

🕷   Starting crawling http://localhost:54327/
✏   Saving / as /index.html
🕸   Finished crawling.
Done in 15.05s.
```

---

But, when I tried to import the `Carousel` component into the project and build it, the error occurred.

`App.js`:
```
import React, { Component } from 'react';
import Carousel from 'antd/lib/carousel';
import './App.css';

export default class App extends Component {
  render() {
    return (
      <div>
        <Carousel>
          <div><h3>1</h3></div>
          <div><h3>2</h3></div>
          <div><h3>3</h3></div>
          <div><h3>4</h3></div>
        </Carousel>
      </div>
    );
  }
}
```

Terminal output when building:
```
❯ yarn build
yarn build v0.27.5
$ react-scripts build && react-snapshot
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  63.52 KB (+7.3 KB)  build/static/js/main.a9a116e7.js
  46.39 KB            build/static/css/main.10ddcd22.css

The project was built assuming it is hosted at the server root.
To override this, specify the homepage in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  serve -s build

🕷   Starting crawling http://localhost:54853/
Error: Uncaught [Error: matchMedia not present, legacy browsers require a polyfill]
    at reportException (/Users/songkeys/snaptest/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
    at processJavaScript (/Users/songkeys/snaptest/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
    at HTMLScriptElementImpl._eval (/Users/songkeys/snaptest/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
    at /Users/songkeys/snaptest/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
    at Object.check (/Users/songkeys/snaptest/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:89:11)
    at /Users/songkeys/snaptest/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:108:12
    at wrappedEnqueued (/Users/songkeys/snaptest/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at Request.request [as _callback] (/Users/songkeys/snaptest/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:203:9)
    at Request.self.callback (/Users/songkeys/snaptest/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13) Error: matchMedia not present, legacy browsers require a polyfill
    at new r (http://localhost:54853/static/js/main.a9a116e7.js:1:214187)
    at Object.<anonymous> (http://localhost:54853/static/js/main.a9a116e7.js:1:214123)
    at t (http://localhost:54853/static/js/main.a9a116e7.js:1:101)
    at Object.<anonymous> (http://localhost:54853/static/js/main.a9a116e7.js:1:193869)
    at t (http://localhost:54853/static/js/main.a9a116e7.js:1:101)
    at Object.<anonymous> (http://localhost:54853/static/js/main.a9a116e7.js:1:192924)
    at t (http://localhost:54853/static/js/main.a9a116e7.js:1:101)
    at Object.<anonymous> (http://localhost:54853/static/js/main.a9a116e7.js:1:178894)
    at t (http://localhost:54853/static/js/main.a9a116e7.js:1:101)
    at Object.<anonymous> (http://localhost:54853/static/js/main.a9a116e7.js:1:177811)
🔥 'render' from react-snapshot was never called. Did you replace the call to ReactDOM.render()?
🕸   Finished crawling.
Done in 15.53s.
```

===

Also, when i tried to use `yarn test`  with `Carousel` imported, test would fail:
```
 FAIL  src/App.test.js
  ● Test suite failed to run

    matchMedia not present, legacy browsers require a polyfill
      
      at new MediaQueryDispatch (node_modules/enquire.js/src/MediaQueryDispatch.js:15:15)
      at Object.<anonymous> (node_modules/enquire.js/src/index.js:2:18)
      at Object.<anonymous> (node_modules/react-slick/lib/slider.js:37:38)
      at Object.<anonymous> (node_modules/react-slick/lib/index.js:3:18)
      at Object.<anonymous> (node_modules/antd/lib/carousel/index.js:31:19)
      at Object.<anonymous> (src/App.js:2:17)
      at Object.<anonymous> (src/App.test.js:3:12)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.09s
Ran all test suites.
```

### What is expected?
Build successfully.

### What is actually happening?
Build failed.

---
I have tried add polyfill files descried here: [https://ant.design/docs/react/getting-started#Compatibility](https://ant.design/docs/react/getting-started#Compatibility). But it doesn't work for me.
Could anyone help me please or if you met any similar problems ever. Thanks a lot!

### PR DESCRIPTION
**Pull request by afc163**
close #6560

close #3308

close #7341

Make it works without testSetup.js.

### CODE REVIEW

File: components/carousel/index.tsx [hunk 1]
```diff
@@ -15,9 +16,11 @@ if (typeof window !== 'undefined') {
...
   window.matchMedia = window.matchMedia || matchMediaPolyfill;
 }
-
-import SlickCarousel from 'react-slick';
-import React from 'react';
+// Use require over import (will be lifted up)
+// make sure matchMedia polyfill run before require('react-slick')
+// Fix https://github.com/ant-design/ant-design/issues/6560
+// Fix https://github.com/ant-design/ant-design/issues/3308
+const SlickCarousel = require('react-slick').default;
```
Comment (afc163) [inline components/carousel/index.tsx]: trick code here
