### PR TITLE
style: fix Select baseline align bug

### LINKED ISSUE #44907: select样式问题
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-stfgz8)

### Steps to reproduce

select 组件的选择项是div元素的时候，展示的样式和之前不一样，元素会超出选择框

### What is expected?

不超出选择框

### What is actually happening?

超出了

| Environment | Info |
| --- | --- |
| antd | 5.9.1 |
| React | 18.2.0 |
| System | windows 10 |
| Browser | chrome 117 |

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/44907

ref https://github.com/antvis/L7VP/pull/28

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix Select style problem when `label` contains `div` element.         |
| 🇨🇳 Chinese |  修复 Select 当 `label` 内使用了 `div` 块级元素时的样式问题。         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 2f4e965</samp>

This pull request enhances the demos and fixes a bug related to the alignment of the `Input` and `Select` components. It adds titles and more cases to the `align` demo of the `Input` component, and improves the `option-label-center` demo of the `Select` component. It also fixes the baseline alignment of the single style of the `Select` component when the value is empty or undefined.

### <samp>🤖 Generated by Copilot at 2f4e965</samp>

*  Add titles for the align demo of the input component ([link](https://github.com/ant-design/ant-design/pull/44927/files?diff=unified&w=0#diff-2c6ed6c4e78c478ae953ef7fe49965734a1b52abe0d7b30ac09ae74c2eef2df6L1-R7))
*  Simplify and extend the select components in the align demo of the input component ([link](https://github.com/ant-design/ant-design/pull/44927/files?diff=unified&w=0#diff-64121df36812155affced4e25d63108d87be66393b84741ebec1255ad285952cR60-R64),[link](https://github.com/ant-design/ant-design/pull/44927/files?diff=unified&w=0#diff-64121df36812155affced4e25d63108d87be66393b84741ebec1255ad285952cL72-R79))
*  Fix and extend the select components in the option-label-center demo of the select component ([link](https://github.com/ant-design/ant-design/pull/44927/files?diff=unified&w=0#diff-05de49c151214d9ed1911d5c74659093c2f82e4c3be358d8b005d6a0b1c6acefL7-R7),[link](https://github.com/ant-design/ant-design/pull/44927/files?diff=unified&w=0#diff-05de49c151214d9ed1911d5c74659093c2f82e4c3be358d8b005d6a0b1c6acefL27-R45))
*  Fix the bug in the single style of the select component that caused the baseline alignment to be incorrect with empty or undefined values ([link](https://github.com/ant-design/ant-design/pull/44927/files?diff=unified&w=0#diff-d074c411bd6636664ae405c3b7a1744f68b0d236d82b2adbef155746711ec8a2L58-R60))

### CODE REVIEW

File: components/select/style/single.tsx [hunk 1]
```diff
@@ -55,9 +55,9 @@ function genSizeStyle(token: SelectToken, suffix?: string): CSSObject {
         [[
           '&:after',
           /* For '' value baseline align */
-          `${componentCls}-selection-item:after`,
+          `${componentCls}-selection-item:empty:after`,
           /* For undefined value baseline align */
-          `${componentCls}-selection-placeholder:after`,
+          `${componentCls}-selection-placeholder:empty:after`,
```
Comment (afc163) [inline components/select/style/single.tsx:60]: 在 components/input/demo/align.tsx 里补充了这两个样式的使用场景，发现只有 :empty 的时候是需要的。在其他情况下去掉可解决 https://github.com/ant-design/ant-design/issues/44907 的问题。

**Review by li-jia-nan — APPROVED** [review]

File: components/input/demo/align.tsx [hunk 2]
```diff
@@ -69,14 +73,9 @@ const App: React.FC = () => (
...
-      <Option value="jack">Jack</Option>
-      <Option value="lucy">Lucy</Option>
-      <Option value="disabled" disabled>
-        Disabled
-      </Option>
-      <Option value="Yiminghe">yiminghe</Option>
-    </Select>
+    <Select style={{ width: 100 }} defaultValue="jack" options={selectOptions} />
+    <Select style={{ width: 100 }} defaultValue="" options={selectOptions} />
+    <Select style={{ width: 100 }} options={selectOptions} />
```
Comment (Yuiai01) [inline components/input/demo/align.tsx:78]: 增加一个覆盖这个对应问题的 demo，比如 `{label: <div>Tes </div>, value: 'xxx'}` 会不会好些。

Comment (afc163) [reply components/input/demo/align.tsx:78]: https://github.com/ant-design/ant-design/pull/44927/files#diff-05de49c151214d9ed1911d5c74659093c2f82e4c3be358d8b005d6a0b1c6acef

这里有

**Review by zombieJ — APPROVED** [review]
