### PR TITLE
Table: fix showing only first page

### LINKED ISSUE #14723: Table - usage with ajax showing only first page
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/6v6zz3w3vr)

### Steps to reproduce
Select any other page than #1

### What is expected?
Fetched data are shown in table

### What is actually happening?
Table shows empty page

| Environment | Info |
|---|---|
| antd | 3.13.1 |
| React | 16.7.0 |
| System | Windows 10 17763 |
| Browser | Chrome 71.0.3578.98 |

---
Regression from 3.13.0 ( https://codesandbox.io/s/6lj9zp5omz ). Reproduction is the same code as in official documentation https://ant.design/components/table/#components-table-demo-ajax

### PR DESCRIPTION
**Pull request by imhele**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch.
Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

Fix #14723

### CODE REVIEW

**Comment by ycjcl868** [comment]
pull master.

File: components/table/Table.tsx [hunk 1]
```diff
@@ -1028,7 +1025,7 @@ export default class Table<T> extends React.Component<TableProps<T>, TableState<
     if (
       data.length > pageSize ||
       pageSize === Number.MAX_VALUE ||
-      current * pageSize > data.length
+      (typeof pagination.current === 'undefined' && current * pageSize > data.length)
```
Comment (zombieJ) [inline components/table/Table.tsx]: directly `pagination.current === undefined`

File: components/table/__tests__/Table.pagination.test.js [hunk 2]
```diff
@@ -190,5 +190,7 @@ describe('Table.pagination', () => {
     expect(renderedNames(wrapper)[0]).toEqual('Jack');
     wrapper.find('.ant-pagination-item-2').simulate('click');
     expect(renderedNames(wrapper)).toEqual([]);
+    wrapper.setProps({ pagination: { current: 1, pageSize: 10, total: 100 } });
+    expect(renderedNames(wrapper)[0]).toEqual('Jack');
```
Comment (zombieJ) [inline components/table/__tests__/Table.pagination.test.js]: Add another test case for this fix with different page.

File: components/table/Table.tsx (hunk 1 above)
Comment (imhele) [reply components/table/Table.tsx]: Oh, I'm used to writing like this to avoid `var undefined = 0`  from other scripts.

File: components/table/__tests__/Table.pagination.test.js (hunk 2 above)
Comment (imhele) [reply components/table/__tests__/Table.pagination.test.js]: 👌

**Comment by imhele** [comment]
What happened...

**Comment by zombieJ** [comment]
You can use `npm test -- --coverage` to check why the coverage down.

**Comment by arthur657834** [comment]
"antd": "^3.12.4",
"react": "^16.8.1",
"react-dom": "^16.8.1",
Table组件第二页以后可以加载出数据

"antd": "^3.13.2",
"react": "^16.8.1",
"react-dom": "^16.8.1",
Table组件第二页以后都加载不出数据

**Comment by imhele** [comment]
> "antd": "^3.12.4",
> "react": "^16.8.1",
> "react-dom": "^16.8.1",
> Table组件第二页以后可以加载出数据
> 
> "antd": "^3.13.2",
> "react": "^16.8.1",
> "react-dom": "^16.8.1",
> Table组件第二页以后都加载不出数据

我这里同样的版本没有发现问题，能给一下复现吗？

**Comment by andyyxw** [comment]
Unfortunately, I also met this problem in version `3.13.1` and `3.13.2`.

**Comment by zombieJ** [comment]
> Unfortunately, I also met this problem in version `3.13.1` and `3.13.2`.

Could you provide an online reproduce?

**Comment by wworrall** [comment]
Also facing this issue with version 3.13.2.

**Comment by ztplz** [comment]
@wworrall  Could you provide a online demo?

**Comment by Yuan-Zi-Yuan** [comment]
the problem still exists

**Comment by touring** [comment]
The problem still exists in version 3.13.2 @imhele

**Comment by ztplz** [comment]
@touring  Please provide a online demo, thanks!

**Comment by ztplz** [comment]
If your project still has similar problems:
1. Please check your `Antd` version, make sure you are not using `Antd 3.12.1`. 
2. Open a new issue with a online demo.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14875

**Comment by CesarDav** [comment]
the problem still persists

**Comment by yoyo837** [comment]
Feel free to open a new issue for that.  Thanks.
