### PR TITLE
fix: List grid not working in React.Fragment or wrapped List.Item

### LINKED ISSUE #24553: Broken Grid List styles when adding a component between List and List.Item
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/wild-hooks-95i3s?file=/src/App.tsx)

### Steps to reproduce
Use `List` in grid mode, and wrap `List.Item` in a component.

I have a large UI codebase which uses a lot of wrapper components around `List.Item` (to use item-level hooks for example...). This used to work fine in AntDesign 3. Using the grid mode, the new version 4 breaks the styles because [they are directly injected into `List.Item` using `cloneElement`](https://github.com/ant-design/ant-design/blob/master/components/list/index.tsx#L248).

### What is expected?
Styles should be applied via style sheets, not by element cloning which is not only an unlisted breaking change from v3 but also prohibits an easy use of component wrapper around `List.Item` (without forwarding props).

### What is actually happening?
Styles are broken. The grid layout doesn't render correctly.

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | react 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 81.0.4044.138 |

### LINKED ISSUE #24828: 4.x 版本将 List.Item 包装成组件会导致响应式栅格列表无法正常显示， 3.x 版本没有问题
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/admiring-cerf-kiw7j?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
4.x 版本将 `List.Item` 包装成组件会导致响应式栅格列表无法正常显示，之前 3.x 版本的时候这样使用没有问题的

#### 4.x 版本
[Edit admiring-cerf-kiw7j](https://codesandbox.io/s/admiring-cerf-kiw7j?fontsize=14&hidenavigation=1&theme=dark)

显示效果:
4 x

#### 3.x 版本
[Edit upbeat-goldberg-ueme0](https://codesandbox.io/s/upbeat-goldberg-ueme0?fontsize=14&hidenavigation=1&theme=dark)

显示效果:
3 x

### What is expected?
ant-col 自动根据浏览器宽度自动加上 width 和 max-width 属性

### What is actually happening?
ant-col  width 和 max-width 属性缺失

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.12 |
| System | win10 |
| Browser | chrome |

本来在这个 [issue](https://github.com/ant-design/ant-design/issues/24553) 里面增加了说明，几天没有看到答复所以单独提了 issue

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #24553
close #24828

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix List `grid` not working in React.Fragment or wrapped List.Item |
| 🇨🇳 Chinese | 修复 List `grid` 属性在 React.Framgment 或者封装了的 List.Item 上失效的问题。  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

-----
[View rendered components/list/demo/grid-test.md](https://github.com/ant-design/ant-design/blob/list/components/list/demo/grid-test.md)

### CODE REVIEW

**Comment by joelschou** [comment]
Hi. I'm not sure the best way to report this, but I'm fairly sure this PR represents a regression in how list items are displayed when in grid mode. By [wrapping](https://github.com/ant-design/ant-design/pull/24955/files#diff-01734310e1b0bfd2999f0252c3fbe593R252) the `{child}` element in a `<div>` the element with className `ant-col` is no longer a direct child of `ant-row`. As a result, the columns do not stretch to being the same height. This can be easily seen by editing the grid demo in a browser web inspector to give one list longer content:

image

File: components/list/index.tsx [hunk 1]
```diff
@@ -249,23 +248,15 @@ function List<T>({
...
-              key: keys[index],
-              colStyle,
-            }
-          : {
-              key: keys[index],
-            },
-      ),
-    );
+    const childrenList = React.Children.map(items, (child: any, index) => (
+      <div key={keys[index]} style={colStyle}>
```
Comment (joelschou) [inline components/list/index.tsx:252]: This is the regression I mentioned in [my comment](https://github.com/ant-design/ant-design/pull/24955#issuecomment-663578997).

**Comment by JaKXz** [comment]
I think @joelschou is correct, has this been fixed in any future patches?
