### PR TITLE
fix(notification): placement bottom animation should be correct

### LINKED ISSUE #44919: notification 底部弹出动画有问题
### Reproduction link

[https://ant.design/components/notification-cn#notification-demo-placement](https://ant.design/components/notification-cn#notification-demo-placement)

### Steps to reproduce

多次点击 bottom

### What is expected?

每点击一次，只有新出来的有动画，而不是全部都是最底下再弹出来

### What is actually happening?

每点击一次，全部都从底部再重新弹出来

| Environment | Info |
| --- | --- |
| antd | 5.9.1 |
| React | lastest |
| System | mac |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by linxianxi**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix https://github.com/ant-design/ant-design/issues/44919

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix the bug of pop-up animation at the bottom of notification      |
| 🇨🇳 Chinese |   修复 notification 底部弹出动画的问题        |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 572dd72</samp>

This pull request enhances the notification component by using `transform` for smoother animation and fixing a minor style issue in `placement.ts`.

### <samp>🤖 Generated by Copilot at 572dd72</samp>

* Improve performance and fix bug of notification component when placed at the bottom of the screen by using transform instead of margin for animation ([link](https://github.com/ant-design/ant-design/pull/44918/files?diff=unified&w=0#diff-da4d2980e968bf7ec54db139303120e6105d73f3d214f60e9f5feec3b9c60dbdL23-R29))
* Format `components/notification/style/placement.ts` by adding an empty line at the beginning of the file ([link](https://github.com/ant-design/ant-design/pull/44918/files?diff=unified&w=0#diff-da4d2980e968bf7ec54db139303120e6105d73f3d214f60e9f5feec3b9c60dbdR3))

### CODE REVIEW

**Comment by MadCcc** [comment]
看下 feature 上怎么写的吧，感觉会有冲突

**Review by kiner-tang — APPROVED** [review]

File: components/notification/style/placement.ts [hunk 1]
```diff
@@ -1,10 +1,11 @@
 import type { CSSObject } from '@ant-design/cssinjs';
 import { Keyframes } from '@ant-design/cssinjs';
+
 import type { NotificationToken } from '.';
 import type { GenerateStyle } from '../../theme/internal';
 
 const genNotificationPlacementStyle: GenerateStyle<NotificationToken, CSSObject> = (token) => {
-  const { componentCls, width, notificationMarginEdge } = token;
+  const { componentCls, width, notificationMarginEdge, animationMaxHeight } = token;
```
Comment (MadCcc) [inline components/notification/style/placement.ts:8]: lint broken

**Review by MadCcc — APPROVED** [review]
