### PR TITLE
fix: Typography error on context ellipsis

### LINKED ISSUE #33126: ellipsis Suffix lost React Context
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/ji-ben-antd-4-17-2-forked-o03us?file=/index.js)

### Steps to reproduce
- open codesandbox

### What is expected?
no error

### What is actually happening?
lost context

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | any |
| System | any |
| Browser | any |

---
https://github.com/ant-design/ant-design/blob/441eb649bd7c7609fffd960c29e1b999361f1e4e/components/typography/util.tsx#L110

ellipsis suffix create a clone element but not in original component tree, so react context is lost, suggest change to React Portal

### LINKED ISSUE #33450: TextArea 设置 autoSize 抖动
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-qgbdd4](https://stackblitz.com/edit/react-qgbdd4)

### Steps to reproduce
-

### What is expected?
不抖动

### What is actually happening?
抖动

| Environment | Info |
|---|---|
| antd | 4.18.0 |
| React | latest |
| System | mac |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #33450
resolve #33126

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Refactor Typography `ellipsis` logic to fix error when `children` use Context content.        |
| 🇨🇳 Chinese |  重构 Typography `ellipsis` 逻辑以修复 `children` 如果消费上游 Context 会报错的问题。.         |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/typography/Base/Ellipsis.tsx [hunk 1]
```diff
@@ -0,0 +1,211 @@
...
+
+  // ======================== Walk ========================
+  React.useLayoutEffect(() => {
+    if (enabledMeasure && width && totalLen) {
+      setWalkingState(PREPARE);
+      setCutLength([0, Math.ceil(totalLen / 2), totalLen]);
+    }
+  }, [enabledMeasure, width, text, totalLen, rows]);
+
+  React.useLayoutEffect(() => {
```
Comment (SoYoung210) [inline components/typography/Base/Ellipsis.tsx:103]: useLayoutEffect generates the following warning in the SSR environment.

Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format.

Can you consider the SSR environment without directly using useLayoutEffect in the antd and react-component packages?

Reference:
https://github.com/andarist/use-isomorphic-layout-effect/blob/master/src/index.ts

Comment (SoYoung210) [reply components/typography/Base/Ellipsis.tsx:103]: @zombieJ

Comment (ngmiduc) [reply components/typography/Base/Ellipsis.tsx:103]: I see the change but somehow React is still complaining about the useLayoutEffect at `line77` on file: 
`webpack-internal:///./node_modules/antd/lib/typography/Base/Ellipsis.js`
