### PR TITLE
fix: fix divider component innerStyle style error

### LINKED ISSUE #42796: A style bug about Drivider component
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/dai-wen-zi-de-fen-ge-xian-antd-5-5-2-forked-9liceo?file=/demo.tsx)

### Steps to reproduce

```tsx
     {/** Working */}  
    <Divider orientation="right" orientationMargin={20}>
       text number 20
    </Divider>

    {/** Not Working */}
    <Divider orientation="right" orientationMargin="20">
      text string 20
    </Divider>
```

### What is expected?

> Their children's style shoule be same.

```html
<span class="ant-divider-inner-text" style="margin-right: 20px;">text string 20</span>
```

### What is actually happening?

```html
<span class="ant-divider-inner-text">text string 20</span>
```

| Environment | Info |
| --- | --- |
| antd | 5.5.2 |
| React | 18.2.0 |
| System | Windows |
| Browser | Google Version 113.0.5672.64 |

### PR DESCRIPTION
**Pull request by kongmingLatern**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

- fix #42796  

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix divider component's style error  |
| 🇨🇳 Chinese |  修复Divider组件的样式问题        |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### 🚀 Summary

I use a `toNumber` function to convert  string into number to make sure Divider's innerStyle can operate normally.

```tsx

// Type Define
export interface DividerProps {
  ...
  orientationMargin?: string | number;
 ...
}
// Before
 const innerStyle: React.CSSProperties = {
    ...(hasCustomMarginLeft && { marginLeft: orientationMargin  }), // orientationMargin may be string,
    ...(hasCustomMarginRight && { marginRight: orientationMargin  }),
  };

// Fix
 const innerStyle: React.CSSProperties = {
  ...(hasCustomMarginLeft && { marginLeft: toNumber() }),
  ...(hasCustomMarginRight && { marginRight: toNumber() }),
};

function toNumber() {
    return typeof orientationMargin === 'string' ? Number(orientationMargin) : orientationMargin;
}
```

### CODE REVIEW

**Comment by BoyYangzai** [comment]
https://github.com/ant-design/ant-design/pull/42797/checks?check_run_id=13964527995
lint error

File: components/divider/index.tsx [hunk 1]
```diff
@@ -80,6 +80,10 @@ const Divider: React.FC<DividerProps> = (props) => {
       )}
     </div>,
   );
+
+  function toNumber() {
+    return typeof orientationMargin === 'string' ? Number(orientationMargin) : orientationMargin;
```
Comment (BoyYangzai) [inline components/divider/index.tsx:85]: 直接强制转换 会导致 '20px' 这种写法无法使用

File: components/divider/index.tsx [hunk 2]
```diff
@@ -57,13 +57,23 @@ const Divider: React.FC<DividerProps> = (props) => {
     rootClassName,
   );
 
-  function toNumber() {
-    return typeof orientationMargin === 'string' ? Number(orientationMargin) : orientationMargin;
+  function convertToNumberIfPureNumber(str: string) {
+    if (/^\d+$/.test(str)) {
+      return Number(str);
+    } else {
```
Comment (BoyYangzai) [inline components/divider/index.tsx:63]: lint error

Comment (kongmingLatern) [reply components/divider/index.tsx]: Fix it

**Review by BoyYangzai — APPROVED** [review]

File: components/divider/index.tsx [hunk 3]
```diff
@@ -57,9 +57,22 @@ const Divider: React.FC<DividerProps> = (props) => {
...
   );
 
+  function convertToNumberIfPureNumber(str: string) {
+    if (/^\d+$/.test(str)) {
+      return Number(str);
+    }
+    return str;
+  }
+
+  function convertToNumberOrReturn() {
```
Comment (li-jia-nan) [inline components/divider/index.tsx:67]: 感觉一个函数就可以了，好像没必要封装两个：

```ts
const memoizedOrientationMargin = React.useMemo<string | number>(() => {
  if (typeof orientationMargin === 'number') {
    return orientationMargin;
  }
  if (/^\d+$/.test(orientationMargin!)) {
    return Number(orientationMargin);
  }
  return orientationMargin!;
}, []);
```

Comment (li-jia-nan) [reply components/divider/index.tsx:67]: 另外文档可以补充一下：如果传入 string 类型的数字并且不带单位的话，默认单位是 px

Comment (kongmingLatern) [reply components/divider/index.tsx]: Ok

File: components/divider/index.tsx [hunk 4]
```diff
@@ -82,8 +92,4 @@ const Divider: React.FC<DividerProps> = (props) => {
   );
 };
 
-if (process.env.NODE_ENV !== 'production') {
```
Comment (li-jia-nan) [inline components/divider/index.tsx:85]: 这个为啥要删掉？

Comment (kongmingLatern) [reply components/divider/index.tsx]: 不好意思😂，可能是我vim编辑的时候不小心删掉了，补上了

**Comment by li-jia-nan** [comment]
麻烦再补充个测试用例吧

**Review by li-jia-nan — APPROVED** [review]

**Comment by li-jia-nan** [comment]
> 麻烦再补充个测试用例吧

- #42800
