### PR TITLE
Fix changing the count of a badge with border-color raises an error

### LINKED ISSUE #14516: Changing the count of a badge with border-color raises an error
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/oxrl1zz349)

### Steps to reproduce
1. Have a Badge with a custom border-color
2. Change the count of the badge

### What is expected?
Badge count is changed

### What is actually happening?
"TypeError: Attempted to assign to readonly property." is thrown

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | React 16.7.0 |
| System | MacOS Mojave |
| Browser | Chrome 71.0.3578.98 |

### PR DESCRIPTION
**Pull request by ztplz**
First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch.
Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
Fix https://github.com/ant-design/ant-design/issues/14516
> 3. Related issue link.
https://github.com/ant-design/ant-design/issues/14516
  
### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
Fix the problem that changing the count of a badge with border-color will raises an `property readonly` error
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

### CODE REVIEW

**Comment by ztplz** [comment]
image
这里要加个类型  
image
这样只是强行把定义的这个定型符合props的类型

File: components/badge/ScrollNumber.tsx [hunk 1]
```diff
@@ -169,7 +169,13 @@ export default class ScrollNumber extends Component<ScrollNumberProps, ScrollNum
...
     // <Badge count={4} style={{ backgroundColor: '#fff', color: '#999', borderColor: '#d9d9d9' }} />
     if (style && style.borderColor) {
-      newProps.style.boxShadow = `0 0 0 1px ${style.borderColor} inset`;
+      newProps = {
+        ...newProps,
+        style: {
+          ...style,
+          boxShadow: `0 0 0 1px ${style.borderColor} inset`,
+        },
+      };
```
Comment (zombieJ) [inline components/badge/ScrollNumber.tsx]: 简化一下： 
```jsx
newProps.style = {
  ...newProps.style,
  boxShadow: `0 0 0 1px ${style.borderColor} inset`,
}
```

**Comment by ztplz** [comment]
Done.
