### PR TITLE
fix: Modal static func

### LINKED ISSUE #47007: Modal.confirm motion missing
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/ji-ben-antd-5-13-1-forked-sss5gc?file=%2Fpackage.json%3A10%2C20)

5.12.x work as expect: https://codesandbox.io/p/sandbox/ji-ben-antd-5-13-1-forked-v393kd?file=%2Fpackage.json%3A6%2C34

### Steps to reproduce

1. 设置 CP 的 `prefixCls`
2. 当先有 Modal 组件时，会创建对应样式并且记录 key path 到 cache 中。
3. 调用 Modal.confirm 并且设 `prefixCls` 对应于 CP 的 `prefixCls`，由于静态方法的 key path 相同，会命中缓存而略过。
4. 但是通过组件的 prefixCls 创建的样式，和 CP prefixCls 创建的样式并不相同，导致静态方法创建的样式丢失。

### What is expected?

Closable

### What is actually happening?

Not Closable

| Environment | Info |
| --- | --- |
| antd | 5.13.1 |
| React | latest |
| System | IOS |
| Browser | chrome |

---

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #47007

### 💡 Background and solution

`Modal.confirm` 的 `prefixCls`不应该作为 `rootPrefixCls` 生效，导致 CSSINJS Cache 命中策略失效 以及 子元素 `prefixCls` break change。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix Modal static function with `prefixCls` breaks children other component `prefixCls` and thus bring the motion miss.      |
| 🇨🇳 Chinese |  修复 Modal 静态方法配置 `prefixCls`  时，会改变所有子元素的 `prefixCls` 并导致动画丢失的问题。       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

**Review by kiner-tang — APPROVED** [review]

File: components/modal/confirm.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ const ConfirmDialogWrapper: React.FC<ConfirmDialogProps> = (props) => {
   const runtimeLocale = getConfirmLocale();
 
   const config = useContext(ConfigContext);
-  const rootPrefixCls = customizePrefixCls || getRootPrefixCls() || config.getPrefixCls();
```
Comment (yoyo837) [inline components/modal/confirm.tsx:32]: 这个位置是否应该留个注释？

Comment (zombieJ) [reply components/modal/confirm.tsx:32]: 感觉是不需要，毕竟 antd 里所有的 customizePrefixCls 都代表的是组件自身的 prefixCls
