### PR TITLE
fix: remove pointer-events: 'none' for disabled items in date-picker panel

### LINKED ISSUE #51293: Tooltips/Popovers/etc don't work inside disabled date picker cells
### Reproduction link

[Edit on StackBlitz](https://stackblitz.com/edit/vitejs-vite-dxuv9j?file=package.json,src%2FApp.tsx,src%2Findex.css&terminal=dev)

### Steps to reproduce

Hover over any date and you'll see the tooltip, unless the date is disabled

### What is expected?

The tooltip should be visible for all cells

### What is actually happening?

The tooltip is not visible for disabled cells

| Environment | Info |
| --- | --- |
| antd | 5.21.4 |
| React | latest |
| System | Mac OSX |
| Browser | Firefox 131.0.3 |

---
This is because pointer-events: none on `ant-picker-cell-disabled`

### PR DESCRIPTION
**Pull request by ajenkins-mparticle**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [x] 🆕 New feature
- [x] 🐞 Bug fix

### 🔗 Related Issues

Closes https://github.com/ant-design/ant-design/issues/51293

### 💡 Background and Solution

> Tooltips/Popovers were non-functional when used inside `cellRender` if an item was disabled via `disabledDate`
> Remove `pointer-events: none` from the style of disabled items and adjust hover styles accordingly.

### 📝 Change Log

> Allows usage of Tooltips/Popovers inside of `cellRender` for disabled items.

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fixes inability to use Tooltip/Popover inside `cellRender` when dealing with disabled dates |
| 🇨🇳 Chinese | 修复了处理禁用日期时无法在 `cellRender` 内使用 Tooltip/Popover 的问题  |

### CODE REVIEW

File: components/date-picker/style/panel.ts [hunk 1]
```diff
@@ -124,7 +124,7 @@ const genPickerCellInnerStyle = (token: SharedPickerToken): CSSObject => {
     // >>> Disabled
     '&-disabled': {
       color: colorTextDisabled,
-      pointerEvents: 'none',
+      cursor: 'default',
```
Comment (ajenkins-mparticle) [inline components/date-picker/style/panel.ts:127]: Arguably could change to `not-allowed`

Comment (afc163) [inline components/date-picker/style/panel.ts:127]:
```suggestion
      cursor: 'not-allowed',
```

**Review by afc163 — APPROVED** [review]
