### PR TITLE
fix: Input click should get focus

### LINKED ISSUE #21412: 4.0 Input will affix can not click to get focus
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/input-cn/#components-input-demo-presuffix](https://next.ant.design/components/input-cn/#components-input-demo-presuffix)

### Steps to reproduce
Click border

### What is expected?
focus

### What is actually happening?
not focus

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.5 |
| React | latest |
| System | IOS |
| Browser | chrome |

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix #21412

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix Input click with `prefix` / `suffix` not get focused.      |
| 🇨🇳 Chinese |   修复 Input 点击 `prefix` / `suffix` 不会获得焦点的问题。       |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/input/Input.tsx [hunk 1]
```diff
@@ -273,6 +273,7 @@ class Input extends React.Component<InputProps, InputState> {
             ref={this.saveClearableInput}
             direction={direction}
             focused={focused}
+            triggerFocus={this.focus}
```
Comment (afc163) [inline components/input/Input.tsx]: 应该命名 onFocus 比较好

**Review by afc163 — APPROVED** [review]

File: components/input/Input.tsx (hunk 1 above)
Comment (zombieJ) [reply components/input/Input.tsx]: 这个是外侧 `span` 触发 `onMouseUp` 后，调用 input `focus` 。它本身不是 `onFocus` 事件。
