### PR TITLE
fix: fix Message component icon style

### LINKED ISSUE #40467: message 内 icon 颜色被错误的指定
### Reproduction link

image

[Edit on CodeSandbox](https://codesandbox.io/s/qi-ta-ti-shi-lei-xing-antd-5-1-6-forked-snyxgy?file=/demo.tsx)

### Steps to reproduce

点击 error 按钮

### What is expected?

在消息中，仅 IconError 为红色，其余 icon 还是默认颜色（注：此处应该 inherit 自 Typography.Link 的蓝色）

### What is actually happening?

错误指定了其他 icon 的颜色

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 18 |
| System | macOS 11.7(M1) |
| Browser | Chrome 108 |

### PR DESCRIPTION
**Pull request by Wxh16144**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #40467 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     fix `<Message />` component icon style      |
| 🇨🇳 Chinese |     修复  `<Message />` 组件图标样式      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/message/style/index.tsx [hunk 1]
```diff
@@ -135,15 +135,15 @@ const genMessageStyle: GenerateStyle<MessageToken> = (token) => {
         [`${componentCls}-success ${iconCls}`]: {
```
Comment (dancerphil) [inline components/message/style/index.tsx:135]: 这是漏了 success 么？

Comment (Wxh16144) [reply components/message/style/index.tsx]: 感谢提醒~，resolved

**Review by MadCcc — APPROVED** [review]
