### PR TITLE
fix(Cascader): Should show not found content when options.length is 0

### LINKED ISSUE #17513: Cascader notFoundContent not work?
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/antd-cascader-t36v3)

### Steps to reproduce
```
<Cascader options={[]} />
```

### What is expected?
notFoundContent hint like Select.

### What is actually happening?
no notFoundContent hint.

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.9.0 |
| System | windows 7 |
| Browser | Chrome Version 75.0.3770.100 |

### PR DESCRIPTION
**Pull request by dengfuping**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

- Close #17513.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | 🐞 Fix Cascader's notFoundContent not showing when options' length is 0. #17513 |
| 🇨🇳 Chinese | 🐞 修复 Cascader 组件在 options 为空时不展示空内容的问题。#17513 |

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/cascader/index.tsx [hunk 1]
```diff
@@ -493,8 +494,19 @@ class Cascader extends React.Component<CascaderProps, CascaderState> {
...
 
     let options = props.options;
-    if (state.inputValue) {
-      options = this.generateFilteredOptions(prefixCls, renderEmpty);
+    if (options.length > 0) {
+      if (state.inputValue) {
+        options = this.generateFilteredOptions(prefixCls, renderEmpty);
+      }
+    } else {
+      const names: FilledFieldNamesType = getFilledFieldNames(this.props);
```
Comment (ztplz) [inline components/cascader/index.tsx]: 已经返回这个类型了 不需要再指定了

**Review by ztplz — APPROVED** [review]

**Review by zombieJ — APPROVED** [review]
