### PR TITLE
fix(Table): table pagination.align should be working

### LINKED ISSUE #55305: Table配置pagination  align:center 不生效
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/xuan-ze-he-cao-zuo-antd-5-27-4-forked-gx58j3?file=%2Fdemo.tsx%3A48%2C1)

### Steps to reproduce

1、Tabel的pagination设置 align: "center" 

### What is expected?

align生效

### What is actually happening?

align不生效

| Environment | Info |
| --- | --- |
| antd | 5.27.4 |
| React | 18.0.0 |
| System | mac |
| Browser | chrom |

### PR DESCRIPTION
**Pull request by afc163**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

close https://github.com/ant-design/ant-design/issues/55305

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

统一用 Pagination 的 `align` 属性来配置位置，避免 Table 单独实现一套。

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)! Track your changes, like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Table `pagination.align` is not working.<br /> Pagination now automatically wraps when it overflows.     |
| 🇨🇳 Chinese |  修复 Table `pagination.align` 属性失效的问题。<br /> Pagination 现在在空间不足时会自动换行。         |

### CODE REVIEW

File: components/pagination/style/index.ts [hunk 1]
```diff
@@ -616,6 +616,7 @@ const genPaginationStyle: GenerateStyle<PaginationToken, CSSObject> = (token) =>
     [componentCls]: {
       ...resetComponent(token),
       display: 'flex',
+      flexWrap: 'wrap',
```
Comment (afc163) [inline components/pagination/style/index.ts:619]:
```suggestion
      flexWrap: 'wrap',
      rowGap: token.paddingXS,
```

**Review by meet-student — APPROVED** [review]

**Comment by thinkasany** [comment]
冲突太大了，不太好同步到 next，需要老板再操作一次
