### PR TITLE
fix(Typography): button with href wrapped by Typography showing incorrect color and flickering outline on hover

### LINKED ISSUE #56606: Some issues with document websites
### Reproduction link

[https://ant.design/](https://ant.design/)

### Steps to reproduce

1.  首页时中切英国际化失效 \ 需要去其他页面切换再回来

Image

2. 更新日志样式 与 5.0.0 不一致 hover 有抖动

Image

### What is expected?

- 首页时中切英国际化正常
- 更新日志样式 正常

### What is actually happening?

效果不符合预期

| Environment | Info |
| --- | --- |
| antd | 6.2.0 |
| React | 19.0 |
| System | Mac |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by QdabuliuQ**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

close #56606

### 💡 Background and Solution
Fix Typography link styles conflicting with Button component by adding style exclusions.

### 📝 Change Log
| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Button with href wrapped by Typography showing incorrect color and flickering outline on hover |
| 🇨🇳 Chinese | 修复被 Typography 包裹的带 href 的 Button 显示错误颜色和 hover 时 outline 闪烁的问题 |

### CODE REVIEW

File: components/typography/style/mixins.ts [hunk 1]
```diff
@@ -54,13 +54,33 @@ export const getTitleStyles: GenerateStyle<TypographyToken, CSSObject> = (token)
...
+        outline: 'none !important',
+        '&:hover, &:focus, &:active': {
+          color: 'unset',
+          textDecoration: 'unset',
+          border: 'none !important',
+          outline: 'none !important',
+        },
+        '&:focus-visible': {
+          border: 'none !important',
+          outline: 'none !important',
```
Comment (afc163) [inline components/typography/style/mixins.ts]: 不要加这么多 !important，味道不好。

**Comment by afc163** [comment]
看看是哪里改坏的，找原因，不叠 buffer

File: components/typography/style/mixins.ts (hunk 1 above)
Comment (QdabuliuQ) [reply components/typography/style/mixins.ts]: 好的

**Comment by afc163** [comment]
看下 visual diff 是否符合预期，我感觉好像不太对。

**Comment by meet-student** [comment]
image

颜色不对, 和 v5 场景在 typography 下的 button 色值不一致

**Review by meet-student — APPROVED** [review]

**Comment by QdabuliuQ** [comment]
这个什么时候可以合呀 😊

**Review by afc163 — APPROVED** [review]
