### PR TITLE
type: Alert.ErrorBoundary type issue with @type/react@18

### LINKED ISSUE #52213: 'Alert.ErrorBoundary' cannot be used as a JSX component.
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jyh2k9)

### Steps to reproduce

使用最新的vite react-ts模板（node 22.12.0）
安装antd，放入<Alert.ErrorBoundary/>组件
运行tsc -b

### What is expected?

返回0

### What is actually happening?

```
src/App.tsx:7:8 - error TS2786: 'Alert.ErrorBoundary' cannot be used as a JSX component.
  Its type 'typeof ErrorBoundary' is not a valid JSX element type.
    Type 'typeof ErrorBoundary' is not assignable to type 'new (props: any, deprecatedLegacyContext?: any) => Component<any, any, any>'.
      Construct signature return types 'ErrorBoundary' and 'Component<any, any, any>' are incompatible.
        The types returned by 'render()' are incompatible between these types.
          Type 'string | number | bigint | boolean | Element | Iterable<ReactNode> | Promise<string | number | bigint | boolean | ReactPortal | Iterable<ReactNode> | ReactElement<...> | null | undefined> | null | undefined' is not assignable to type 'ReactNode'.
            Type 'bigint' is not assignable to type 'ReactNode'.

7       <Alert.ErrorBoundary/>
         ~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

| Environment | Info |
| --- | --- |
| antd | 5.22.7 |
| React | 18.3.1 |
| System | Windows 11 |
| Browser | 无 |

---
package.json
```
"dependencies": {
    "antd": "^5.22.7",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@eslint/js": "^9.17.0",
    "@types/react": "^18.3.18",
    "@types/react-dom": "^18.3.5",
    "@vitejs/plugin-react": "^4.3.4",
    "eslint": "^9.17.0",
    "eslint-plugin-react-hooks": "^5.0.0",
    "eslint-plugin-react-refresh": "^0.4.16",
    "globals": "^15.14.0",
    "typescript": "~5.6.2",
    "typescript-eslint": "^8.18.2",
    "vite": "^6.0.5"
  }
```

### PR DESCRIPTION
**Pull request by afc163**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [ ] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [x] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

close https://github.com/ant-design/ant-design/issues/52213

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Alert.ErrorBoundary type error when used as a JSX component with `@types/react@18.x`.        |
| 🇨🇳 Chinese | 修复 Alert.ErrorBoundary 在 `@types/react@18.x` 中无法作为 JSX 组件使用的类型错误问题。          |

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

File: components/alert/ErrorBoundary.tsx [hunk 1]
```diff
@@ -44,7 +44,7 @@ class ErrorBoundary extends React.Component<ErrorBoundaryProps, ErrorBoundarySta
             <pre style={{ fontSize: '0.9em', overflowX: 'auto' }}>{errorDescription}</pre>
           }
         />
-      );
+      ) as React.ReactNode;
```
Comment (afc163) [inline components/alert/ErrorBoundary.tsx:47]: 避免转译成 https://unpkg.com/antd@5.24.0/lib/alert/ErrorBoundary.d.ts 这样。

```
    render(): string | number | bigint | boolean | Iterable<React.ReactNode> | Promise<string | number | bigint | boolean | React.ReactPortal | React.ReactElement<unknown, string | React.JSXElementConstructor<any>> | Iterable<React.ReactNode> | null | undefined> | React.JSX.Element | null | undefined;
``
