### PR TITLE
fix: unable to close modal when using visible in Modal.confirm().update

### LINKED ISSUE #37461: Modal.confirm().update 之后无法关闭modal
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/ji-ben-antd-4-23-0-forked-fj57gx?file=/demo.js)

### Steps to reproduce

点击show modal, 然后点击关Cancel

### What is expected?

希望能正确关闭modal

### What is actually happening?

没有关闭modal

| Environment | Info |
| --- | --- |
| antd | 4.23.0 |
| React | 16.14.0 |
| System | mac 10.15.7 |
| Browser | chrome 104.0.5112.79 |

### PR DESCRIPTION
**Pull request by Aaron674092290**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix #37461

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      fix: unable to close modal when using visible in Modal.confirm().update     |
| 🇨🇳 Chinese |    修复Modal.confirm().update({visible: true}) 导致无法关闭modal的问题      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/modal/confirm.tsx [hunk 1]
```diff
@@ -65,6 +72,7 @@ export default function confirm(config: ModalFuncProps) {
       reactRender(
         <ConfirmDialog
           {...props}
+          open={open ?? visible}
```
Comment (Aaron674092290) [inline components/modal/confirm.tsx:75]: 这样再次点击展现modal是展示不出来的，一直用的是open，但是第二次点击的时候open一直都是false

Comment (zombieJ) [reply components/modal/confirm.tsx:75]: > 这样再次点击展现modal是展示不出来的，一直用的是open，因为第二次点击的时候open一直都是false @zombieJ

关闭后实体就清除了，再次打开是新的实体。给重现看看？

Comment (zombieJ) [reply components/modal/confirm.tsx:75]: 哦，get 了。复用同一个 Confirm。
