### PR TITLE
fix: textarea reset style

### LINKED ISSUE #39099: [Input.TextArea]: resize 不为 none 时 close 和 feedback 图标样式问题
### Reproduction link

[https://ant.design/~demos/components-form-demo-validate-static](https://ant.design/~demos/components-form-demo-validate-static)

### Steps to reproduce

调整文本域宽度即可复现

### What is expected?

close 和 feedback 图标在文本域内

### What is actually happening?

close 和 feedback 图标在文本域外

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | 18.2.0 |
| System | MACOS 12.1 |
| Browser | chrome 107.0.5304.121 |

---
4.x 版本的文本域仅支持高度调整所以没有这个问题，5.x 版本同时支持了高度和宽度的调整

image

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [x] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #39099
close #39113

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix Input.TextArea resize behavior by adding reset style.        |
| 🇨🇳 Chinese |  修复 Input.TextArea 没有重置样式导致 resize 行为和 4.x 不一致的问题。         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/input/style/index.tsx [hunk 1]
```diff
@@ -180,12 +180,7 @@ export const genBasicInputStyle = (token: InputToken): CSSObject => ({
     lineHeight: token.lineHeight,
     verticalAlign: 'bottom',
     transition: `all ${token.motionDurationSlow}, height 0s`,
-  },
-
-  '&-textarea': {
-    '&-rtl': {
-      direction: 'rtl',
-    },
+    resize: 'vertical',
```
Comment (zombieJ) [inline components/input/style/index.tsx:183]: 居然这么细。。。

**Review by zombieJ — APPROVED** [review]
