### PR TITLE
fix: make closeIcon in useNotification work (#52494)

### LINKED ISSUE #52494: useNotification config does not accept "closeIcon"
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/hooks-usage-recommended-antd-5-23-1-forked-qq975z?file=%2Fdemo.tsx%3A22%2C5-22%2C8)

### Steps to reproduce

Add closeIcon=null to config of useNotification.

### What is expected?

The hook notification сloseIcon is missing.

### What is actually happening?

CloseIcon into config of useNotification has no effect.

| Environment | Info |
| --- | --- |
| antd | 5.23.1 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Google Chrome |

### PR DESCRIPTION
**Pull request by typenoob**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues
fix #52494

### 💡 Background and Solution

- `closeIcon` is configured by `notification.success(config)`
- `notificationConfig.closeIcon` is configured by `notification.useNotification(config)`
- `notification.closeIcon` is configured by `ConfigProvider`
When compute `realCloseIcon`, take `closeIcon` as the first choice, `notificationConfig.closeIcon` as the second choice, and `notification.closeIcon` as the third choice.

This is a work ground, and I think it'd be better to refactor logic of notification configuration. 

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix closeIcon config not work in useNotification |
| 🇨🇳 Chinese |   修复useNotification中closeIcon配置无效的问题 |

### CODE REVIEW

File: components/notification/useNotification.tsx [hunk 1]
```diff
@@ -158,7 +158,11 @@ export function useInternalNotification(
 
       const realCloseIcon = getCloseIcon(
         noticePrefixCls,
-        typeof closeIcon !== 'undefined' ? closeIcon : notification?.closeIcon,
+        typeof closeIcon !== 'undefined'
+          ? closeIcon
+          : typeof notificationConfig?.closeIcon !== 'undefined'
+            ? notificationConfig?.closeIcon
+            : notification?.closeIcon,
```
Comment (afc163) [inline components/notification/useNotification.tsx:165]: 三元混用，味道挺差的。

Comment (afc163) [inline components/notification/useNotification.tsx:165]:
```suggestion
        closeIcon ?? notificationConfig?.closeIcon ?? notification?.closeIcon
```

Comment (typenoob) [reply components/notification/useNotification.tsx:165]:
```
      const {
        message,
        description,
        icon,
        type,
        btn,
        className,
        style,
        role = 'alert',
        closable,
        ...restConfig
      } = config;

      const closeIcon = typeof config.closeIcon !== 'undefined' ? config.closeIcon : notificationConfig?.closeIcon

      const realCloseIcon = getCloseIcon(
        noticePrefixCls,
        typeof closeIcon !== 'undefined' ? closeIcon : notification?.closeIcon,
      );
```
这样和提取函数，您觉得哪种更好？

Comment (afc163) [reply components/notification/useNotification.tsx:165]: 提函数，render 里干净点。

Comment (typenoob) [reply components/notification/useNotification.tsx:165]: 函数放在util.ts中 是吗

**Review by afc163 — DISMISSED** [review]

**Review by afc163 — APPROVED** [review]
