### PR TITLE
style: fix Typography.Text lost right border when text is ellipsis

### LINKED ISSUE #40261: Typography.Text code ellipsis 丢失右边框
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/sheng-lue-hao-antd-5-1-5-forked-1gog5y?file=/demo.tsx)

### Steps to reproduce

开启 ellipsis Switch

### What is expected?

Typography.Text code 有完整的边框
image

### What is actually happening?

Typography.Text code 丢失右边框
image

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | 18.2.0 |
| System | macOS 12.4 |
| Browser | 108.0.5359.98 |

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/40261
close https://github.com/ant-design/ant-design/pull/40503
close https://github.com/ant-design/ant-design/pull/40967
close https://github.com/ant-design/ant-design/pull/41005

### 💡 Background and solution

图片

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix Typography.Text lost right border when enable `ellipsis` and `code`.          |
| 🇨🇳 Chinese |   修复 Typography.Text 同时启用 `ellipsis` 和 `code` 时丢失右边框样式的问题。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 4d60df6</samp>

This pull request enhances the typography component and its demos by adding ellipsis support for code style, adjusting the width of the ellipsis demo, and improving the code formatting and readability.

### <samp>🤖 Generated by Copilot at 4d60df6</samp>

* Increase the width of the text component with ellipsis and add another text component with code style and ellipsis in `components/typography/demo/ellipsis.tsx` ([link](https://github.com/ant-design/ant-design/pull/45575/files?diff=unified&w=0#diff-087584a45eea0476eeb93f7d78c3ae29930569b7bea871722e0a63b6a5f05109L37-R49))
* Enable ellipsis and overflow handling for the code element inside the typography component and set its vertical alignment to bottom in `components/typography/style/mixins.ts` ([link](https://github.com/ant-design/ant-design/pull/45575/files?diff=unified&w=0#diff-5e2c2184e054706f99691f617b33901f0929824030ce7847ac693ad475154775R256-R264))
* Add empty lines to separate the import statements, the component declaration, and the component usage in `components/typography/demo/basic.tsx` ([link](https://github.com/ant-design/ant-design/pull/45575/files?diff=unified&w=0#diff-70179fb9c68d923be8b3778dc155010b5adc133174c3ec8e4cefa014c058ad6bR12), [link](https://github.com/ant-design/ant-design/pull/45575/files?diff=unified&w=0#diff-70179fb9c68d923be8b3778dc155010b5adc133174c3ec8e4cefa014c058ad6bR18))
* Add empty lines to separate the paragraphs and titles in `components/typography/demo/basic.tsx` ([link](https://github.com/ant-design/ant-design/pull/45575/files?diff=unified&w=0#diff-70179fb9c68d923be8b3778dc155010b5adc133174c3ec8e4cefa014c058ad6bL27-R31), [link](https://github.com/ant-design/ant-design/pull/45575/files?diff=unified&w=0#diff-70179fb9c68d923be8b3778dc155010b5adc133174c3ec8e4cefa014c058ad6bL55-R63), [link](https://github.com/ant-design/ant-design/pull/45575/files?diff=unified&w=0#diff-70179fb9c68d923be8b3778dc155010b5adc133174c3ec8e4cefa014c058ad6bL64-R72))

### CODE REVIEW

**Review by kiner-tang — APPROVED** [review]

File: components/typography/style/mixins.ts [hunk 1]
```diff
@@ -253,6 +253,15 @@ export const getEllipsisStyles = (): CSSObject => ({
     'a&, span&': {
       verticalAlign: 'bottom',
     },
+
+    '> code': {
+      paddingBlock: 0,
+      maxWidth: 'calc(100% - 1.2em)',
```
Comment (zombieJ) [inline components/typography/style/mixins.ts:259]: `1.2` 是 magic code?

Comment (afc163) [reply components/typography/style/mixins.ts:259]: 其实是 padding + margin 加起来的，我加一下。

**Review by zombieJ — APPROVED** [review]

File: components/typography/style/mixins.ts (hunk 1 above)
Comment (afc163) [reply components/typography/style/mixins.ts:259]: 不太好提变量，有点碎。
