### PR TITLE
fix: form item support comment

### LINKED ISSUE #41769: form组件里switch组件后面些注释为什么form就获取不到值了
### Reproduction link

[https://ant.design/components/switch-cn](https://ant.design/components/switch-cn)

### Steps to reproduce

<Field
          label="开关"
          name={'switch'}
          valuePropName='checked'
        >
          <Switch /> {/* 23 */}
        </Field>

### What is expected?

switch:true

### What is actually happening?

无论开关switch的值都为undefined

| Environment | Info |
| --- | --- |
| antd | 5.4.2 |
| React | 17.0.2 |
| System | mac |
| Browser | 谷歌 |

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #41769

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |       Optimize Form field binding, now will ignore comments in Form.Item as subcomponents.    |
| 🇨🇳 Chinese |      优化 Form 字段绑定，现在会忽略在 Form.Item 内的注释不再作为子组件进行绑定。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 7d5da61</samp>

The pull request introduces a new custom hook `useChildren` to handle the `children` prop of `Form.Item` more consistently and avoid potential bugs or warnings. It also updates the `Form.Item` component to use the hook and refactors the test file `components/form/__tests__/index.test.tsx` to follow the code style guide and add a new test case.

### <samp>🤖 Generated by Copilot at 7d5da61</samp>

*  Import `resetWarned` function and use it to reset warning state before each test case in `components/form/__tests__/index.test.tsx` ([link](https://github.com/ant-design/ant-design/pull/41771/files?diff=unified&w=0#diff-f3bb49bfe69c75aa977732eec74dfe67b8b00e00fc5e008c4f1d3835ae296eacR11))
*  Replace single quotes with double quotes for JSX attributes in `components/form/__tests__/index.test.tsx` ([link](https://github.com/ant-design/ant-design/pull/41771/files?diff=unified&w=0#diff-f3bb49bfe69c75aa977732eec74dfe67b8b00e00fc5e008c4f1d3835ae296eacL1462-R1463), [link](https://github.com/ant-design/ant-design/pull/41771/files?diff=unified&w=0#diff-f3bb49bfe69c75aa977732eec74dfe67b8b00e00fc5e008c4f1d3835ae296eacL1550-R1551))
*  Add new test case `children support comment` to check the functionality of `useChildren` hook in `components/form/__tests__/index.test.tsx` ([link](https://github.com/ant-design/ant-design/pull/41771/files?diff=unified&w=0#diff-f3bb49bfe69c75aa977732eec74dfe67b8b00e00fc5e008c4f1d3835ae296eacR1863-R1880))
*  Reorder import statements alphabetically in `components/form/FormItem/index.tsx` ([link](https://github.com/ant-design/ant-design/pull/41771/files?diff=unified&w=0#diff-ca241b27784d31abb99a7d491adda5dd50f6969f7d25389fb3513d267835f3aeL9-R15))
*  Import `useChildren` hook from `components/form/hooks/useChildren.ts` and use it to convert `children` prop to a single or array element or a render function in `components/form/FormItem/index.tsx` ([link](https://github.com/ant-design/ant-design/pull/41771/files?diff=unified&w=0#diff-ca241b27784d31abb99a7d491adda5dd50f6969f7d25389fb3513d267835f3aeR21), [link](https://github.com/ant-design/ant-design/pull/41771/files?diff=unified&w=0#diff-ca241b27784d31abb99a7d491adda5dd50f6969f7d25389fb3513d267835f3aeL113-R118))
  - layout rendering ([link](https://github.com/ant-design/ant-design/pull/41771/files?diff=unified&w=0#diff-ca241b27784d31abb99a7d491adda5dd50f6969f7d25389fb3513d267835f3aeL235-R240))
  - warning condition for array children with name prop ([link](https://github.com/ant-design/ant-design/pull/41771/files?diff=unified&w=0#diff-ca241b27784d31abb99a7d491adda5dd50f6969f7d25389fb3513d267835f3aeL290-R295))
  - assignment of `childNode` and warning condition for render function with name prop or no dependencies ([link](https://github.com/ant-design/ant-design/pull/41771/files?diff=unified&w=0#diff-ca241b27784d31abb99a7d491adda5dd50f6969f7d25389fb3513d267835f3aeL296-R301))
  - element validation and warning for `defaultValue` prop ([link](https://github.com/ant-design/ant-design/pull/41771/files?diff=unified&w=0#diff-ca241b27784d31abb99a7d491adda5dd50f6969f7d25389fb3513d267835f3aeL314-R326))
  - ref attachment and `getItemRef` function call ([link](https://github.com/ant-design/ant-design/pull/41771/files?diff=unified&w=0#diff-ca241b27784d31abb99a7d491adda5dd50f6969f7d25389fb3513d267835f3aeL345-R351))
  - event handler binding and call ([link](https://github.com/ant-design/ant-design/pull/41771/files?diff=unified&w=0#diff-ca241b27784d31abb99a7d491adda5dd50f6969f7d25389fb3513d267835f3aeL358-R363))
  - `MemoInput` component and condition for render function with no name prop but dependencies ([link](https://github.com/ant-design/ant-design/pull/41771/files?diff=unified&w=0#diff-ca241b27784d31abb99a7d491adda5dd50f6969f7d25389fb3513d267835f3aeL372-R384))
  - warning condition for name prop with invalid element or function and assignment of `childNode` ([link](https://github.com/ant-design/ant-design/pull/41771/files?diff=unified&w=0#diff-ca241b27784d31abb99a7d491adda5dd50f6969f7d25389fb3513d267835f3aeL386-R391))
*  Add new file `components/form/hooks/useChildren.ts` that exports `useChildren` hook to handle different types of `children` prop for `Form.Item` component ([link](https://github.com/ant-design/ant-design/pull/41771/files?diff=unified&w=0#diff-bcff919efcf0dcb42c694395467c0b7700162e1ffbfda4f7092b06e53f8ab60fR1-R11))

### CODE REVIEW

File: components/form/FormItem/index.tsx [hunk 1]
```diff
@@ -110,7 +111,11 @@ function InternalFormItem<Values = any>(props: FormItemProps<Values>): React.Rea
   } = props;
   const { getPrefixCls } = React.useContext(ConfigContext);
   const { name: formName } = React.useContext(FormContext);
-  const isRenderProps = typeof children === 'function';
+
+  const mergedChildren = useChildren(children);
+  console.log('mergedChildren:', mergedChildren);
```
Comment (li-jia-nan) [inline components/form/FormItem/index.tsx:116]: console

**Review by li-jia-nan — APPROVED** [review]

File: components/form/__tests__/index.test.tsx [hunk 2]
```diff
@@ -1859,4 +1860,22 @@ describe('Form', () => {
...
     expect(container.querySelectorAll('.ant-form-item-required-mark-optional')).toHaveLength(2);
   });
+
+  it('children support comment', () => {
+    resetWarned();
+
+    const { container } = render(
+      <Form initialValues={{ name: 'bamboo', age: '14' }}>
+        <Form.Item name="name">
+          {/* Comment here */}
```
Comment (afc163) [inline components/form/__tests__/index.test.tsx:1870]: 这里如果是普通的文本 node 能兼容么？

Comment (afc163) [reply components/form/__tests__/index.test.tsx:1870]: 比如这个例子：https://github.com/ant-design/ant-design/issues/41862

File: components/form/hooks/useChildren.ts [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+export default function useChildren(
+  children?: FormItemProps['children'],
+): FormItemProps['children'] {
+  if (typeof children === 'function') {
+    return children;
+  }
+
+  const childList = toArray(children);
+  return childList.length <= 1 ? childList[0] : childList;
+}
```
Comment (tquann286) [inline components/form/hooks/useChildren.ts:13]: Hi, I'm trying to use form.item in version 5.6.1, but when I pass the value to children prop I get the `undefined` value in the children component. I think this useChildren is causing it. When I downgrade to antd@5.4.2 (when this useChildren wasn't added yet), it works fine.
