### PR TITLE
enhance: ssr ellipsis effect

### LINKED ISSUE #48200: Paragraph一行时展开后显示不正确
### Reproduction link

[https://ant.design/components/typography-cn#components-typography-demo-ellipsis-controlled](https://ant.design/components/typography-cn#components-typography-demo-ellipsis-controlled)

### Steps to reproduce

rows=1时，点击展开。
image

### What is expected?

内容不超出

### What is actually happening?

内容超出

| Environment | Info |
| --- | --- |
| antd | 5.16.0 |
| React | 18 |
| System | windows 11 |
| Browser | edge 123.0.2420.65 |

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [x] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

resolve #48200

### 💡 Background and solution

SSR 的时候文本是不缩起的，这导致体感上很怪异。SSR 阶段无论是否需要 js 测量 ellipsis 都先使用 css 做裁剪。等注水后再使用 js 切割:

#### SSR

截屏2024-04-01 12 56 13

#### Client

截屏2024-04-01 12 56 46

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Adjust Typography `ellipsis` logic to use CSS ellipsis in SSR to enhance user experience.       |
| 🇨🇳 Chinese |   调整 Typography 的 `ellipsis` 使其在 SSR 阶段使用 CSS 省略以优化用户体验。        |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/typography/Base/index.tsx [hunk 1]
```diff
@@ -207,14 +207,14 @@ const Base = React.forwardRef<HTMLElement, BlockProps>((props, ref) => {
...
-      // Can't use css ellipsis since we need to provide the place for button
-      ellipsisConfig.expandable ||
-      enableEdit ||
-      enableCopy,
+      (ellipsisConfig.suffix !== undefined ||
+        ellipsisConfig.onEllipsis ||
+        // Can't use css ellipsis since we need to provide the place for button
+        ellipsisConfig.expandable ||
+        enableEdit ||
+        enableCopy),
```
Comment (afc163) [inline components/typography/Base/index.tsx:217]: 这个换行貌似不太对劲。

Comment (zombieJ) [reply components/typography/Base/index.tsx:217]: 嗯，怎么搞 prettier 都变成这个鬼样子。蛋疼

Comment (zombieJ) [reply components/typography/Base/index.tsx:217]: 先 resolve 了。不为了 prettier 加额外的逻辑去了

**Review by li-jia-nan — APPROVED** [review]
