### PR TITLE
fix: Backtop cannot work in Chrome iframe

### LINKED ISSUE #24192: BackTop 无效
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/back-top-cn/#components-back-top-demo-custom](https://ant.design/components/back-top-cn/#components-back-top-demo-custom)

### Steps to reproduce
滚动后点击up 并没有返回到顶部 同时，up消失了

### What is expected?
滚动到顶部，同时再次滚动到底部后出现up

### What is actually happening?
没有任何效果

| Environment | Info |
|---|---|
| antd | 4.2.2|
| React | latest |
| System | windows  |
| Browser |  chrome latest |

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #24192

### 💡 Background and solution

https://github.com/ant-design/ant-design/pull/22788 没有修干净，Chrome 下还是不能用。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix BackTop not working in iframe of Chrome. |
| 🇨🇳 Chinese |  修复 BackTop 在 Chrome 的 iframe 里不生效的问题。  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/_util/scrollTo.ts [hunk 1]
```diff
@@ -24,8 +24,8 @@ export default function scrollTo(y: number, options: ScrollToOptions = {}) {
     const nextScrollTop = easeInOutCubic(time > duration ? duration : time, scrollTop, y, duration);
     if (isWindow(container)) {
       (container as Window).scrollTo(window.pageXOffset, nextScrollTop);
-    } else if (container instanceof Document) {
-      container.documentElement.scrollTop = nextScrollTop;
+    } else if (container instanceof HTMLDocument || container.constructor.name === 'HTMLDocument') {
```
Comment (afc163) [inline components/_util/scrollTo.ts:27]: Chrome 下 `element.ownerDocument instanceof HTMLDocument` 是 false，比较奇怪。

Comment (hengkx) [reply components/_util/scrollTo.ts:27]: image
为啥控制台是true...

Comment (afc163) [reply components/_util/scrollTo.ts:27]: image

image

非常诡异。
