### PR TITLE
fix: Select should show scrollbar if scrollable

### LINKED ISSUE #45935: 当下拉列表里面有9条或10条数据的时候，Select 组件的滚动条不会出现
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/dai-sou-suo-kuang-antd-5-11-1-forked-5tw59w?file=/demo.tsx)

### Steps to reproduce

点击select组件，显示下拉列表，不出现滚动条，但是鼠标滚轮可以滚动

### What is expected?

dropdown出现滚动条

### What is actually happening?

dropdown没有滚动条

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | 18 |
| System | windows10 |
| Browser | chrome 119.0.6045.159 |

---
看代码应该是virtual-list问题，inVirtual是false，导致不展示滚动条组件

### LINKED ISSUE #46390: Scrollbar not visible in select when there are 9 or 10 options
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-55fhd7?file=%2Findex.js)

### Steps to reproduce

Create a select with nine or ten options. Open the drop-down. Observe that only eight items are shown and that there is no scrollbar to indicate that more options are available.

### What is expected?

Scrollbar to appear when select options are scroll-able.

### What is actually happening?

Select is scroll-able, but there is no scrollbar to indicate it.

| Environment | Info |
| --- | --- |
| antd | 5.12.1 |
| React | 18.0 |
| System | Windows |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by MadCcc**
- fix: select scrollbar
- chore: code clean

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/45935
close https://github.com/ant-design/ant-design/issues/46390

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix Select that scrollbar do not display in some case.       |
| 🇨🇳 Chinese |      修复 Select 组件滚动条在某些条件下不会显示的问题。     |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by li-jia-nan — APPROVED** [review]

File: components/select/index.tsx [hunk 1]
```diff
@@ -116,6 +117,10 @@ const InternalSelect = <
     select,
   } = React.useContext(ConfigContext);
 
+  const [, token] = useToken();
+
+  const listItemHeight = customListItemHeight ?? token?.controlHeight;
```
Comment (afc163) [inline components/select/index.tsx:122]: https://github.com/ant-design/ant-design/pull/46672 是不是也这么改比较好？
