### PR TITLE
fix(Button): child element's className being cleared when rendering two Chinese characters.

### LINKED ISSUE #56591: Button 子元素自定义的class被去掉
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/priceless-ioana-th88hm)

### Steps to reproduce

Button 组件的 children 如果是一个只有两个文字内容的标签,这个标签的className会被清空

### What is expected?

不清空自己定义的ClassName ,可以和 classNames  做一个merge

### What is actually happening?

两个文字的子标签 className被清空

| Environment | Info |
| --- | --- |
| antd | 6.2.0 |
| React | 18.3.1 |
| System | windows |
| Browser | edge |

### PR DESCRIPTION
**Pull request by QdabuliuQ**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues
- fix https://github.com/ant-design/ant-design/issues/56591

### 💡 Background and Solution
When Button's children is a tag element containing two Chinese characters, the component overwrites the child element's original className and style attributes while inserting spaces between characters, causing custom styles to be lost.
Modified lines 54-59 in the splitCNCharsBySpace function in buttonHelpers.tsx to merge className and style instead of overwriting

### 📝 Change Log
| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix child element's `className` being cleared when rendering two Chinese characters |
| 🇨🇳 Chinese | 修复 children 为包含两个中文字符的标签时，原有 `className` 被清空的问题 |

### CODE REVIEW

**Review by wanpan11 — APPROVED** [review]

File: components/button/buttonHelpers.tsx [hunk 1]
```diff
@@ -54,8 +54,8 @@ function splitCNCharsBySpace(
     return cloneElement(child, (oriProps) => ({
       ...oriProps,
       children: oriProps.children.split('').join(SPACE),
-      className,
-      style,
+      className: clsx(oriProps.className, className) || undefined,
```
Comment (li-jia-nan) [inline components/button/buttonHelpers.tsx:57]: 这个 undefined 看起来是多余的

File: components/button/buttonHelpers.tsx [hunk 2]
```diff
@@ -54,8 +54,8 @@ function splitCNCharsBySpace(
...
+      style: { ...oriProps.style, ...style },
```
Comment (li-jia-nan) [inline components/button/buttonHelpers.tsx:58]: oriProps.style 应该在后边吧，这个是自身的样式，优先级肯定高于外层的 style

Comment (li-jia-nan) [reply components/button/buttonHelpers.tsx:58]: - #56597

Comment (thinkasany) [reply components/button/buttonHelpers.tsx:58]: '' || undefined 是 undefined
className={undefined} 的时候变成 dom 会自动去掉空的 class。
image
image

Comment (li-jia-nan) [reply components/button/buttonHelpers.tsx:58]: 没必要特殊处理，其它组件里面也有这个，要特殊处理的话，要改的地方太多了

Comment (li-jia-nan) [reply components/button/buttonHelpers.tsx:58]: image
