### PR TITLE
fix: add Japanese localization for Table 

### LINKED ISSUE #27041: Adds ja_JP localisations
- [x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The ja_JP localisations is not enough.
日语本地化资源不足，希望能够完善

### What does the proposed API look like?
我们团队在日本，翻译的内容是由日本的同事提供，希望能够完善日本本地的资源

### PR DESCRIPTION
**Pull request by iorikingdom**
增加了几处日语翻译，希望下个版本能用上

[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [x] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

close #27041

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix Japanese localization.  |
| 🇨🇳 Chinese | 调整日语国际化文案。 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/locale/ja_JP.tsx [hunk 1]
```diff
@@ -19,6 +19,9 @@ const localeValues: Locale = {
     filterReset: 'リセット',
     selectAll: 'すべてを選択',
     selectInvert: '選択を反転',
+    triggerDesc: 'クリックで降順にソート',
+    triggerAsc: 'クリックで昇順にソート',
+    cancelSort: 'クリックでソートをキャンセル',
```
Comment (yoyo837) [inline components/locale/ja_JP.tsx:24]: `selectionAll`, `sortTitle`, `expand`, `collapse` 也给加上呗

Comment (iorikingdom) [reply components/locale/ja_JP.tsx:24]: OK、稍等片刻

**Comment by yoyo837** [comment]
image
