### PR TITLE
fix(Image): preview.rootClassName

### LINKED ISSUE #51510: Image设置`preview.rootClassName`后样式丢失
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-6mlssd)

### Steps to reproduce

Image组件传入`preview.rootClassName`,点击图片打开预览

### What is expected?

正常显示预览

### What is actually happening?

预览样式丢失

| Environment | Info |
| --- | --- |
| antd | 5.21.6 |
| React | 18.3.1 |
| System | windows 11 |
| Browser | Edge 125 |

---
传入的rootClassName覆盖了原有的classname, 似乎classNames合并没有正常工作

### PR DESCRIPTION
**Pull request by dislido**
Fix the issue of preview.rootClassName not merging classnames

[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

fix https://github.com/ant-design/ant-design/issues/51510

### 💡 Background and Solution

在未传入`ImageProps.preview.rootClassName`的情况下，`Preview`会默认使用合并了`hashId, cssVarCls, rootCls`的`ImageProps.rootClassName`，而`ImageProps.preview.rootClassName`会覆盖此值且没有做上述合并处理，导致className丢失

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |fix `ImageProps.preview.rootClassName` causes Preview className lost|
| 🇨🇳 Chinese |修复`ImageProps.preview.rootClassName`导致预览图类名丢失|

### CODE REVIEW

File: components/image/index.tsx [hunk 1]
```diff
@@ -64,6 +64,7 @@ const Image: CompositionImage<ImageProps> = (props) => {
       ),
       icons,
       ...restPreviewProps,
+      rootClassName: rootClassName ? classNames(rootClassName, hashId, cssVarCls, rootCls) : mergedRootClassName,
```
Comment (afc163) [inline components/image/index.tsx:67]:
```suggestion
      rootClassName: mergedRootClassName,
```

Comment (dislido) [reply components/image/index.tsx:67]: `ImageProps.rootClassName`和`ImageProps.preview.rootClassName`是不同的东西，`ImageProps.rootClassName`同时也会影响`Image`自身的`wrapperClass`

Comment (afc163) [inline components/image/index.tsx:67]:
```suggestion
      rootClassName: classNames(rootClassName, hashId, cssVarCls, rootCls),
```

那这样就行了，不要使用上面的 mergedRootClassName。

Comment (afc163) [reply components/image/index.tsx:67]: 那确实是。

Comment (afc163) [reply components/image/index.tsx:67]:
```suggestion
```suggestion
      rootClassName: classNames(mergedRootClassName, rootClassName),
```

这样应该对了。
```

Comment (dislido) [reply components/image/index.tsx]: 👌

**Review by afc163 — APPROVED** [review]
