### PR TITLE
fix: fix loading.icon error when loading === null

### LINKED ISSUE #52507: 5.23 Button loading未判断为null的情况
### What problem does this feature solve?

5.23 button loading增加了{ delay: number, icon: ReactNode } 的功能但是判断的时候使用了typeof 导致在传入null时直接取icon造成程序奔溃，希望能兼容旧接口真值为true，假值为false

### What does the proposed API look like?

在判断loading时增加对null的判断

### PR DESCRIPTION
**Pull request by li-jia-nan**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

- close #52507

> - Describe the source of related requirements, such as links to relevant issue discussions.
> - For example: close #xxxx, fix #xxxx

### 💡 Background and Solution

> - The specific problem to be addressed.
> - List the final API implementation and usage if needed.
> - If there are UI/interaction changes, consider providing screenshots or GIFs.

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix: fix loading error when loading === null |
| 🇨🇳 Chinese | fix: fix loading error when loading === null |

### CODE REVIEW

File: components/button/button.tsx [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import React, { Children, useContext, useEffect, useMemo, useRef, useState } from 'react';
+import omit from '@rc-component/util/lib/omit';
+import { useComposeRef } from '@rc-component/util/lib/ref';
```
Comment (yoyo837) [inline components/button/button.tsx]: master 切换包名了？

Comment (li-jia-nan) [reply components/button/button.tsx]: 木有

File: components/button/button.tsx [hunk 2]
```diff
@@ -310,7 +310,7 @@ const InternalCompoundedButton = React.forwardRef<
       <IconWrapper prefixCls={prefixCls} className={iconClasses} style={iconStyle}>
         {icon}
       </IconWrapper>
-    ) : typeof loading === 'object' && loading.icon ? (
+    ) : loading && typeof loading === 'object' && loading.icon ? (
```
Comment (yoyo837) [inline components/button/button.tsx:313]: 要不干脆直接简单点 loading?.icon ?

**Review by afc163 — APPROVED** [review]

File: components/button/button.tsx (hunk 2 above)
Comment (li-jia-nan) [reply components/button/button.tsx:313]: 那前后逻辑不等价了，这里判断了 object

**Review by afc163 — APPROVED** [review]

**Comment by li-jia-nan** [comment]
为啥会出现这么多 diff，应该跟当前 PR 无关吧
