### PR TITLE
fix: Description key warning

### LINKED ISSUE #21686: Descriptions 提示Sum of column `span` in a line not match `column` of Descriptions.
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/mystifying-hooks-indtj)

### Steps to reproduce
直接打开页面，即可看到问题

### What is expected?
无警告输出且 `<Descriptions.Item label="工作经验" span={3}> `独占一行

### What is actually happening?
有两个警告：  
1.Warning: [antd: Descriptions] Sum of column `span` in a line not match `column` of Descriptions.  
2.Warning: Each child in a list should have a unique "key" prop. Check the render method of `Descriptions`.

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.0 |
| System | Window 10 |
| Browser | Microsoft Edge 80.0.361.62 |

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix #21686

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix Descriptions warning for duplicate `key`.       |
| 🇨🇳 Chinese |    修复 Descriptions 报 `key` 重复的警告信息。    |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/descriptions/Row.tsx [hunk 1]
```diff
@@ -69,7 +69,7 @@ function renderCells(
             bordered={bordered}
             content={children}
           />
-        </>
+        </React.Fragment>
```
Comment (afc163) [inline components/descriptions/Row.tsx]: 这一层是不是可以直接去掉。
