### PR TITLE
fix: Space duplicated key warning

### LINKED ISSUE #35305: Space duplicated child key
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/antd-space-duplicated-child-key-forked-ppg5hc?file=/index.js)

### Steps to reproduce

```jsx
<Space>
    <div key="1" />
    <div />
</Space>
```

### What is expected?

No duplicated key

### What is actually happening?

Warning: Encountered two children with the same key, `ant-space-item-1`.

| Environment | Info |
| --- | --- |
| antd | 4.20.1 |
| React | React 17 |
| System | macOS 12 |
| Browser | Chrome 100 |

---
This bug is introduced by #33607

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #35305

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix Space throws `Encountered two children with the same key` in some cases.         |
| 🇨🇳 Chinese | 修复 Space 在某些情况下抛出 `Encountered two children with the same key` 警告的问题。          |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/space/index.tsx [hunk 1]
```diff
@@ -89,11 +89,14 @@ const Space: React.FC<SpaceProps> = props => {
     }
 
     const keyOfChild = child && child.key;
+    // Add `-space-item` as suffix in case simple key string trigger duplicated key warning
+    // https://github.com/ant-design/ant-design/issues/35305
+    const defaultKey = `${i}-space-item`;
```
Comment (cncolder) [inline components/space/index.tsx:94]: 感谢 🙏
虽然生成的 key 丑了点. `ant-space-item-1-space-item` 😄
