### PR TITLE
fix(Timeline): Fixed the Timeline item className error

### LINKED ISSUE #40833: Timeline "alternate" and "right" modes are broken for items that have an extra className
### Reproduction link

[https://stackblitz.com/edit/react-rfoveg?file=demo.tsx](https://stackblitz.com/edit/react-rfoveg?file=demo.tsx)

### Steps to reproduce

1. Add mode="alternate" or mode="right" to the `<Timeline />`
2. Add "className" property to one or more items

### What is expected?

Timeline items are displayed either in center ("alternate") with the text on alternating sides or on the right ("right") with the text on left side

### What is actually happening?

Items with "className" property are displayed in the center

| Environment | Info |
| --- | --- |
| antd | 5.2.2 |
| React | 18.2 |
| System | Windows |
| Browser | Chrome |

---
Most likely caused by this fix https://github.com/ant-design/ant-design/pull/40700

### PR DESCRIPTION
**Pull request by Yuiai01**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/40833
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fixed the Timeline item className error          |
| 🇨🇳 Chinese | 修复 `Timeline` 的 item 其 className 错误           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/timeline/TimelineItemList.tsx [hunk 1]
```diff
@@ -52,13 +52,16 @@ const TimelineItemList: React.FC<TimelineProps & { hashId: string; direction?: s
...
+      const itemClassName = item?.className ?? '';
+
       return (
         <TimelineItem
+          {...item}
           className={classNames([
+            itemClassName,
             !reverse && !!pending ? pendingClass : readyClass,
             getPositionCls(item?.position ?? '', idx),
           ])}
```
Comment (MadCcc) [inline components/timeline/TimelineItemList.tsx:64]:
```suggestion
      const itemClassName = item?.className;

      return (
        <TimelineItem
          {...item}
          className={classNames(
            itemClassName,
            !reverse && !!pending ? pendingClass : readyClass,
            getPositionCls(item?.position ?? '', idx),
          )}
```

Comment (Yuiai01) [reply components/timeline/TimelineItemList.tsx:64]: 好~

**Review by MadCcc — APPROVED** [review]
