### PR TITLE
fix(Menu): remove unexpected re-render, which causes flash and shake when collapsed

### LINKED ISSUE #15614: inline Menu component  flash and shake when collapsed
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/ouzhou/pen/MxxgZQ?&editable=true&editors=001](https://codepen.io/ouzhou/pen/MxxgZQ?&editable=true&editors=001)

### Steps to reproduce
click the top primary blue button 

### What is expected?
menu collapsed with no flash

### What is actually happening?
shake and flash

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.x |
| System | win10 |
| Browser | chrome 72.0.3626.121（正式版本） （64 位） |

### PR DESCRIPTION
**Pull request by orzyyyy**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

1. Describe the source of requirement, like related issue link.

    To close #15614
2. Describe the problem and the scenario.

### 💡 Solution

1. How to fix the problem, and list final API implementation and usage sample if that is an new feature.

2. GIF or snapshot should be provided if includes UI/interactive modification.

### 📝 Changelog description

> Describe changes from userside, and list all potential break changes or other risks.

1. English description

    Fix Menu unexpected shaking when collapsed.
2. Chinese description (optional)

   修复 Menu 收缩的异常闪动。

### ☑️ Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

File: components/menu/MenuItem.tsx [hunk 1]
```diff
@@ -17,37 +16,30 @@ export interface MenuItemProps {
...
+    titleNode = title || (level === 1 ? children : '');
 
     return (
       <Tooltip
         title={titleNode}
         placement="right"
         overlayClassName={`${rootPrefixCls}-inline-collapsed-tooltip`}
       >
-        <Item {...rest} title={inlineCollapsed ? null : title} ref={this.saveMenuItem} />
+        <Item {...rest} title={title} ref={this.saveMenuItem} />
```
Comment (afc163) [inline components/menu/MenuItem.tsx]: image

这里造成了非 `inlineCollapsed` 情况下显示了多余的 Tooltip 问题。

@zy410419243

Comment (zy410419243) [reply components/menu/MenuItem.tsx]: https://github.com/ant-design/ant-design/pull/15705
