### PR TITLE
fix: Fixed an issue where the z-index setting of the pop-up component was abnormal in the pop-up container

### LINKED ISSUE #45863: 多层Drawer时，zIndex值过高，遮住了Popconfirm,Modal等弹框
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-67hgtt?file=/index.js:0-1169)

### Steps to reproduce

1、页面上有两个嵌套的Drawer；
2、打开第1个Drawer中，再打开第2个Drawer，第2个Drawer中的Popconfirm按钮点击，不显示Popconfirm对话框。

### What is expected?

正常显示Popconfirm，以及其他Modal等

### What is actually happening?

不能显示

| Environment | Info |
| --- | --- |
| antd | 5.11.1 |
| React | react |
| System | window |
| Browser | chorm 119 |

### PR DESCRIPTION
**Pull request by kiner-tang**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [X] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #45863

### 💡 Background and solution

理论上，Tooltip、Popover、Popconfirm、ColorPicker 底层都是 Tooltip, 因此他们的 z-index 应该处于同一个量级，仅有各自偏移量可能略有不同，如：
image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fixed an issue where the z-index setting of the pop-up component was abnormal in the pop-up container |
| 🇨🇳 Chinese | 修复弹出式组件在弹出容器内 z-index 设置异常问题 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at a186284</samp>

This pull request improves the zIndex handling of the `ColorPicker`, `Popconfirm`, `Popover`, and `Tooltip` components. It fixes some bugs and adds some features to make the zIndex consistent and configurable across different scenarios. It also adds some tests and comments to explain the logic.

### <samp>🤖 Generated by Copilot at a186284</samp>

*  Add logic to handle ColorPicker component type in useZIndex hook and tests ([link](https://github.com/ant-design/ant-design/pull/45864/files?diff=unified&w=0#diff-7e29bdf7b3d15903dfc9bea72d699ed4bef2146dc1a0689897752772a15c3de5L234-R245), [link](https://github.com/ant-design/ant-design/pull/45864/files?diff=unified&w=0#diff-7e29bdf7b3d15903dfc9bea72d699ed4bef2146dc1a0689897752772a15c3de5L299-R318), [link](https://github.com/ant-design/ant-design/pull/45864/files?diff=unified&w=0#diff-7e29bdf7b3d15903dfc9bea72d699ed4bef2146dc1a0689897752772a15c3de5L310-R325), [link](https://github.com/ant-design/ant-design/pull/45864/files?diff=unified&w=0#diff-2a902ec0f175b29920c300ea9a4023433a9a9720749632f5ac132e73694b1f71R40-R44))
*  Add custom data attribute to ColorPicker and Popconfirm components to indicate zIndex injection to Popover component ([link](https://github.com/ant-design/ant-design/pull/45864/files?diff=unified&w=0#diff-be92dd92152a780003d48ddc95ec6716367d327f9f890f1221b84614aaa8168fR258), [link](https://github.com/ant-design/ant-design/pull/45864/files?diff=unified&w=0#diff-36878e30875e0d3ac3e1c9a9d6bebbcb023b8197cddd259fb7bc00976d795285R126))
*  Use useZIndex hook and zIndex prop in Popconfirm component and pass zIndex to Popover component ([link](https://github.com/ant-design/ant-design/pull/45864/files?diff=unified&w=0#diff-36878e30875e0d3ac3e1c9a9d6bebbcb023b8197cddd259fb7bc00976d795285R16), [link](https://github.com/ant-design/ant-design/pull/45864/files?diff=unified&w=0#diff-36878e30875e0d3ac3e1c9a9d6bebbcb023b8197cddd259fb7bc00976d795285R101-R103), [link](https://github.com/ant-design/ant-design/pull/45864/files?diff=unified&w=0#diff-36878e30875e0d3ac3e1c9a9d6bebbcb023b8197cddd259fb7bc00976d795285R113))
*  Use custom data attribute and zIndex prop in Popover and Tooltip components to determine zIndex value and pass it down ([link](https://github.com/ant-design/ant-design/pull/45864/files?diff=unified&w=0#diff-8255c20b0fc82fa28472ee578129241aab0b6c6d3f2cdafba5f74fa2614a92f0R54), [link](https://github.com/ant-design/ant-design/pull/45864/files?diff=unified&w=0#diff-8255c20b0fc82fa28472ee578129241aab0b6c6d3f2cdafba5f74fa2614a92f0L70-R73), [link](https://github.com/ant-design/ant-design/pull/45864/files?diff=unified&w=0#diff-15851db1188c7109b62716f8105c243911fa7473baa0436e6e0798e0c10b4966R260), [link](https://github.com/ant-design/ant-design/pull/45864/files?diff=unified&w=0#diff-15851db1188c7109b62716f8105c243911fa7473baa0436e6e0798e0c10b4966L303-R304))

### CODE REVIEW

**Comment by Inori-Lover** [comment]
第三层drawer也能盖住吗？

**Comment by kiner-tang** [comment]
> 第三层drawer也能盖住吗？

会根据嵌套层级累加的

**Comment by deific** [comment]
Modal也会被遮住

**Comment by kiner-tang** [comment]
> Modal也会被遮住

这个问题本质上不是 modal 和 drawer 的问题，是 Popover、Popconfirm 层级计算的问题，导致层级太低，修复后应该都会恢复正常

File: components/popconfirm/index.tsx [hunk 1]
```diff
@@ -97,6 +97,8 @@ const Popconfirm = React.forwardRef<TooltipRef, PopconfirmProps>((props, ref) =>
 
   const [wrapSSR] = usePopconfirmStyle(prefixCls);
 
+  // ============================ zIndex ============================
+
```
Comment (kiner-tang) [inline components/popconfirm/index.tsx:101]:
```suggestion
```

File: components/tooltip/index.tsx [hunk 2]
```diff
@@ -300,7 +300,7 @@ const Tooltip = React.forwardRef<TooltipRef, TooltipProps>((props, ref) => {
   const content = (
     <RcTooltip
       {...otherProps}
-      zIndex={injectFromPopover ? otherProps.zIndex : zIndex}
```
Comment (MadCcc) [inline components/tooltip/index.tsx:303]: 这里改 Popover 的 zIndex 不应该还是继承下来吗？

Comment (kiner-tang) [reply components/tooltip/index.tsx:303]: image
这里会处理透传过来的 zIndex

**Review by MadCcc — APPROVED** [review]

**Comment by hxing** [comment]
新版本5.11.2出现问题，原来Modal上放的Dropdown下拉框的列表居然跑到Modal的后面去了，可能是因为这个修复引起的吧
