### PR TITLE
fix: spin icon in Badge should have correct animation

### LINKED ISSUE #42558: Spin in a Badge component rotates too fast
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/objective-roentgen-hogv1u)

### Steps to reproduce

Use a Spin in a Badge component with "count" property.

### What is expected?

Spin component should rotate at a lower speed, as expected in the doc: https://ant.design/components/spin

### What is actually happening?

Spin component rotates very fast.

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.2.0 |
| System | Windows 11 / Ubuntu at least |
| Browser | Chrome / Brave |

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/42558

### 💡 Background and solution
image
参照 v4 的样式修复

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Fix spinning icon animation in Badge.      |
| 🇨🇳 Chinese |   修复 Badge 组件中旋转的 icon 动画。        |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 87fbc74</samp>

Improved `Badge` component style and functionality by fixing imports and icon issues.

### <samp>🤖 Generated by Copilot at 87fbc74</samp>

* Reorder imports alphabetically to follow code style guide and improve readability ([link](https://github.com/ant-design/ant-design/pull/42575/files?diff=unified&w=0#diff-b8c8d1867c9fbda6cf6dad3121f976971c2934a5a5ff1b47aa3984aa0c472809L3-R5))
* Prefix selector for spinning icon with `&` to avoid conflicts and change animation duration to match design spec ([link](https://github.com/ant-design/ant-design/pull/42575/files?diff=unified&w=0#diff-b8c8d1867c9fbda6cf6dad3121f976971c2934a5a5ff1b47aa3984aa0c472809L153-R155))

### CODE REVIEW

File: components/badge/style/index.ts [hunk 1]
```diff
@@ -150,9 +150,9 @@ const genSharedBadgeStyle: GenerateStyle<BadgeToken> = (token: BadgeToken): CSSO
         insetInlineEnd: 0,
         transform: 'translate(50%, -50%)',
         transformOrigin: '100% 0%',
-        [`${iconCls}-spin`]: {
+        [`&${iconCls}-spin`]: {
           animationName: antBadgeLoadingCircle,
-          animationDuration: token.motionDurationMid,
+          animationDuration: '1s',
```
Comment (afc163) [inline components/badge/style/index.ts:155]: 那这个就不能定义了，感觉也不合理

Comment (MadCcc) [reply components/badge/style/index.ts:155]: 现在比较长 duration 的 animation 都是魔法的，不太好统一定制。
这里作为一个兼容样式其实也不太好开组件 token，用户自己覆盖可能比较好，或者用其他的 loading 组件

**Review by li-jia-nan — APPROVED** [review]

**Review by kiner-tang — APPROVED** [review]
