### PR TITLE
fix: AutoComplete dataSource prop type error

### LINKED ISSUE #27865: AutoComplete dataSource prop has a type error
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/auto-complete/index.tsx](https://github.com/ant-design/ant-design/blob/master/components/auto-complete/index.tsx)

### Steps to reproduce
https://github.com/ant-design/ant-design/blob/master/components/auto-complete/index.tsx

### What is expected?
export type DataSourceItemType = string | DataSourceItemObject | React.ReactElement

### What is actually happening?
export type DataSourceItemType = string | DataSourceItemObject;

| Environment | Info |
|---|---|
| antd | 4.8.3 |
| React | 16.14.0 |
| System | mac |
| Browser | chrome 86 |

---
image

在react   ts 的项目中，使用 AutoComplete 的dataSource属性时如果传入的是 React.ReactElement数组会报类型错误。但是源码里面虽然做了dataSource元素的类型校验，但是申明其类型的时候没有写。

### PR DESCRIPTION
**Pull request by ElsaOOo**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
fix #27865

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

File: components/auto-complete/index.tsx [hunk 1]
```diff
@@ -20,7 +20,7 @@ export interface DataSourceItemObject {
   value: string;
   text: string;
 }
-export type DataSourceItemType = string | DataSourceItemObject;
+export type DataSourceItemType = string | DataSourceItemObject | React.ReactElement<any, any>;
```
Comment (afc163) [inline components/auto-complete/index.tsx:23]:
```suggestion
export type DataSourceItemType = string | DataSourceItemObject | React.ReactNode;
```

如何？

Comment (ElsaOOo) [reply components/auto-complete/index.tsx:23]: nice!

**Review by ElsaOOo — COMMENTED** [review]
nice!
