### PR TITLE
fix: align TextArea `maxLength` logic

### LINKED ISSUE #28940: Input.TextArea组件，当输入的字符长度等于maxLength，继续输入（中文输入法）时，会出现英文替换字符后几位
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/daizishutishidewenbenyu-antd4103-forked-invjq?file=/index.js:295-302)

### Steps to reproduce
1.maxLength={20}  defaultValue="11111111112222222222"，文本长度为20；
2.Input.TextArea获取焦点进行输入，切换到拼音输入法，反复点击英文，会发现“22”被替换成了英文

### What is expected?
value文本长度等于maxLength时，之后无论怎么输入，都不应该修改value值，应保持“11111111112222222222”，而不是类似“111111111122222222ad”等替换。

### What is actually happening?
value文本长度等于maxLength时，之后输入中文，“11111111112222222222”会被替换成“111111111122222222ad”之类。

| Environment | Info |
|---|---|
| antd | 4.10.3 |
| React | 16.14.0 |
| System | windows 10 |
| Browser | Google Chrome 版本 87.0.4280.141（正式版本）64 |

### PR DESCRIPTION
**Pull request by zombieJ**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

fix #28940
ref #29057
close #29066

### 💡 Background and solution

基本都是因为这个 `maxLength` 导致的，现在改成模拟原生元素逻辑。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix TextArea display value will be cut by `maxLength` when in controlled. Fix `onCompositionEnd` not trigger when input exceed `maxLength`. Fix emoji count not align with `maxLength` & `showCount`.          |
| 🇨🇳 Chinese |   修复 TextArea 受控时展示值会被 `maxLength` 截取的问题；修复 `maxLength` 下超出部分无法触发 `onCompositionEnd` 事件的问题；修复使用 emoji 时 `maxLength` 和 `showCount` 计数逻辑不一致的问题。        |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
不好好休息。。

File: components/input/TextArea.tsx [hunk 1]
```diff
@@ -100,17 +128,19 @@ const TextArea = React.forwardRef<TextAreaRef, TextAreaProps>(
...
         ref={innerRef}
       />
     );
 
     let val = fixControlledValue(value) as string;
 
-    // Max length value
-    const hasMaxLength = Number(maxLength) > 0;
-    // fix #27612 将value转为数组进行截取，解决 '😂'.length === 2 等emoji表情导致的截取乱码的问题
-    val = hasMaxLength ? [...val].slice(0, maxLength).join('') : val;
```
Comment (afc163) [inline components/input/TextArea.tsx:113]: 把 fixEmojiLength 这段逻辑去掉就好了？受控模式下 maxLength 不应该生效。

Comment (zombieJ) [reply components/input/TextArea.tsx:113]: `fixEmojiLength` 不用去掉，受控模式下不走这段逻辑。受控时，`maxLength` 无效。触发 `onChange` 时，会根据当前是否是 composition 状态提供对应的 `value`。compositing 时，不按照 `maxLength` 截取。非 compositing 时，按照 `maxLength` 截取。
