### PR TITLE
fix: Descriptions warning should work as expect

### LINKED ISSUE #16815: 使用Descriptions组件控制台会报Warning错误
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/l0xml)

### Steps to reproduce
直接使用组件就会出现这样的问题

### What is actually happening?
使用Descriptions组件控制台会报Warning错误

image

| Environment | Info |
|---|---|
| antd | 3.19.0 |
| React | 16.7.0 |
| System | mac 10.14.4 |
| Browser | chrome 74.0 |

### PR DESCRIPTION
**Pull request by zombieJ**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 👻 What's the background?

fix #16815

### 💡 Solution

Adjust warning logic

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Description warning with column count not correct. |
| 🇨🇳 Chinese | 修复 Descriptions 排列警告信息逻辑错误的问题。 |

### ☑️ Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/descriptions/index.tsx [hunk 1]
```diff
@@ -48,14 +48,15 @@ const generateChildrenRows = (
       totalRowSpan += 1;
     }
     if (totalRowSpan >= column) {
-      childrenArray.push(columnArray);
-      columnArray = [];
-      totalRowSpan = 0;
       warning(
-        totalRowSpan > column,
+        totalRowSpan <= column,
```
Comment (afc163) [inline components/descriptions/index.tsx]: 居然是反的..
