### PR TITLE
fix Modal.confirm error when onCancel not set

### LINKED ISSUE #5269: BUG: Model.confirm throw error: Uncaught TypeError: Cannot read property 'apply' of undefined
#### Environment(required)

- antd version: 2.8.1
- OS and its version: OS X
- Browser and its version: chrome

#### What did you do? Please provide steps to re-produce your problem.

when click ok button in confirm modal:
it throw: `Uncaught TypeError: Cannot read property 'apply' of undefined`, like following image:

image

My code is:

```
      confirm({
        title: 'are you sure?',
        onOk () {
          // onDeleteItem(record.id)
        }
      })
```

#### What do you expected?

without error throw

#### Re-producible online demo

http://codepen.io/anon/pen/mWmQJx?editors=001

image

actually in official documentation is wrong too:

image

### PR DESCRIPTION
**Pull request by ddcat1115**
- fix Modal.confirm error when `onCancel` not set
- fix duplicate call `onCancel`

close #5269

### CODE REVIEW

**Comment by afc163** [comment]
I think #5278 is enough.

**Comment by afc163** [comment]
What is `triggerCancel` for?

**Comment by ddcat1115** [comment]
The `onCancel` of current Modal.confirm will be triggered twice if you click the cancel button, even clicking the ok button will trigger `onCancel`...

File: components/modal/confirm.tsx [hunk 1]
```diff
@@ -35,7 +35,13 @@ export default function confirm(config) {
     if (unmountResult && div.parentNode) {
       div.parentNode.removeChild(div);
     }
-    props.onCancel(...args);
+    const triggerCancel = args && args.length &&
+      args.some((param) => {
+        return typeof param === 'object' && param !== null && param.triggerCancel;
+      });
```
Comment (afc163) [inline components/modal/confirm.tsx]: `args.some(param => param && param.triggerCancel)`

**Comment by afc163** [comment]
Add test cases?

**Review by afc163 — APPROVED** [review]

**Comment by walkerqiao** [comment]
原来这个bug已经修复了， 赞赞的。
