### PR TITLE
fix: tour default zIndex

### LINKED ISSUE #50298: tourZIndexPopup is undefined
Reproduce: https://ant.design/components/tour-cn

图片

### PR DESCRIPTION
**Pull request by zombieJ**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #50298

### 📝 Changelog

- Use a developer-oriented tone and narrative style.
- Describe the user's first-hand experience of the issue and its impact on developers, rather than your solution approach.
- Refer to: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix Tour default `z-index` not follow `zIndexPopup` token issue.       |
| 🇨🇳 Chinese |    修复 Tour 默认 `z-index` 没有使用 `zIndexPopup` token 的问题。       |

### CODE REVIEW

File: components/tour/style/index.ts [hunk 1]
```diff
@@ -75,7 +74,7 @@ const genBaseStyle: GenerateStyle<TourToken> = (token) => {
         ...resetComponent(token),
 
         position: 'absolute',
-        zIndex: tourZIndexPopup,
+        zIndex: zIndexPopup,
```
Comment (li-jia-nan) [inline components/tour/style/index.ts:77]: 这个不需要用 useZIndex 来管理吗？

Comment (li-jia-nan) [reply components/tour/style/index.ts:77]: 哦，看了一下，好像没问题

**Review by MadCcc — APPROVED** [review]
