### PR TITLE
fix(menu): menu horizontal border bottom when dark

### LINKED ISSUE #38734: Menu height in Header
### Reproduction link

[https://ant.design/~demos/components-layout-demo-top](https://ant.design/~demos/components-layout-demo-top)

### Steps to reproduce

Menu is 1px higher than Header so creates a visible 1px offset.

### What is expected?

Menu to be contained in Header.

### What is actually happening?

Menu is 1px higher.

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18 |
| System | macOS |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by LuciNyan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [X] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

Closes: #38734

### 💡 Background and solution
Set the border-bottom of `menu-horizontal` to 0 in the dark mode in the same way as antd@4.X.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix Menu 1px higher when `theme="dark"`.   |
| 🇨🇳 Chinese |  修复 Menu 深色 theme 下高度多了 1px 的问题。  |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

### CODE REVIEW

File: components/menu/style/theme.tsx [hunk 1]
```diff
@@ -154,6 +154,12 @@ const getThemeStyle = (token: MenuToken, themeSuffix: string): CSSInterpolation
 
       // ====================== Horizontal ======================
       [`&${componentCls}-horizontal`]: {
+        ...(themeSuffix === 'dark'
+          ? {
+              borderBottom: 0,
+            }
+          : {}),
```
Comment (afc163) [inline components/menu/style/theme.tsx:161]: 这不是应该放暗色算法里？

**Review by afc163 — APPROVED** [review]
