### PR TITLE
fix: deprecated clearIcon prop

### LINKED ISSUE #43943: Warning: `clearIcon` will be removed in future. Please use `allowClear` instead.
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-463zfs)

### Steps to reproduce

1. Once the page finish loaded, error will show up in the console

### What is expected?

The error should not be shown, whenever input related component are used

### What is actually happening?

Error shows whenever input related component are used

| Environment | Info |
| --- | --- |
| antd | 5.8.0 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Brave, Chrome |

---
The error seems to be coming from rc-util package `node_modules/rc-util/es/warning.js`

### PR DESCRIPTION
**Pull request by kiner-tang**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [X] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close #43943

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  deprecated clearIcon prop  |
| 🇨🇳 Chinese | 废弃 clearIcon 属性 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 0856114</samp>

This pull request adds the ability to customize the clear icon in several components that use the `allowClear` prop, such as `Cascader`, `Select`, `TreeSelect`, `RangePicker`, `DatePicker`, and `TimePicker`. It also refactors the code to use a common variable for the clear icon logic and passes an object with a `clearIcon` property instead of a boolean to the `allowClear` prop.

### <samp>🤖 Generated by Copilot at 0856114</samp>

*  Add `allowClear` prop to `Cascader`, `Select`, `TreeSelect`, `DatePicker`, and `TimePicker` components to enable customizing the clear icon or using the default one ([link](https://github.com/ant-design/ant-design/pull/43945/files?diff=unified&w=0#diff-4737f6ef564486c449ec019f2826176d8b8d186088e5e912ad06ad1919b2d804R301-R302), [link](https://github.com/ant-design/ant-design/pull/43945/files?diff=unified&w=0#diff-cf9c6a6fcee364e93144b7afa91b8ff8b85e8bab46a1b602752c25b6c8de55d0R102), [link](https://github.com/ant-design/ant-design/pull/43945/files?diff=unified&w=0#diff-f4ebf787ec0bc13112f49b0d9a2df0bfa73f8ea80cec9a6c92d311e120fa6ffeR109), [link](https://github.com/ant-design/ant-design/pull/43945/files?diff=unified&w=0#diff-fba17c237c150271f91ee2ca848654484ecbbbcc71b010a8947620e945e10e34L119-R123), [link](https://github.com/ant-design/ant-design/pull/43945/files?diff=unified&w=0#diff-678a0178404ab41221775c01d203e79ccb84496e2f0b7cf4ef38222d7a7b562bL142-R146))
*  Introduce `mergedAllowClear` variable to store the boolean or object value of `allowClear` prop and pass it to the underlying `RcCascader`, `RcSelect`, `RcTreeSelect`, and `Picker` components ([link](https://github.com/ant-design/ant-design/pull/43945/files?diff=unified&w=0#diff-4737f6ef564486c449ec019f2826176d8b8d186088e5e912ad06ad1919b2d804L328-R334), [link](https://github.com/ant-design/ant-design/pull/43945/files?diff=unified&w=0#diff-cf9c6a6fcee364e93144b7afa91b8ff8b85e8bab46a1b602752c25b6c8de55d0R176-R177), [link](https://github.com/ant-design/ant-design/pull/43945/files?diff=unified&w=0#diff-f4ebf787ec0bc13112f49b0d9a2df0bfa73f8ea80cec9a6c92d311e120fa6ffeR194-R195), [link](https://github.com/ant-design/ant-design/pull/43945/files?diff=unified&w=0#diff-fba17c237c150271f91ee2ca848654484ecbbbcc71b010a8947620e945e10e34L119-R123), [link](https://github.com/ant-design/ant-design/pull/43945/files?diff=unified&w=0#diff-678a0178404ab41221775c01d203e79ccb84496e2f0b7cf4ef38222d7a7b562bL142-R146))
*  Replace `clearIcon` prop with `mergedAllowClear` variable in `components/cascader/index.tsx`, `components/select/index.tsx`, `components/tree-select/index.tsx`, `components/date-picker/generatePicker/generateRangePicker.tsx`, and `components/date-picker/generatePicker/generateSinglePicker.tsx` ([link](https://github.com/ant-design/ant-design/pull/43945/files?diff=unified&w=0#diff-4737f6ef564486c449ec019f2826176d8b8d186088e5e912ad06ad1919b2d804L328-R334), [link](https://github.com/ant-design/ant-design/pull/43945/files?diff=unified&w=0#diff-cf9c6a6fcee364e93144b7afa91b8ff8b85e8bab46a1b602752c25b6c8de55d0L262-R265), [link](https://github.com/ant-design/ant-design/pull/43945/files?diff=unified&w=0#diff-f4ebf787ec0bc13112f49b0d9a2df0bfa73f8ea80cec9a6c92d311e120fa6ffeL271-R274), [link](https://github.com/ant-design/ant-design/pull/43945/files?diff=unified&w=0#diff-fba17c237c150271f91ee2ca848654484ecbbbcc71b010a8947620e945e10e34L119-R123), [link](https://github.com/ant-design/ant-design/pull/43945/files?diff=unified&w=0#diff-678a0178404ab41221775c01d203e79ccb84496e2f0b7cf4ef38222d7a7b562bL142-R146))

### CODE REVIEW

File: components/cascader/index.tsx [hunk 1]
```diff
@@ -298,6 +298,8 @@ const Cascader = React.forwardRef<CascaderRef, CascaderProps<any>>((props, ref)
 
   const mergedBuiltinPlacements = useBuiltinPlacements(builtinPlacements, popupOverflow);
 
+  const mergedAllowClear = allowClear === true ? { clearIcon } : allowClear;
```
Comment (zombieJ) [inline components/cascader/index.tsx:301]: 看起来 `getIcons` 里需要 warning  props 的 `clearIcon` 才对

Comment (kiner-tang) [reply components/cascader/index.tsx:301]: done

File: components/select/utils/iconUtil.tsx [hunk 2]
```diff
@@ -33,7 +35,16 @@ export default function getIcons({
   prefixCls: string;
   showSuffixIcon?: boolean;
   showArrow?: boolean;
+  componentName: string;
 }) {
+  if (process.env.NODE_ENV !== 'production') {
+    warning(
+      !clearIcon,
+      componentName,
+      '`clearIcon` will be removed in future. Please use `allowClear` instead.',
```
Comment (afc163) [inline components/select/utils/iconUtil.tsx:44]:
```suggestion
      '`clearIcon` is deprecated, please use `allowClear={{ clearIcon }}` instead.',
```

**Review by MadCcc — APPROVED** [review]
