### PR TITLE
fix: Progress steps didn't change when update percent

### LINKED ISSUE #24532: Progress with steps does not reverse indicator when moving reducing progress percent
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-742yx?file=/index.js)

### Steps to reproduce
Click   button 2 times to increment progress
Click - button 2 times to decrement progress

### What is expected?
I would expect that the filled in step indicators would be reverted back to the original state

### What is actually happening?
The Percentage correctly updates but the step "indicators" do not

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.1 |
| System | Macos |
| Browser | Chrome (latest) |

### PR DESCRIPTION
**Pull request by ChuckJonas**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Perfermance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
fix #24532 

### 💡 Background and solution

Previously `background-color` was being set to `undefined`.  I updated the Progress `Step` component so it just omits the property if the `color` variable is not set.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix Progress with `steps` don't update `percent` expectedly.  |
| 🇨🇳 Chinese | 修复步骤 Progress `percent` 样式未正确更新的问题。  |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/progress/Steps.tsx [hunk 1]
```diff
@@ -18,7 +18,7 @@ const Steps: React.FC<StepsProps> = props => {
         color = strokeColor;
       }
       const stepStyle = {
-        backgroundColor: `${color}`,
```
Comment (afc163) [inline components/progress/Steps.tsx:21]: 直接 `backgroundColor: color,` 是不是就行了。

**Comment by afc163** [comment]
补个用例。

File: components/progress/Steps.tsx [hunk 2]
```diff
@@ -18,7 +18,7 @@ const Steps: React.FC<StepsProps> = props => {
...
+        ...(color !== undefined && { backgroundColor: `${color}` }),
```
Comment (yoyo837) [inline components/progress/Steps.tsx:21]:
```suggestion
        backgroundColor: color,
```

**Comment by yoyo837** [comment]
oops!  Incompatible types:
image

**Comment by ChuckJonas** [comment]
Should we just revert that suggestion then?

File: components/progress/style/index.less [hunk 3]
```diff
@@ -26,6 +26,11 @@
       min-width: 2px;
       margin-right: 2px;
       background: @progress-steps-item-bg;
+      transition: all 0.3s;
+
+      &-active {
+        background: @progress-default-color;
```
Comment (afc163) [inline components/progress/style/index.less:32]: 补充默认颜色。
