### PR TITLE
fix: Input should hide webkit cancel button

### LINKED ISSUE #40450: `AutoComplete` will show a clear icon in the input suffix, if add `Input` as `AutoComplete` `children`
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/cha-xun-mo-shi-que-ding-lei-mu-antd-5-1-6-forked-lrvqj0?file=/demo.js)

### Steps to reproduce

Pls check the link

### What is expected?

As you can see, here comes a clear icon and this clear icon color will always be "blue".

I hope "No clear icon, or the clear icon follow my global theme config"

### What is actually happening?

An unexpected clear icon appears and also doesn't follow theme config.

| Environment | Info |
| --- | --- |
| antd | 5.1.6 |
| React | 18.2.0 |
| System | MacOS 13.1 |
| Browser | 103.0.5060.134 |

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/40450

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix Input that unexpected cancel button is shown when `type="search"`.        |
| 🇨🇳 Chinese |    修复 Input 组件 `type="search"` 时未隐藏浏览器原生取消按钮的问题。       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/input/style/index.ts [hunk 1]
```diff
@@ -317,7 +317,6 @@ export const genInputGroupStyle = (token: InputToken): CSSObject => {
     },
 
     [`${componentCls}`]: {
-      float: 'inline-start',
```
Comment (yoyo837) [inline components/input/style/index.ts:320]: 这是笔误吗?

Comment (MadCcc) [reply components/input/style/index.ts:320]: float 还不支持这种写法，所以是失效的。现在看没啥问题所以删了

Comment (MadCcc) [reply components/input/style/index.ts:320]: group 相关的样式感觉可以用 Compact 取代了，能省一大笔

**Review by yoyo837 — APPROVED** [review]
