### PR TITLE
fix: Modal.confirm content rtl config miss

### LINKED ISSUE #31727: Modal RTL Form Problem
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/internationalization-antd-4-16-10-forked-vhjx3?file=/index.js)

### Steps to reproduce
*

### What is expected?
Form content of modal most RTL 

### What is actually happening?
*

| Environment | Info |
|---|---|
| antd | 4.16.11 |
| React | 17.0.0 |
| System | Windows 10 |
| Browser | Chrome 90 |

---
I asked before this problem:
[https://github.com/ant-design/ant-design/issues/31715](https://github.com/ant-design/ant-design/issues/31715)

and send me a link and I try say in link and work but Form content in modal RTL not work

### PR DESCRIPTION
**Pull request by xrkffgg**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
fix https://github.com/ant-design/ant-design/issues/31727

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix the rtl config of Modal.confirm custom content missing.       |
| 🇨🇳 Chinese | 修复 Modal.confirm 自定义内容全局 rtl 配置缺失的问题。          |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: components/modal/ConfirmDialog.tsx [hunk 1]
```diff
@@ -104,7 +104,7 @@ const ConfirmDialog = (props: ConfirmDialogProps) => {
       focusTriggerAfterClose={focusTriggerAfterClose}
     >
       <div className={`${contentPrefixCls}-body-wrapper`}>
-        <ConfigProvider prefixCls={rootPrefixCls}>
+        <ConfigProvider prefixCls={rootPrefixCls} direction={direction}>
```
Comment (afc163) [inline components/modal/ConfirmDialog.tsx:107]: 来个 test case

Comment (xrkffgg) [reply components/modal/ConfirmDialog.tsx:107]: 之后补个
