### PR TITLE
fix: margin between menu item and submenu title

### LINKED ISSUE #42159: Menu item and submenu have different margin
https://codesandbox.io/s/nei-qian-cai-dan-antd-5-4-6-forked-zb6267?file=/demo.tsx

图片

Menu.Item 之间的间距比 submenu 之间的更小一点。

可以对比一下 4.x 的效果：https://4x.ant.design/components/menu-cn/#components-menu-demo-inline-collapsed

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/42159

### 💡 Background and solution

修改前后效果对比在这里 https://app.argos-ci.com/ant-design/ant-design/builds/7920/46194312

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   Fix Menu different margin between Menu.Item and Menu.Submenu in vertical and inline mode.        |
| 🇨🇳 Chinese |   修复 Menu.Item 与 Submenu 之间间距不统一的问题。       |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 1498169</samp>

Add bottom margin to vertical menu items in `components/menu/style/vertical.tsx`. This improves the style consistency of the ant-design library with styled-components.

### <samp>🤖 Generated by Copilot at 1498169</samp>

* Add bottom margin to vertical menu items, except for the last one, to match ant-design style ([link](https://github.com/ant-design/ant-design/pull/42160/files?diff=unified&w=0#diff-b7b7775fd3e73c4510f6e127d709629338c94f257ad4cde92ffa63c62f11e25bR22-R26))

### CODE REVIEW

File: components/menu/style/vertical.tsx [hunk 1]
```diff
@@ -19,6 +19,11 @@ const getVerticalInlineStyle: GenerateStyle<MenuToken, CSSObject> = (token) => {
   return {
     [`${componentCls}-item`]: {
       position: 'relative',
+
+      // https://github.com/ant-design/ant-design/blob/5e52057671f9781ad2b957b0ff9adfcd1eb1eb88/components/menu/style/index.less#L487-L489
```
Comment (afc163) [inline components/menu/style/vertical.tsx:23]: 4.x 里这段样式在 5.x 里丢了。

Comment (afc163) [reply components/menu/style/vertical.tsx:23]: diff 效果在这里 https://app.argos-ci.com/ant-design/ant-design/builds/7920/46194312

**Review by yoyo837 — APPROVED** [review]

File: components/menu/style/vertical.tsx (hunk 1 above)
Comment (MadCcc) [reply components/menu/style/vertical.tsx:23]: 这里是 v5 设计缩短了，现在子菜单有点问题的
image

Comment (MadCcc) [reply components/menu/style/vertical.tsx:23]: https://github.com/ant-design/ant-design/pull/42848
在这里改回去了

Comment (afc163) [reply components/menu/style/vertical.tsx:23]: https://github.com/ant-design/ant-design/issues/42159

那这个问题要解，menu 与 submenu 之间间距不等。可以统一成 4px

图片
