### PR TITLE
fix: Fix image group preview z index in nested modal

### LINKED ISSUE #46034: Image PreviewGroup 多层Modal也有 z-index的问题
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/cool-tess-yfx4cp?file=/src/App.js)

### Steps to reproduce

多层modal中 Image PreviewGroup  层级错误

### What is expected?

层级正常

### What is actually happening?

错误

| Environment | Info |
| --- | --- |
| antd | 5.11.3 |
| React | 18.2.0 |
| System | windows |
| Browser | chrome版本 113.0.5672.127（正式版本） （64 位） |

### PR DESCRIPTION
**Pull request by kiner-tang**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [X] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

fix #46034 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix: Fix image group preview z-index in nested modal |
| 🇨🇳 Chinese | 解决图片组 z-index 在嵌套弹框中设置异常问题 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] TypeScript definition is updated/provided or not needed
- [X] Changelog is provided or not needed

---

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 0b7ff02</samp>

This pull request adds a new feature to the `Image.PreviewGroup` component that allows users to customize the z-index of the modal that shows the image preview group. It also adds a new demo example of using the `Image.PreviewGroup` component nested in a modal, and updates the documentation and tests accordingly.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 0b7ff02</samp>

*  Add `Image.PreviewGroup` component to support previewing multiple images in a group with a modal ([link](https://github.com/ant-design/ant-design/pull/46035/files?diff=unified&w=0#diff-229cf95fe3dde541084c824a9a86e2ed7f5c88be0d6ad5fdaae9f538cb7c6138R18), [link](https://github.com/ant-design/ant-design/pull/46035/files?diff=unified&w=0#diff-229cf95fe3dde541084c824a9a86e2ed7f5c88be0d6ad5fdaae9f538cb7c6138R44-R48), [link](https://github.com/ant-design/ant-design/pull/46035/files?diff=unified&w=0#diff-229cf95fe3dde541084c824a9a86e2ed7f5c88be0d6ad5fdaae9f538cb7c6138R61), [link](https://github.com/ant-design/ant-design/pull/46035/files?diff=unified&w=0#diff-7e29bdf7b3d15903dfc9bea72d699ed4bef2146dc1a0689897752772a15c3de5L183-R199), [link](https://github.com/ant-design/ant-design/pull/46035/files?diff=unified&w=0#diff-7e29bdf7b3d15903dfc9bea72d699ed4bef2146dc1a0689897752772a15c3de5L210-R225), [link](https://github.com/ant-design/ant-design/pull/46035/files?diff=unified&w=0#diff-7e29bdf7b3d15903dfc9bea72d699ed4bef2146dc1a0689897752772a15c3de5L279-R294))
*  Use `useZIndex` hook to get the z-index value for the `Image.PreviewGroup` component and pass it to the `Modal` component ([link](https://github.com/ant-design/ant-design/pull/46035/files?diff=unified&w=0#diff-229cf95fe3dde541084c824a9a86e2ed7f5c88be0d6ad5fdaae9f538cb7c6138R18), [link](https://github.com/ant-design/ant-design/pull/46035/files?diff=unified&w=0#diff-229cf95fe3dde541084c824a9a86e2ed7f5c88be0d6ad5fdaae9f538cb7c6138R44-R48), [link](https://github.com/ant-design/ant-design/pull/46035/files?diff=unified&w=0#diff-229cf95fe3dde541084c824a9a86e2ed7f5c88be0d6ad5fdaae9f538cb7c6138R61))
*  Test the `useZIndex` hook with the `Image.PreviewGroup` component in the `useZIndex.test.tsx` file ([link](https://github.com/ant-design/ant-design/pull/46035/files?diff=unified&w=0#diff-7e29bdf7b3d15903dfc9bea72d699ed4bef2146dc1a0689897752772a15c3de5L183-R199), [link](https://github.com/ant-design/ant-design/pull/46035/files?diff=unified&w=0#diff-7e29bdf7b3d15903dfc9bea72d699ed4bef2146dc1a0689897752772a15c3de5L210-R225), [link](https://github.com/ant-design/ant-design/pull/46035/files?diff=unified&w=0#diff-7e29bdf7b3d15903dfc9bea72d699ed4bef2146dc1a0689897752772a15c3de5L279-R294))
*  Add a new demo example of using the `Image.PreviewGroup` component nested in a modal in the `image/demo` folder and the documentation files ([link](https://github.com/ant-design/ant-design/pull/46035/files?diff=unified&w=0#diff-d124313e2c4dac92be547d13fb9b890fc064084289036e3d6e42d3c537ee4799R1-R7), [link](https://github.com/ant-design/ant-design/pull/46035/files?diff=unified&w=0#diff-ed8fb3d5b42c707d1b397ccc037d829b140863b1b3be52352f46049b8cabb7b4R1-R85), [link](https://github.com/ant-design/ant-design/pull/46035/files?diff=unified&w=0#diff-6a52026f5728b46e5b93ce0149ddfd4b94f79896c72f98ad4cbfa9ed2843a8b2R30), [link](https://github.com/ant-design/ant-design/pull/46035/files?diff=unified&w=0#diff-f5b985fbb4265b0e83d262d5f201a0b268c58dcadfde017e1126a4c1e6c15281R31))

### CODE REVIEW

**Review by zombieJ — APPROVED** [review]

File: components/image/demo/nested.tsx [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+              />
+            </Image.PreviewGroup>
+          </Modal>
+        </Modal>
+      </Modal>
+    </>
+  );
+};
+
+export default App;
```
Comment (afc163) [inline components/image/demo/nested.tsx:85]: 能用受控演示，来做 image 截图测试么？

**Review by MadCcc — APPROVED** [review]
