### PR TITLE
fix: fix tag border style

### LINKED ISSUE #42616: Tag 无边框样式被 status 覆盖
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/wu-bian-kuang-antd-5-5-1-forked-hg2tjt?file=/demo.tsx)

image

### What is actually happening?

边框又出现了

| Environment | Info |
| --- | --- |
| antd | 5.5.1 |
| React | 18.2.0 |
| System | macos |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close #42616

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix: fix tag border style |
| 🇨🇳 Chinese | 修复无边框样式 css 权重不够的问题 |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at bd352d2</samp>

Changed the colors and border style of borderless tags in the `Tag` component. This improved the consistency and usability of the component and fixed a visual bug.

### <samp>🤖 Generated by Copilot at bd352d2</samp>

* Changed the colors of the borderless tags to match the predefined status colors ([link](https://github.com/ant-design/ant-design/pull/42619/files?diff=unified&w=0#diff-dc53dc1260f4f0bd2795d9f45df6f718ba958f7f0e1182dd28cd5db91213a134L18-R27)) in `components/tag/demo/borderless.tsx`

### CODE REVIEW

File: components/tag/demo/borderless.tsx [hunk 1]
```diff
@@ -15,6 +15,18 @@ const App: React.FC = () => (
     </Space>
     <Divider />
     <Space size={[0, 'small']} wrap>
+      <Tag bordered={false} color="processing">
+        magenta
```
Comment (MadCcc) [inline components/tag/demo/borderless.tsx:19]: 文本改下哈

Comment (li-jia-nan) [reply components/tag/demo/borderless.tsx]: done~

**Comment by li-jia-nan** [comment]
image

**Review by MadCcc — APPROVED** [review]
