### PR TITLE
fix(AutoComplete): add missing style to ensure alignment

### LINKED ISSUE #52818: AutoComplete, size='large' , text is not centered
### Reproduction link

[https://qzkwmv.csb.app/](https://qzkwmv.csb.app/)

### Steps to reproduce

Look at the AutoComplete value in the minimal reproduction.

### What is expected?

Text is centered in AutoComplete like it is in Input

### What is actually happening?

Text is aligned to bottom

| Environment | Info |
| --- | --- |
| antd | 5.24.0 |
| React | 18.2.0 |
| System | MacOS 15.3 |
| Browser | Google Chrome Version 133.0.6943.54 (Official Build) (arm64) |

### PR DESCRIPTION
**Pull request by aojunhao123**
### 🤔 This is a ...

- [x] 🐞 Bug fix

### 🔗 Related Issues

- fix #52818 

### 💡 Background and Solution

**Before**
QQ_1739547599574

**After**
QQ_1739547651365

### 📝 Change Log

> - Read [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) like a cat tracks a laser pointer.
> - Describe the impact of the changes on developers, not the solution approach.
> - Reference: https://ant.design/changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Fix: Add a missing style to ensure that the AutoComplete text is centered |
| 🇨🇳 Chinese | Fix: 添加缺失样式，确保AutoComplete文字居中对齐 |

### CODE REVIEW

**Review by h3nk42 — APPROVED** [review]

File: components/select/style/single.ts [hunk 1]
```diff
@@ -93,10 +93,6 @@ function genSizeStyle(token: SelectToken, suffix?: string): CSSObject {
           alignItems: 'center',
           padding: `0 ${unit(inputPaddingHorizontalBase)}`,
 
-          [`${componentCls}-selection-search-input`]: {
-            height: selectHeightWithoutBorder,
-          },
```
Comment (afc163) [inline components/select/style/single.ts:98]: 得看看当时为啥会加这个

Comment (aojunhao123) [reply components/select/style/single.ts:98]: - #34339 
cc @zombieJ

File: components/select/style/single.ts [hunk 2]
```diff
@@ -93,10 +93,6 @@ function genSizeStyle(token: SelectToken, suffix?: string): CSSObject {
           alignItems: 'center',
           padding: `0 ${unit(inputPaddingHorizontalBase)}`,
 
-          [`${componentCls}-selection-search-input`]: {
```
Comment (zombieJ) [inline components/select/style/single.ts:96]: 这个不对，AutoComplete 和 Select 是共用样式的。Select 里是对的：
截屏2025-02-17 11 27 41

要看一下 AutoComplete 为什么会不一致

Comment (aojunhao123) [reply components/select/style/single.ts:96]: image

不一致的原因在于：非combobox mode下，会多一个item dom，把selector的高度撑起来了。而AutoComplete没有这个dom，又显式设定了height，导致large size下没居中

File: components/auto-complete/index.zh-CN.md [hunk 3]
```diff
@@ -35,6 +35,7 @@ demo:
 <code src="./demo/variant.tsx" version="5.13.0">多种形态</code>
 <code src="./demo/allowClear.tsx">自定义清除按钮</code>
 <code src="./demo/form-debug.tsx" debug>在 Form 中 Debug</code>
+<code src="./demo/AutoComplete-and-Select.tsx" debug>AutoComplete 和 Select </code>
```
Comment (afc163) [inline components/auto-complete/index.zh-CN.md:38]:
```suggestion
<code src="./demo/AutoComplete-and-Select.tsx" debug>AutoComplete 和 Select</code>
```

**Review by zombieJ — APPROVED** [review]
