### PR TITLE
fix: List.Item ref

### LINKED ISSUE #34620: 虚拟列表报ref错误
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/list-cn/中VirtualList例子](https://ant.design/components/list-cn/)

### Steps to reproduce
https://ant.design/components/list-cn/中VirtualList例子

### What is expected?
运行正常 但是控制台有报错

### What is actually happening?
运行正常 但是控制台有报错

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | 17.0.2 |
| System | win10 |
| Browser | 谷歌90.0.4758.102 |

### PR DESCRIPTION
**Pull request by hengkx**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #34620

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   fix List.Itemref        |
| 🇨🇳 Chinese |      修复 List.Item ref       |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
Add test case

File: components/list/Item.tsx [hunk 1]
```diff
@@ -1,40 +1,51 @@
...
+  CSSProperties,
+  FC,
+  forwardRef,
+  ForwardRefExoticComponent,
+  ForwardRefRenderFunction,
+  HTMLAttributes,
+  ReactElement,
+  ReactNode,
+  useContext,
+} from 'react';
```
Comment (afc163) [inline components/list/Item.tsx:12]: 用 import type { ... } 导出 CSSProperties ReactNode 这些。

Comment (hengkx) [reply components/list/Item.tsx:12]: eslint 能加上么

Comment (afc163) [reply components/list/Item.tsx:10]: 加

File: components/list/Item.tsx [hunk 2]
```diff
@@ -54,30 +63,26 @@ export const Meta: React.FC<ListItemMetaProps> = ({
   );
 };
 
-export interface ListItemTypeProps extends React.FC<ListItemProps> {
+export interface ListItemTypeProps
+  extends ForwardRefExoticComponent<ListItemMetaProps & React.RefAttributes<HTMLElement>> {
```
Comment (leonardfactory) [inline components/list/Item.tsx:67]: Hello! I'm having some issues after the release, I'm wondering if this should be `ListItemProps` instead of `ListItemMetaProps`?

Comment (hengkx) [reply components/list/Item.tsx:67]: ref https://github.com/ant-design/ant-design/pull/35455
