### PR TITLE
docs:fix error syntax

### LINKED ISSUE #42820: Antd Form example typo issue
### Reproduction link

[https://ant.design/components/form#components-form-demo-register](https://ant.design/components/form#components-form-demo-register)

### Steps to reproduce

In the antd form example (Registration)
In the antd form example (Registration)
<Form.Item
        name="confirm"
        label="Confirm Password"
        dependencies={['password']}
        hasFeedback
        rules={[
          {
            required: true,
            message: 'Please confirm your password!',
          },
          ({ getFieldValue }) => ({
            validator(_, value) {
              if (!value || getFieldValue('password') === value) {
                return Promise.resolve();
              }
              return Promise.reject(new Error('The two passwords that you entered do not match!'));
            },
          }),
        ]}
      >
        <Input.Password />
      </Form.Item>

### What is expected?

In above example here is syntax "The two passwords that you entered do not match"
This syntax should be "The new passwords that you entered do not match"

### What is actually happening?

Error Syntax is not matching with validation

| Environment | Info |
| --- | --- |
| antd | 5.5.2 |
| React | 18 |
| System | Windows 11 |
| Browser | Chrome |

### PR DESCRIPTION
**Pull request by Ali-ovo**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
 close #42820

### 📝 Changelog
| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |  更新了提示         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at da25aee</samp>

Fixed a typo in the error message of the password confirmation validator in the form register demo. Updated `components/form/demo/register.tsx` to use the word "new" instead of "two".

### <samp>🤖 Generated by Copilot at da25aee</samp>

* Changed the error message for the password confirmation validator to use the word "new" instead of "two" ([link](https://github.com/ant-design/ant-design/pull/42824/files?diff=unified&w=0#diff-58442f7a7d2f977ada14ffe3b43f91e68dc604c5f6829fe3b4e2a72ec2b218aaL179-R179))

### CODE REVIEW

**Review by afc163 — APPROVED** [review]

File: components/form/demo/register.tsx [hunk 1]
```diff
@@ -176,7 +176,7 @@ const App: React.FC = () => {
               if (!value || getFieldValue('password') === value) {
                 return Promise.resolve();
               }
-              return Promise.reject(new Error('The two passwords that you entered do not match!'));
+              return Promise.reject(new Error('The new passwords that you entered do not match!'));
```
Comment (afc163) [inline components/form/demo/register.tsx:179]: `The new passwords` or `The new password`?

Comment (Ali-ovo) [reply components/form/demo/register.tsx:179]: `The new password`
