### PR TITLE
fix[Splitter]:  ant-splitter-mask should be removed when drag end

### LINKED ISSUE #54315: Splitter 修复拖拽结束时，屏幕仍然无法操作的问题
### Reproduction link

[https://github.com/xxzzgg/antd-react-project](https://github.com/xxzzgg/antd-react-project)

### yarn dev 
#用的代码就是Splitter 文档的第一个例子

### What is expected?

正常拖拽

### What is actually happening?

拖拽页面卡死，拖拽状态不释放

| Environment | Info |
| --- | --- |
| antd | 5.26.4 |
| React | 17.0.85 |
| System | macos |
| Browser | chrome - 137.0.7151.120（正式版本） (arm64) |

---
我使用的mac M芯片。双指拖动

### PR DESCRIPTION
**Pull request by QdabuliuQ**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [x] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [ ] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ⌨️ Accessibility improvement
- [ ] ❓ Other (about what?)

### 🔗 Related Issues
fix: [issue](https://github.com/ant-design/ant-design/issues/54315)

### 💡 Background and Solution
1. The ant-splitter-mask overlay element stays on the top layer and is not hidden, which causes the so-called "freezing" issue.
image
2. The ant-splitter-mask overlay element appears during the`mousemove` event and is hidden when`mouseup` is called.
3. after mouseup is triggered, moving the mouse may occasionally trigger another mousemove event, which causes the ant-splitter-mask overlay to reappear, making the page unresponsive.
image

### 📝 Change Log
ant-splitter-mask should be removed when drag end

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  ant-splitter-mask should be removed when drag end |
| 🇨🇳 Chinese |  ant-splitter-mask 元素在拖拽结束后应该被移除  |

### CODE REVIEW

**Comment by QdabuliuQ** [comment]
大佬可以review一下吗 @afc163 @thinkasany  😄

**Comment by wanpan11** [comment]
mask 的测试用例 150 行有的。

image

感觉这个bug像是 useEffect 更新慢了导致的，换成 React.useLayoutEffect 看下呢

image

**Comment by QdabuliuQ** [comment]
已调整，有空review一下 @wanpan11

File: components/splitter/SplitBar.tsx [hunk 1]
```diff
@@ -113,6 +113,8 @@ const SplitBar: React.FC<SplitBarProps> = (props) => {
       };
 
       const onMouseUp = () => {
+        window.removeEventListener('mousemove', onMouseMove);
```
Comment (wanpan11) [inline components/splitter/SplitBar.tsx]: 我没说清楚-。-
window.removeEventListener( 
这些还是放到 return 函数里面，然后看下使用 useLayoutEffect 还会不会有bug，没问题的话只用将 useEffect 换成 useLayoutEffect 就行了。如果不行的话就按你的来

**Comment by xxzzgg** [comment]
大佬们 这个啥时候会发版呀 @QdabuliuQ @wanpan11

**Comment by QdabuliuQ** [comment]
> 大佬们 这个啥时候会发版呀 @QdabuliuQ @wanpan11
我只是个提pr的 👀 大佬们好像都没review

**Comment by wanpan11** [comment]
@QdabuliuQ 我改了下 你拉到本地看看 还有问题不

**Comment by QdabuliuQ** [comment]
> @QdabuliuQ 我改了下 你拉到本地看看 还有问题不

我拉了本地跑了一下和测试用例，没啥问题  @wanpan11

**Comment by wanpan11** [comment]
> 我拉了本地跑了一下和测试用例，没啥问题 @wanpan11

👌 
这个问题 我这边没法复现😂

**Review by wanpan11 — APPROVED** [review]

**Comment by wanpan11** [comment]
> 大佬们 这个啥时候会发版呀 @QdabuliuQ @wanpan11

下个版本

**Comment by QdabuliuQ** [comment]
> > 我拉了本地跑了一下和测试用例，没啥问题 @wanpan11
> 
> 👌 这个问题 我这边没法复现😂

issue 里面的提供的demo可以复现，就是 mouseup / mousemove 事件触发影响到 😊
