### PR TITLE
style: fix Modal.confirm description long text layout

### LINKED ISSUE #45102: 使用 Modal.info(), content 属性中的内容较长时，会超出 Modal 边界
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/wr72f7?file=/demo.tsx)

### Steps to reproduce

在content内部输入一行较长的文本，例如:
        <p>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</p>
image

### What is expected?

content 中的内容不会超出了Modal 边界

### What is actually happening?

content 中的内容超出了Modal 边界

| Environment | Info |
| --- | --- |
| antd | 5.9.3 |
| React | 18.2.0 |
| System | win11 |
| Browser | edge 117 |

---
之前提过一个相同的 issue：https://github.com/ant-design/ant-design/issues/39247
当时的版本修复了，现在这个版本（5.9.3）又出现了

### PR DESCRIPTION
**Pull request by afc163**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close https://github.com/ant-design/ant-design/issues/45102
close https://github.com/ant-design/ant-design/pull/45204

ref https://github.com/ant-design/ant-design/pull/39249

### 💡 Background and solution

https://github.com/ant-design/ant-design/pull/39249 修复过，后续改 dom 结构改丢了。

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | 修复 Modal.confirm `description` 是长文本时的内容溢出问题。          |
| 🇨🇳 Chinese | Fix Modal.confirm broken layout when `description` is long text.         |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at 2782586</samp>

Fix modal confirm content overflow issue. Add `maxWidth` to `components/modal/style/confirmCmp.tsx` to limit the content width when icon is present.

### <samp>🤖 Generated by Copilot at 2782586</samp>

* Fix the modal confirm icon size and alignment by adding a new `iconSize` prop to the `ConfirmDialog` component and using it to calculate the icon width and height (                          F0L

### CODE REVIEW

**Review by kiner-tang — APPROVED** [review]

File: components/modal/style/index.tsx [hunk 1]
```diff
@@ -324,15 +324,8 @@ const genWireframeStyle: GenerateStyle<ModalToken> = (token) => {
...
       },
-      [`${confirmComponentCls}-body`]: {
-        [`> ${token.iconCls}`]: {
-          marginInlineEnd: token.margin,
-
-          // `content` after `icon` should set marginLeft
-          [`+ ${confirmComponentCls}-title + ${confirmComponentCls}-content`]: {
-            marginInlineStart: token.modalConfirmIconSize + token.margin,
-          },
-        },
```
Comment (afc163) [inline components/modal/style/index.tsx:335]: 删除无用的代码。

File: components/modal/style/confirmCmp.tsx [hunk 2]
```diff
@@ -53,6 +53,7 @@ const genModalConfirmStyle: GenerateStyle<ModalToken> = (token) => {
         flexDirection: 'column',
         flex: 'auto',
         rowGap: token.marginXS,
+        maxWidth: `calc(100% - ${token.modalConfirmIconSize + token.marginSM}px)`,
```
Comment (afc163) [inline components/modal/style/confirmCmp.tsx:56]: 这是核心改动。
