### PR TITLE
fix: incorrect Select and Pagination text color for dark theme

### LINKED ISSUE #38805: `Select` search text color didn't follow theme config
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/dai-sou-suo-kuang-antd-5-0-0-forked-b34zwf)

### Steps to reproduce

Please check link

### What is expected?

The search text color should be white

### What is actually happening?

The search text color is black, and it's super hard to see it in dark mode

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 18.2.0 |
| System | MacOS 12.6 |
| Browser | 107.0.5304.110 |

### PR DESCRIPTION
**Pull request by Dunqing**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close: https://github.com/ant-design/ant-design/issues/38805

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      Fix Select and Pagination incorrect text color in dark theme.     |
| 🇨🇳 Chinese |     修复 Select 和 Pagination 在暗色主题下文字颜色不正确。      |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by MadCcc — APPROVED** [review]

File: components/select/style/index.tsx [hunk 1]
```diff
@@ -35,6 +35,7 @@ const genSelectorStyle: GenerateStyle<SelectToken, CSSObject> = (token) => {
 
       input: {
         cursor: 'auto',
+        color: token.colorText,
```
Comment (afc163) [inline components/select/style/index.tsx:38]:
```suggestion
        color: 'inherit',
```

看上去这样就够了

**Review by afc163 — APPROVED** [review]
