### PR TITLE
fix: Tour `step.type` should work

### LINKED ISSUE #45081: Type primary is not applied to tours first step
### Reproduction link

[Edit on CodeSandbox](https://codesandbox.io/s/non-modal-antd-5-9-3-forked-hnx5tf?file=/demo.tsx)

### Steps to reproduce

It is stated in the [docs](https://ant.design/components/tour#tourstep) that the type prop affects the background color and text color.
Lets say that the tour steps are in the following order

```jsx
const steps: TourProps["steps"] = [
    {
      title: "Upload File",
      description: "Put your files here.",
      cover: (
        <img
          alt="tour.png"
          src="https://user-images.githubusercontent.com/5378891/197385811-55df8480-7ff4-44bd-9d43-a7dade598d70.png"
        />
      ),
      target: () => ref1.current,
      type: "primary" // the first step has antd primary color as background 
    },
    {
      title: "Save",
      description: "Save your changes.",
      target: () => ref2.current
    },
    {
      title: "Other Actions",
      description: "Click to see other actions.",
      target: () => ref3.current
    }
  ];
  ```
chrome-capture-2023-8-25 (3)

### What is expected?
I want to apply the type primary color as the background of the first step only.

### What is actually happening?
The primary color of the first tour step is not applied when the component mounts, the primary color is applied when visiting the first step for the 2nd time using the previous button. 

| Environment | Info |
| --- | --- |
| antd | 5.9.0 |
| React | 18.2.0 |
| System | MacOs |
| Browser |  Google chrome Version 116.0.5845.187 (Official Build) (arm64) |

### PR DESCRIPTION
**Pull request by MadCcc**
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link
close https://github.com/ant-design/ant-design/issues/45081

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    Fix Tour that `step.type` didn't work when shown at first time.       |
| 🇨🇳 Chinese |       修复 Tour 组件第一次展示时 `step.type` 无效的问题。   |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### <samp>🤖 Generated by Copilot at bb09de8</samp>

This pull request refactors and improves the tour component by using the `useMemo` hook, removing the `useMergedType` hook and its test file, and fixing the type annotation of the defaultType prop. It also adds a new test case to verify the className of the tour panel based on the type prop.

### <samp>🤖 Generated by Copilot at bb09de8</samp>

*  Simplify the logic of applying the type prop to the tour component and its steps by using the className prop instead of a custom state ([link](https://github.com/ant-design/ant-design/pull/45086/files?diff=unified&w=0#diff-adad9b12865a3221e41486d220d744321efe428765a7ef91e2f5719dcd00a342L1-R1), [link](https://github.com/ant-design/ant-design/pull/45086/files?diff=unified&w=0#diff-adad9b12865a3221e41486d220d744321efe428765a7ef91e2f5719dcd00a342L13), [link](https://github.com/ant-design/ant-design/pull/45086/files?diff=unified&w=0#diff-adad9b12865a3221e41486d220d744321efe428765a7ef91e2f5719dcd00a342L33-R41), [link](https://github.com/ant-design/ant-design/pull/45086/files?diff=unified&w=0#diff-adad9b12865a3221e41486d220d744321efe428765a7ef91e2f5719dcd00a342L50), [link](https://github.com/ant-design/ant-design/pull/45086/files?diff=unified&w=0#diff-adad9b12865a3221e41486d220d744321efe428765a7ef91e2f5719dcd00a342L67), [link](https://github.com/ant-design/ant-design/pull/45086/files?diff=unified&w=0#diff-adad9b12865a3221e41486d220d744321efe428765a7ef91e2f5719dcd00a342L82-R83), [link](https://github.com/ant-design/ant-design/pull/45086/files?diff=unified&w=0#diff-e7526e6b079e5959051ae4a933231c0edaad482dd6220f4c7fb98ce311a95110L46), [link](https://github.com/ant-design/ant-design/pull/45086/files?diff=unified&w=0#diff-e7526e6b079e5959051ae4a933231c0edaad482dd6220f4c7fb98ce311a95110L123-R122))
*  Add a test case to check that the first step of the tour component has the primary type and the corresponding class name ([link](https://github.com/ant-design/ant-design/pull/45086/files?diff=unified&w=0#diff-b4b0d601d29dec66f1b7249355b887e75ac36d1acd82071053c2c9af3b7eaac1R532-R565))
*  Fix the type annotation of the defaultType prop in the useMergedType hook ([link](https://github.com/ant-design/ant-design/pull/45086/files?diff=unified&w=0#diff-660cdf6fc0f7add8cd2336c4be31ff0e3f8619125d3b5d90efad9c53c4a48feaL6-R6))
*  Delete the unused file `components/tour/__tests__/useMergedType.test.ts` ([link](https://github.com/ant-design/ant-design/pull/45086/files?diff=unified&w=0#diff-3e3dc297c30ffd67243630aa222c6af8339bd2ef2f3958e8101ef1fcfb06b177))

### CODE REVIEW

File: components/tour/panelRender.tsx [hunk 1]
```diff
@@ -120,7 +119,7 @@ const TourPanel: React.FC<TourPanelProps> = ({
   const [contextLocale] = useLocale('Tour', defaultLocale.Tour);
 
   return (
-    <div className={classNames(className, `${prefixCls}-content`)}>
```
Comment (MadCcc) [inline components/tour/panelRender.tsx:123]: 这里 className 重复了，在 rc-tour 里已经将这个 `className` 给了 root 元素

**Review by kiner-tang — APPROVED** [review]
