### PR TITLE
fix(input): border-radius issue with `addonAfter` in compact mode

### LINKED ISSUE #52483: 当 Space.Compact 和 input 在一起的时候，input 如果同时存在 addonAfter 和 prefix或suffix，则拼接处的圆角无效。
当存在 addonAfter 且 存在 prefix 或 suffix 属性的时候，**拼接处**就会出现圆角问题。

```
<Space.Compact >
    <Button type="primary">Button 1</Button>
    <Input prefix="前面" suffix="后面" addonAfter="00:01"/>
</Space.Compact>
```

| Environment | Info |
| --- | --- |
| antd | 5.23.1 |
| React | 18/19 |
| System | windows/macos |
| Browser | edge/chrome |

### PR DESCRIPTION
**Pull request by DDDDD12138**
[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE_CN.md?plain=1)

### 🤔 This is a ...

- [ ] 🆕 New feature
- [ ] 🐞 Bug fix
- [ ] 📝 Site / documentation improvement
- [ ] 📽️ Demo improvement
- [x] 💄 Component style improvement
- [ ] 🤖 TypeScript definition improvement
- [ ] 📦 Bundle size optimization
- [ ] ⚡️ Performance optimization
- [ ] ⭐️ Feature enhancement
- [ ] 🌐 Internationalization
- [ ] 🛠 Refactoring
- [ ] 🎨 Code style optimization
- [ ] ✅ Test Case
- [ ] 🔀 Branch merge
- [ ] ⏩ Workflow
- [ ] ❓ Other (about what?)

### 🔗 Related Issues

fix #52483

#### Before
image

#### After
image

### 📝 Change Log

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      resolve border-radius issue with `addonAfter` in compact mode     |
| 🇨🇳 Chinese |      解决紧凑模式中 `addonAfter` 的圆角问题     |

### CODE REVIEW

File: components/input/style/index.ts [hunk 1]
```diff
@@ -642,6 +642,14 @@ const genGroupStyle: GenerateStyle<InputToken> = (token: InputToken) => {
...
           },
         },
+        // Fix the issue of input use `addonAfter` param in space compact mode
+        // https://github.com/ant-design/ant-design/issues/52483
+        [`&:not(${componentCls}-compact-first-item)${componentCls}-compact-item`]: {
+          [`${componentCls}-affix-wrapper`]: {
+            borderStartStartRadius: 0,
+            borderEndStartRadius: 0,
+          },
+        },
```
Comment (afc163) [inline components/input/style/index.ts:652]:
```suggestion
        [`&:not(${componentCls}-compact-first-item)${componentCls}-compact-item ${componentCls}-affix-wrapper`]: {
           borderStartStartRadius: 0,
           borderEndStartRadius: 0,
        },
```

**Comment by afc163** [comment]
留个 demo 截图作为测试用例。

File: components/input/style/index.ts (hunk 1 above)
Comment (DDDDD12138) [reply components/input/style/index.ts:652]: 这块的话我想，和上面 639行，保持风格上统一

**Comment by afc163** [comment]
snapshot 要更新一下

**Comment by DDDDD12138** [comment]
> 要更新一下

是还要做什么操作嘛

**Review by afc163 — APPROVED** [review]
